### ISSUE TITLE
Topoplot issue

### ISSUE THREAD

**Issue by Andesha** [eeglabdevelopers/eeglab#10]
Hi there,

Currently working with the latest version of EEGLAB and saw a strange addition. Namely, in topoplot.m line ~1000 there is a call to "dsaffsda".

Not sure exactly what this is for - but this call forces my script into the catch portion of the code and then gdatav4 fails.

For now I've commented the line out and everything seems to be back to normal.

Is this a known issue or is something off with my datastructures?

thanks!

**Comment by nucleuscub** [comment]
The typo has been corrected.
Thanks for the hint,
Ramon
