### ISSUE TITLE
freqs output from Spectopo.m

### ISSUE THREAD

**Issue by CorentinWicht** [eeglabdevelopers/eeglab#101]
Dear EEGLab developpers,

I am having a hard time figuring it out why the freqs output from Spectopo.m always starts at 0.

From my understanding, this is because Spectopo.m computes the PSD (i.e. which is a density under the curve), which would mean that when freqs = 0Hz it is in fact the PSD from 0 to 0.9999 Hz ? 

Am i correct?

I want to extract frequency ranges from the spectra output (e.g. 2-4Hz) and average them.
Then if I am correct, this means that I will have to do mean(spectra(:,3-4),2) since:
- freqs(3) is 2-2.999Hz 
- freqs(4) is 3-3.999Hz 

Using the function:
[spectra ,freqs]=spectopo(EEG, 1, EEG.srate,'freqfac',1)

Many thanks and best regards,

Corentin Wicht

**Comment by arnodelorme** [comment]
Dear Corentin,

Frequency 0 is the DC offset in the FFT. Both the pwelch and psd (psd now deprecated) Matlab functions return it as well.

Arno
