### ISSUE TITLE
Better Octave compatibility

### ISSUE THREAD

**Issue by bewantbe** [eeglabdevelopers/eeglab#104]
### Description

I have read [Running EEGLAB on Octave](https://sccn.ucsd.edu/wiki/Running_EEGLAB_on_Octave). But still, I can not start current stable version of EEGLAB in GNU Octave 6.0.0.

#### Steps to Reproduce

In a shell window:

    $ ~/soft/octave6.0/bin/octave-cli -q
    octave-cli:1> pkg load signal
    octave-cli:2> graphics_toolkit('fltk')
    octave-cli:3> cd eeglab2019_1
    octave-cli:4> eeglab
    warning: findstr is obsolete; use strfind instead
    warning: This Matlab version is too old to run the current EEGLAB
    warning: Download EEGLAB 4.3b at http://sccn.ucsd.edu/eeglab/eeglab4.5b.teaching.zip
    warning: This version of EEGLAB is compatible with all Matlab version down to Matlab 5.3
    octave-cli:5> pop_loadset
    error: 'pop_loadset' undefined near line 1 column 1

The last error ('pop_loadset' undefined) indicates EEGLAB is not correctly loaded. Adding '--traditional' do not help

#### Expected behavior:

Correctly recognize Octave and load package path.

#### Actual behavior:

Fail to recognize Octave, fail to load package path.

#### Versions

|  |  |
|----| ---- | 
| OS version     | Debian 9 (stretch) |
| Octave version | 6.0.0 |
| EEGLAB version | 2019.1 |

#### Proposed solution

In `eeglab.m` add
`ismatlab = exist('OCTAVE_VERSION','builtin') == 0;`
before any call to `ismatlab`.

BTW, the version number of Octave now reach "6". Soon the [`eeglab/functions/adminfunc/ismatlab.m`](https://github.com/sccn/eeglab/blob/441123ab368cb7529b837728e29e333704cdb8a2/functions/adminfunc/ismatlab.m#L5) will be broken.

A solution is replace it with

```Matlab
function res = ismatlab
% true if called from Matlab; false if called from Octave
res = exist('OCTAVE_VERSION','builtin') == 0;
```

Or better (see official manual of Octave, section [D.4 How to Distinguish Between Octave and Matlab](https://octave.org/doc/interpreter/How-to-Distinguish-Between-Octave-and-Matlab.html))

```Matlab
function res = ismatlab
% true if called from Matlab; false if called from Octave
persistent cacheres;
if isempty (cacheres)
  cacheres = (exist ("OCTAVE_VERSION", "builtin") == 0);
end
res = cacheres;
```

**Comment by arnodelorme** [comment]
Yes, this is because of Octave 6.0. I have implemented the fix. Thank you.
