### ISSUE TITLE
pop_rejepoch.m: incorrectly calls pop_select if all trials are rejected

### ISSUE THREAD

**Issue by les-g1** [eeglabdevelopers/eeglab#105]
### Description

Issue following Bug #21 (https://github.com/sccn/eeglab/issues/21).
I've updated pop_rejepoch.m to the newer version on Github. It appears that pop_rejepoch still tries to call pop_select if all trials are marked for rejection, but pop_select can't handle this.

<br>
#### Steps to Reproduce

1. load the epoched tutorial data, 
2. run the following code which marks all trials for rejection:
EEG = pop_rejepoch( EEG, [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1],0);

<br>
#### Expected behavior:
EEG.trials should now be 0 because all trials were rejected, the other data from the EEG structure should be gone

<br>
#### Actual behavior:
error, the command window displays:

80/80 trials rejected
Error using pop_select (line 227)
Error: dataset is empty

Error in pop_rejepoch (line 96)
EEG = pop_select( EEG, 'notrial', tmprej);

The same error occurs if you take the same steps through the GUI. A pop_select dialog box shows up saying "Error: dataset is empty,"

<br>

#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 7] |
| Matlab version | [2015b] |
| EEGLAB version | [2019_1] |

**Comment by arnodelorme** [comment]
Yes, you cannot process an empty dataset. We thought about removing the error message, but then people (and EEGLAB) would be confused. What to do with an empty dataset.

In you script, simply test if all the trials are removed before calling pop_rejepoch
