### ISSUE TITLE
Show trial number at bottom of `eegplot()`

### ISSUE THREAD

**Issue by mattansb** [eeglabdevelopers/eeglab#107]
### Description

Currently, when looking at many trials at once, with many events, it often impossible to see the trial number - which is hidden by the event flags:

![image](https://user-images.githubusercontent.com/35330040/71809515-ebe3b900-3078-11ea-9f08-777d9d96684b.png)

#### Expected behavior:

This could be solved by having the trial numbers on the bottom of the plot, where they would not be obscured by anything.

#### Actual behavior:

(Trial number is obscured)

#### Versions

|   |   |
|----| ---- | 
| OS version     | Win10 |
| Matlab version | R2017b |
| EEGLAB version | 2019.1 |

**Comment by nucleuscub** [comment]
@mattansb, 
 The lower x-axis is for displaying the latencies. You may shrink the time displayed by adjusting the **Time range to display** in the menu **Settings**, that way you will see clearly all the labels.
 Hope this helps,
R

**Comment by mattansb** [comment]
> You may shrink the time displayed by adjusting the Time range to display 

True - but would like to look at many trials at once, without having to switch between display settings to "zoom in" like that.
Other solutions:
- Perhaps the zoom in feature could also scale the events and would allow with simple click-and-drag to see the trial number.
- like the latency / amp / channel values in the bottom-right, showing the values at current mouse location could also display the current trial number over which the mouse is.
