### ISSUE TITLE
hlp_vrect error: argument 'axesHandle' must be numeric

### ISSUE THREAD

**Issue by Chillynights** [eeglabdevelopers/eeglab#110]
Hello team
I have this bug saying "hlp_vrect error: argument 'axesHandle' must be numeric" when trying to run **Model Fitting and Validation > Model Order Selection**

**Comment by nucleuscub** [comment]
Hi @Chillynights , 
 Which toolbox are you using? This does not seem to be a built-in menu in EEGLAB.
Thanks,
Ramon

**Comment by arnodelorme** [comment]
This is SIFT. Which version of SIFT are you using?

**Comment by arnodelorme** [comment]
We will assume you are using an outdated version of SIFT. Closing bug for now, feel free to reopen.
