### ISSUE TITLE
subsasgn error

### ISSUE THREAD

**Issue by bambarBrl** [eeglabdevelopers/eeglab#117]
help me!!!!!!!

EEGlab error in function subsasgn() at line 66:

Matrix index is out range for deletion.

if you think this is a bug, please submit a detailed description of how to reproduce the problem(and upload a small dataset) at https://github.com/sccn/eeglab/issues

**Comment by bambarBrl** [comment]
![418](https://user-images.githubusercontent.com/59819123/72793997-3454c680-3c76-11ea-920b-14ad40356c0f.png)

**Comment by nucleuscub** [comment]
@bambarBrl , 
We need more information on the context of this issue to be able to help you (please read and follow the form when submitting an issue). The most probable thing, though,  is a mismatch of the events and data latencies. But without the dataset, it is impossible to confirm.  Please consider sharing the dataset with us, so we can look into it.
 Thanks,
Ramon

**Comment by arnodelorme** [comment]
In the EEGLAB Preferences make sure the option to use memory mapping and EEG objects (option number 5 and 6) are unchecked. Let us know,

Arno

**Comment by arnodelorme** [comment]
Closing bug because no response. Feel free to reopen.
