### ISSUE TITLE
problem with data import into EEGLAB

### ISSUE THREAD

**Issue by amitkanthi** [eeglabdevelopers/eeglab#121]
I am facing a peculiar problem while importing .mat and .raw file into EEGLAB. When I import data using .mat file then the EEGLAB doesn't import the events along with it. When I import data using .raw file then the EEGLAB doesn't show up the reference channel. Moreover, I failed to input the reference channel manually. Please help me with this issue.

**Comment by arnodelorme** [comment]
By .raw, do you mean "Binary simple" EGI file format. The reference is a flat channel (equal to 0 all the time). If you wanted to see, you should define it in the channel location editor then re-reference the data. See this page for more information https://sccn.ucsd.edu/wiki/I.4:_Preprocessing_Tools#Re-referencing_the_data
