### ISSUE TITLE
problems in ICA sphere data importing

### ISSUE THREAD

**Issue by HisayukiOsanai** [eeglabdevelopers/eeglab#122]
### Description

This is with regard to data importing. From 'File' -> 'Import data' -> 'Using EEG functions' -> 'From ASCII/float files or Matlab array', I tried to import ICA weights and sphere, but the result of ICA was different with what is calculated originally. After the importing, the MATLAB variable 'EEG.icasphere' was unit matrix which is very different from the original 'EEG.icasphere', that I tried to import.
Instead, when I import ICA unmixing matrix (= weights*sphere) in 'ICA wheights array or text/binary file', leaving 'ICA sphere array' blank, independent components were successfully calculated and they are identical with the original ICA results. So, I guess ICA sphere importing is not working now.

<br>
#### Steps to Reproduce

1.   'File' -> 'Import data' -> 'Using EEG functions' -> 'From ASCII/float files or Matlab array'
2.   Import Matlab variables in 'Data file/array', ICA weights and ICA sphere ( originally calculated by 'runica.m'.
3.   ICA sphere becomes unit matrix. ICA results are not same with what is originally calculated by 'runica.m'.

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10|
| Matlab version | 2019a|
| EEGLAB version | v2019.1|

**Comment by arnodelorme** [comment]
When exporting a weight matrix, weight*sphere is exported, so when importing sphere is set to the identity matrix. I have tried to reproduce your problem above but could not.

I have exported an ICA solution 
File -> Export data -> Weight Matrix to text file
(this exports weight*sphere)

Then tried importing it in the dataset
Edit -> Dataset info

And sphere does show eye(32) which is fine. 
The ICA solution (inverse weight matrix recalculated from weight matrix) was identical to the original. This might not be the case if you remove components as the inverse weight matrix cannot be recalculated any more.

Please, reopen the issue with more details (and if possible data files for testing) so we can fix the bug if there is one.

Arno
