### ISSUE TITLE
Error when trying to change sampling rate

### ISSUE THREAD

**Issue by zegamer** [eeglabdevelopers/eeglab#130]
### Description

An error occurs whenever I try to change the sampling rate, I get the following error

>EEGLAB error in function myresample() at line 298:
>
>Undefined function 'pop_firwsord' for input arguments of type 'char'.

I tried it on both of the pre-existing datasets and it didnt't work.

<br>

![image](https://user-images.githubusercontent.com/17596923/74421615-9ce62c00-4e4d-11ea-914d-027e78a8ab68.png)

| OS version     | Windows 10 |
| Matlab version | R2019b |
| EEGLAB version | v2019.1 |

**Comment by arnodelorme** [comment]
Did you use github clone. You have to use the --recursive-submodule flag when cloning otherwise some functions will be missing.

If that fixes the problem, please reopen the bug report.
