### ISSUE TITLE
Invalid MEX-file with load_xdf()

### ISSUE THREAD

**Issue by cbl008** [eeglabdevelopers/eeglab#132]
I am getting an error when I work with xdimport.

Warning: Escaped character '\U' is not valid. See 'doc sprintf' for supported special characters. 
Warning: Invalid MEX-file 'C: 

We've tried to seperate the load_xdf folder alone from EEGLab. The problem is in the load_xdf_innerloop.C file at about line 327 that works with MEX files. It worked about a week ago.

**Comment by arnodelorme** [comment]
I have moved your issue to the XDF repository.

https://github.com/sccn/xdf/issues/51
