### ISSUE TITLE
eeg_checkset.m does not properly use operator "||"

### ISSUE THREAD

**Issue by CloudyDory** [eeglabdevelopers/eeglab#133]
For me it seems that line 433 of `eeg_checkset.m` does not properly use operator "||":
`removeevent = find( allepochs < 1 || allepochs > EEG.trials);`

I guess it should be changed to:
`removeevent = find( allepochs < 1 | allepochs > EEG.trials);`
since variable "`allepochs`" is a vector.

**Comment by arnodelorme** [comment]
This is right. This has been fixed. Thank you for noticing.

Arno
