### ISSUE TITLE
.csv and edf extension files did not import 

### ISSUE THREAD

**Issue by Rneem** [eeglabdevelopers/eeglab#135]
### Description:
 I tried to import two kind of eeg files .csv and .edf
but show me a problem
for .edf the message is (BIOSIG extention is not onatalled, do you want to download it now?) i already extract the zip file in the plug-in file but i don/t know the problem

also for .csv file i alreday plug-in musemonitor3.1 it show me to contact this page 

please find the error i captured in the attachment file
best regards

![csv](https://user-images.githubusercontent.com/24796264/75567047-e5166880-5a61-11ea-917a-48beb227cd3d.jpg)
![222](https://user-images.githubusercontent.com/24796264/75567111-07a88180-5a62-11ea-8011-90f9ca1e5c43.jpg)
![33333](https://user-images.githubusercontent.com/24796264/75567206-2dce2180-5a62-11ea-9c00-f8fccaba6bcc.jpg)

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by Rneem** [comment]
matlav version 2019a
EEGLAB version eeglab2019_1
OS windows 10

**Comment by arnodelorme** [comment]
Musemonitor plugin will only import .csv file generated by the Musemonitor program. To import any CVS file, import it on the matlab command line using

data = csvread(...);

Then use the EEGLAB interface to import the array using Menu item File > Import data > Using EEGLAB ... > From ASCII/float file or Matlab array.

For the problem with EDF, something prevents EEGLAB from accessing the internet and download the necessary plugin for importing EDF file. It is likely your firewall. You can download the zip file manually at https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php, uncompress it in the EEGLAB plugins folder and restart EEGLAB. 

Best wishes,

Arno
