### ISSUE TITLE
AMICA 15 plugin on Debian 10

### ISSUE THREAD

**Issue by heidichiu** [eeglabdevelopers/eeglab#136]
### Description

When using the following command to call AMICA, an error occurs on Debian 10:

`[W,S,mods] = runamica15(EEG.data(:,:),'max_threads',1500,'max_iter',7);`

```
eeglab14_1_1b/plugins/AMICA1.5.1/amica15c /Code/amicaouttmp/input.param: Segmentation fault
Something went wrong...
No gm present, setting num_models to 1
No W present, exiting
Reference to non-existent field 'W'.

Error in runamica15 (line 892)
    weights = mods.W(:,:,1);
```
The same error has occurred on 2 different computers with Debian 10. It does not happen when I use the exact same EEG data and the same command on Windows 10. Thus, it is possibly the binfile amica15c has not been updated for the Debian 10 OS.

#### Versions

|   |   |
|----| ---- | 
| OS version     | Debian10 |
| Matlab version | R2019a |
| EEGLAB version | 14.1.1b |

**Comment by arnodelorme** [comment]
I have transferred this report to the AMICA plugin

https://github.com/japalmer29/amica/issues/21
