### ISSUE TITLE
Study fails with Matlab 2019a, but runs with 2019b

### ISSUE THREAD

**Issue by JohnAtl** [eeglabdevelopers/eeglab#137]
### Description
When running plot channel measures on 2019a, there is an assignment error. The same study runs without error on 2019b.

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<img width="982" alt="Screen Shot 2020-03-03 at 11 23 18 AM" src="https://user-images.githubusercontent.com/5720074/75796610-ea193780-5d41-11ea-849a-2b41319ac667.png">

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [macOS 10.15.3] |
| Matlab version | [2019a and 2019b] |
| EEGLAB version | [2019.0] |

**Comment by arnodelorme** [comment]
That is surprising. Share the study if you can.

**Comment by JohnAtl** [comment]
[vfnf.study.zip](https://github.com/sccn/eeglab/files/4302586/vfnf.study.zip)

**Comment by JohnAtl** [comment]
I'll email it to you.

**Comment by arnodelorme** [comment]
Hi John,

Did you send me the study so I could have a look?

Arno

**Comment by JohnAtl** [comment]
Hi Arno,

I thought I had deleted those files and lost them for good, but found a 
backup on Backblaze.
I've uploaded them to the shared folder you sent.
Thanks!

https://drive.google.com/drive/folders/1mBzosm2q1-M2pWpmbfnzxIeN3IVbT0LY

Regards,
John

**Comment by arnodelorme** [comment]
Closing this bug report
