### ISSUE TITLE
Spectra and Maps error

### ISSUE THREAD

**Issue by ksk-2** [eeglabdevelopers/eeglab#141]
### Description
Not able to generate Spectra and Maps through the plot options. The data is a muse csv file. 
<br>
#### Steps to Reproduce

1. Import muse data
2. Set locations
3. Run ICA
4. Under Plot select channel or component maps
5. confirm options

#### Expected behavior:
Spectral maps with freq and power info along with 2D images

<br>
#### Actual behavior:
Error. See attached image. 

<br>
#### Versions
latest version

|   |   |
|----| ---- | 
| OS version     | [windows 10] |
| Matlab version | [2019] |
| EEGLAB version | [2019] |

![image](https://user-images.githubusercontent.com/61888225/76120037-7c6d4580-5fa5-11ea-9103-99ac085319b9.png)

**Comment by ksk-2** [comment]
Can anyone shed some light on this? Thanks!

**Comment by arnodelorme** [comment]
This is because you do not have the Matlab signal processing toolbox installed. However, the function should use alternative methods. What does this command return on your machine?

usepwelch = license('checkout','Signal_Toolbox')

**Comment by arnodelorme** [comment]
And apologies for replying so late. You replied to your own message which led us to believe that your concern had been addressed by someone from our team.

**Comment by cbpickro13** [comment]
Hi, 
I've run into the same issue EEGLab error in function spectcomp() at line 941. 
Here is what it says in the Maltab command window... 
C:\Program Files\MATLAB\R2020a\toolbox\stats\stats\finv.m
Pop_spectopo: finding data discontinuities
Selecting the first 15.0% of data for analysis...

I tried running usepwelch = license('checkout','Signal_Toolbox') and I received usepwlch = 1 as the return.

**Comment by qwezy923** [comment]
Hello, I also got stuck in this issue, and tried your method from #119, but I cannot find the path to signal processing toolbox.
After running usepwelch = license('checkout','Signal_Toolbox') , I still got usepwlch = 1.
Thanks.

**Comment by arnodelorme** [comment]
This is because it is available on your network but you cannot check it out (someone else is using it).
