### ISSUE TITLE
eeglab error in function eeg_rpsd() at line 17: undefined function 'windows' for input arguments of type 'char'

### ISSUE THREAD

**Issue by Naama2020** [eeglabdevelopers/eeglab#142]
### Description

I have four datasets per subject. After running ICA decomposition, and using ICLabel "Label components" option (after which the default option is chosen in the next window), this error message appears.
<img width="494" alt="error in function eeg_rspd()" src="https://user-images.githubusercontent.com/61835444/76137639-12f24300-6048-11ea-970b-67eaeb5b8b92.PNG">
 

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment]
When you downloaded the zip file from Github, it did not install firfilt and dipfit plugins. You need to install these manually using the plugin manager.

Best wishes,

Arno
