### ISSUE TITLE
'Merge clusters' not available in 'View and edit current component clusters' window

### ISSUE THREAD

**Issue by Naama2020** [eeglabdevelopers/eeglab#144]
Hi,  

The 'Merge clusters' option in the 'View and edit current component clusters' window is not available in my study dataset. Attached is a print screen image of the unavailable 'Merge clusters' option. Does anybody know a solution to this problem?

Thanks for your help,  
Naama

  |  
-- | --
OS version | [Windows 10 64 bit]
Matlab version | [2019b]
EEGLAB version | [2019.1 dev

<img width="462" alt="Merge error" src="https://user-images.githubusercontent.com/61835444/77388811-d0479f00-6d99-11ea-82c8-22e3663e3502.PNG">

**Comment by arnodelorme** [comment]
Yes, this menu has been disabled because it was not compatible with new cluster format. I have removed it. You many use "Reassign selected components" instead.
