### ISSUE TITLE
channel location

### ISSUE THREAD

**Issue by kevencurry123** [eeglabdevelopers/eeglab#145]
ok,now I am using the datasets which collected at the Children’s Hospital Boston,which is called the CHB-MIT,the datasets' channels are bipolar montages.So,I cannot match the location file that you have supplied for me because your file is based on single montages,so can you give me a location file that based on the datasets collected at the Children’s Hospital Boston.Thanks so much for your patience.

**Comment by arnodelorme** [comment]
The type of reference is independent of channel locations. It says on this page that the channel location follow the international 10-20 system for this dataset https://physionet.org/content/chbmit/1.0.0/

It is true that for vizualization purposes, you will need to have a common reference. This data should be converted to common reference if at all possible.
