### ISSUE TITLE
EEG Error dialog point people to bugzilla to report bugs

### ISSUE THREAD

**Issue by jiversen** [eeglabdevelopers/eeglab#15]
Suggest before next release update to point people to **https://github.com/sccn/eeglab/issues**

**Comment by nucleuscub** [comment]
Thanks, @jiversen . We have updated this message ahead to the new release. 

See commit here for reference: https://github.com/sccn/eeglab/commit/fa35ea4ec9ffc7bdacc0debbfceaa917d6fded05
