### ISSUE TITLE
How to compile EEGLAB

### ISSUE THREAD

**Issue by inobug** [eeglabdevelopers/eeglab#150]
Hi，
I tried to compile EEGLAB myself，but I don't know where to start。In this article on （Compiling EEGLAB: Technical note for developers）, I find some hope, but in the end I couldn't find you write (batchjob_eeglab_win. Bat) file, I hope to get some help。

Best Regards，
Zhen

**Comment by arnodelorme** [comment]
@nucleuscub, would you mind to add that script to our release?

Arno

**Comment by arnodelorme** [comment]
There is a new documentation https://eeglab.org/others/Compiled_EEGLAB.html#can-i-compile-eeglab-myself
