### ISSUE TITLE
MFFMatlabIO3.2  plugin

### ISSUE THREAD

**Issue by cannavac** [eeglabdevelopers/eeglab#152]
### Description
MFFMatlabIO3.2 generates the following error message when called
**too many input arguments error function uigetdir line 51**
 
[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. Simply from eeglab current (2019_1) version try to import mff data
No problem with eeglab2019_0 with MFFMatlabIO2.02.

<br>
#### Expected behavior:
Import mff data

<br>
#### Actual behavior:
error message
too many input arguments error function uigetdir line 51

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version  Fedora 31   | [*fill in*] |
| Matlab 2019b| [*fill in*] |
| EEGLAB 2019_1 | [*fill in*] |

**Comment by arnodelorme** [comment]
Yes, this was a Windows only problem. It was fixed in version 3.4 of the plugin.
Thank you,

Arno
