### ISSUE TITLE
Gracefully handle error when downloading extensions in function "plugin_askinstall()"

### ISSUE THREAD

**Issue by CloudyDory** [eeglabdevelopers/eeglab#155]
### Description

When EEGLAB needs a missing extension it will ask the user to download it by function `plugin_askinstall()`. However if EEGLAB cannot connect to the plugin server the function failed with an unintuitive message `Dot indexing is not supported for variables of this type` at line 78 instead of explicitly telling the user that it cannot download the plugin.

<br>
#### Steps to Reproduce

1. Remove FileIO and Fieldtrip plugin from MATLAB path and EEGLAB plugin folder.
2. Disable internet connection.
3. Launch EEGLAB.
4. Click "Import data" --> "Using the FILE-IO interface".
5. Click "Yes" when EEGLAB says the plugin is not installed and asks whether to download the plugin.

<br>
#### Expected behavior:
EEGLAB pops out an error message that it cannot download the plugin due to internet connection problems.

<br>
#### Actual behavior:
EEGLAB pops out an error message that "Dot indexing is not supported for variables of this type" at line 78 of function "plugin_askinstall.m".

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 1909 |
| Matlab version | MATLAB R2020a |
| EEGLAB version | 2019.1 |

#### Suggestion

Add following code after line 77 in function `plugin_askinstall.m`:
```
if isempty(plugins)
     error('Cannot download the extension. Please check your internet connection');
end
```

**Comment by arnodelorme** [comment]
Thank you. I have added your check and another one so the error message is clearer.
