### ISSUE TITLE
no spectrum plotted

### ISSUE THREAD

**Issue by cereso69** [eeglabdevelopers/eeglab#156]
### Description

no spectrum plotted when inspect/label components by map

<br>
#### Steps to Reproduce

1. After Decompose data by ICA
2. Inspect/label components by map
3. Click on a component
4. See image for error - no spectrum plotted

<br>
#### Expected behavior:
spectrum plotted

<br>
#### Actual behavior:
no spectrum plotted

<br>
v2019.1

|   |   |
|----| ---- | 
| OS version     | [latest] |
| Matlab version | [2019b
<img width="1293" alt="Screenshot 2020-05-07 at 11 54 38" src="https://user-images.githubusercontent.com/64956174/81276645-f67c8200-905b-11ea-8d87-7fc044c7e744.png">
] |
| EEGLAB version | [2019.1] |

**Comment by nucleuscub** [comment]
It may be that you do not have the signal processing toolbox available in your MATLAB installation.
By typing in the MATLAB command window the following command, you should get the location of the pwelch function :  _which pwelch_ 
The output should resemble this: /Applications/MATLAB_R2018b.app/toolbox/signal/signal/pwelch.m

If not like this, you probably don't have the toolbox.
It should work without the toolbox, though. So we'll take a look.

**Comment by nucleuscub** [comment]
@cereso69 , 
 Can you please paste the output of the following commands in the MATLAB command window?

license('checkout','Signal_Toolbox')
which pwelch

Thanks, 
R

**Comment by cereso69** [comment]
>> license('checkout','Signal_Toolbox')
which pwelch

ans =

     1

'pwelch' not found.
>>

**Comment by cereso69** [comment]
Thank you for helping!

**Comment by nucleuscub** [comment]
Dear @cereso69 , 
 It seems you do have the Signal Processing Toolbox, but the pwelch function is missing (should be in this toolbox). I'll try reinstalling the Signal Processing Toolbox. 
Hope this helps, 
R

**Comment by cereso69** [comment]
Hi R,

Thank you, but how do I re-install the signal processing toolbox please? Simple instructions would be much appreciated.

Thanks again
