### ISSUE TITLE
DIPFIT 

### ISSUE THREAD

**Issue by linaismail** [eeglabdevelopers/eeglab#158]
I am running DIPFIT for 64 electrodes
receiving this issue
"Warning: Name is nonexistent or not a directory: C:\EEGLAB\eeglab2019\functions\javachatfunc  > In path (line 109)   In addpath (line 86)   In eeglab>myaddpath (line 2073)   In eeglab (line 315)"

| OS version      [window 10] 
| Matlab version [R2019b] 
| EEGLAB version [20019]

**Comment by arnodelorme** [comment]
Yes, this has been fixed in version 2019.1 I believe. Thank you for reporting.
