### ISSUE TITLE
pop_icflag error due to different behavior of str2double under older Matlab versions

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#161]
(This problem is due to different behavior of str2double under old MATLAB versions.

In `pop_icflag()`, the rejection thresholds for some ICLABEL categories (e.g. for heart) are left empty by default in the GUI. Those inputs are collected in a cell array `res` looking something like this:

`res = {'','','','','0.9','1','0.9','1.0','',''}`

Under **Matlab 2016a (on Mac OS)**, this creates an error in line 69 of `pop_icflag`, when the inputs are converted from cell array of strings to a matrix:

`thresh = cellfun(@str2double,res) % empty strings converted to [ ] instead of NaN causing error`

Under recent Matlab versions (e.g. R2019 on Windows), empty strings are instead converted to `NaN,` so line 69 of `pop_icflag` works as intended.

**Comment by arnodelorme** [comment]
We have fixed that and issued version 1.2.6 of ICLabel. Thank you.
