### ISSUE TITLE
MFF import

### ISSUE THREAD

**Issue by JoannaZioga** [eeglabdevelopers/eeglab#162]
### Description

I'm trying to **import mff** files to EEGLAB using the **mffimport2.2 plugin**, but I get an error when using the pop_readegimff function: **"Undefined variable "com" or class "com.egi.services.mff.api.MFFResourceType.kMFF_RT_MFFFile"**

Here is a link to Google Drive with my data and screenshot of the matlab error:
https://drive.google.com/drive/folders/1_yH37owTiVme2A1kaPQZtJSrTaLPgx3c?usp=sharing

<br>
#### Steps to Reproduce

1. Add the mffimport2.2 plugin to the EEGLAB plugin folder & add this to matlab path
2. EEG = pop_readegimff;
3. Click OK on pop up window.

<br>
#### Expected behavior:
Import mff data

<br>
#### Actual behavior:
Error (see gdrive pic)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 10*] |
| Matlab version | [*2011b or 2018b*] |
| EEGLAB version | [*eeglab13_6_5b*] |

**Comment by arnodelorme** [comment]
I have moved your report to the mffmatlabio repository and will be addressing it hopefully today.
https://github.com/arnodelorme/mffmatlabio/issues/25
