### ISSUE TITLE
Minor issue: Main start-up GUI refers to non-existing menu option

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#163]
EEGLAB2019.1: The "suggested steps to get started" displayed in EEGLAB's main window (shown before loading dataset) refer to a menu item `Tools > Reject continuous data` that does not exist verbatim (anymore) in EEGLAB2019.1. It is also ambiguous whether it refers to "Automatic continuous rejection" or "Reject data using Clearn Rawdata (...)".

**Comment by arnodelorme** [comment]
OK, we fixed that. Thank you,

Arno
