### ISSUE TITLE
Improvement: pop_rmbase should remain downward-compatible with 3rd input optional

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#165]
`pop_rmbase` and `rmbase` now require three mandatory inputs. The option of the third input is highly appreciated, but this change will wreck **a lot** of old scripts and pipelines. The third input should be optional rather than mandatory, with the function defaulting to all channels ([ ]) in case that only two inputs are provided.

**Comment by arnodelorme** [comment]
Yes, this is definitely a problem. I have implemented a fix. Would you mind to pull your changes and let me know.
