### ISSUE TITLE
Minor issue: pop_iclabel produces incomplete eegh entry

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#166]
Minor issue: The history (eegh) entry for` pop_iclabel` (generated in lines 72:76 of pop_iclabel) is missing the quotation marks around the "version" (e.g. 'default'). This causes scripts to crash if the history is copy-pasted verbatim.

Problematic line (see also line 72):
`varargout = {['EEG = pop_iclabel(EEG, ' version ');']};`

Resulting eegh entry:
`EEG = pop_iclabel(EEG, default);`

Should be:
`EEG = pop_iclabel(EEG, 'default');`

**Comment by arnodelorme** [comment]
This bug was apparently already fixed in version 1.2.6. Which version are you using. Thank you for spending the time to report problems.
