### ISSUE TITLE
Minor issue: pop_iclabel crashes if channel locations absent

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#167]
Minor exotic issue:

An unlikely case (and not sure whether a normal user can realistically get there), but if the user has not retrieved channel locations by the time he/she executes `pop_iclabel`, the function will produce a error when topoplotting. 

Suggested solution: Add check in `pop_iclabel `whether channel locations exist.

**Comment by arnodelorme** [comment]
Thank you. I have fixed the issue and this will be available in IC_label v 1.2.7.
