### ISSUE TITLE
Spectra and maps Error

### ISSUE THREAD

**Issue by Zeinebbensassi** [eeglabdevelopers/eeglab#169]
### Description

Not able to generate Spectra and Maps through the plot options with EDF data.

#### Steps to Reproduce

1. Import data
2.  Load channel location information
3. Plot Channel Spectra and Maps 
4. Plot > Channel spectra and maps

#### Expected behavior:
Spectral maps with freq and power info along with 2D images

#### Actual behavior:
EEGLAB ERROR in function spectcomp() at line [941]
![Capture d’écran 2020-06-09 à 13 26 47](https://user-images.githubusercontent.com/66676466/84142449-15a07200-aa55-11ea-9e6d-57372de556e0.png)

#### Versions

| OS version    : MAC
| Matlab version : 2020
| EEGLAB version : 2019

**Comment by arnodelorme** [comment]
You are missing the signal processing toolbox. Nevertheless, this function should use an alternate function. Would you mind to try with the development version of EEGLAB (the one that can be downloaded from GIT). I believe this was fixed recently. Then reopen the issue if you still experiencing the problem.
