### ISSUE TITLE
Events import bug

### ISSUE THREAD

**Issue by mzleena** [eeglabdevelopers/eeglab#170]
When I try to upload an events file I get error: line 1149 eegplot error.
How to solve this problem.?

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. Import data file 
[Uploading eeglabsubj2.txt…]

2. Import Event file 
[Events_sub2_subtract.txt](https://github.com/sccn/eeglab/files/4767757/Events_sub2_subtract.txt)

3. Go to Plot menu, channel data scroll

Error Message shows up 
EEGLab error in function eegplot() line 1149 
Matrix dimensions must agree

<br>
#### Expected behavior:
I expect it to plot the data with the event markers in it.

<br>
#### Actual behavior:
Error message (see above)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | 2019b |
| EEGLAB version | 2019.1 |

**Comment by arnodelorme** [comment]
I have tried again with no problem, creating a dataset with 100,000 data points.

data = rand(4, 100000);
EEG = pop_importdata('dataformat','array','nbchan',0,'data','data','srate',1000,'pnts',0,'xmin',0);
EEG = pop_importevent( EEG, 'event','/Users/arno/Downloads/Events_sub2_subtract.txt','fields',{'latency','type','duration'},'timeunit',NaN);

**Comment by arnodelorme** [comment]
<img width="705" alt="Screen Shot 2020-06-16 at 10 06 40 AM" src="https://user-images.githubusercontent.com/1872705/84792268-46365d80-afb9-11ea-98d1-e191cf5789a9.png">
