### ISSUE TITLE
GUI text for pop_spectopo seems to confuse milliseconds/samples

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#171]
EEGLAB version 2019_1

For `pop_spectopo`, the GUI asks for` "Epoch time range to analyze **[min_ms max_ms]**` 

This seems to be incorrect - at least in the case of continuous rather than epoched data, the GUI appears to expect the sample range rather than ms range. The sample range, that is,  `[0  size(EEG.data,2)]`, is also preset per default in this case (and written to `eegh`). 

Since some users may intend to only analyze certain parts/minutes of their dataset here, I'd consider this bug somewhat important.

**Comment by arnodelorme** [comment]
Seems to be working as expected for me.

**Comment by arnodelorme** [comment]
<img width="802" alt="Screen Shot 2020-06-16 at 10 50 54 AM" src="https://user-images.githubusercontent.com/1872705/84797387-5e10e000-afbf-11ea-95d9-238544427b96.png">

**Comment by arnodelorme** [comment]
And history is

figure; pop_spectopo(EEG, 1, [0 238304.6875], 'EEG' , 'percent', 15, 'freq', [6 10 22], 'freqrange',[2 25],'electrodes','off');

**Comment by arnodelorme** [comment]
All in millisecond. I am closing this report, but please reopen it if you judge the issue has not been addressed. Thank you for taking the time.

**Comment by olafdimigen** [comment]
You are right - sorry about that one. There's indeed no issue here. (Analyzed a dataset sampled at 1000 Hz, rather than my usual 500 Hz, that where the confusion came from).

**Comment by arnodelorme** [comment]
Thank you Olaf
