### ISSUE TITLE
EEGlab downloading compiled version on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by rbanerjee6** [eeglabdevelopers/eeglab#174]
Hello,

I downloaded the compiled Zip drive for my macOS Catalina 10.15.3. Myappinstaller_mcr file seems to not be working when try to install. When I open it up, it says "macOS cannot verify that the app is free from malware." Ive tried going on system preferences to allow for this, but even that seems to not work. Anything I can do at this point?

Thanks

**Comment by arnodelorme** [comment]
Yes, there are some compatibility issues. We are planning to recompile EEGLAB with Matlab 2020a which apparently is compatible with Catalina.

https://www.mathworks.com/matlabcentral/answers/468831-is-matlab-compatible-with-macos-catalina
