### ISSUE TITLE
Unintialised variable 'opt' in pop_erpimage when calling with no varargin

### ISSUE THREAD

**Issue by zenBen** [eeglabdevelopers/eeglab#176]
### Description

When calling pop_erpimage with no varargin, function hits line 668 with empty 'options' variable and thus enters block (line 669-680) which expects variable 'opt' to exist, but it doesn't.

<br>
#### Steps to Reproduce

1. Load valid data
2. Call pop_erpimage() with no varargin:
`pop_erpimage(eegA, 1, channel, [], title_str, smooth_val, decimate_val, sortype, [], sortfld)`

<br>
#### Expected behavior:
Plot of erpimage for given dataset and channel

<br>
#### Actual behavior:
Unrecognized function or variable 'opt'.

Error in pop_erpimage (line 669)
    if isfield(opt, 'topo')

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Ubuntu |
| Matlab version | R2019b |
| EEGLAB version | 2019_0 |

**Comment by arnodelorme** [comment]
We have made a change to the function bf65d3cb6. Would you mind to let us know if that works for you?

Arno

**Comment by arnodelorme** [comment]
The corrected function is available at 

https://github.com/sccn/eeglab/blob/develop/functions/popfunc/pop_erpimage.m

Please reopen the bug report if this does not fully fix the issue for you.
