### ISSUE TITLE
Bad-code bug when calling condstat.m from newtimef.m

### ISSUE THREAD

**Issue by zenBen** [eeglabdevelopers/eeglab#179]
### Description

When calling condstat.m from newtimef.m, the condstat parameter `bootside` must be scalar or line 86 will throw an error:
`if ~strcmpi(bootside, 'both') && ~strcmpi(bootside, 'upper')`

Line 86 is part of the following codeblock:
```
for index = 1:length(bootside)
	if ~strcmpi(bootside, 'both') && ~strcmpi(bootside, 'upper')
		error('Bootside must be either ''both'' or ''upper''');
	end
end;
```

So presumably the authors intended to _index_ bootside in line 86, like so?
```
for index = 1:length(bootside)
	if ~strcmpi(bootside(index), 'both') && ~strcmpi(bootside(index), 'upper')
		error('Bootside must be either ''both'' or ''upper''');
	end
end;
```

All places in newtimef.m where condstat.m is called are passing a fixed cell string array with two elements to the parameter bootside, so at least from newtimef.m this bug must always be triggered? 

<br>
#### Steps to Reproduce

1. Call newtimef

<br>
#### Expected behavior:

ERSP plot

<br>
#### Actual behavior:

```
K>> [resdiff resimages res1 res2] = condstat(formula, g.naccu, g.alpha, {'both' 'both'}, { '' g.condboot}, ...
                        alltfXpower, alltfXnorm);
Operands to the || and && operators must be convertible to logical
scalar values.

Error in condstat (line 86)
	if ~strcmpi(bootside, 'both') && ~strcmpi(bootside, 'upper')
```

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Ubuntu 18.04.4 LTS |
| Matlab version | R2019b |
| EEGLAB version | 2019_0 |

**Comment by arnodelorme** [comment]
This is correct. This has been corrected in  2099cffaf
