### ISSUE TITLE
EEGLAB error in function pop_writeeeg()

### ISSUE THREAD

**Issue by chanhowansunny** [eeglabdevelopers/eeglab#18]
EEGLAB error in function pop_writeeeg() at line 83:
Undefined function 'writeeeg' for input arguments of type 'cell'.

Pls help, thanks!!

**Comment by apavlo89** [comment]
Same issue :( Can anyone help with this? Chan did you figure it out?

**Comment by nucleuscub** [comment]
This function was moved to the plugin 'neuroscanio'. The issue is resolved once the plugin is installed. For this, see this page from the EEGLAB wiki: https://sccn.ucsd.edu/wiki/EEGLAB_Extensions#To_install_or_update_an_EEGLAB_extension
R
