### ISSUE TITLE
Alois code update

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#181]
Dear Arno,

attached are two patches for Eegkab (against commit f2fac387a6d35)

The first was necessary to make eeglab usable on octave 4.4 and 5.2.

The second patch enables the use mexbiosig (mexSLOAD/mexSOPEN) as a
possible alternative to biosig4octmat (sopen/sread/sclose/sload). This
has some improvments in terms of performance (performance, feature
support). Most notable it also improves support of EDF+ format
(multi-channel annotations, sub-second accuracy of timestamps).

Please consider these two patches for inclusion in EEGlab.

Best regards,
  Alois

**Comment by arnodelorme** [comment]
[Archive 2.zip](https://github.com/sccn/eeglab/files/4921496/Archive.2.zip)

**Comment by amisepa** [comment]
@arnodelorme Was this implemented? Because it may have the solutions to most issues we are having with annotations/events from EDF+ data. I looked at the files and have not idea how to implement it.

**Comment by amisepa** [comment]
I have tried to implement eeglab-0002-add-mexbiosig-support.diff by copy-pasting the changes, but it's not working.
[pop_biosig.zip](https://github.com/sccn/eeglab/files/6126255/pop_biosig.zip)

**Comment by arnodelorme** [comment]
Thanks for your effort. Let me know when it does work.

**Comment by arnodelorme** [comment]
@amisepa this is the modified file

**Comment by arnodelorme** [comment]
[pop_biosig.zip](https://github.com/sccn/eeglab/files/6152731/pop_biosig.zip)

**Comment by arnodelorme** [comment]
Use MELD or other tools to visualise changes https://www.git-tower.com/blog/diff-tools-windows/

**Comment by amisepa** [comment]
Done. I sent a pull request. It is working on my side.
