### ISSUE TITLE
Plot ERSP in plot channel

### ISSUE THREAD

**Issue by TristanVenot** [eeglabdevelopers/eeglab#182]
### Description
Hi again,

I am trying to plot the results from the ERSP, it does the precomputation but when I want to plot with the plot channel measures it gives this message (I did extract the baseline)  : 
![image](https://user-images.githubusercontent.com/48324026/87527004-ce2c8780-c68b-11ea-9169-e3091e58eb36.png)

I really don't know from where the problem comes from.
I join you in a drive datasets for you to create the study and see what you find.
https://drive.google.com/drive/folders/1_os1CRNXEQK6eF8PqxqkrlJET40gMmc8?usp=sharing
Thank you very much for taking the time.
Tristan

#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows] |
| Matlab version | [r2020a] |
| EEGLAB version | [v2020.0] |

**Comment by arnodelorme** [comment]
This is because your datasets only have one trial so they are considered continuous data. I have implemented a fix in b79ad1932 but using one trial for ERSP does not have much meaning.
