### ISSUE TITLE
Array indices must be positive integers or logical values.

### ISSUE THREAD

**Issue by Zeinebbensassi** [eeglabdevelopers/eeglab#183]
### Description

Array indices must be positive integers or logical values.

Error in readlocs (line 348)
   fileextension = filename(periods(end)+1:end);

Error in pop_chanedit (line 699)
                        [chans] = readlocs(tmpargs{:});
 
Error using inputgui (line 218)
Error while evaluating UIControl Callback.

#### Steps to Reproduce

1. Import EDF data
2. edit : channel location
3. No locations uploaded , i try to clic on 'read location' by selecting my file that i imported and than i have this error (picture 1)

<br>
#### Expected behavior:
I was expecting to have the location like with my others data

<br>
#### Actual behavior:
[Nothing happens i don't have any location]

<br>
#### Versions
EEGlab 2019

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | E2019a |
| EEGLAB version | EEGlab [2019|](url
![Error](https://user-images.githubusercontent.com/66676466/87784374-72523200-c836-11ea-
![What i expected](https://user-images.githubusercontent.com/66676466/87784396-81d17b00-c836-11ea-8c25-cb1b563fcf33.png)
![what i have](https://user-images.githubusercontent.com/66676466/87784405-872ec580-c836-11ea-9e88-9f2db71ecf91.png)

86fc-d0bff4347f45.png)

)

**Comment by arnodelorme** [comment]
Sorry for the late response. This is because you channel location file does not have an extension so the function cannot figure which type it is. I would just add ".txt" extension. I have fixed the issue d277b782a so the function does not return an error.
