### ISSUE TITLE
Bug in pop_select

### ISSUE THREAD

**Issue by fvalleinclan** [eeglabdevelopers/eeglab#187]
### Description

I came across what seems to be a bug. I have epochs from -12 to 1 s. When I select a time window including the 0 point (e.g., EEG = pop_select( EEG, 'time', [-6, -0] ), it works. However, when the time window does not include the 0 point (e.g., EEG = pop_select( EEG, 'time', [-6, -2] ), the resulting EEG structure contains only one epoch. 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [OSX 10.15.5] |
| Matlab version | [14b] |
| EEGLAB version | [2020] |

**Comment by arnodelorme** [comment]
Yes, there was a message on the EEGLABLIST about that. The solution is to define a new event at time -2 and epoch based on that event. It is not perfect but EEGLAB does not allow events which are not associated with data samples.
