### ISSUE TITLE
Bug in runica

### ISSUE THREAD

**Issue by StuJF** [eeglabdevelopers/eeglab#189]
### Description

  I encountered a pop up error(pop_runica error line 538), which is caused by function 'runica'. The code in function 'runica' at line 292 is
`elseif strcmp(Keyword,'interupt') `,
 however the input Keyword is 'interrupt'. After rewriting the code this function works.

#### Versions

| Matlab version | R2019b |
| EEGLAB version | 2020.0|

**Comment by arnodelorme** [comment]
This is because Fieldtrip is overloading your runica function as this code has been fixed a long time ago in EEGLAB. We will try to see if we can fix it in Fiedltrip as well.
