### ISSUE TITLE
pop_runica EEG structure mis-named

### ISSUE THREAD

**Issue by zenBen** [eeglabdevelopers/eeglab#19]
### Description

The EEG data structure is given the wrong name 'data' on line 357 of pop_runica
Variable 'data' is not defined and the function thus throws an error, as below.

`Undefined variable "data" or class "data.chanlocs.type".

Error in pop_runica (line 357)
    datatype = {data.chanlocs.type};`

<br>
#### Steps to Reproduce

1. Run ICA from a script using FastICA option

<br>
#### Expected behavior:
pop_runica will compute ICA and create ICA matrices in the EEG structure

<br>
#### Actual behavior:
pop_runica throws 'undefined vairable "data"' error.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Debian Linux |
| Matlab version | r2019a |
| EEGLAB version | development / latest from github |

**Comment by nucleuscub** [comment]
Thank for the detailed report, we have corrected the name of the variable. See commit [here](https://github.com/sccn/eeglab/commit/049055df5a0eca1652dd893f8dc8ddd35477931d).
R
