### ISSUE TITLE
pop_comperp.m missing from GUI

### ISSUE THREAD

**Issue by schalles** [eeglabdevelopers/eeglab#190]
### Description

Sum/Compare ERPs used to be a GUI menu item in v 14, but is missing in most recent version - it is still present for comparing component space ERPs, but not for sensor space.

| OS version     | Win10/xUbuntu 20.04|
| Matlab version |R2015|
| EEGLAB version | v2019.1 |

**Comment by arnodelorme** [comment]
Yes, it is still here. You need to go in the preferences and activate the old menus. This menu is obsolete because everything can be done better in studies.

**Comment by schalles** [comment]
Ah, thanks Arno.

I stopped using the study structure when I transitioned from human testing
in groups and now do almost exclusively single subject experiments with
dolphins.

Matt Schalles, Ph.D.
Research Associate
Auditory Neuroscience Lab, BU

**Comment by arnodelorme** [comment]
Sounds like fun :-)
