### ISSUE TITLE
Bug in newtimef()

### ISSUE THREAD

**Issue by xiaora1992** [eeglabdevelopers/eeglab#191]
The calculated energy will be squared when two eeglab tools are added into the Matlab path. Considering that loading two eeglab into the path is an improper operation, but this bug will have a significant impact on the results. Hope it helps.

| OS version |Win7 & Win10 |
| Matlab version |R2014b|
| EEGLAB version | v2019.1 & v14.1.2b|

**Comment by arnodelorme** [comment]
Thank you for your message. I do not think loading 2 versions of EEGLAB would have impact how newtimef calculates power. I would reach to the eeglablist@sccn.ucsd.edu if you have questions about the output of newtimef. Best wishes.
