### ISSUE TITLE
problem with importing .eeg format

### ISSUE THREAD

**Issue by amirmoeini1993** [eeglabdevelopers/eeglab#192]
### Description

https://www.dropbox.com/s/fdsxxpbuct3l42q/sub-S01.rar?dl=0

<br>
#### Steps to Reproduce

I try to load .eeg format with MatLab 
loadeeg('')
and with eeglab 
file>>>import data>>>use EEGLab functions and plugins>>>from neuroscan .EEG

<br>
#### Expected behavior:
loading data

<br>
#### Actual behavior:
I have a problem with importing .eeg format in EEG Lab although my data size is not so huge, it gives me an error at line 177 out of memory. I try with two different versions so I  want to make sure that data has no problem.

<br>
#### Versions
Windows10
matlab 2013a  matlab 2018b
EEGLAB 2013a EEGLAB 2019.0

**Comment by arnodelorme** [comment]
This is not a neuroscan file. You need to use the File-IO plugin to import this file (I did it successfully).

**Comment by arnodelorme** [comment]
@widmann I fixed an issue associated with reading that data (that reads OK under File-IO but made BVA-IO crash). We should issue a new release of BVA-IO (but see also my other comment).

**Comment by widmann** [comment]
Arno, sorry, I disagree with this change. The provided file is not standard conforming. The problematic line (9; "Data orientation: MULTIPLEXED=ch1,pt1, ch2,pt1 ...") should actually be commented/is a comment. If you prefix this line with a semicolon the file is loaded flawlessly.

Please revert the change. Thanks!

The bug presumably is in the MNE Analyzer export.

**Comment by arnodelorme** [comment]
OK, I agree with you. 

Could we though simply skip the line and show a message in red that the file is badly formed and might be corrupted and still import it. This is going to be a blocker for a lot of people. These files are BIDS files that are publicly released. And in BIDS datasets, they have to change not one but dozens of files manually.

Arno

**Comment by widmann** [comment]
Implemented as suggested.

Best,
Andreas

> Am 17.08.2020 um 18:53 schrieb Arnaud Delorme <notifications@github.com>:
> 
> 
> OK, I agree with you. 
> 
> Could we though simply skip the line and show a message in red that the file is badly formed and might be corrupted and still import it. This is going to be a blocker for a lot of people. These files are BIDS files that are publicly released. And in BIDS datasets, they have to change not one but dozens of files manually.
> 
> Arno
>

**Comment by arnodelorme** [comment]
Hi Andreas,

Are we ready to release a new revision of the new plugin?

Arno

**Comment by widmann** [comment]
No, I would like to wait for the revision of the ahdr import. See other msg.
Andreas

> Am 19.08.2020 um 18:17 schrieb Arnaud Delorme <notifications@github.com>:
> 
> 
> Hi Andreas,
> 
> Are we ready to release a new revision of the new plugin?
> 
> Arno
>

**Comment by arnodelorme** [comment]
OK. Once it is done, this is the link to upload a plugin revision to the plugin manager

http://sccn.ucsd.edu/eeglab/plugin_uploader/version_update.php

Or I can do it if you prefer.
Best wishes,

Arno
