### ISSUE TITLE
Error in function parsebvmrk() at line 40:

### ISSUE THREAD

**Issue by jbernard-McMaster** [eeglabdevelopers/eeglab#194]
### Description

I'm attempting to import a .vhdr file produced by Brain Vision Analyzer 2. The process fails with error:

EEGLAB error in function parsebvmrk() at line 40:

Operands to || and && operators must be convertible to logical scalar values.

#### Steps to Reproduce

The data I'm using is from https://osf.io/rmuje/.  I can upload one of the files but they're quite big (49,000 K).

Outside EEGLab:

1, Download the EEG1 file from OSF
2. Unzip the file
3. Go to .\EEG1\EEG1\35\export
4. Remove the "_" symbols from between "Pulse" and "Artifact" and "Correction" (I think this might be due to WinRAR adding them?)

Inside EEGLAB:

1. File > Import data > .. > From Brain Vis Rec vhdr file
2. Select the vhdr file from  .\EEG1\EEG1\35\export
3. Click OK (I've tried changing the interval and channels, but same error)
4. Error

#### Expected behavior:

The data should load.

#### Actual behavior:

It doesn't load.

#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10.0.18363 |
| Matlab version | R2020a 9.8.0.1323502 |
| EEGLAB version | I couldn't find a version number but if I click find update it says I'm using the latest |

**Comment by arnodelorme** [comment]
Moved to BVA-IO plugin https://github.com/widmann/bva-io/issues/11
