### ISSUE TITLE
error in function fmrib_fastr() at line 758

### ISSUE THREAD

**Issue by guangyuanzou** [eeglabdevelopers/eeglab#195]
### Description

EEGLAB error in function fmrib_fastr() at line 758:
Index exceeds matrix dimensions.

<br>
#### Steps to Reproduce

1. load data using load_bv
2. EEG=pop_fmrib_fastr(EEG,0,4,30,'R128',0,0,0,0,0,0.03,[],'auto')
3. I found that there was no error after I changed the averaging window length from 30 to 60, but I don't know why. There were 3 parts of MR artifacts in the EEG data (i.e., three MR sessions, but a single EEG file). Is that a problem?

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Ubuntu/Linaro 4.6.3-1ubuntu5 |
| Matlab version | 2016b |
| EEGLAB version | 14_1_1b/2020_0 |

**Comment by arnodelorme** [comment]
I am not sure about that. This is an old plugin that is no longer maintained (except for new Matlab version compatibilities). I do not think that having multiple MR artifacts in the EEG data is a problem. Maybe look at the Neuroimage paper describing the plugin.
