### ISSUE TITLE
ICLABEL fails: Input signal X must be a double-precision vector

### ISSUE THREAD

**Issue by AlanAHartley** [eeglabdevelopers/eeglab#200]
ICLABEL aborts with the message “The input signal X must be a double-precision vector., (Error occurred in function validateinput() at line 101)”. ICLABEL 1.2.6 installed. The EEGLAB preference for single precision is NOT checked.  Using a 64-bit PC.  SASICA runs without difficulty.  Problem seems to be unique to my installation/configuration:  When I take the same dataset to a friend’s lab, ICLABEL runs without problems.

**Comment by arnodelorme** [comment]
Moved to ICLABEL

https://github.com/sccn/ICLabel/issues/11
