### ISSUE TITLE
Different p-values masks between std_stat and statcondfieldtrip

### ISSUE THREAD

**Issue by CorentinWicht** [eeglabdevelopers/eeglab#201]
### Description

Dear EEGLAB,
I am reporting a strange finding of a discrepancy between the p-values masks (logical vector) returned by the ```std_stat``` wrapper function and the ```statcondfieldtrip``` function called by the former.

<br>
#### Steps to Reproduce

1. [*First Step: Generate random data*]
```
rng(1) % set seed for reproducibility 
data = { rand(50,10) rand(50,10)};  % 2 groups (between-subj design)
```

2. [*Second Step: run statistics*]
```
**Using EEGLAB std_stat wrapper function**
[~, pgroup, ~, ~, statsgroup] = std_stat(data, 'groupstats','on','fieldtripnaccu',5000,'fieldtripmethod','montecarlo','fieldtripmcorrect','max','fieldtripalpha',0.05,'mode','fieldtrip');

**Using FIELDTRIP statcondfieldtrip function which is called by std_stat**
Stats = statcondfieldtrip(SpectDataChan','paired','off','method','permutation','naccu',5000,'alpha',0.05,'fieldtripmcorrect','max','avgoverchan','yes','avgovertime','yes','structoutput','on');
```

3. [*Third Step: generate table output*]
```
Tab = array2table([statsgroup{:} Stats.stat pgroup{:} Stats.mask Stats.pval]);
Tab.Properties.VariableNames = {'EEGLAB.T' 'FIELDTRIP.T' 'EEGLAB.mask' 'FIELDTRIP.mask' 'FIELDTRIP.p'};
```

<br>
#### Actual behavior:

As you can see below the t-values are exactly the same but the p-values masks are different. Since std_stat doesn't return the p-values themselves, I cannot tell where the discrepancy is arising:

![image](https://user-images.githubusercontent.com/52161904/90873961-411dd200-e39f-11ea-93f3-16a9401099b4.png)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 Enterprise 17763 |
| Matlab version | Matlab R2019b |
| EEGLAB version | EEGLAB v.2020 (development version from GitHub) |

**Comment by arnodelorme** [comment]
Hi Corentin, this is because the function statcondfieldtrip uses 'mcorrect' as input and not 'fieldtripmcorrect.' std_stat uses 'fieldtripmcorrect'  to differentiate it from 'mcorrect' of EEGLAB. I have clarified the documentation and now return an error if you try using 'fieldtripmcorrect' with that function.

```matlab
Stats = statcondfieldtrip(data,'paired','off','method','permutation','naccu',5000,'alpha',0.05,'mcorrect','max','avgoverchan','yes','avgovertime','yes','structoutput','on');
```

will return the right correction.
