### ISSUE TITLE
Importing channel locations from ANT neuro

### ISSUE THREAD

**Issue by lucameroll** [eeglabdevelopers/eeglab#211]
Hello everyone!
I am acquiring eeg data with the ANT neuro's 64-channel system and I want to use eeglab to analyse the data. I am using Lab Streaming Layer (LSL) as software for data acquisition, which saves the file in .xdf format. One problem that I am facing is that the electrodes on eeglab are labelled as numbers, from 1 to 65 (because I have an EOG channel), and I would like them to be labelled following the 10-20 international system (so Fz, Cz, etc), this way is more clear. I am not interested in a source estimation, so I don't need anatomical precision, but I want to get the PSD under some electrodes to evaluate cognitive workload.
I have found an electrode locations file in .elc format, but when I try to load it I get this error:
"Index in position 1 exceeds array bounds (must not exceed 64)."
My eeg data matrix is 65x128000.

Unfortunately on other websites I could not find any helpful solution. Can somebody help me out, please?
Thank you in advance!
Luca

**Comment by arnodelorme** [comment]
Hi Luca,

If you know the correspondence
1 -> Cz
2 -> P3
...

Then simply change the labels in the channel editor after importing the file (menu item Edit > Channel locations). When you are done, select the button "Look up locs." to get the template localization for these electrodes. Save the dataset as you can reuse the location for other subjects (menu item Edit > Dataset info, then select channel location from other dataset).

**Comment by marieanselmet** [comment]
Hi @lucameroll,
I have the same issue and I would like to know how you even found your electrode locations file in .elc format ? From ANT neuro software directly ?
Thank you in advance,
Marie

**Comment by yst19941129** [comment]
> 

Did you solve this problem please?
