### ISSUE TITLE
Error in Topoplot Function

### ISSUE THREAD

**Issue by Prithila05** [eeglabdevelopers/eeglab#215]
### Description

I tried to get the topoplots for DEAP dataset for frequency range 0 to 256 at 1Hz interval. I get the error below, however, a smaller frequency range works just fine.

![image](https://user-images.githubusercontent.com/60676086/97657609-af86ac80-1a40-11eb-89cd-2a4b287e5d4d.png)

Can anyone please help me with this?

<br>

|   |   |
|----| ---- | 
| OS version     | [*windows 10*] |
| Matlab version | [*R2019b*] |
| EEGLAB version | [*v2020.0*] |

**Comment by arnodelorme** [comment]
This looks like you have not imported channel locations.

**Comment by Prithila05** [comment]
Hi,

Thank you for replying. For channel locations I followed the steps:
1. edit
2. channel locations
3. Use MNI coordinates for the BEM Dipfit model

![image](https://user-images.githubusercontent.com/60676086/97659252-e2cb3a80-1a44-11eb-9e2d-a770b510a182.png)

I get these results for a smaller frequency interval.

Thank you
