### ISSUE TITLE
Save Topoplots as image files

### ISSUE THREAD

**Issue by Prithila05** [eeglabdevelopers/eeglab#216]
Hi,

I wanted to save individual topoplot as image files something like this:

![image](https://user-images.githubusercontent.com/60676086/97658101-dabdcb80-1a41-11eb-86df-3c3a9c109eef.png)

I want to save several topoplot images for a wide frequency range. Can you please guide me on how to do that? 

Thank you!!

|   |   |
|----| ---- | 
| OS version     | [*windows 10*] |
| Matlab version | [*R2019b*] |
| EEGLAB version | [*v2020.0*] |

**Comment by arnodelorme** [comment]
This is a duplicate report of #215

**Comment by Prithila05** [comment]
Sorry These issues are not same

**Comment by arnodelorme** [comment]
You should direct your question to the eeglablist. This web site is for submission of bugs. Cheers.
