### ISSUE TITLE
Problem in loading EEG file

### ISSUE THREAD

**Issue by bsalafia** [eeglabdevelopers/eeglab#221]
Hello, when I upload my EEG file in EEGLAB it requires me to enter some information in the image that I have attached. So, I was wondering if there is any specific answer to these questions or I have to ask the person who got this data?

![photo_2020-11-17_10-27-15](https://user-images.githubusercontent.com/74611025/99409580-875fd000-28bf-11eb-9088-d77ec16755e9.jpg)

**Comment by arnodelorme** [comment]
You can just leave all options as default. You do not need to contact the person who collected the data.
