### ISSUE TITLE
plugin_status + plugin_askinstall: dependency check not working inside 'eegplugin_'-function

### ISSUE THREAD

**Issue by Lbuesing** [eeglabdevelopers/eeglab#225]
### Description

I am working on an eeglab extension which needs another extension (fieldtrip) to work properly. Inside the 'eegplugin_' function I placed a dependency check:

if ~plugin_status('fieldtrip-lite')
    plugin_askinstall('fieldtrip-lite', [], false); 
end

If eeglab is started with a clean workspace (PLUGINLIST not global yet), it creates an loop of not finding the fieldtrip extension, installing it and restarting eeglab (and not finding fieldtrip again).

Is there a way to make it work?

<br>
#### Steps to Reproduce

1. create an 'eegplugin_' function
2. place dependency check (see above)
3. start eeglab.m

<br>
#### Expected behavior:
function checks if plugin is installed and installs it, if not.

<br>
#### Actual behavior:
Plugin is not found (even if it is installed).
Plugin gets installed.
eeglab restarts.
Plugin is not found.
Plugin gets installed.
eeglab restarts... and so on.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Win 10 |
| Matlab version | R2019b |
| EEGLAB version | v2020_0 |

**Comment by arnodelorme** [comment]
Good question. Apparently, plugins are executed by alphabetical order.
So renaming your plugin folder with a letter than starts with after "f" fowercase could fix the issue.

But the solution I would use would be simpler. Simply do the check in the function called by the menu item not when the plugin starts. This is what other plugins do.
