### ISSUE TITLE
pop_saveset.m refers to .dat file: confusion with fdt?

### ISSUE THREAD

**Issue by sappelhoff** [eeglabdevelopers/eeglab#230]
The documentation in `pop_saveset.m` refers to the option to save binary data to `.dat`.

I thought EEGLAB uses `.fdt` for that?

https://github.com/sccn/eeglab/blob/e8e5dfb76777281e0513dc36306c4631afe2acf1/functions/popfunc/pop_saveset.m#L19

Questions:

- Was `.dat` used in the past and has now been replaced by `.fdt`?
- Is the documentation in `pop_saveset.m` thus currently outdated?
- What does `fdt` actually stand for?
- Are `.dat` files still around, or are they legacy-only? and should all be converted to `.fdt`?

**Comment by arnodelorme** [comment]
It used to use .dat. I have updated the documentation. Thanks.

**Comment by sappelhoff** [comment]
Thanks Arno!
