### ISSUE TITLE
pop_eegplot() note: Baseline subtraction disabled to speed up display

### ISSUE THREAD

**Issue by baharkk20** [eeglabdevelopers/eeglab#231]
### EEGPlot

[*Couldn't plot the data
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
[https://vumc.box.com/s/27h8ux6goysxqbl6nd3e9gcv7pw0s6sf](url)
1. I imported the data that is collected at EGI net station
2. Marked the R wave 
3. Plot -> channel data (scroll)

 I couldn't open the plot. When I try this is seen : 'pop_eegplot() note: Baseline subtraction disabled to speed up display' with this error: 

![image](https://user-images.githubusercontent.com/75824610/101866069-89732280-3b3d-11eb-8551-19f63eba1a93.png)

EEGLAB error in function eegplot() at line 1149:
Matrix dimensions must agree.

| OS version     | [*Windows 7 Professional Version 6.19 (Build 7601:Service Pack 1)*] |
| Matlab version | [*R2020a-academic use*] |
| EEGLAB version | [*EEGLABv2019.1*] |

Thank you so much for your time! 
Bahar

**Comment by arnodelorme** [comment]
What was the problem?

**Comment by baharkk20** [comment]
Hi Arnaud,

The data was collected at net station and marked for the heart beats but I couldn't plot when I load the .mff file. And then I figure out that when I load the .set file that is marked for heart beats, I could plot.
I had a new problem though and may be you could help with that or have an idea. The heartbeats marked through biopac and there is a shift at the marked beats (it is at -100ms or -150 ms) and I couldn't figure out what causes this problem.

Thank you so much for your time!

Kind Regards,
Bahar
