### ISSUE TITLE
EEGLAB error in function pop-loadstudy() at line 105: Reference to non-existent field 'design')

### ISSUE THREAD

**Issue by zachary6666** [eeglabdevelopers/eeglab#234]
I try to load the example STUDY file in Chapter 04: STUDY Data Visualization Tools, but I come up with this error: EEGLAB error in function pop-loadstudy() at line 105: Reference to non-existent field 'design')

MATLAB version R2020a

macOS Catalina: 10.15.7

<img width="502" alt="Screen Shot 2020-12-17 at 2 18 33 PM" src="https://user-images.githubusercontent.com/76181050/102532953-c033c600-4072-11eb-837a-787f159e0403.png">

**Comment by arnodelorme** [comment]
I have fixed this error in ba072c3d70c42beb04821dbe184887c781957685 . Thank you for reporting it.
