### ISSUE TITLE
Cannot writelocs with type 'custom'

### ISSUE THREAD

**Issue by cll008** [eeglabdevelopers/eeglab#239]
https://github.com/sccn/eeglab/blob/d404c63d9d181c64f7e24ed242585d4d05ee5da3/functions/sigprocfunc/writelocs.m#L115

The check currently only allows for 7 named export types (which contain read format info). It's not a critical feature, and maybe the best thing to do is to drop 'custom' format support by removing the custom' option from the drop down in pop_writelocs().

**Comment by arnodelorme** [comment]
Yes, sure. Let's do that. Can you push the change?

**Comment by arnodelorme** [comment]
Let's keep it as an option on the command line though.

**Comment by cll008** [comment]
Oops, should've probably committed 3f45698 with Closes #239...

Fixed with commit 3f456989efc96e76f5ff18aa3eb864a7f1a672f7
