### ISSUE TITLE
Can't load a existing dataset if the dataset has no the field 'ref'.

### ISSUE THREAD

**Issue by RanWX** [eeglabdevelopers/eeglab#248]
### Description
When use a existing dataset without the field 'ref', the eeglab (current version) will give an error message "EEGLAB error in function eeg_checkset() at line 1042..."

<br>

#### Steps to Reproduce

1.  Use the  eeglab (current version) to open a existing dataset without the field 'ref'.

<br>

#### Expected behavior:

Load the dataset.

<br>

#### Actual behavior:

Can't load.

<br>

#### Bug 

When I load a existing dataset, eeglab use the function pop_loadset(), and in this fuction, it call the function eeg_checkset(). In the line 1034 of  eeg_checkset() like this:

```
if isfield(EEG, 'ref')
            EEG.ref = '';
end
```

It means  when my dataset has the field of 'ref', the value of 'ref' will be set ''. And if the dataset has no the field of 'ref', it will do nothing, but the follow code will use the field of 'ref'. So it give the error message.

In the version of 14_1_2b, at the same position like this:

```
if ~isfield(EEG, 'ref'), EEG.ref = ''; end;
```

When my dataset  has no the field of 'ref', it will set this field with the value of ''.

<br>

#### Versions

| key  |  value  |
|----| ---- | 
| OS version     | [*Win 10*] |
| Matlab version | [*R2017b*] |
| EEGLAB version | [*eeglab_current (modified by 2020/8/6)*] |

**Comment by arnodelorme** [comment]
Thank you. You are correct, I will review the code to see how this bug came to be.
