### ISSUE TITLE
EEGLAB 2021.0 release candidate 

### ISSUE THREAD

**Issue by denizdor** [eeglabdevelopers/eeglab#252]
Hello,

I am trying out the new version of EEGlab. I came across the following error while initiating eeglab.

**Undefined function or variable 'p'.

Error in eeglab (line 947)
        [dircontent(:).folder] = deal(fullfile(p, 'plugins')); **

1. Unzipped the Matlab version under my Matlab directory (Matlab 2016a)
2. Selected directory and typed 'eeglab' from the command window

| OS version: MacOS BigSur
| Matlab version 2016a 
| EEGLAB version: EEGLAB 2021.0 release candidate  Matlab version

Thanks!
Deniz

**Comment by arnodelorme** [comment]
Thank you Deniz. This occurred because of the version of Matlab you are using. We have been able to reproduce the problem in Matlab 2014 and fixed it in 1326485a4 (replacing “p" by “eeglabp” on line 947). Thank you again for your contribution.
