### ISSUE TITLE
EEGLab not recognizing AMICA plugin

### ISSUE THREAD

**Issue by isim95** [eeglabdevelopers/eeglab#256]
### Description

Running EEGLab 2020.0 on mac Catalina. amica1.5 folder is under the plugins path, and the amica15mac file permissions have been changed through terminal. However, when I open EEGLab from MatLab, I do not see AMICA as an option under 'Tools'.

<br>
#### Steps to Reproduce

1. Download eeglab & set up
2. download AMICA, place in EEGLab plugins folder, change amica15mac file permissions with chmod 777 amica15mac on terminal
3. open eeglab
4. load dataset
5. filter with range .5 - 50 hz
6. 

<br>
#### Expected behavior:
amica should be an option under 'Tools'

<br>
#### Actual behavior:
AMICA is not an appearing as an option

<br>
#### 2020.0

|   |   |
|----| ---- | 
| OS version     | [Catalina 10.15.7|
| Matlab version | R2020b|
| EEGLAB version | 2020.0 |

**Comment by arnodelorme** [comment]
Amica creates its own menu.

Tools > Run Amica

I have just installed the plugin from the plugin manager and I can see it. I did not have the change the permission to the amica15mac file either. It worked right away.

**Comment by isim95** [comment]
This doesn't work for me. I installed from the plugin manager and got the attached error. I've tried installing both ways and am unable to see the Run Amica option under Tools.


<img width="688" alt="Screen Shot 2021-02-14 at 8 22 18 PM" src="https://user-images.githubusercontent.com/75797725/107905023-587ae980-6f02-11eb-8325-2421a45794e1.png">

**Comment by isim95** [comment]
Apologies, forgot to thank you for the original response! Thank you!

**Comment by arnodelorme** [comment]
Would you mind to try downloading it from this page?

https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php

**Comment by isim95** [comment]
I got this to work, thank you, and apologies for the inconvenience.

However, I'm not getting the attached error when actually running amica that I'm not quite sure what to do with. Are you potentially able to help with this?
![Uploading Screen Shot 2021-02-15 at 9.36.19 AM.png…]()
