### ISSUE TITLE
Cleanline and Blinker path broken with EEGLAB 2021.0

### ISSUE THREAD

**Issue by CorentinWicht** [eeglabdevelopers/eeglab#265]
Dear Arnaud,

I recently updated my old _EEGLAB v14.1.2b_ to the new _EEGLAB 2021.0_ version (many thanks for this update). 
Nevertheless, I am encountering an issue I haven't seen earlier which seems to be specific to some plugins (e.g. _Cleanline 2.0_ and _BLINKER 1.1.2_). 

While both plugins are up-to-date,  correctly loaded at EEGLAB startup and adequately included in MATLAB environment path, running simple commands such as e.g. `checkBlinkerDefaults(struct(), getBlinkerDefaults(EEG));` for BLINKER, returns an error that make it look like the path is not set correctly:
![image](https://user-images.githubusercontent.com/52161904/110469985-98388980-80da-11eb-9b94-0cbd5a4e8e40.png)

I recently opened a similar issue on the Cleanline Github page thinking  at first it was specific to one plugin:
https://github.com/sccn/cleanline/issues/3

What makes me think it is an EEGLAB-related issue is that running the following fixes the bug:
```
addpath(genpath('E:\GitHub\autoERP\Functions\eeglab2021.0\plugins\Cleanline2.00'))
addpath(genpath('E:\GitHub\autoERP\Functions\eeglab2021.0\plugins\blinkerv1.1.2'))
```

Did anyone report this issue already?

Best,

Corentin

**Comment by arnodelorme** [comment]
It is interesting. These two plugins have issues with the internal version being different than the exposed one. I fixed it and also put Blinker on the EEGLAB plugin manager. However, I could not find the problem. The paths are added properly for me.

**Comment by arnodelorme** [comment]
I have tried on Windows now and cannot see the problem either. I think it might have to do with a strange path configuration. Usually, you should just start EEGLAB and all the paths will be added. Let me know if you get more insight as to what the problem might be. I am closing this for now, but feel free to reopen.

**Comment by enricovara** [comment]
Hi!

I have this issue on a Mac with MATLAB R2019b and EEGLAB v2022.0 and Cleanline v2.0.0.

Please let me know if I can help solve this by providing more information.

Best wishes,
Enrico

**Comment by arnodelorme** [comment]
Hi Enrico,
Thank you for reviving that. Can you try again now. I have updated the Blinker plugin.
