### ISSUE TITLE
SIFT 1.52 crashes BSS

### ISSUE THREAD

**Issue by UgoBruzadin** [eeglabdevelopers/eeglab#266]
The SIFT plugin has a function called pca that is a conflict with the matlab pca function. When I call BSS artefact removal, it crashes saying: "There must be exactly 3 outputs.," in line 139. Problem was solved once I changed the pca.m (inside SIFT plugin) function's name to pca2.m, or remove the SIFT plugin altogether.

**Comment by arnodelorme** [comment]
Thank you for your comment. I have moved this comment to SIFT repo.
