### ISSUE TITLE
EEGLAB error in function loadeeg() at line 141:

### ISSUE THREAD

**Issue by uyanbekardes** [eeglabdevelopers/eeglab#271]
#I have eeg data i will open it but i get this errorcode what can i do ?
![EEG](https://user-images.githubusercontent.com/46527832/111464910-b4af7400-8721-11eb-9751-31dc24e10295.png)

**Comment by arnodelorme** [comment]
Are you trying to import Neuroscan files? This function is only to import an old version of neuroscan files with the extension .eeg

**Comment by uyanbekardes** [comment]
yes i try to import eeg. data how can i open it ?

**Comment by arnodelorme** [comment]
This is not the correct menu for the file you have. You should describe your files and send a message to the eeglablist@sccn.ucsd.edu
