### ISSUE TITLE
EEGLAB error in function eeg_autocorr_fftw() at line 27

### ISSUE THREAD

**Issue by shutli1127** [eeglabdevelopers/eeglab#273]
[ED1_P.zip](https://github.com/sccn/eeglab/files/6169746/ED1_P.zip)

### Description

Undefined function 'resample' for input arguments of type 'double'
I cannot use the 'Tools - Classify components using ICLabel - Label components' in the EEGLAB

<br>
#### Expected behavior:
I want to give the component figure and justified score after ICA.

<br>
#### Actual behavior:
There is an error

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10|
| Matlab version | 2020a |
| EEGLAB version | v2020.0 |

**Comment by arnodelorme** [comment]
Missing signal processing toolbox
