### ISSUE TITLE
Option 'verbose' in pop_epoch is ignored

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#277]
### Description

Input of option 'verbose' in pop_epoch is ignored. This option is indeed not used in the code.

**Comment by nucleuscub** [comment]
@arnodelorme, I can fix this so we indeed suppress any print, or remove the option. I find the verbosity of the function in demos a bit annoying, so it would be nice to have the option to shut it down. However, any option is good as long as we are consistent. Let me know.
Cheers,
R

**Comment by arnodelorme** [comment]
Yes, please do. Thanks, Ramon.

**Comment by arnodelorme** [comment]
Did it in 6c666c1aa
