### ISSUE TITLE
BIDS installation through plug-in manager: wrong folder hierarchy

### ISSUE THREAD

**Issue by cll008** [eeglabdevelopers/eeglab#278]
When installing bids-matlab-tools5.3.1 through the EEGLAB gui, the files are nested in `plugins\bids-matlab-tools5.3.1\bids-matlab-tools5.3.1` (also `plugins\bids-matlab-tools5.3.1\_MACOSx` is downloaded). A couple other plug-ins install normally.

| OS version     | [Win 10] |
| Matlab version | [2019a |
| EEGLAB version | [2021.0] |
bids-matlab-tools@5.3.1

**Comment by arnodelorme** [comment]
Would you mind to try to put them in a new ZIP and resubmit the plugin?

http://sccn.ucsd.edu/eeglab/plugin_uploader/version_update.php

Arno

**Comment by cll008** [comment]
Done
