### ISSUE TITLE
rounding problem in eeg_point2lat

### ISSUE THREAD

**Issue by Nyx333** [eeglabdevelopers/eeglab#279]
On line 102, the code is newlat = round(newlat*1E9)*1E-9. When I run this line of code, I get rounding errors, and problems further down the track. However, when I run:  newlat = round(newlat*1E9)/1E9, I dont get rounding problems or problems further down the track. I honestly dont know why it matters, but apparently: (round(newlat*1E9)*1E-9)==(round(newlat*1E9)/1E9) always comes out as false, with a difference of 2.8422e-14. Again, I dont know why there is a difference, but it fixed a whole number of problems I was having. I found it running the line of code: pop_select( EEG, 'point', [ 1, EEG.pnts]). So I was selecting all the data, the reason for that was because another function found that no samples needed to be thrown out (clean_windows). Moreover, the previous line of code would remove samples, even when I have asked for all the data back.

So again: 

newlat = round(newlat*1E9)/1E9

in place of:

newlat = round(newlat*1E9)*1E-9

Im really sorry if Ive missed something obvious, but it really did solve a lot of issues for me.

**Comment by arnodelorme** [comment]
Thanks, we have implemented the fix a7cdc2edb
