### ISSUE TITLE
Bug in newtimef() when using old output format (minor, legacy)

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#281]
When using the old output format option of the current version of `newtimef`, that is

`'outputformat','old', % newtimef input parameter`

...this produces an error on line 1444 of newtimef(): 

`if strcmpi(g.scale, 'log'), mbase = 10^(mbase/10); end`

```
Incorrect dimensions for raising a matrix to a power. Check that the matrix is square and the power is a scalar. To perform
elementwise matrix powers, use '.^'.

```
To my (superficial) understanding, I believe this should be the element-wise operator, that is:

`if strcmpi(g.scale, 'log'), mbase = 10.^(mbase/10); end`

|----| ---- | 
| OS version     | Win10 |
| Matlab version | R2020a |
| EEGLAB version | 2021.0 |

**Comment by arnodelorme** [comment]
This is correct. I have implemented the fix. 5129ce7ff
