### ISSUE TITLE
eeg_eegrej: misleading warning if two events on last sample

### ISSUE THREAD

**Issue by widmann** [eeglabdevelopers/eeglab#284]
### Description

When removing regions from a file with two valid events on the last sample a warning is thrown:

```
Warning: Discrepency when recomputing event latency.
Try to reproduce the problem and send us your dataset 
> In eeg_eegrej (line 203)
```

The event is not actually deleted from the resulting dataset, thus not really harmful, but the error message is troubling and tracking down the problem is cumbersome.
<br>

#### Steps to Reproduce

1. Add two events at the last sample
2. Remove an arbitrary region from the data file with eeg_eegrej
<br>

#### Expected behavior:
No or more informative warning.
<br>

#### Actual behavior:
The above warning message.

In line 139:
```
if length(event2) > 2 && event2(end).latency == event2(end-1).latency, event2(end) = []; end
```
the last event is removed from the event2 reference structure if the last two events have the same latency. This is however a valid use case occurring quite frequently here. I suggest
- additionally comparing the event2.type
- give a more informative warning message
<br>

#### Versions

|   |   |
|----| ---- | 
| OS version     | any |
| Matlab version | any |
| EEGLAB version | v2021.0 (and earlier) |

**Comment by arnodelorme** [comment]
This is a good point. I have added a check for the event type when the field is present in 4cf00d819
