### ISSUE TITLE
Enhancement: allow MATLAB file format version 7 in pop_saveset

### ISSUE THREAD

**Issue by widmann** [eeglabdevelopers/eeglab#285]
### Description

pop_saveset currently allows only MATLAB file format versions 6 and 7.3.
- Version 6 does not include compression
- Version 7.3 is HDF5 based. HDF5 has problems saving structures in general and structures within structures in particular (as for example event structure in EEG structure) blowing up on disk file size beyond reasonable limits. The MATLAB HDF5 implementation appears to be particularly problematic.

Example: The on disk file size and time required for saving a simple EEG file. The only special thing about it is that it contains some more events than usual.
- v6: 86 MB, 0.3 secs
- v7: 26 MB, 2.11 secs
- v7.3: 115 MB, 12.8 secs

v7 appears to give best file size vs. speed tradeoff. Note that v7.3 is *with* compression.

Find attached a simple patch allowing to save in v7 file format: [pop_saveset.txt](https://github.com/sccn/eeglab/files/6377924/pop_saveset.txt)

Personally, I would suggest to consider using file format version 7 instead of 6 (or even better both) for the persistent configurable user preference (Octave can read and write v7 files).
<br>

#### Versions

|   |   |
|----| ---- | 
| OS version     | any |
| Matlab version | any |
| EEGLAB version | v2021.0 and earlier |

**Comment by arnodelorme** [comment]
Thank you Andreas. I have applied the patch. ceb4e88
