### ISSUE TITLE
EEGlab study - plot channel measures (average potentials)

### ISSUE THREAD

**Issue by santonial** [eeglabdevelopers/eeglab#286]
Good morning,

I am currently working with ERP data using EEGlab study GUI. I want to use the "plot channel measures" option to plot averaged potentials of selected channels and display statistics. If I select up to five channels, the output displays the statistic correctly as in the image:
![Immagine1](https://user-images.githubusercontent.com/83275467/116212682-5ecce380-a745-11eb-899f-a72e7ed232fa.png)

However, if I select more than five channels the statistics are not dislayed at all: 
![Immagine2](https://user-images.githubusercontent.com/83275467/116212684-5f657a00-a745-11eb-8a3b-f4a09bbd0506.png)

| OS version     | [Windows 10 |
| Matlab version | R2020.a |
| EEGLAB version | v2021.0 |

I had the same issue with previous versions of EEGLAB.
As I need to work with clusters of channels for display purposes, it would be helpful for me to understand what is the issue.
Thank you,
Alessia

**Comment by arnodelorme** [comment]
I understand. This seems like an easy fix. Let us look into it.

**Comment by arnodelorme** [comment]
This has been fixed in the GitHub version 3eb7b4b03
Thank you for reporting the problem
