### ISSUE TITLE
EEGLAB reports a new version available for a plugin which is superseded.

### ISSUE THREAD

**Issue by iras** [eeglabdevelopers/eeglab#29]
I get this line on opening EEGLAB 2019_0 in MATLAB..
`EEGLAB: adding "dipfit" v3.2 (see >> help eegplugin_dipfit) - new version 3.0 available`

The dipfit version present in the EEGLAB plugins folder is newer (3.2) than the one prompted in red (3.0).

**Comment by nucleuscub** [comment]
Hi @iras, 
 We noticed this behavior a couple of weeks ago and we fixed in the version on the '_develop_' branch. This fix will eventually make it to the stable release. 
 Thanks, 
R
