### ISSUE TITLE
Citation for eeg_interp's spherical interpolation method?

### ISSUE THREAD

**Issue by a-hurst** [eeglabdevelopers/eeglab#293]
### Description

I've been doing some work with the PREP Pipeline for EEGLAB, and noticed that it uses two separate methods of spherical spline interpolation, specifically [`sphericalSplineinterpolation.m`](https://github.com/sccn/clean_rawdata/blob/master/private/sphericalSplineInterpolate.m) from the `clean_rawdata` EEGLAB plugin and `eeg_interp.m` from EEGLAB itself. Surprisingly, I've noticed that these two methods give different numeric results for the same data.

Looking into it myself, I noticed that `clean_rawdata`'s function cites [Perrin et al. 1989](https://doi.org/10.1016/0013-4694(89)90180-6) as the basis for its code, but that `eeg_interp` makes no similar citation. `eeg_interp` also seems to have a  different method of calculating `g` values than the Perrin paper, using relative linear distances (I think?) instead of cosine angles (which produces different `g` values vs `sphericalSplineinterpolation` for the same input locations):

https://github.com/sccn/eeglab/blob/6c666c1aa9f221f224fbb3301ef186644bdcbfe0/functions/popfunc/eeg_interp.m#L347-L353

Additionally, the values used to calculate `pinv(C)` in both methods seem to be different, with different input values for each. Is there a specific paper that EEGLAB's interpolation approach is based off of? If so, would it be possible to add a reference in the docstring? I'm trying to figure out whether one method is theoretically better than the other, but without understanding the rationale behind `eeg_interp`'s code that's hard to evaluate.

Thanks in advance!

#### Steps to Reproduce

(Can write an example script if needed, but it seems unnecessary given the lack of an obvious error)

#### Versions

|   |   |
|----| ---- | 
| OS version     | [macOS 10.13.6] |
| Matlab version | [2020a] |
| EEGLAB version | [2021.0] |

**Comment by cll008** [comment]
Not sure if @arnodelorme has a citation for that implementation... @a-hurst, have you posted the theory question on the [EEGLAB mailing list](https://eeglab.org/others/EEGLAB_mailing_lists.html)? Some experts may respond there.
