### ISSUE TITLE
cannot load .cnt data

### ISSUE THREAD

**Issue by saskianijmeijer** [eeglabdevelopers/eeglab#294]
### Description

Loading the .cnt data file using pop_loadcnt(EEGfile) does not work. Different .cnt files result in differnt errors. 4 different datafiles of 2 subjects can be found here: https://www.dropbox.com/sh/picap3jzcgrsnm3/AACohZNJnJNCBXqF-BeHig56a?dl=0

<br>
#### Steps to Reproduce

1.  pop_loadcnt(EEGfile) 

<br>
#### Versions

|   |   |
|----| ---- | 
| Matlab version | 2020a|
| EEGLAB version | 2021|

**Comment by cll008** [comment]
switch_1004.cnt imports correctly for me `EEG = pop_loadcnt(filename , 'dataformat', 'auto', 'memmapfile', ''`
switch_0001.cnt and switch_004.cnt are missing electrode locations, events, and data from the 'end tag' of the files
switch_1001.cnt seems to have an incorrect number of channels and datapoints... 

Do you have more datasets that do work? Is there any chance that the three datasets that won't load are recorded incorrectly or corrupted (file transfer or compression issues)? The fact that both 'pre' files fail in one way and one of the 'post' files fails in another way is interesting (but might be pure chance).
