### ISSUE TITLE
EEGLAB error in function plugin_menu() at line 39

### ISSUE THREAD

**Issue by colorfulclouds** [eeglabdevelopers/eeglab#30]
I don't know why.

**Comment by nucleuscub** [comment]
@colorfulclouds ,  I think I know what you are referring to,  but... This is not a proper way to report an issue. Templates and documentation have been provided to ensure that issue report contains the information necessary to reproduce and fix the error. Please, follow those indications while reporting an issue. 
A quick search in the previous issues will bring that the problem you are reporting has been already addressed: see [issue 20](https://github.com/sccn/eeglab/issues/20) and its duplicates.
 Hope this helps,
R

**Comment by colorfulclouds** [comment]
ok , thx




------------------ 原始邮件 ------------------
发件人: "Ramon Martinez-Cancino"<notifications@github.com>; 
发送时间: 2019年7月18日(星期四) 凌晨1:23
收件人: "sccn/eeglab"<eeglab@noreply.github.com>; 
抄送: "飞飞"<1228794458@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sccn/eeglab] EEGLAB error in function plugin_menu() at line 39(#30)




@colorfulclouds ,  I think I know what you are referring to,  but... This is not a proper way to report an issue. Templates and documentation have been provided to ensure that issue report contains the information necessary to reproduce and fix the error. Please, comply with the conduct code on this.
 Also, a quick search in the previous issues will bring that this problem as been addressed : see issue 20 and its duplicates.
