### ISSUE TITLE
Fail to resample using eeglab

### ISSUE THREAD

**Issue by AAAnais** [eeglabdevelopers/eeglab#300]
"EEGLAB error in function chckxy()" has been reported.

The resample step could used to be run. Recently this error was reported and fail to fail this step.

**Comment by arnodelorme** [comment]
Would you mind to be more specific about the error. Which version of Matlab and signal processing toolbox are you using.

**Comment by cll008** [comment]
@AAAnais did you recently update EEGLAB? Have you tried reprocessing some data that you know could be resampled in the past? Closing this issue for now but please reopen if you would like to continue working on this issue.
