### ISSUE TITLE
eegplot before and after a regression

### ISSUE THREAD

**Issue by DavidGHaydock** [eeglabdevelopers/eeglab#304]
I have a simple regression that changes the values in EEG.data, but when I apply EEG plot before and after the manipulation, as well as other plotting functions, there is no difference between the plots before and after. I feel I may be doing something wrong, but I have made sure my regression actually changes things, have tried saving the data before and after in separate files and comparing etc, but even though both have different values in their EEG.data, the plots come out identical.

**Comment by CPernet** [comment]
Hi David, it's hard to tell why this doesn't work -- I can propose as an alternative to use STUDY and call [LIMO](https://github.com/LIMO-EEG-Toolbox/limo_tools) which will regress whatever you want
