### ISSUE TITLE
build preclustering array problem

### ISSUE THREAD

**Issue by Pengpeichu** [eeglabdevelopers/eeglab#309]
I did these steps
![messageImage_1623722216134](https://user-images.githubusercontent.com/73431927/121981408-2ef2a180-cdc0-11eb-8d4d-2ee857fdc174.jpg)
but I encounter the problem below.

![messageImage_1623722085140](https://user-images.githubusercontent.com/73431927/121981593-81cc5900-cdc0-11eb-8c13-7d9bc2fae107.jpg)
I checked the select by rv in the edit window

**Comment by arnodelorme** [comment]
You will need to localize dipoles if you want to use them for clustering.
