### ISSUE TITLE
Error for plot ERSPs when no varialbles are selected in the study design

### ISSUE THREAD

**Issue by HTGorji** [eeglabdevelopers/eeglab#31]
Hello,

When no variable selected in the study design I cannot plot my ERSPs, while I have no problem with EEGALAB 14. When I updated to 2019 version I have this problem.
the error is:  `EEGLAB error in function std_erspplot() at line 210:`
I would be so thankful if you could solve it.

Best,
Hamed

**Comment by nucleuscub** [comment]
Hi @HTGorji,
_% When no variable selected in the study design_
Do you mean in pop_studydesign?

_% I cannot plot my ERSPs_
From where?

Please provide accurate information in order to address and reproduce your issue.
 Thanks,
R

**Comment by arnodelorme** [comment]
This has been fixed. Use the development version of EEGLAB (the one available on Github).
