### ISSUE TITLE
Error in using eegfilt function with 'fir1' type

### ISSUE THREAD

**Issue by sirenxi** [eeglabdevelopers/eeglab#320]
Received errors down below when loaded parameters as suggested by the eegfilt function with 'fir1' type.

Error using  * 
Incorrect dimensions for matrix multiplication. Check that the number of columns in the first matrix matches the number of rows
in the second matrix. To perform elementwise multiplication, use '.*'.

Error in firls (line 79)
    cos_ints = [omega; sin((1:N)' * omega)];

Error in fir1>eFir1 (line 170)
    hh = firls(L-1,freq,magnitude);

Error in fir1 (line 92)
    [b,a] = eFir1(varargin{:});

Error in eegfilt (line 175)
        filtwts = fir1(filtorder, locutoff./(srate/2), 'high');

It seems that the desiredfreq() in the fir1() function creates a omega as a column vector that does not compatible with sin(1:N)'.

**Comment by arnodelorme** [comment]
Would you mind to share your data and the function call or menu sequence to reproduce the issue?

**Comment by arnodelorme** [comment]
Would you mind to share your data and the function call or menu sequence to reproduce the issue?
