### ISSUE TITLE
Modulation Index Value EEGLAB PACTools

### ISSUE THREAD

**Issue by cristinabenetton** [eeglabdevelopers/eeglab#322]
### Modulation Index Value EEGLAB PACTools

I have one question regarding the plugin PACTools to compute PAC on EEG resting state data. 

After estimating PAC on my dataset, I plot the comodulogram results. Do you know if there is a way in which I can extract the Modulation index single value to then do statistics on it? Either the maximum modulation index value in the comodulogram or maybe a z-score based on the comodulogram.

<br>
#### Steps to Reproduce

1. Open a dataset in EEGLAB
2. Compute PAC [_Tools --> PAC Tools --> Estimate PAC_]

![image](https://user-images.githubusercontent.com/86304995/123615561-b64f0480-d805-11eb-8ef5-c0edfd204d69.png)

3. Plot PAC estimation [Tools --> PAC Tools --> Plot PAC]

![image](https://user-images.githubusercontent.com/86304995/123615669-d252a600-d805-11eb-9b4b-21d5e4f2d649.png)

4. Plot the Comodulogram

Here I stop and don't know where to find the Modulation Index value

**Comment by arnodelorme** [comment]
@nucleuscub any clue? Tx.

**Comment by arnodelorme** [comment]
@nucleuscub how can we help?

**Comment by nucleuscub** [comment]
Hi Arno, I transferred this issue to the pactools repo and replied to her
from there. Alll good with this. Ppl just don't read the documentation. 🙄

Thks for letting me know.
Cheers.
R

**Comment by arnodelorme** [comment]
Thanks so ugh Ramon for taking the time.
