### ISSUE TITLE
Writing to EDF

### ISSUE THREAD

**Issue by Andesha** [eeglabdevelopers/eeglab#33]
### Description

When attempting to export a file to EDF via the menu (File -> Export) with either the Biosig or Fileio plugin installed, EEGLAB crashes as the pop_writeeeg function is undefined.

In previous versions of EEGLAB, the functions pop_writeeeg and writeeeg were included as part of base EEGLAB. Perhaps it got removed by accident?

Thanks!

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Ubuntu 19.04 |
| Matlab version | 2019a |
| EEGLAB version | Development Head |

**Comment by nucleuscub** [comment]
@Andesha , 
You must install the EEGLAB plug-in **neuroscanio**. This will fix this issue. The function _pop_writeeeg_ is now part of this plug-in.
Hope this helps,
R
