### ISSUE TITLE
MW project: Run Matlab script at SDSC

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#336]

**Comment by arnodelorme** [comment]
See video @jnnstchr

https://drive.google.com/file/d/1RtCOqC3DOOt0UJDbGoJXHfhGsX1KDvcJ/view?usp=sharing

**Comment by arnodelorme** [comment]
Tasks:
- Get the script to run on Expanse
- Try to do commits on our repo, set up SSH for Github

**Comment by arnodelorme** [comment]
In addition to setting up SSH with expanse, you might want to use the same private key for GitHub. You would need to add both your local key and your expanse key. This way you can push code from both sides.
Here is how to do it

https://www.youtube.com/watch?v=nQDFBd5NFA8

**Comment by jnnstchr** [comment]
I did setup the SSH keys both my local computer and expanse, created my own branch for childmind repository and pushed the modified script, pulled the master branch on my expanse account. I do not have the permission to access /expanse/projects/nemar, however I managed to copy both the eeglab and the previously used file from my local computer with sftp, unpack it, modify the path again and run it on expanse.

**Comment by arnodelorme** [comment]
This part is done.

**Comment by jnnstchr** [comment]
I'm added to nemar group now and all the paths work as expected

**Comment by arnodelorme** [comment]
Great.
