### ISSUE TITLE
STUDY plot ERPimage error

### ISSUE THREAD

**Issue by tingyu653** [eeglabdevelopers/eeglab#341]
### Description
After precompute channel measures, I set the parameters of ERP as 78 trials(because the number if total trials of the experiment is 78). 
However, I got the error.
Should I check if any of my data's trials is less than 78?
![image](https://user-images.githubusercontent.com/85797007/124381275-3557a780-dcf4-11eb-9c03-35b12d27a19f.png)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*R2020a*] |
| EEGLAB version | [*v2020.0*] |

**Comment by arnodelorme** [comment]
Yes, this is correct. Reduce the number on the precompute screen.
