### ISSUE TITLE
fmrib toolbox bug

### ISSUE THREAD

**Issue by DBermudez0** [eeglabdevelopers/eeglab#349]
fmrib plugin to EEGLAB (bug)

Hi,

I am using the fmrib toolbox plug-in to remove the gradient artifact in simultaneous EEG-fMRI. However, I run into the following bug during slice alignment: cannot match the size of A to the iterator when it uses the pcoor2 function. I don't know where else to seek advice on this issue since I had trouble registering as a new user to the eeglablist platform. Can you give me advice on how to resolve this issue? If not, can you give me information on who to contact for advice on this bug?
Versions
Linux (Ubuntu 20.04)
Matlab 2021a
EEGLAB v 2020_0
fmrib v 1.21

Thank you,
Dalton

**Comment by arnodelorme** [comment]
I see that you submitted the bug at https://github.com/sccn/fMRIb/issues/10
Unfortunately, we do not support that plugin. Consider contacting the author or hiring someone to fix it.
