### ISSUE TITLE
EEGlab LIMO data analysis

### ISSUE THREAD

**Issue by sasis001** [eeglabdevelopers/eeglab#350]
Hi,

Do you provide assistance with data analysis using the LIMO plugin? I have run the data set twice and both times the beta files are empty, although the program is generating the output files for each subject. The other steps to the analysis worked fine and I can compute channel and component measures when using just EEGlab without LIMO.

Thanks,
Jay

**Comment by arnodelorme** [comment]
Transfered to https://github.com/LIMO-EEG-Toolbox/limo_tools/issues/71
