### ISSUE TITLE
Download page not redirecting to page asking for consent

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#357]
Check cookies

**Comment by cll008** [comment]
Getting a MATALB warning on 2020a when trying to test out the rc. Maybe because of remote connection? Will check tomorrow in person.

> Warning: Could not check for the latest EEGLAB version (internet may be disconnected).
> To prevent long startup time, disable checking for new EEGLAB versions (File > Preferences). 

Internet is connected.

**Comment by arnodelorme** [comment]
Seems to be a Chrome issue.
