### ISSUE TITLE
EEGLAB not listed on the octave package index

### ISSUE THREAD

**Issue by tpapastylianou** [eeglabdevelopers/eeglab#363]
Dear EEGLAB maintainers,

I noticed your package does not appear on the octave package index. Please consider adding it! You can find the octave package index and instructions how to add your package here: https://gnu-octave.github.io/packages/

Ideally, packages should be provided in the octave package format, such that could be installed via octave's pkg command; however, this no longer a strict requirement, and packages with custom installation instructions are also accepted on the index, as long as they provide clear installation instructions. :)

**Comment by arnodelorme** [comment]
Thank you, we are going to add it.

**Comment by cll008** [comment]
https://github.com/gnu-octave/packages/pull/8
