### ISSUE TITLE
EEGLAB error in function pop_biosig() at line 119

### ISSUE THREAD

**Issue by shutli1127** [eeglabdevelopers/eeglab#365]
### Description

[*EEGLAB error in function pop_biosig() at line 119.
data链接：https://pan.baidu.com/s/1PFZrQ7IMTq-4YnGFSQ_8mA 
提取码：lar0*]

<br>
#### Steps to Reproduce

1. [*load EEGLAB v2021.1*]
2. [*FIle - Import data - Using the BIOSIG interface*]
3. [*Error in function pop_biosig() at line 119*]

<br>
#### Expected behavior:
[*I want to load .RAW file using EEGLAB*]

<br>
#### Actual behavior:
[*I used the plugin BIOSIG to load .RAW file using EEGLAB, but it showed EEGLAB error in function pop_biosig() at line 119*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*WIndows 10 64bit*] |
| Matlab version | [*MATLAB 2020b*] |
| EEGLAB version | [*eeglab v2021.1*] |

**Comment by cll008** [comment]
Hi @shutli1127 could you please upload a sample .raw file to a google drive link, along with a screenshot or description about the exact EEGLAB error that occurs. Thanks.

**Comment by shutli1127** [comment]
> Hi @shutli1127 could you please upload a sample .raw file to a google drive link, along with a screenshot or description about the exact EEGLAB error that occurs. Thanks.

https://drive.google.com/file/d/1-CuPdOEehT6RbTp7j0_8ufb78xu4KlBm/view?usp=sharing. Thank you very much. This is the sample data link. And the error is "Unsuported data format ".

**Comment by cll008** [comment]
What amp / system did you use to collect the data? I think the .raw that biosig imports has to be from EGI

**Comment by arnodelorme** [comment]
.raw is also an EGI format (simple binary).

Arno

**Comment by arnodelorme** [comment]
This file needs the binary simple plugin of EGI (called EGI legacy). I was able to import the data.
