### ISSUE TITLE
EDF+ import issue

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#375]
File is below

https://drive.google.com/file/d/1iXF_4bG4HvI-wcENr43nCxsaklB_yMX3/view?usp=sharing

@schloegl could you tell us what the problem is. Seems to be a valid file.

**Comment by schloegl** [comment]
What problem do you see ?

**Comment by arnodelorme** [comment]
It is an event problem

**Comment by schloegl** [comment]
Tested with various Biosig tools, and do not see anything unusuall. 
What is needed to reproduce the issue ? What outcome do expect, and what do you acutally get ?

**Comment by arnodelorme** [comment]
This is the full error. Let me run more tests on this file.

Index exceeds the number of array elements (1).

Error in edfannot2evt (line 57)
			s2 = t1(ix(1)+1:ix(2)-1);

Error in sopen (line 1062)
		HDR = edfannot2evt(HDR);

Error in pop_biosig>readfile (line 298)
dat = sopen(filename, 'r', channels,'OVERFLOWDETECTION:OFF');

Error in pop_biosig (line 194)
    [dat, DAT, interval] = readfile(filename{iFile}, g.channels, g.blockrange, g.memorymapped);

**Comment by arnodelorme** [comment]
This was due to BIOSIG 3.3.0. Upgrading BIOSIG fixed the issue.
