### ISSUE TITLE
Tiny issue: Persistent typo in EEGLAB startup

### ISSUE THREAD

**Issue by olafdimigen** [eeglabdevelopers/eeglab#378]
### Description
Surely the smallest and most nitpicky/obsessive issue I will ever create, but it just bugs me a little each time that whenever one starts EEGLAB (v2021.1 and prior versions), one is immediately greated with a typo (in the 3rd command window output line)  :-)

`Retreiving download statistics...`  % --> Retrieving

**Comment by arnodelorme** [comment]
Fixed. Thanks
