### ISSUE TITLE
ERSP plotting-Error in function newtimefbaseln() at line 112

### ISSUE THREAD

**Issue by jacobsen-noelle** [eeglabdevelopers/eeglab#379]
### Description

EEGLAB error in function newtimefbaseln() at line 112:
Index in position 2 exceeds array bounds.
![image](https://user-images.githubusercontent.com/46551692/132149390-39f20308-e157-4c7f-9523-22f1f282989f.png)

It seems like the x input to this function is empty, which is why there's an error with the index exceeding array bounds. 

<br>
#### Steps to Reproduce

1. Load STUDY, datasets have ICA decomp
2.  STUDY--> precompute component measures --> spectra, ERSPs, default settings ('cycles', [3 0.8], 'nfreqs', 100, 'ntimesout', 200)
        -Test ERSPs works
3. Study --> Build preclustering array --> selected location based info : dipole locations, dipole orientation
4. Study -->Cluster Components, 15 clusters
5. Plot ERSPs using GUI

<br>
#### Expected behavior:
I would expect the ERSPs to plot just like they do in the Test ersp or with tftopo()

<br>
#### Actual behavior:
Error in newtimefbaseln() at line 112

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [2018a] |
| EEGLAB version | [2021.0] |

**Comment by arnodelorme** [comment]
Would you mind to upload your data (or send a separate link). If the whole study is too large, just upload a couple of subjects.

**Comment by jacobsen-noelle** [comment]
I think the issue may have been that I had a field called EEG.event.condition, and it was conflicting with EEG.condition (which is empty). The function may be trying to find my ersp data at an empty index indicated by EEG.condition. I am going to see if changing the event field name to EEG.event.cond will help avoid this confusion. I was not aware this would affect ERSPs. I will let you know if this is the cause of the issue.

**Comment by arnodelorme** [comment]
Yes, please let us know. Closing this issue for now but feel free to reopen.
