### ISSUE TITLE
eeg_checkset fills all empty fields

### ISSUE THREAD

**Issue by JohnAtl** [eeglabdevelopers/eeglab#38]
I have many fields on my epochs, and it's a pain to set them all to 0 so that eeg_checkset won't copy other values into these fields. In some instances (events) the fields are meaningless, and I would prefer not to even set a 0 value.
Apparently, this was removed and re-installed at some point.

```
                       % THIS WAS REMOVED SINCE SOME FIELDS ARE ASSOCIATED WITH THE EVENT AND NOT WITH THE EPOCH  
                       % I PUT IT BACK, BUT IT DOES NOT ERASE NON-EMPTY VALUES
```
Can we have a setting or option to disable this field copying?

**Comment by arnodelorme** [comment]
I have moved the code to the STUDY std_maketrialinfo.m function. This functionality is mainly used at the STUDY level so time-locking event have all the necessary information. It is not necessary at the single dataset level.
