### ISSUE TITLE
Error to import Neuroscan .CNT file

### ISSUE THREAD

**Issue by VictorGimenez** [eeglabdevelopers/eeglab#384]
I am facing an issue at the moment when I try to upload a .CNT extension file through: File > Import Data > Using EEGLAB functions and plugins >  From Neuroscan .CNT file, it is showing me that there is an error at the loadcnt() at line 'str2mat' undefined near line 693 column .

Here is the error: https://drive.google.com/file/d/1mLi-WPdhjwrSzdhWcUO_qJPYj9zrMcik/view?usp=sharing

<br>
#### Steps to Reproduce

1. [*Open the folder where EEGLAB/eeglabdevelop was uncompressed and there is a file called eeglab.m*]
2. [*Open Octave through line command on terminal typing: octave --gui*]
3. [*Typed eeglab at the command line*]
4. [*At EEGLab select File tab*]
5. [*At File tab select Import data*]
6. [*At Import data tab select Using EEGLAB functions and plugins*]
7. [*At Using EEGLAB functions and plugins tab select From Neuroscan .CNT file*]
8. [*Select the .CNT file*]
9. [*Data format set to Autodetect*]
10. [*Checked the checkbox Check to import keystrokes*]
11. [*OK*]

<br>
#### Expected behavior:
[*Next screen*]

<br>
#### Actual behavior:
[*Message EEGLAB error in function loadgnt() at line 'str2mat' undefined near line 693 column...*]

<br>
#### Versions

|   |   |
|----| ---- | 
| Ubuntu version     | [*20.04.2 LTS Focal Fossa*] |
| Octave version | [*5.2.0*] |
| EEGLAB version | [*v2021.1*] |

**Comment by VictorGimenez** [comment]
How could I proceed? Thanks

**Comment by VictorGimenez** [comment]
I am very stuck on it, and there isn't another version about the neuroscanio package to download, it looks like be a issue involving anything on this function `loadcnt()`, the picture was private before I realized it but now it's public to check it out.

**Comment by cll008** [comment]
Hi Victor, thanks for your patience.
If we check 'help str2mat' in the Octave command line we find that it is a file that is not yet implemented.
Please try the following:

1. \>edit loadcnt to open up the script (or open in your favorite text editor)
2. Navigate to line 693 where `str2mat` is
3. Replace `str2mat` with `char`
4. Save the changes to the script
5. Try to load file again

Let me know if that works.

Thanks for making that photo public by the way. I meant to request access the other day but must've been distracted by something else - glad I was able to see it earlier.

**Comment by VictorGimenez** [comment]
Hey @cll008 thank you so much for the reply and the solution!! It worked until now and I'm in the Dataset info -- pop_newset() window, I hope that after this fix I am not gonna receive more errors!!

**Comment by cll008** [comment]
Awesome. I'll close this for now but feel free to follow up here or open another issue should one arise.
