### ISSUE TITLE
issue with plugin_getweb

### ISSUE THREAD

**Issue by yunshufan** [eeglabdevelopers/eeglab#386]
### when I type "eeglab" to load the GUI, I got the following error message:
![image](https://user-images.githubusercontent.com/32801111/134571427-e0f6189c-b401-4c4c-bf56-84cdd3c15c57.png)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [2021a and 2019b] |
| EEGLAB version | [eeglab2019_1] |

**Comment by arnodelorme** [comment]
Are you using EEGLAB 2021.1?

@cll008 would you mind answering?

**Comment by yunshufan** [comment]
I’m using eeglab2019_1

-Yunshu

**Comment by arnodelorme** [comment]
Could you update to EEGLAB 2021.1 and try again?

**Comment by Jacsbill** [comment]
@yunshufan see https://github.com/sccn/eeglab/issues/385 for a quick fix if you don't want to update just yet (worked for me to finish my current batch)
