### ISSUE TITLE
ERSP plot mismatch in eeglab2021 vs eeglab14

### ISSUE THREAD

**Issue by jjurgiel** [eeglabdevelopers/eeglab#389]
### Description

I'm seemingly unable to produce correct study ERSP plots for IC clusters in eeglab2021 (unless I'm missing some newly added specifier), compared to those obtained using eeglab14 (which is what I was using prior). Study is using a paired analysis (2 conditions per subject ID, 1 group). Data from each subject is from the same session (same ICs within subject).

eeglab14 dipole decomp:
![image](https://user-images.githubusercontent.com/12466792/135213126-90eb2c26-1bbe-41b8-aa77-e7116d9f0018.png)

eeglab cluster 6 ERSP:
![image](https://user-images.githubusercontent.com/12466792/135213230-5e6367c8-614e-4757-ad11-ade6c9477e6a.png)

eeglab2021 produces same dipole decomp:
![image](https://user-images.githubusercontent.com/12466792/135212517-39809156-35a7-44c1-9049-a7570473a842.png)

but different (and oddly high magnitude scale) ERSP plot for same cluster in eeglab2021:
![image](https://user-images.githubusercontent.com/12466792/135212554-0fb72877-e97a-46f8-b7db-92ec6c99b286.png)

I've also used the eeglab2021 .icatimef files themselves to basically recreate the eeglab14 ersp plot using my own code which is why I didn't expect an issue with those specifically. 

<br>
#### Steps to Reproduce

1. Create study with N subjects, 2 conditions per subject, single group, same ICs across conditions within subject (same recording session)
2. Precompute ERSP, input argument 'baseline', [time0 time1] added to ERSP arguments, along with default arguments that are present in the text box
3. Precluster (dipole locations only), cluster (k-means), and plot ERSP for a given cluster

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [2020b] |
| EEGLAB version | [EEGLAB2021] |

**Comment by arnodelorme** [comment]
Would you mind to upload your study and we will investigate. Drag and drop the whole study below.

https://drive.google.com/drive/folders/14M8bmSxCDUzvdKL4s6G7tskq0q-1jIo5?usp=sharing

**Comment by jjurgiel** [comment]
I uploaded the study file and subject files. I didn't upload the .icatimef files as they're quite large, but please let me know if you'd like those from my end. They're simply component ERSP files using  'baseline', [-3500 -2500], using all ICs, as I think is described in study history.

**Comment by arnodelorme** [comment]
@cll008 would you mind to have a look?

**Comment by jjurgiel** [comment]
Update: I figured out that the issue with the study plotting is that trial info from the individual EEG files was not being detected when extracting ersp from the .icatimef files, and thus only a single trial from each file was being used instead of all trials for average ERSP, giving seemingly extreme values. The reason was because I was epoching my files from -4s to 0s prior to the locked event, which for some reason messed up the epoch numbers (my EEG.epoch variable info for epoch #1 was empty, and the true epochs and events started at epoch #2). I believe you should be able to see this in the .set files I provided, as well as ALLEEG.epoch structure of the study file. After epoching from -4s to 0.05s (to make sure the locked event didn't get accidentally dropped out), the issue disappeared and epoch info was in tact.

Upon loading the study which wasn't working, I realized that the warning: "std_maketrialinfo: not the same number of time-locking events as trials, trial info ignored" appeared, which I didn't think was related but is associated with the same issue.

I'm not sure if EEGLAB14 and EEGLAB2021 handle these epoch details differently (i.e., EEGLAB2021 needs trial info variable to pull data while EEGLAB14 doesn't, as the latter uses individual files), but that's where this issue came from. Perhaps a flag check for scenarios where EEGLAB only detects a single trial for the study ERSP calculation for a particular subject may help for troubleshooting.

So this plotting issue is solved for myself (and isn't an issue with the study plotting or ERSP itself) but please let me know if you need any other details of how to possibly recreate the secondary issue of eeg epoch details not forming properly.

**Comment by cll008** [comment]
Thanks for the follow up @jjurgiel. I actually no longer work at SCCN or UCSD, and I'm not sure if @arnodelorme has the bandwidth to implement this feature. If you end up implementing that flag check yourself, I'm sure a PR would be appreciated.

**Comment by arnodelorme** [comment]
This is a long one. Will get to it eventually.

**Comment by arnodelorme** [comment]
@amisepa if you have time, can you have a look.

**Comment by amisepa** [comment]
@arnodelorme  Looks like this issue is solved: "So this plotting issue is solved for myself (and isn't an issue with the study plotting or ERSP itself)"

Do you want me to add the flag check? "Perhaps a flag check for scenarios where EEGLAB only detects a single trial for the study ERSP calculation for a particular subject may help for troubleshooting."

**Comment by arnodelorme** [comment]
OK, thanks

**Comment by arnodelorme** [comment]
Let close the bug then. Thanks Cedric.
