### ISSUE TITLE
Epoch import

### ISSUE THREAD

**Issue by kissadamfkut** [eeglabdevelopers/eeglab#394]
Hi there,

I am trying to import time locking events, and trial events to my EEG record. I've created an event file like this:

latency type
135440 ScreenOn
140098 ScreenOn
143557 ScreenOn
147138 ScreenOn
...

I can import this using the import events menu, works great. The epoch extraction menu works also. Then I want to use pop_importepoch(), which fails. My epoch file looks like this:

screenon        info    buttondown      duration        ansshowtime     str1    str2
135440  1;1;1;0;121     138032  2592    2048    ScreenOn        ButtonDown
140098  2;2;1;1;112     141504  1406    2048    ScreenOn        ButtonDown
143557  3;3;1;1;112     145060  1503    2048    ScreenOn        ButtonDown
...

The screenon means the same time as the TLE above. Info is some metadata. Buttondown is the time when the user pressed the key. Duration means the time between buttondown and screenon. ansshowtime is 1 sec (so buttondown would have a duration).

Using str1 and str2 as labels for the to events in the imported epoch causes an error, leaving it blank the import process runs as expected. But, the plot shows me only one event per epoch, and the EEG structure looks ugly. EEG.epoch has almost every column duplicated but with different name. EEG.event shows me only time locking events, every duration is set to zero, and the latency field shows the time neither in seconds nor in samples for the TLEs.

My eeglab history:

EEG.etc.eeglabvers = '2021.0'; % this tracks which version of EEGLAB is being used, you may ignore it
EEG = pop_biosig('/EEG_process/data/EEG/0422.bdf', 'importevent','off');
EEG = eeg_checkset( EEG );
EEG = pop_importevent( EEG, 'event','/EEG_process/data/midfile/0422.event','fields',{'latency','type'},'skipline',1,'timeunit',NaN);
EEG = eeg_checkset( EEG );
EEG = eeg_checkset( EEG );
EEG = pop_epoch( EEG, {  }, [-1  2], 'newname', 'BDF file epochs', 'epochinfo', 'yes');
EEG = eeg_checkset( EEG );
EEG = pop_importepoch( EEG, '/EEG_process/data/midfile/0422.epoch', {'screenon','info','buttondown','duration','ansshowtime','str1','str2'},'latencyfields',{'screenon','buttondown'},'durationfields',{'duration','ansshowtime'},'timeunit',NaN,'headerlines',1);
EEG = eeg_checkset( EEG );

I've also checked the source code for pop_importepoch and the program structure is not really clear for me. Setting the events and the latencies separately and merge the events after multiple insertion is a bit of mess for me, that is why I think the goal I want to use this function is not what the function is supposed to to.

Is this the desired operation? Am I trying to do this the wrong way?

**Comment by cll008** [comment]
Please share your file and script so I can take a closer look.

**Comment by kissadamfkut** [comment]
The event and epoch files are in the issue. The first three events are enough to reproduce the situation. The script is also pasted. For the waveform any random data should be okay. The sample freq I used was 2048 Hz.

Thank you!

**Comment by cll008** [comment]
Hi I don't see a link for the files or any attachments, could you share those instead of pasting the raw text?

**Comment by kissadamfkut** [comment]
Hello!

[Here](https://github.com/sccn/eeglab/files/7338026/issue_394.zip) you can find the source files. Thank you!

**Comment by cll008** [comment]
Could you share the 0422.bdf as well? It's not clear to me what your error is and I can't really reproduce it to help you given the info. That said, maybe the 'proper' way to move forward here is to treat everything as events: it looks like your events 'Screen On' and "Button Down", which contains latency info. You can add both events, then continue to process by time-locking to 'Screen On'. 

Some more comments:
- Formatting with semicolon idea (e.g. 1;1;1;0;121) may also cause issues. Maybe you need to format it as a string or a cell. 
-  Have you looked at the [tutorial on importing epochs](https://eeglab.org/tutorials/04_Import/Importing_Event_Epoch_Info.html)? Your epoch fields are rather unfamiliar to me. 
- When you type `EEG.event`, what are the fields? These fields should be consistent with what you have in the epoch file.
