### ISSUE TITLE
Epoch extract breaks latency field in EEG.event

### ISSUE THREAD

**Issue by kissadamfkut** [eeglabdevelopers/eeglab#395]
Hello!

I'm trying to import a data to the EEG lab. The event file looks like this:

```
latency type
135440 ScreenOn
140098 ScreenOn
143557 ScreenOn
147138 ScreenOn
...
```
After the import process (```EEG = pop_importevent( EEG, 'event','/EEG_process/data/22.event','fields',{'latency','type'},'skipline',1,'timeunit',NaN);```) the EEG.event structure looks like this, which is desired and okay:
![image](https://user-images.githubusercontent.com/8297886/136547552-4a029d81-13e0-41a5-ac36-5708a65c2c80.png)

But after doing epoch extraction using the menu and the default parameters (```EEG = pop_epoch( EEG, {  }, [-1  2], 'newname', 'BDF file epochs', 'epochinfo', 'yes');```) the latency field seems to be uninterpretable to me:
![image](https://user-images.githubusercontent.com/8297886/136548052-ea0946fe-985f-49fb-a691-c94f94088bb7.png)
It is not either in seconds nor in samples and even not the samplecount from the epoch start.

What happens here?

Thank you, Adam

**Comment by cll008** [comment]
Hi Adam,
After epoching, `EEG.event.latency` should be sample count from the start of the epoch, so if that is not the case then we have a problem. The 'true' event information is stored in `EEG.urevent`

Could you share the file so I can take a look?

**Comment by cll008** [comment]
You mentioned your sampling rate of 2048 Hz in #394. Based on `latency` above that puts your events at 1s and 4s, which seems plausibly not broken. Could you confirm?

**Comment by kissadamfkut** [comment]
Yes, it looks great in this point of view. Knowing after epoching the latency is relative to the start of the trial everything is fine. Thank you!
