### ISSUE TITLE
unable to resolve the name EEG.data

### ISSUE THREAD

**Issue by tingyu653** [eeglabdevelopers/eeglab#402]
### Description

[*Description of the bug or feature*]
I loaded a .study file into plv script.  
S = load('-mat','/Users/hsutingyu/Desktop/data/slapjack.study');
    A = EEG.data;
    eegData = rand(A); 
    srate = 500; %Hz
    filtSpec.order = 50;
    filtSpec.range = [35 45]; %Hz
    dataSelectArr = rand(231, 1) >= 0.5; % attend trials
    dataSelectArr(:, 2) = ~dataSelectArr(:, 1); % ignore trials
    [plv] = pn_eegPLV(eegData, srate, filtSpec, dataSelectArr);
    figure; plot((0:size(eegData, 2)-1)/srate, squeeze(plv(:, 17, 20, :)));
    xlabel('Time (s)'); ylabel('Plase Locking Value');
an error appeared below:
![image](https://user-images.githubusercontent.com/85797007/138578251-bc724925-b114-4b71-b8e2-04f383396154.png)

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*R2020a*] |
| EEGLAB version | [*v2020.0*] |

**Comment by cll008** [comment]
What is S after you load the matrix? Does it actually contain an EEG data structure?
Maybe you need to use File > Load study from the EEGLAB gui.
