### ISSUE TITLE
Add support for Signal Type prefix in channel label for imported EDF/BDF files.

### ISSUE THREAD

**Issue by pklapperich** [eeglabdevelopers/eeglab#403]
The [EDF Specification](https://www.edfplus.info/specs/edftexts.html) recommends prefixing signal names with the signal type. So rather than naming a signal "Fp1" it should be named "EEG Fp1".

I've noticed that "Lookup Channel Locations" wizard is unable to extract the location name from channels that are named with the signal type in the prefix, though it does correctly identify the channel type.
![image](https://user-images.githubusercontent.com/12666157/138609353-eb62a599-a776-46b3-86f8-9f98b6e9bef5.png)

If I delete the "EEG " prefix from each channel label and click "Look up locs" then it does fill in the location but also strips off the channel type, so I then have to go back and add "EEG" back in.
![image](https://user-images.githubusercontent.com/12666157/138609656-ae45a523-ffc9-4f77-90cd-fbf9605e4526.png)

I think it would be good if the software was able to extract both the location and the channel type from the channel label.

**Steps**
1. Have a EDF or BDF file that has "EEG {location_name}" as all of the channel names
2. Import the file, then choose "Edit -> Channel Locations"
3. Proceed through the wizard. Notice the locations were not detect even thought they were in the channel labels and the Channel Type is filled in.
4. Repeat 1-3 with an EDF or BDF file with channel names that don't have the prefix.
5. Note that in the repeat of step 3 that the locations were all recognized but now the Channel Type is not (because it was not in the label).

**Desired behavior**
In step 3 the Channel Type and Label should both be extracted from the label.

**Comment by cll008** [comment]
Hi @pklapperich, thanks for linking the EDF specs, I had no idea that that's why some datasets have the EEG prefix. Let me discuss with @arnodelorme how we want to handle this. To my understanding the 'correct' thing is to use a script to rename channel labels to just the 10-05 name. Not sure if we want to support different formats ('EEG Fp1', 'EEGFp1', 'Fp1-Cz', etc.)

When you lookup locs after removing the EEG prefix, if you use the .ced file templates the channel type should also populate.

**Comment by arnodelorme** [comment]
@cll008 add code to eeg_checkchanlocs
- check first channel for 'EEG' in the name
If this is the case:
- check for 'EEG-' and remove
- check for 'EEG' and remove then use strip to remove blank
