### ISSUE TITLE
potential issue with std_readdata that cause time limit being omitted when plotting ERSP in study

### ISSUE THREAD

**Issue by qiushifu-ucf** [eeglabdevelopers/eeglab#405]
### Description

When we try to plot ERSP in with a Study, the output does not use the parameters for time limits. After some digging, I found a potential issue with the function std_readdata that would cause time limits being omitted if both time limits and freq limits are set.

The problematic line is ln 135:

if ~isempty(opt.freqrange), opts = { 'freqlimits', opt.freqrange }; end

which should be changed to

if ~isempty(opt.freqrange), opts = { opts{:} 'freqlimits', opt.freqrange }; end

in this way, the freq limits will not overwrite the previous line of time limit setting.

I have tested it and it worked for me.

<br>
#### Versions 2020_0, 2021_0, current version

|   |   |
|----| ---- | 
| OS version     | [windows] |
| Matlab version | [2020b] |

**Comment by arnodelorme** [comment]
Thanks. We have fixed it.
