### ISSUE TITLE
writeeeg() cannot export edf/gdf/bdf files

### ISSUE THREAD

**Issue by f21ya** [eeglabdevelopers/eeglab#408]
### Description

Hey Manager,
[I would like to export my dataset from cnt to edf files.]

<br>
#### Steps to Reproduce

1. [load existing dataset]
2. [export=>Data to EDF/GDF/BDF file]
3. [Enter file name]
4. Error message: EEGLAB error in function writeeeg() at line 252:
Undefined function 'swrite' for input arguments of type 'struct'

Should I add more APPs to this version of Matlab except Signal Processing toolbox/Statistics toolbox/Optimization toolbox/Image processing toolbox?
I have installed plugins including Biosig/Fileio/ICLabel/clean_rawdata/dipfit/firfilt. Should I add more plugins to fix swrite?

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*win10*] |
| Matlab version | [*2021a*] |
| EEGLAB version | [[*2021.1*]](url) |
[](url)

**Comment by f21ya** [comment]
Sorry, I got it.
Because of set path in the Matlab. writeeeg cannot call swrite.

**Comment by 3-methylindole** [comment]
please tell me how to solve it, thank you very much!
