### ISSUE TITLE
Error when using IClabel

### ISSUE THREAD

**Issue by ana-maria-flps** [eeglabdevelopers/eeglab#415]
![Screenshot (3)](https://user-images.githubusercontent.com/95289260/144047302-d97ed402-dcfc-4f6a-a4b8-721b306607cc.png)
Hi, everyone. I am getting the following error when using ICLabel. Weirdly, it was working a couple of days ago. Anyone has ideas of how to fix it?

**Comment by cll008** [comment]
The function in the error is part of fieldtrip. Reinstalling/updating your fieldtrip plugin should work.
Which step are you encountering this error? Did you change anything (update plugins, install another EEGLAB, etc.)?

**Comment by arnodelorme** [comment]
Closing this bug for now, but if you can share your file please reopen the bug.
