### ISSUE TITLE
Calculating PCA not sensitive

### ISSUE THREAD

**Issue by DouweHorsthuis** [eeglabdevelopers/eeglab#416]
### Description

[*Thank you for your time, I hope you can help me better understand where I am making my mistake, or whether I did find a bug. 

When trying to calculate the PCA, that I want to use for the ICA, the code from pop_runica seems not very sensitive. Just running rank(EEG.data) would provide different (lower) amount of components, but after doing an average ref both seem to cause different problems.
 
If I would run 
`rank(EEG.data)`
it would result in a lower number than the amount of channels. which if I understand it correctly is the case because of bridged channels. However, when I do an average ref `EEG = pop_reref( EEG, []);` in some cases (16% for this 56 people) the amount of components increases by up to 9 components. 

So I did a test where I compared the code that does this copied from pop_runica:
```
 tmpdata = EEG.data; %only edited this line
    tmprank = rank(tmpdata);
    covarianceMatrix = cov(tmpdata', 1);
    [~, D] = eig (covarianceMatrix);
    rankTolerance = 1e-7;
    tmprank2=sum (diag (D) > rankTolerance);
    if tmprank ~= tmprank2
        tmprank2 = max(tmprank, tmprank2);
    end
```
This would however always give me the full amount of channels (64 or 160). 
So I did an average ref and ran it again and this code would sometimes be 1 component less, but around 50% of the time just stay the same. So it's not sensitive to the avg ref always. Which has cause my data to be very distorted during previous studies. 

I also found here: https://sccn.ucsd.edu/wiki/Makoto's_preprocessing_pipeline#Adjust_data_rank_for_ICA_.2805.2F17.2F2019_updated.29
a suggestion to change ` tmprank2 = max(tmprank, tmprank2);` to ` tmprank2 = min(tmprank, tmprank2);` but when I try that it's just identical to `rank(EEG.data)`.

Which makes it not clear to if ICA picks up on an average ref. Which finally get's me to my bug/question 
Is the PCA calulated correctly by pop_runica? And is there a better way for doing this? 

Would doing something like this 
`if strcmp(EEG.ref,'common')  
pca=rank(EEG.data);  
else  
pca=rank(EEG.data)-1;  
end`  
solve this? 

Anyway, thank you so much for your time! 

https://www.dropbox.com/sh/vaunfpgc08cy0nu/AADoto71h0drAq6Hyydfgqa4a?dl=0 has the code and the results, and one de-identified dataset that has the issue.*]

<br>
#### Steps to Reproduce
[*see script in dropbox*]
or
1. load a non-referenced dataset
2. run rank(EEG.data) or the pop_runica code (mentioned above)
3. run `EEG = pop_reref( EEG, []);`
4. re-run the rank(EEG.data) or the pop_runica code (mentioned above)

<br>
#### Expected behavior:
[*I expected to be able to calculate a rank, that is lower than the total amount of channels (due to bridging) and that would drop by one after doing an average reference, but I don't see this drop and if I use the pop_runica code just sets pca to amount of channels*]

<br>
#### Actual behavior:
[*the average ref increases the amount of components when using rank(EEG.data) and the code copied from pop_runica gives me rank==amount of channels and ~50% of the time it drops by 1 after an avg ref*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*windows 10.0.17134*] |
| Matlab version | [*2019b*] |
| EEGLAB version | [*2021.1*] |

**Comment by arnodelorme** [comment]
Yes, there are numerical issues with computing rank. I personally always set the number of PCA components manually. This line "if strcmp(EEG.ref,'common') pca=rank(EEG.data); else pca=rank(EEG.data)-1; end" seems sensible but what if there are mode linear dependencies?
