### ISSUE TITLE
GUI not Updating when EEGLAB is run inside a function

### ISSUE THREAD

**Issue by ioalessandro** [eeglabdevelopers/eeglab#419]
### Description

After a long time of trial and error I have made the observation that the EEGLAB GUI won't update to show the current Dataset Overview (Title, Channels, SR, ICA Weights, etc.) when it is run **inside a function**! I can imagine how this makes sense, for me this poses an issue since I want to call the function to open EEGLAB and then use the interface for some manual task and plotting (most of my other stuff is done automatically using command line code)

<br>
Steps to reproduce

1. Run this: 
```
eegdata = rand(19, 128*100);
subj = 'P17';
NEW_SR = 128;
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
EEG = pop_importdata('dataformat','array','nbchan',0,'data',eegdata,'setname', subj,'srate',NEW_SR,'pnts',0,'xmin',0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, CURRENTSET,'gui','off');
eeglab redraw;
```
2. Save and call this function:
```
function [] = testEEGLAB()
   eegdata = rand(19, 128*100);
   subj = 'P17';
   NEW_SR = 128;
    
   [ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
   EEG = pop_importdata('dataformat','array','nbchan',0,'data',eegdata,'setname', subj,'srate',NEW_SR,'pnts',0,'xmin',0);
   [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, CURRENTSET,'gui','off');
   eeglab redraw;
end
```
3. See the difference!

<br>
#### Expected behavior:
I would like to be able to work with the EEGLAB interface normally.

<br>
#### Actual behavior:
EEGLAB GUI stays empty.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*2021.0*] |

**Comment by arnodelorme** [comment]
Yes, when run inside a function the variables are local to that function. If you want the variables to be global, you can use a script instead of a function or use the command evalin('base', 'xxx'); with 'xxx' being all the commands in your script.
