### ISSUE TITLE
pop_mergeset() reference to non-existent field 'urevent'

### ISSUE THREAD

**Issue by ycYiwei** [eeglabdevelopers/eeglab#420]
### Description

I'm trying to merge two datasets and get the following error:
EEGLAB error in function pop_mergeset() at line 283:
Reference to non-existent field 'urevent'

I looked into pop_mergeset, 
`tmpevents = INEEG2.event;`
`nonemptymask = ~cellfun('isempty',{tmpevents.urevent});`

It appears that since tmpevents = INEEG2.event, it doesn't have a urevent field to start with. Is this a bug or am I misunderstanding something?

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [R2017b] |
| EEGLAB version | [2021.1] |

**Comment by arnodelorme** [comment]
I have fixed the issue. Pull the latest changes. Thank you.
