### ISSUE TITLE
eegrej.m miscalculating "times" output

### ISSUE THREAD

**Issue by gdemirezen** [eeglabdevelopers/eeglab#421]
### Description

Line 168 of eegrej.m is
`times = times * size(indata,2) / length(reject);`

It needs to be 
`times = times * (size(indata,2)-1) / (length(reject)-1);`
to correctly apply a ratio and calculate the duration.

I used pop_select function to retain a certain time range and it yielded times vector and xmax value of new EEG data wrong. (In line 149 of "eeg_eegrej.m" `EEG = eeg_checkset(EEG, 'eventconsistency');` times field is miscalculated due to wrong EEG.xmax value calculated using eegrej.m output.)
<br>

#### Steps to Reproduce

Suppose we have a time vector from 0 to 25 seconds with a dt = 0.5 seconds (srate=2) and we want to reject the first 20 points (reject between 0 and 9.5 seconds) 
After loading a sample dataset, execute the following to generate an EEG data with a duration of 25 seconds and 51 points and then perform the selection operation with pop_select:

`EEG.pnts = 51;`
`EEG.srate = 2;`
`EEG.xmin=0;`
`EEG.xmax=25;`
`EEG.times = 0:500:25000;`
`EEG.data=zeros(EEG.nbchan,51);`
`new_EEG = pop_select(EEG, 'time', [10 EEG.xmax]) ;`
<br>

#### Expected behavior:
*Expected new total data length is 15 seconds. The result should be `EEG.times=0:500:15000` with a total of 31 points.*

>   Columns 1 through 10
>            0         500        1000        1500        2000        2500        3000        3500        4000        4500
>   Columns 11 through 20
>         5000        5500        6000        6500        7000        7500        8000        8500        9000        9500
>   Columns 21 through 30
>        10000       10500       11000       11500       12000       12500       13000       13500       14000       14500
>   Column 31
>        15000

<br>

#### Actual behavior:
*New total data length is calculated to be 25\*31/51=15.1961 instead of 15 to be calculated by 25\*30/50. This also leads to miscalculated times vector of new_EEG although srate is 2.*

`new_EEG.times` yields

> ans =
>    1.0e+04 *
>   Columns 1 through 13
>          0    0.0507    0.1013    0.1520    0.2026    0.2533    0.3039    0.3546    0.4052    0.4559    0.5065    0.5572    0.6078
>   Columns 14 through 26
>     0.6585    0.7092    0.7598    0.8105    0.8611    0.9118    0.9624    1.0131    1.0637    1.1144    1.1650    1.2157    1.2663
>   Columns 27 through 31
>     1.3170    1.3676    1.4183    1.4690    1.5196

<br>

#### Versions

|   |   |
|----| ---- | 
| OS version     | [*-*] |
| Matlab version | [*2020a*] |
| EEGLAB version | [*eeglab2021.1*] |

**Comment by arnodelorme** [comment]
If you have 51 points, you have 25.5 seconds. This is because the sample at time 0 is in fact the sample between time 0 to 0.5 seconds (or time -0.25 second to 0.25 whichever convention you want to use).

So I think your reasoning is not correct, but please let me know if anything is inclear.
