### ISSUE TITLE
Error in function std_precomp()

### ISSUE THREAD

**Issue by devariel** [eeglabdevelopers/eeglab#422]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. create a study (the study I created was for 8 subjects with 3 conditions)
2. study ---> precompute component measures
3. check which measures to precompute (any combination of selecting these measures still results in the same error)
4. Hit "ok"

<br>
#### Expected behavior:
for EEGlab to precompute the component measures

<br>
#### Actual behavior:
no code runs in MatLAB, and the following error shows up:
EEGLAB error in function std_precomp() at line 234:
Undefined function 'gcp' for in put arguments of type 'char'.
<img width="509" alt="EEGlab_error_precompute" src="https://user-images.githubusercontent.com/73409584/149684418-5e4fbe54-a1ad-42f6-ba28-83b875a21adc.png">

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [2019b] |
| EEGLAB version | [2021.1] |

**Comment by arnodelorme** [comment]
This has been fixed in the dev. release. Would you mind checking.
