### ISSUE TITLE
std_precompute() - undefined function or variable 'option_parallel'

### ISSUE THREAD

**Issue by schaefj3** [eeglabdevelopers/eeglab#424]
### Description

When I try to precompute anything for a study (e.g., ERPs), I get the error "Undefined function or varialbe 'option_parallel" in the std_precompute() at line 233.  I cannot figure out why.

<br>
#### Steps to Reproduce

1. "Create study" -> browse for datasets (add data)
2. Select/edit study design -> add an independent variable (type - categorical, any of them)
3. Precompute channel measures -> select 
[sample_data_error.zip](https://github.com/sccn/eeglab/files/7944133/sample_data_error.zip)
ERPs

<br>
#### Expected behavior:

precompute channel measures to be able to plot ERPs

<br>
#### Actual behavior:

Error message: undefined function or variable 'option_parallel' in std_precomp() at line 233

![option_parallel_precomputestudy](https://user-images.githubusercontent.com/98483431/151220557-f18592ed-2bd2-4cdf-a3bc-da62f602e234.PNG)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 Enterprise |
| Matlab version | R2017a |
| EEGLAB version | 2021.1 |

**Comment by arnodelorme** [comment]
This has been fixed in the dev release. Would you mind confirming.
