### ISSUE TITLE
STUDY ERPimage plotting error

### ISSUE THREAD

**Issue by carleycode** [eeglabdevelopers/eeglab#427]
Hello, I am following along the SCCN tutorials. Have been fine up until tutorial 10. I am using v2021.1 of EEGlab, MATLAB R2021b, Edition	Windows 10 Pro
Version	21H1
Installed on	‎20/‎05/‎2021
OS build	19043.1526
Experience	Windows Feature Experience Pack 120.2212.4170.0

![Error when select ok on pop_studyerp using SCCN tut 10b study5 data](https://user-images.githubusercontent.com/55937943/154349492-966f03ca-01fd-4372-ac87-199cd4353a91.PNG)

To reproduce: (follow Quick STUDY creation guidelines using study5 data)
1. file->Create study ->simple ERP STUDY
2. enter 2 for number of conditions and 5 for number of subjects
3. press okay
4. Name the study
5. enter condition names
6. enter condition data sets (for each of the 5 subjects put the -s253 file on the left and the -s254 file on the right)
7. press okay and get and bug window is generated instead of Channel ERP figure and pop_chanplot()

**Comment by carleycode** [comment]
Incase it's helpful

MATLAB Version: 9.11.0.1769968 (R2021b)
MATLAB License Number: 40636010
Operating System: Microsoft Windows 10 Pro Version 10.0 (Build 19043)
Java Version: Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
-----------------------------------------------------------------------------------------------------
MATLAB                                                Version 9.11        (R2021b)
Computer Vision Toolbox                               Version 10.1        (R2021b)
Curve Fitting Toolbox                                 Version 3.6         (R2021b)
Data Acquisition Toolbox                              Version 4.4         (R2021b)
Deep Learning HDL Toolbox                             Version 1.2         (R2021b)
Deep Learning Toolbox                                 Version 14.3        (R2021b)
EEGLAB Toolbox to process EEG data                    Version -           see     
Image Acquisition Toolbox                             Version 6.5         (R2021b)
Image Processing Toolbox                              Version 11.4        (R2021b)
MATLAB Coder                                          Version 5.3         (R2021b)
MATLAB Compiler                                       Version 8.3         (R2021b)
MATLAB Compiler SDK                                   Version 6.11        (R2021b)
MATLAB Report Generator                               Version 5.11        (R2021b)
Signal Processing Toolbox                             Version 8.7         (R2021b)
Spreadsheet Link                                      Version 3.4.6       (R2021b)
Statistics and Machine Learning Toolbox               Version 12.2        (R2021b)
Vision HDL Toolbox                                    Version 2.4         (R2021b)
Wavelet Toolbox                                       Version 6.0         (R2021b)

**Comment by carleycode** [comment]
Same error occurs in following 10c tutorial with the STERN STUDY at the point of Study->precompute channel measures, click the ERP checkbox and press OK.  (Same error as above: EEGLAB error in function std_precomp() at line 234: Undefined function 'gcp' for input arguments of type 'char'.)

**Comment by arnodelorme** [comment]
This has been fixed in the EEGLAB version which will be released this week

**Comment by carleycode** [comment]
Okay awesome, thank you so much.

**Comment by carleycode** [comment]
I will be able to retest it for you :)

**Comment by arnodelorme** [comment]
You can try it here ahead of the release.

https://sccn.ucsd.edu/eeglab/currentversion/eeglab2022.0rc.zip

**Comment by carleycode** [comment]
Yip, tutorials 10a - 10c now work fine, no errors with pre-release version. Thanks so much.

**Comment by carleycode** [comment]
Bug with plotting ERP image in pre-release version. Would you like me to open a specific bug report for that one or do you know about it?
![error using animal_study data and plotting ERP image as per 10d SCCN tutorial](https://user-images.githubusercontent.com/55937943/154598694-b19784d8-7eca-4b44-a540-c2b221526905.PNG)

**Comment by arnodelorme** [comment]
Could you upload your data? I will change the title of the bug report. No need to create a new one.

**Comment by carleycode** [comment]
Hi Arnodelorme, It was the animal study data used in the 10d tutorial. It was generated when I pressed the Plot ERPimage button. Cheers Carley

**Comment by arnodelorme** [comment]
OK, I will give it a shot. You mean you imported the data using the BIDS importer?

https://openneuro.org/datasets/ds002680/versions/1.2.0

**Comment by carleycode** [comment]
I clicked on the link in the at the beginning of the tutorial. I think it says "These data are available for download here (443Mb)."

**Comment by carleycode** [comment]
I still have the zip file if you would like me to upload but it is rather large :)

**Comment by arnodelorme** [comment]
Ah ok. Thank you.

Arno

**Comment by carleycode** [comment]
Hi Arno, it doesn't seem to be possible to upload the zip file here. Probably best to click on the link at the beginning of the tutorial, unless there is somewhere else you would like me to upload the data to? 
Cheers
Carley

**Comment by arnodelorme** [comment]
I will give it a shot. Which section exactly of the tutorial creates a problem for you?

**Comment by arnodelorme** [comment]
I have tried the tutorial. I loaded the STUDY, precomputed ERP-image and plotted and it worked. What kind of problem are experiencing? Please reopen the bug when you respond. Thanks so much
