### ISSUE TITLE
Binica and Amica pop_runica() bug

### ISSUE THREAD

**Issue by KCull887** [eeglabdevelopers/eeglab#428]
### Description

Hello,

I recently discovered what may be just a small coding fix for the pop_runica function for the binica and amica method cases in the icatype switch statement.

On lines 468 and 476 respectively, the getrank() function is only called with the single input of the data itself when getrank() expects two input parameters of the data and pca option.  Thus, it leads to an error and the ICA computation is not completed.

#### Steps to Reproduce
1. Load any pre-ICA dataset
2. Select Tools -> Select 'Decompose data by ICA'
3. In interactive window, select 'binica' for ICA algorithm to use field
4. Select OK

#### Expected behavior:
Expected ICA decomposition to start.

#### Actual behavior:
Received error message box:

![pop_runica](https://user-images.githubusercontent.com/78427349/154549862-43db30fb-1773-4fe6-8dc3-6207d15b5e9f.PNG)

#### Versions
|   |   |
|----| ---- | 
| OS version     | Windows 10 1909|
| Matlab version | R2018a |
| EEGLAB version | 2021.1|

**Comment by arnodelorme** [comment]
Fixed the issue. Thanks.
