### ISSUE TITLE
Importing events from a MATLAB array or text file- Index exceeds the number of array elements 

### ISSUE THREAD

**Issue by Katerinaprm** [eeglabdevelopers/eeglab#431]
Hi all, 

I'm trying to import events from a MATLAB array or text file. 

My text file is composed of 5 columns (number type edftype latency urevent). 
In the 'import event info--pop _improvement window I browsed my file'; in the input field column I completed number type edftype latency urevent; number of file header lines I put 1; time: 1E-3; 

However, it appears **an error in function improvement, index exceeds the number of array elements (5).**

![index exceeds the number of array elements (5)](https://user-images.githubusercontent.com/100354130/155521338-225750b4-7a05-47aa-ade7-9f979255efe7.png)
Do you have any idea why this is happens and how can I solve it? 
Thanks in advance, 
Katerina

**Comment by arnodelorme** [comment]
Katerina, would you mind sharing your event text file. You can share it here (drag and drop).

**Comment by arnodelorme** [comment]
Hi Katerina, closing this bug for now, but feel free to post the file and reopen. Cheers
