### ISSUE TITLE
EEG checkset error

### ISSUE THREAD

**Issue by saiviswanth** [eeglabdevelopers/eeglab#432]
Hi all 

I have been trying to synchronise the gait cycle to the EEG signal where my raw EEG file(continuous data) is a  .vhdr extension file. When my section of code of synchronisation is completed for each trial(total no of trials - 4)  I am getting a eeg checkset error - which says that it does not have an epoch field in the event struct of EEG workspace variable. I went inside the event struct to find out there is no epoch field.

![Checkset error](https://user-images.githubusercontent.com/47557110/155655449-f9dc978a-71af-4bc0-a6d9-c3aa28a06357.jpeg)

<img width="871" alt="Screenshot 2022-02-25 at 10 26 44 AM" src="https://user-images.githubusercontent.com/47557110/155656305-4218276b-4a4f-400f-a038-14570dbd2a23.png">

Thanks in advance for your help 
Sai viswanth

**Comment by arnodelorme** [comment]
Is the data continuous or are there trials? If you artificially created trials, then the event structure needs an epoch field that is equal to 1, 2, 3 or 4 indicating which trial the event fall in.

**Comment by saiviswanth** [comment]
The data is continuous and there are four trials - MLP,Stroop,uplift,Walk.
So  could i know how to create an epoch field which is equal to my trial
event(ie 1,2,3 and 4).

**Comment by mumumu-tang** [comment]
Have you solved your problem？I meet the same problem. :(
