### ISSUE TITLE
EEGLAB error occurs when I try to create a simple ERP study (pic attached) 

### ISSUE THREAD

**Issue by okn10** [eeglabdevelopers/eeglab#434]
### Description
<img width="496" alt="Screenshot 2022-03-02 at 10 36 38" src="https://user-images.githubusercontent.com/99102734/156411138-a38b7072-2d2e-47e2-977c-96cea08c4d4a.png">

Best way to fix this ?

**Comment by arnodelorme** [comment]
This has been fixed in the latest EEGLAB release EEGLAB 2022.0. Which version are you using? Thanks

**Comment by arnodelorme** [comment]
Please reopen the bug if you still have problems.

**Comment by okn10** [comment]
*Thank you for the response. I am currently using eeglab 2021, I downloaded Parallel computing toolbox which solved the initial problem and will download the latest version and see if the new problem still persists.

**Comment by arnodelorme** [comment]
OK, let us know

**Comment by okn10** [comment]
Hello, where can I download eeg 2022.0, this site still gives the 2021 version as the latest download:
https://sccn.ucsd.edu/eeglab/downloadtoolbox.php

**Comment by okn10** [comment]
> OK, let us know
> […](#)

Is it possible to get a link to the 2022 version ?

**Comment by okn10** [comment]
I still also keep getting this error even though I've downloaded eeg202
<img width="1172" alt="Screenshot 2022-03-10 at 19 00 43" src="https://user-images.githubusercontent.com/99102734/157959538-84123dcb-9f25-4a8d-a922-167c0d6028f9.png">
2
