### ISSUE TITLE
this is not a bug(error occurred in function pop_ediset() at line 445)

### ISSUE THREAD

**Issue by leticiabragas2** [eeglabdevelopers/eeglab#435]
Hello,
I need help to fix this bug!
Can someone expert help me please!

Thank you!

![remmina_Alfred_143 107 199 50_202234-14325](https://user-images.githubusercontent.com/79654396/156777234-08ea04ce-e638-45f8-95f4-57613c775f72.png)

**Comment by arnodelorme** [comment]
Are you trying to import a MATLAB file? I see accents on your name. MATLAB could be confused by that. Would you mind trying to move the file to a folder that does not have accents (i.e. C:\TEMP\) and try again?

**Comment by arnodelorme** [comment]
Closing this issue for now. Feel free to reopen.
