### ISSUE TITLE
ERSP plotting error (matrix size error?)

### ISSUE THREAD

**Issue by myonetta** [eeglabdevelopers/eeglab#436]
In my STUDY set, I'm having a problem of some ERSPs can't  plot.

When I plotted the ERSP topography of all subjects, error was occurred with this figure (and in command window,  "tftopo (): tfdata columns must be a multiple of the length of times").
![image](https://user-images.githubusercontent.com/42949823/156884018-5d40add6-99d9-47cd-88fb-3d09a4ca4c91.png)

In addition, it can plot each subject's ERSP of each channel, but cannot draw topography (with an error, "Unable to perform assignment because the size of the left side is 100-by-41-by-50 and the size of the right side is 100-by-41-by-50-by-19. ").
![image](https://user-images.githubusercontent.com/42949823/156884259-346f0774-d0d8-4ed6-8406-0d76c917df45.png)

I thought there was a problem with my EEG-data matrix, but I can't find a solution.

Could you let me know if I have any necessary data processing?
Thank you in advance.

**Comment by arnodelorme** [comment]
Can you send us your study (even if it is large).

**Comment by arnodelorme** [comment]
Most likely, this is because EEGLAB cannot find the data.

**Comment by myonetta** [comment]
Thank you for your support.
I'll share the google-drive link because I can't upload files here (although .dat* and .irc* were too big to upload).
[https://drive.google.com/file/d/1IbYq2Mi4hMjat7q0bH2rRey72tTNDhCo/view?usp=sharing](url)

If you need all files, I'll send as split archives.

**Comment by myonetta** [comment]
Add
I uploaded all the data of this study to the GITHUB repository and invited you.
I look forward to hearing from you.
https://github.com/myonetta/erpserror

**Comment by arnodelorme** [comment]
I have fixed the issue. This is because you had sessions. 3520139f5
Please pull the latest changes from GitHub and recompute ERSP and ERPimage. It works for me on your data.

**Comment by myonetta** [comment]
I appriciated your helping. already I've already performed recompute, and it worked fine.

Best wishes,

**Comment by arnodelorme** [comment]
Good. Thank you for getting back
