### ISSUE TITLE
Problems Compiling EEGLAB

### ISSUE THREAD

**Issue by tjhendrickson** [eeglabdevelopers/eeglab#437]
### Description

[*I am attempting to compile EEGLAB through the Application Compiler tool because it is required by a workflow. 

When I attempt to compile EEGLab I get the following error: 

Error while determining required deployable files. Compilation terminated. Details:
Error using <a href="matlab:matlab.internal.language.introspective.errorDocCallback('parseFile', '/panfs/roc/msisoft/matlab/R2021a/toolbox/matlab/depfun/+matlab/+depfun/+internal/private/parseFile.m', 13)" style="font-weight:bold">parseFile</a> (<a href="matlab: opentoline('/panfs/roc/msisoft/matlab/R2021a/toolbox/matlab/depfun/+matlab/+depfun/+internal/private/parseFile.m',13,0)">line 13</a>)
MATLAB code '/panfs/roc/groups/8/faird/shared/data/TOTS_UMD_collab/code/cdl-eeg-processing/MADE-EEG-preprocessing-pipeline/eeglab2021.0/plugins/clean_rawdata/manopt/tests/Test_fixedrank_tensor.m' contains the following syntax error(s):
 Line 297 column 9 : The current use of 'cost' is inconsistent with its previous use or definition (line 85).
mcc failed.

*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | CentOS Linux release 7.9.2009] |
| Matlab version | [R2021a] |
| EEGLAB version | [EEGLAB2021] |

**Comment by arnodelorme** [comment]
Yes, these "manopt" folders need to be removed. The detailed instructions to compile are available at https://eeglab.org/others/Compiled_EEGLAB.html#can-i-compile-eeglab-myself
