### ISSUE TITLE
STUDY doesn't plut spectra; std_readdata cannot deal with selecting condition {'eo' 'ec'} and only session {[2]}

### ISSUE THREAD

**Issue by jnvandermeer** [eeglabdevelopers/eeglab#438]
### Description

I try to use the STUDY design to select from the data, the eyes open/eyes closed spectra, but only during the second session. I (think) I put everything nicely in the STUDY  info. I have separate files for eyes open and eyes closed, and for recorded during session 1 and session 2. There are 5 separate files (5 runs each).

If I make the design with variable 1 ->  condition {'eo' 'ec'}, and session = {[1]}, things run as expected.
If I make the design with variable 1 ->  condition {'eo' 'ec'}, and session = {[2]}, things go wrong.
If I make the design with variable 1 ->  condition {'eo' 'ec'}, and session = {[1 && 2]}, things work again. I only experience crashes once I select ONLY session 2. I expect this to be possible.

Upon further digging, I encountered that std_readdata, in line 208/208 where std_serialize is used to read/reset the STUDY.cache, the tmpdata (which later becomes the erpdata) is cell array like {[], []}; This is normally filled with values.

This (I think ) bug can be overcome by making a new study, and only selecting files from session 1 or 2. But, I thought I could smartly use the study design to reach the same effect (without having to make separate studies and re-estimating spectra).

I attach a sample dataset, and some screenshots on my google drive (zip file).

https://drive.google.com/drive/folders/1J7BSZzmr75KrmX6Z950S-JbjoTG5uC8S?usp=sharing

Many thanks for your time!

Best wishes
Johan

<br>
#### Steps to Reproduce

1. load in the study (may have to fiddle the path)
2. specify design with catagorical variable1 being eo ec (both), and categorical variable2 being Session 2
3. Precompute power spectra
4. Plot any channel's power (left button, see picture) using the STUDY basic stats module

<br>
#### Expected behavior:
I expect the same behavior for session 2 as for session 1: that it plots spectra

<br>
#### Actual behavior:
The design where I select session 2 does not plot any spectra and it gives an error box (see screenshots)

<br>
eeglab 2021.1; matlab 2016b

|   |   |
|----| ---- | 
| OS version     | [RedHat 7.9] |
| Matlab version | [R2016b] |
| EEGLAB version | [2021.1] |

**Comment by arnodelorme** [comment]
I have fixed the issue in 1074dea2a
Let me know if it works for you.
