### ISSUE TITLE
eegplugin_pca doesnt work

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#439]
I followed this lecture https://sccn.ucsd.edu/mediawiki/images/9/95/EEGLAB2018_scripting5.pdf
and also the documentation https://eeglab.org/tutorials/contribute/design_plugin.html for EEG lab function examples (the zip file that is provided there is not working but ok I save the Matlab code that is given below as the function).

Then I save this function inside the plugin folder but then when I start again the EEG lab the RUN PCA option doesn't do anything. 

Can you help me with that?
![image](https://user-images.githubusercontent.com/82998648/158367834-a374964b-ad93-4f35-9803-62f4d6f2a724.png)

Thank you.

**Comment by evastone97** [comment]
This is the error message I got in the command window

![image](https://user-images.githubusercontent.com/82998648/158450021-c9e385c7-a51a-4c15-ab60-85b134c194fd.png)

**Comment by arnodelorme** [comment]
There are sometimes special characters when copying and pasting from PDFs.
I have just tried this and it works for me.

```
function vers = eegplugin_pca(fig, trystrs, catchstrs) 

vers = 'pca1.00';
% find tools menu
menu = findobj(fig, 'tag', 'tools');
% PCA command
cmd = [ '[~, EEG.icawinv] = runpca(EEG.data(:,:));' ]; 
cmd = [ cmd 'EEG.icaweights = pinv(EEG.icawinv);' ]; 
cmd = [ cmd 'EEG.icasphere = eye(EEG.nbchan); disp(''Done'');' ];

% create menu
uimenu( menu, 'Label', 'Run PCA', 'CallBack', cmd, 'separator', 'on');
```

**Comment by evastone97** [comment]
Thank you for your reply!

I solved my issue.

Now I have another one regarding to preclustering. I have created a new issue: https://github.com/sccn/eeglab/issues/443

Thank you for the support and the answers.

Kind Regards,
Evangelia

**Comment by arnodelorme** [comment]
OK, thank you Evangelica. I will look into it.

**Comment by evastone97** [comment]
Thank you in advance!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
