### ISSUE TITLE
pca_ind not initialized in pop_runica()

### ISSUE THREAD

**Issue by chassall** [eeglabdevelopers/eeglab#440]
### Description
I get an error when I try to run pop_runica(). <br>
#### Steps to Reproduce
pop_runica(EEG,'runica') <br>
#### Actual behavior:
Unrecognized function or variable 'pca_ind'.
Error in pop_runica (line 414)
if pca_ind

<br>

#### Versions
|   |   |
|----| ---- | 
| OS version     | macOS 11.6 |
| Matlab version | 2022a|
| EEGLAB version | 2022.0 |

**Comment by arnodelorme** [comment]
This was fixed in f87c05ea6
Thank you

**Comment by chassall** [comment]
Amazing, thanks!
