### ISSUE TITLE
EEGlab study creation error

### ISSUE THREAD

**Issue by mko3** [eeglabdevelopers/eeglab#441]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
I got an error with EEGlab study creation. I have 4 data sets with 6 conditions per set. When I tried to create a study using Simple ERP Study function, I got an error message below. Here is the link to the data sets.

https://cuny547-my.sharepoint.com/:f:/g/personal/mko_gradcenter_cuny_edu/EvsH-hCvjzpLiD44cHGkH3oBBv-jyjXUtk-8WssW9OcdJg?e=sSJBIE

<img width="375" alt="image" src="https://user-images.githubusercontent.com/43448139/159144619-e4ef8add-f86a-4fca-98ab-79b4012e543a.png">

Could you please let me know how I can fix the issue? Thank you. 

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment]
This issue was fixed in the latest 2022.0 version of EEGLAB. WOuld you mind trying it?
