### ISSUE TITLE
Error while running Envtopo analysis

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#447]
I created a study with 19 subjects and with data already preprocessed and with ICA, and PCA clustering afterward and I wanted to run the envtopo function but I face this error here:

![image](https://user-images.githubusercontent.com/82998648/160650073-8fc7770f-44d3-4cb5-866d-9bf93a1acc1e.png)

Do you know what might be the reason?

**Comment by arnodelorme** [comment]
@MakotoMiyakoshi can you assist here. I do not think this function was ever made compatible with the latest version of EEGLAB.
