### ISSUE TITLE
Microstate statistics

### ISSUE THREAD

**Issue by yiye81** [eeglabdevelopers/eeglab#449]
### Description

[I followed the tutorial described in "Microstate EEGlab toolbox: An introductory guide". I have back-fitted to all of the EEG (for the 4 datasets). But when I attempted to calculate the microstate statistics being selected one dataset, it returned me the next message error:
Not enough input arguments
Then I attempted to calculate the microstate statistics being selected the MicroGFPpeakdata, it reyurned me another message error:
Unrecognized field name "fit"

In any case, I used the option Backfitting prototypes to EEG, leave unchecked the other box for microstate statistics.

I cheched that in each dataset, it exist the fit field in microstate of EEG structure, but not for MicroGFPpeakdata.

How can I solve this problem?

Yiyao Ye Lin

Window version Window 10pro 64 bits
| Matlab version | [*2021a*] |
| EEGLAB version | [*2021.1*] |

**Comment by arnodelorme** [comment]
Unfortunately, we cannot help as we did not design the plugin. You should contact the plugin authors. Apologies for the late response I was travelling.
