### ISSUE TITLE
pop_epoch - duplicated events when segmenting resting-state data

### ISSUE THREAD

**Issue by crisglav** [eeglabdevelopers/eeglab#451]
I have detected a small bug when trying to epoch resting state data into 10s epochs using pop_epoch in batch fashion.

First I create markers each 10s and add them at the end of existing markers on the EEG variable
```
EEG = ALLEEG;
epoch_length = 10;
% Create markers each 10s and add them at the end of existing markers
for s=1:size(EEG,2)
    epoch_start = 1:EEG(s).srate * epoch_length:EEG(s).pnts;
    nEpochs = length(epoch_start);
    newEvents = struct('latency',num2cell(epoch_start),...
                       'duration',num2cell(ones(1,nEpochs)),...
                       'sample', repmat({[]},1,nEpochs),...
                       'type',repmat({'epoch_start'},1,nEpochs));
    EEG(s).event = [EEG(s).event,newEvents];
end
EEG = pop_epoch(EEG,{'epoch_start'},[0 epoch_length],'epochinfo','yes');
```
After executing it I noticed that all events were duplicated in EEG.events
I looked deeper into the code and I think is because here a -1 is missing
https://github.com/sccn/eeglab/blob/73f6a7f43fdf2d57c0306fb900b88401ff3851fc/functions/sigprocfunc/epoch.m#L152
so it would have to be 
`        posend  = pos0 + g.alleventrange(2)*g.srate-1; % compute offset`

I've tried it myself and worked for me.

**Comment by crisglav** [comment]
Sorry I reopen the issue because I think I found a different bug in pop_epoch function (I have edited my previous message).

**Comment by arnodelorme** [comment]
I have changed slightly the code in 39ce095db
Would you mind to check if it works for you?
