### ISSUE TITLE
EEGLAB error in function gratton() at line 82

### ISSUE THREAD

**Issue by Jb1c19** [eeglabdevelopers/eeglab#453]
### Description

Hi, 

I am trying to run an artefact correction using EEGLAB and i am getting this error:

_EEGLAB error in function gratton() at line 82

Undefined function 'regress' for input arguments of type 'single'_

I am following a walkthrough with a sample dataset given in the text book "A Psychologists Guide To EEG" by Michiel Spape. I have followed every instruction carefully and precisely,  so i cannot understand why i have received an error when no such error is discussed in this book. Unfortunately i am very new to MatLab so i am really struggling to understand what this issue means, let alone how to solve it. Any help here would be greatly appreciated, as i am aiming to run EEG analysis on my own data as soon as i have finished this walkthrough.

<br>
#### Steps to Reproduce

1. [*You will need the _gratton_ plugin available.*]
2. [*Click on Tools > Ocular Correction (Gratton), for me it is at the bottom of the dropdown list and highlighted in purple.*]
3. [*Enter the appropriate parameters. For some reason i cannot attach the dataset i am working on to this submission; but here are my inputs: input 34 into the Number of EOG channel for regression segment (this is my VEOG channel), input 1:32 in the channels segment (i want to correct these channels), and the final two segments were already filled (with 20 and 200, respectively.*]
4. [*Press OK*]

<br>
#### Expected behavior:
[*IPressing Ok should give a number of details in terms of how many blinks are detected, and how the channels each get a regression coefficient. The plugin will also create a new dataset.*]

<br>
#### Actual behavior:
[*I got the above stated error.*]

<br>
#### Versions

|   |   |
|----| ---- | 
| Matlab version | [*R2022a*] |
| EEGLAB version | [*v2022.0*] |

**Comment by arnodelorme** [comment]
You need the statistics toolbox of Matlab for the regress function. 

Not sure which function you are using. There are ways to do multiple linear regression using least squares without the stat toolbox in MATLAB.
