### ISSUE TITLE
Matlab error when adding eeglab to matlab path

### ISSUE THREAD

**Issue by GeorgiaSou** [eeglabdevelopers/eeglab#454]
### Description

When adding the eeglab in the matlab path and then try to open any script or function from the current folder on the left, I get following error:

usage: unique (x) or unique (x, 'rows')Error using msgbox (line 87)
Bad value for text property: 'Interpreter'

Error in errordlg (line 63)
handle = msgbox(ErrorStringCell,dlgName,'error',replace);

Error in uiopen (line 188)
    errordlg(err);

This happens with all recent versions of eeglab.
I use Matlab R2021b.

<br>
#### Steps to Reproduce

1. Open matlab
2. Add eeglab to path
3. Try to open any function or script from current folder

<br>
#### Expected behavior:
I was expecting to be able to open any file in matlab.

<br>
#### Actual behavior:
I got the previously reported error

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10 Pro] |
| Matlab version | [ R2021b] |
| EEGLAB version | [eeglab2021.1] |

**Comment by arnodelorme** [comment]
It is better to let EEGLAB add its own path. simply add the path to the root folder of EEGLAB. 
Let us know if that fixes the problem.

I have never seen that error. It could be that the msgbox function is overloaded. Type 

```
which msgbox
```

to check if you are using the MATLAB function or some custom function. Closing this report for now, but feel free to reopn.
