### ISSUE TITLE
EEGLAB error in function fit_eeg_distribution()

### ISSUE THREAD

**Issue by louisestolz** [eeglabdevelopers/eeglab#455]
I have analyzed the same dataset/task data on another participant without issues. This problem came up when I ran the automated cleaning pipeline (ASR) on the raw data of another participant: "EEGLAB error in function fit_eeg_distribution() at line 379: index in position 1 exceeds array bounds. How can this issue be resolved? Thank you.

**Comment by arnodelorme** [comment]
This sometimes happens when the data is too short. How long is the data? If the data is long enough, then please send us your data. Note that the issue should be logged at https://github.com/sccn/clean_rawdata/issues

Closing this bug for now but please recreate one at the link above if necessary.
