### ISSUE TITLE
pop_study desing - window doesnt show all the variables

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#456]
Hello, I have created a study and when I edit my study design the window that appears to me is different from the one that you have in your tutorials. For example, it doesn't separate the subjects and the conditions on different tables as it si shows you the youtube videos and tutorials. How can I enable this?

This is how it appears to me:
![image](https://user-images.githubusercontent.com/82998648/163433440-b3684a10-a5c1-43ec-a9e8-3202c6988cbf.png)

Thank you!

**Comment by arnodelorme** [comment]
Which tutorial are you refering to?
This video describes how to use this interface 

https://youtu.be/-jL3PuHD3aY?t=788

as well as this tutorial

https://eeglab.org/tutorials/10_Group_analysis/working_with_study_designs.html
