### ISSUE TITLE
Preclutsering array - Final dimensions not shown

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#457]
Hello, I was watching some of the youtube videos and I was wondering why I don't have the check box for the final dimensions in the creation of the pre clustering matrics.  The final dimension is just the sum of the options that I will choose from the time and location-based info. So if I choose spectra, ERPs, and scalp maps with PCA 3 then the final dimension of my matrix is 9 and in the k means clustering later I have to choose 10. 

And is there any method or extra tool that I can use to find the optimal number of clusters for the specific data?

Am I doing something wrong? Thank you in advance :)

![image](https://user-images.githubusercontent.com/82998648/163437291-16508940-8506-44fc-bb98-0ade731ff0e7.png)

**Comment by arnodelorme** [comment]
This option was removed. It is better to decrease the dimension of each measure.
