### ISSUE TITLE
error in pop_clust() line 252

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#458]
Hello,

After the precomputing measures and the pre-calculation of the pre-clustering matrix I tried to cluster with kmeans 10, but I got the following error.
![image](https://user-images.githubusercontent.com/82998648/163489613-86067331-2a0e-496d-9229-ec781afa8546.png)
The problem is that I don't know exactly what to change in pop_clustering function because in line 252 there is nothing.

Thank you in advance.

**Comment by evastone97** [comment]
This is the part of pop_clust function, but I don't know what to change from here

![image](https://user-images.githubusercontent.com/82998648/163491070-2d43ad02-dcd2-42d6-a54f-052377b6ab89.png)

**Comment by arnodelorme** [comment]
You would need to share your whole study so we could have a look. Does not matter if it is gigabytes as long as you can find a way to give us a link.

**Comment by arnodelorme** [comment]
Closing this for now. Feel free to reopen
