### ISSUE TITLE
ITC and ITC phase plot

### ISSUE THREAD

**Issue by mses61322** [eeglabdevelopers/eeglab#459]
Hello,
I'm wondering why I get an ITC phase plot instead of an ITC plot after I plot the channel time frequency. (As below)
![image](https://user-images.githubusercontent.com/103978164/163911382-92a05426-9e79-4c3e-b887-e904d043404c.png)
What can I do to get an ITC plot just like the tutorial gives? Or it's just a bug?

|   |   |
|----| ---- | 
| OS version     | Win11 |
| Matlab version | R2021b |
| EEGLAB version | v2021.1 |

**Comment by arnodelorme** [comment]
There is an option from the command line to plot just the ERSP, the ITC or both. Also, I believe the interface has checkboxes allowing you to plot just the ERSP or the ITC.

**Comment by mses61322** [comment]
Actually, I mean the eeglab website and other online sources indicating the graph should be "ITC" rather than "ITC phase" just like the picture down below.  
![image](https://user-images.githubusercontent.com/103978164/163916874-7b421ee0-8475-4495-8819-b9999651bffa.png)
I followed the manual steps but got a different result with the graph showing "ITC phase". Please let me know if I've missed anything.

**Comment by arnodelorme** [comment]
You have masked for significance and there is no ITC significant here, hence a green plot. This is the checkbox to toggle showing the phase.
![Screen Shot 2022-04-18 at 9 15 59 PM](https://user-images.githubusercontent.com/1872705/163919176-f164e61f-7661-4730-924c-fce4619d3477.png)

**Comment by mses61322** [comment]
So, the default setting is to print an ITC graph or an ITC phase graph? Or could it be manually manipulated?

I've tested both check and unchecked the checkbox to plot, but I still can't get an ITC graph to further analyze the data like down below. Shouldn't it be ITC?
![image](https://user-images.githubusercontent.com/103978164/163919859-990cc199-ecd9-46b3-8127-96a72c9fd6a6.png)

**Comment by arnodelorme** [comment]
There is no significance so the graph is the same in both cases.
