### ISSUE TITLE
eeglab2fieldtrip error in line 120

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#461]
Hello, I have a problem with the function eeglab2fieldtrip.

![image](https://user-images.githubusercontent.com/82998648/165332573-60ca0360-4142-4107-a0e1-dbbdd0061126.png)

So I have my datasets for each subject that contain three different event types inside and I first apply ICA to the whole dataset using EEGLAb, and then I wanted to separate the three conditions into three different subfiles. set. 

I use this line of code, but I receive an error in line 120 of the eeglab2fieldtrip function and I don't know what to do.

Can you help me with that?
Thank you in advance!

**Comment by arnodelorme** [comment]
Could I have a copy of your dataset. It might be that your dataset does not have any events.

**Comment by evastone97** [comment]
Yes, I can set the .set file but it says here that is not supported. But I will try to send them via email.

Thank you!

**Comment by arnodelorme** [comment]
Problem fixed in e88339156
Simply pull the changes with recursive submodules

git pull --recurse-submodules
