### ISSUE TITLE
i can not undersand

### ISSUE THREAD

**Issue by kkwd22** [eeglabdevelopers/eeglab#463]
the plugin manager is only available for matlab version 2016b and later versions.download plugins from the internet and unzip them in the plugin folder insterd

**Comment by arnodelorme** [comment]
If your version of MATLAB is too old, then go to this page https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php click on the download link for a given plugin. Then uncompress the file in the "plugins" folder of EEGLAB. EEGLAB must be installed of course.
