### ISSUE TITLE
EEGLAB error in function std_preclust() line 270

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#465]
Hello,

I have this study desing (are more subjects but here I just use one)
and I have three different conditions 
Since I want to do ICA, I first used all the preprocessed data, I added the channel locations and then I decomposed with ICA
![image](https://user-images.githubusercontent.com/82998648/166837026-8a690b98-26c4-4fc6-9f8c-a64fd7967872.png)

The next step was to precompute the component measures and to build a pre-clustering array, but I got the following warning when I choose PCA clustering and then build the pre-clustering array. 

So since the warning mentioned that I can only use the dipole and scalp maps then I have added the following options there:

![image](https://user-images.githubusercontent.com/82998648/166837413-c8baf077-b605-4d72-bea7-d926c5deaaa4.png)

Once I press okay I got this EEGLAB error in function std_preclust() line 270
![image](https://user-images.githubusercontent.com/82998648/166837727-33d5265b-a179-4889-ad51-602b57adc2ab.png)

Do you know what might be the reason for that?

Thank you in advance,
Eva

**Comment by arnodelorme** [comment]
I have made a change in 78a9fcb67 which might fix the issue. However, if it does not, I would need to see your STUDY.

**Comment by evastone97** [comment]
ok, I am gonna check it now and see if it works. Thank you!

**Comment by arnodelorme** [comment]
Actually this is the change a4fcca6df3888f90838a3bf34551801d450639ce not the one above.

**Comment by evastone97** [comment]
ok now it works

**Comment by evastone97** [comment]
I still have the same error... Can I send you my file?

**Comment by arnodelorme** [comment]
Yes, please

**Comment by evastone97** [comment]
Here is the link: https://drive.google.com/drive/folders/1SrjI_SA7s_ZMTy2mxqsYXy-2siz6myke?usp=sharing

**Comment by evastone97** [comment]
I realize that the same warning for the same function appears again when I try to precompute the time-based measures  (ERPs, and spectra) and with the command window to say : *Out of memory.*

![image](https://user-images.githubusercontent.com/82998648/167396114-972df199-9e1e-44da-82f4-5b60bebcb681.png)

I can only precompute the scalp maps as measures before clustering (maybe there is less space needed for those)

What would you suggest me to do?

Also, I try to run a simple ERP study with the datasets that I have I will be able to get those time-based measures (at least the ERPs)  and I got the same error.
![image](https://user-images.githubusercontent.com/82998648/167405872-0959618f-1a5e-499b-9183-80dea3181417.png)

**Comment by arnodelorme** [comment]
For this would you need to get more RAM for your computer. How much memory do you have?

**Comment by evastone97** [comment]
I have 16Gb, I think is more than enough that's why I was wondering ..
![image](https://user-images.githubusercontent.com/82998648/167466324-667feb0c-f69e-453c-8a0c-4c0606292e0a.png)

**Comment by arnodelorme** [comment]
Yes, 16Gb should be enough unless your datasets are very large. Simply decrease the time and frequency resolution when computing ERSP.
