### ISSUE TITLE
plotting error (matrix size error)

### ISSUE THREAD

**Issue by snztz** [eeglabdevelopers/eeglab#466]
In my STUDY set, I am having problems with both ERPs and spectra plotting.

For instance, it cannot draw the power spectra of all subjects (with an error, "Unable to perform assignment because the size of the left side is 0-by-15 and the size of the right side is 159-by-15-by-14.").

![error](https://user-images.githubusercontent.com/104977728/166908946-9a1cdc75-3279-4666-af28-5fe6d8bfe167.PNG)

I thought there was a problem with my EEG.data matrix, but I can't find a solution. Actually dimension of data is 14x320x15 in set files. Number of trials and epochs is 15. Number of channels is 14. Number of time points is 320. Sampling rate is 128. EEG structure looks right to me but please could you let me know if I have any necessary data processing?

I am attaching the file set containing some of the data (for only two subjects).

Thank you in advance.

[set and study files.zip](https://github.com/sccn/eeglab/files/8630596/set.and.study.files.zip)

**Comment by arnodelorme** [comment]
I loaded your study, precomputed ERPs and spectrum, and then plotted them without problem. From the data you sent, would you mind to send me the exact sequence of events to reproduce the problem?

**Comment by snztz** [comment]
First of all, thank you for your quick response. I was using 2021.1v of EEGLAB. Now, I've tried it with the latest EEGLAB version and it worked. Thank you very much again.

**Comment by arnodelorme** [comment]
Good to know. Thank you
