### ISSUE TITLE
runica() function error in line 674

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#467]
My study contains 18 subjects and , I have created a study using all the subjects and I have added the channel locations. My next step is to do ICA (note that my data are already preprocessed using Fieldtrp). 

I choose to decompose by ICA from the GUI but then it gave me that error regrading the space and the runica function. 

for the decomposition I did:  runica 'pca', 40 
![image](https://user-images.githubusercontent.com/82998648/166950950-5bbcb462-e1f6-4fad-8a2c-a555206f8207.png)

How can I solve this, am I doing something wrong?

Thank you in advance and sorry for lots of questions.!

**Comment by arnodelorme** [comment]
You do not have enough memory. Try reducing PCA further or using a different computer to run ICA. You can also try a different ICA algorithm. https://eeglab.org/tutorials/06_RejectArtifacts/RunICA.html

**Comment by evastone97** [comment]
ok, I will try that, So the main problem is the RAM of my PC? I prefer to use this specific ICA algorithm but yes I can try different ones and see what I am getting.
