### ISSUE TITLE
Import CSV Error

### ISSUE THREAD

**Issue by asmaabarakat** [eeglabdevelopers/eeglab#468]
I have a problem when I import CSV files from the flowtime app to EEGLAB as declared in the attached image.
![Capture](https://user-images.githubusercontent.com/105000943/166964279-60b2909f-6107-4a34-83d1-575a76fd6876.PNG)
[a.csv](https://github.com/sccn/eeglab/files/8632800/a.csv)

I also attache sample of the file which I tried to import in EEGLAB

**Comment by arnodelorme** [comment]
Which application did you use to save this file? 

There are 2 different muse plugins, one for MuseMonitor (also called BrainMonitor) and one for the Muse Direct app. If you did not use one of these two apps, then your file cannot be imported (unless you do it from the command line yourself). Thank you.
