### ISSUE TITLE
EEGLAB EDF+ annotations not properly loaded

### ISSUE THREAD

**Issue by SilenceofThree** [eeglabdevelopers/eeglab#47]
### Description

Hi

[*For some reason when I import my .edf file to EEGLAB my annotations are all named 1. The file is able to be viewed perfectly with Polyman, all of the annotations load as named. However when I open it in EEGLAB, the annotations all are named 1, which means I cannot separate the data into individual sleep cycles. If anyone knows how to solve this problem, it would be greatly appreciated.*]

Sample File: https://drive.google.com/open?id=1O_UCN6RLUYsvV1KZK-hcYhJPb2C69YwO

![image](https://user-images.githubusercontent.com/54332846/63411760-873ffe80-c3f6-11e9-9dc9-5c14d3f542c8.png)

[*As seen in image, the red annotations are all named 1*]

<br>
#### Steps to Reproduce

1. [*Import file to EEGLAB*]
2. [*Plot Data*]

<br>
#### Expected behavior:
[*Annotations to load as named*]

<br>
#### Actual behavior:
[*Annotations load as 1*]

<br>
#### Versions

|   |   |
|----| ---- | 

| Matlab version |[* R2019a*] |

**Comment by nucleuscub** [comment]
@SilenceofThree , 
 Please check the link to the data. Seems to be broken.
R

**Comment by SilenceofThree** [comment]
It works perfectly if you copy the URL into a new tab, not sure why it isn' working if you click on it.

I'll try to add it here again: https://drive.google.com/open?id=1O_UCN6RLUYsvV1KZK-hcYhJPb2C69YwO

**Comment by SilenceofThree** [comment]
Thanks for letting me know, it should be working now

**Comment by arnodelorme** [comment]
This is now supported in EEGLAB development version (simply download the zip on Github). However, in the file you provided, there was only one sleep stage (sleep stage 1). If this is not the case, please let us know.

**Comment by arnodelorme** [comment]
[SampleData.edf.zip](https://github.com/sccn/eeglab/files/3902493/SampleData.edf.zip)
Attaching file for future reference

**Comment by happymuzi** [comment]
Hello there!

When using pop_biosig function in EEGLAB v2019.1 to import edf files, the following warning showed up: "Warning: EDFANNOT2EVT.M is currently not supported! If there are problems reading EDF files, download and install mexSLOAD.mex* from https://pub.ist.ac.at/~schloegl/src/mexbiosig/".

While the EEG data imported were correct, EEG.event.type only have one value [1]. When trying the development version, EEG.event.type also have one value only which was the value of the first event, and the same warning still popped up.

MATLAB is running R2018b and here is [the link](https://drive.google.com/file/d/1AUsmnkMinjBkMLMFkSwH1nPgChGoj2gO/view?usp=sharing) to a sample file.

Any ideas on how to solve this would be greatly appreciated.

**Comment by mantour** [comment]
I have the same problem as happymuzi described.
After importing edf+ file into eeglab with pop_biosig function, all the event type impored was set to the first event name.
The [sample data](https://github.com/sccn/eeglab/files/3902493/SampleData.edf.zip) attached in the previous discussion actually had 3 event types, namely
sleep stage 1
sleep stage 2
sleep stage W

Which can be recognized normally when opened with [EDFbrowser](https://www.teuniz.net/edfbrowser/)

but all the annotation names was set to "sleep stage 1", despite different annotations in the edf+ file.

> Hello there!
> 
> When using pop_biosig function in EEGLAB v2019.1 to import edf files, the following warning showed up: "Warning: EDFANNOT2EVT.M is currently not supported! If there are problems reading EDF files, download and install mexSLOAD.mex* from https://pub.ist.ac.at/~schloegl/src/mexbiosig/".
> 
> While the EEG data imported were correct, EEG.event.type only have one value [1]. When trying the development version, EEG.event.type also have one value only which was the value of the first event, and the same warning still popped up.
> 
> MATLAB is running R2018b and here is [the link](https://drive.google.com/file/d/1AUsmnkMinjBkMLMFkSwH1nPgChGoj2gO/view?usp=sharing) to a sample file.
> 
> Any ideas on how to solve this would be greatly appreciated.
