### ISSUE TITLE
std_rmalldatafields() line 65

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#470]
Hi again, 

I am trying to load 18subjects with epoched data and create a study with those and I got this error while loading the dataset. 

![image](https://user-images.githubusercontent.com/82998648/167292397-29d4bacb-0749-4bd6-9105-025db05854e2.png)

I did a trial with the first 3 subjects and it worked perfectly, but when I am adding the 18 subjects I have this error.

Is this something that has to do with epoch consistency? because I have different epoch numbers for each subject.

Thank you in advance.

**Comment by arnodelorme** [comment]
Would you mind sharing your data?

**Comment by evastone97** [comment]
Yes my data are in this link here: https://drive.google.com/drive/folders/16BT6nvwei_PXOtBVh3TdX7Tw2YfzqyXY?usp=sharing
I have added the first 6 subjects (I still have the same error)
Let me know if you can see the data.

**Comment by evastone97** [comment]
Let me know if you can see my data 😊

**Comment by evastone97** [comment]
I think I manage to do it
So I relaized that when I am creating a study (by selecting the second option for browsing datasets it works)

But if I am loading the sets and then creating a study by using all the loading datasets I got this error.

So I think it's fine now, but it shouldn't give me an error with any of the two ways of data loading.

But what I have realized is if I load all the subjects and successfully create the study my epochs are not consistent.

![image](https://user-images.githubusercontent.com/82998648/167307778-fb5a66f5-8062-4b9f-9b7b-714ffcbfb71d.png)

Can I continue the clustering if my epochs are not consistent across participants? or how can I fix that?

For now I try to load 18 out of the 20 subjects and it looks ok with the epoch consistency.

![image](https://user-images.githubusercontent.com/82998648/167308469-502b2c10-2d05-4a3c-b1bd-44e97108a783.png)

But even if the loading of these 18 subjects is successful then when is time to precompute measures for clustering I got this error
![image](https://user-images.githubusercontent.com/82998648/167308902-ed38f532-b652-4072-86dd-eae872f303ba.png)

**Comment by arnodelorme** [comment]
Thank you. So I should just try to create a study with the 6 subjects right?

**Comment by arnodelorme** [comment]
OK, found the problem and fixed it in 7ef2a0fa6
It was due to a change I made 2 days ago.

**Comment by evastone97** [comment]
hm ok but why it's saying that there are datasets without the same ICA pairs? 
What I should do except download the edited function that you have fixed in the issue 7ef2a0f?

**Comment by arnodelorme** [comment]
Yes, you just download the function.
If you have different ICA decompositions for the same subjects on the same day, you do get a warning msg. Make sure you have assigned them to different sessions (=days).

**Comment by evastone97** [comment]
ok, what do you mean by assigning the ICA decompositions into different days?

**Comment by evastone97** [comment]
I think I found what was the problem and I cannot precompute all the measures that I want, correct me if I am wrong:

So I got this warning;
![image](https://user-images.githubusercontent.com/82998648/167423019-5bbd9618-c969-45b7-9c79-c364f27ed0fc.png)
and then what I did is to see where are those NAN values. The figures below show the stract and all the fields
![image](https://user-images.githubusercontent.com/82998648/167423105-57159df4-b034-4f1f-8d90-45223ff8a8e6.png)

![image](https://user-images.githubusercontent.com/82998648/167423246-ce89166f-f358-4620-9135-2a965acf56e7.png)


So I went to the STUDY.cluster() and I tried to fill up the empty spaces following the order of my datasets. (Do you think that is ok to do that or should I try to find the main issue on why my datasets are not loading ok?)
![image](https://user-images.githubusercontent.com/82998648/167423324-8c34acb2-76e7-4f95-8473-c94c60db095b.png)

Then after fixing this I was able to precompute all the measures that I wanted and I could also make my clusters.

![image](https://user-images.githubusercontent.com/82998648/167423490-bc4f43df-ba2b-417e-818b-4b8df0b79e73.png)


Thanks again for your effort and all your answers! I really appreciate that.

**Comment by arnodelorme** [comment]
Yes, you are missing some ICA decomposition for some reasons.

**Comment by evastone97** [comment]
Yes, it looks like that. Do you think that is ok to fill the above table, with the same pattern so I can get the data (this is what I have done, but I am not sure if that's correct)

**Comment by arnodelorme** [comment]
In theory yes, but it is better to rerun ICA

**Comment by evastone97** [comment]
I will try that, thank you!

**Comment by evastone97** [comment]
Another quick question, for the preprocessing part we have used binica algorithm and later after the proprocessing runica() algorithm was used with dimensionality reduction pca40. So if I rerun ICA what algorithm should I use? Is there a way to see what is happening if we combine 2 ica algorithms together?
