### ISSUE TITLE
Unable to read MAT-file (s1.icaerp) file might be corrupt error in std_readfile() line 217

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#473]
Hello 

I am trying to precompute components for clustering and I got this error:

These are my choices for the precomputed measures:
![image](https://user-images.githubusercontent.com/82998648/168269930-00a3920f-1a22-45dd-8fcc-e676ff4ed40d.png)

and the error message I got:
![image](https://user-images.githubusercontent.com/82998648/168265981-4657da56-5d9e-48b8-8936-568ba75aee70.png)

Here is the line from the function:

  215-  warning('off', 'MATLAB:load:variableNotFound');
  216- if ~isempty(opt.dataindices)
  217-      fileData = load('-mat', [ fileBaseName fileExt ], chanList{:}, 'trialinfo', 'times', 'freqs', 'parameters', 'events', 'chanlocsforinterp', 'chanall');
218-    else fileData = load('-mat', [ fileBaseName fileExt ], 'trialinfo', 'times', 'freqs', 'parameters', 'events', 'chanlocsforinterp', 'chanall');
 219-   end

![image](https://user-images.githubusercontent.com/82998648/168266251-ee1b2e02-a041-4b09-9250-7e4bfe3ed8de.png)

I have already precomputed the ERP components and I can see them in my folder the problem is that they cannot be read. 

Here is the folder with all the data: 
https://dtudk-my.sharepoint.com/:f:/g/personal/s205726_dtu_dk/EpOB8X0fMMhFplu2dEpeoEMB7DP5uPS4OqgM6Ab2Qo9Jxw?email=arnodelorme%40gmail.com&e=rFwIkN

**Comment by evastone97** [comment]
Ok somehow I have solved the issue. I precompute channel measures and then I recompute again the component measures and then I could create clusters with k means. Is the precomputing of channel measures necessary in order to do the pre-component measures?

I also have one question related to the IC scalp maps for each condition, can I ask here or there is another forum for general questions? 

Kind Regards,
Eva

**Comment by arnodelorme** [comment]
No you do not need to precompute channels to precompute component measures. You can ask questions on the eeglablist 

https://eeglab.org/others/EEGLAB_mailing_lists.html#the-eeglab-discussion-list-eeglablist
