### ISSUE TITLE
error in function pop_envtopo() at line 92

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#474]
Hello,

I am trying to plot the envtopo plots and I have this error about the intermediate dot. indexing in this line of the pop_envtopo function.

![image](https://user-images.githubusercontent.com/82998648/168295925-5c7f1071-3245-46b7-a64c-6c25c4584819.png)

![image](https://user-images.githubusercontent.com/82998648/168295453-f6328cf6-6eb1-407c-9368-81d569338507.png)

**Comment by arnodelorme** [comment]
Fixed in 52f424119. Let me know.

**Comment by evastone97** [comment]
Yes, it works now! thanks :)
