### ISSUE TITLE
error in eeg_interp() at line 67

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#475]
Hello,

I loaded some datasets and tried to create a study and after the creation I choose to add channel locations and I got the following error (ALL of my datasets had the same channel location, I load my chan location file in each one separately)

![image](https://user-images.githubusercontent.com/82998648/168488866-1b1a14d5-350b-4415-8710-51f0dc8960b2.png)

Then when I am trying to Precompute channel measures I got this error.
![image](https://user-images.githubusercontent.com/82998648/168488831-85e89f3c-e86f-4994-8fb0-524a162d4583.png)

Is it because I have loaded the channel location file independently and not to all the study together?

**Comment by arnodelorme** [comment]
Maybe you forgot to import channel locations for one dataset. Or maybe you have already removed bad channels. Feel free to share your study.

**Comment by evastone97** [comment]
Yes, I am using preprocessed data in which the bad channels have been removed, and then interpolation was applied.

I still have the error when trying to compute the channel measures.. don't know what I am doing wrong (all of my datasets have channel locations)
(link)

Thank you in advance.

**Comment by arnodelorme** [comment]
The link requires a password.

**Comment by evastone97** [comment]
Here is the new link: https://drive.google.com/drive/folders/1P4Fimp_YAUZD06kY0R-k3Tn8mzcoJeuU?usp=sharing

I haven't found the reason for that... so any feedback on what might be wrong is useful.
sorry for the inconvenience

**Comment by evastone97** [comment]
I have try to add the channel locations separately to each one of the dataset but it didn't work.. I don't know why but I have tried the same process before in another study and I never had this error with the eeg_interp function

I can also see from the struct that I have all the data for the channel location inside
![image](https://user-images.githubusercontent.com/82998648/169158325-9a1441f7-687b-4f2d-8cdd-5b2476592a16.png)

**Comment by arnodelorme** [comment]
Zip file corrupted as well.

**Comment by evastone97** [comment]
I have just uploaded a new zip file. Let me know if this is working.

**Comment by arnodelorme** [comment]
Still error with the file. I Downloaded the while file but it says it is empty when I tried to uncompress it.

**Comment by evastone97** [comment]
Ok I am gonna try another way then, don’t know what went wrong.
 I will back then in a while

**Comment by arnodelorme** [comment]
After you upload it, try downloading it and uncompressing it. Cheers

**Comment by evastone97** [comment]
This is the new link: its working at least for me hope it works. Let me know.

 https://drive.google.com/drive/folders/1YmqKpZl1uL2-xKYeFeCbFnisECx8aH6G?usp=sharing

Thank you in advance. Let me know if you find the reason for that. (I cannot do further visualizations and analysis with this error..)

Kind Regards, 
Eva

**Comment by evastone97** [comment]
For me It stacks here when I am trying to precompute channel or component measures
(for s9)
![image](https://user-images.githubusercontent.com/82998648/169416694-3c42ce41-ce3f-424d-bb9e-ac558be2400c.png)

and also something else that I realized is that only the 5 subjects are appearing after the calculation of the ERPs

![image](https://user-images.githubusercontent.com/82998648/169418308-a85dd007-961f-4f27-9cf4-6ac80e3a5811.png)

**Comment by arnodelorme** [comment]
Got the data. You can see that datasets 48 and 49 have different channel labels. Why is that, I do not know.

**Comment by arnodelorme** [comment]
![Screen Shot 2022-05-20 at 12 26 26 AM](https://user-images.githubusercontent.com/1872705/169476196-c28857df-4323-4603-9893-1d5699f15d87.png)

**Comment by arnodelorme** [comment]
Delete channel location and reload the file

```
for ichan = 1:72, ALLEEG(ichan).chanlocs = []; end
EEG = ALLEEG;
EEG=pop_chanedit(EEG, 'lookup','/System/Volumes/Data/data/matlab/eeglab/plugins/dipfit/standard_BEM/elec/standard_1005.elc','load',{'/Users/arno/Downloads/eeginterpol/128_channel_easycap.elp.elp','filetype','autodetect'});
```

I reloaded the file from the GUI

**Comment by evastone97** [comment]
I haven't noticed the different channel labels, and indeed don't know why and how that happened.  


I have changed the column from the dataset that was with different channel labels and now it's working I can do the precomputing for channel locations and for the components! 

Thank you very much!


I only have one question, when I am trying to plot than the channel measures it says that the s1-dataerp is corrupt, 


![image](https://user-images.githubusercontent.com/82998648/169505785-8ccfea29-7470-4f53-9b3d-f8579a4c7f35.png)

**Comment by arnodelorme** [comment]
Correct or restart from scratch. Best
