### ISSUE TITLE
pop_loadstudy error()

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#476]
Hello,

I have tried to save my study and then open it but I got this error for load study.
Do you know what might be the reason for that?
![image](https://user-images.githubusercontent.com/82998648/168498158-c9380373-879a-4686-8644-c68fbdf58683.png)

**Comment by arnodelorme** [comment]
Would you mind sharing your study? Might be due to a recent change? I am able to load studies myself right now.

**Comment by jiadeL** [comment]
Sorry, I can't. It says GitHub doesn't support edf file.

**Comment by evastone97** [comment]
I have tried it now but again I have the same error. Do you want all the data or just the study .set file? This link has just my study: https://drive.google.com/drive/folders/1xKhEj_hh_ZfET5O41l42i6Gq9AtA4vHZ?usp=sharing

**Comment by arnodelorme** [comment]
Yes, I need the whole thing.

**Comment by evastone97** [comment]
Here is the link: https://dtudk-my.sharepoint.com/:u:/r/personal/s205726_dtu_dk/Documents/s1_A_2.zip?csf=1&web=1&e=cGsF7b

I gave access to you. Let me know if it works. Thank you in advance!

**Comment by jiadeL** [comment]
Sorry, it doesn't work.
________________________________
发件人: Eva ***@***.***>
发送时间: 2022年5月17日 5:28
收件人: sccn/eeglab ***@***.***>
抄送: Liang, Jiade ***@***.***>; Comment ***@***.***>
主题: Re: [sccn/eeglab] pop_loadstudy error() (Issue #476)


External Sender. Be aware of links, attachments and requests.

Here is the link: https://dtudk-my.sharepoint.com/:u:/r/personal/s205726_dtu_dk/Documents/s1_A_2.zip?csf=1&web=1&e=cGsF7b<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdtudk-my.sharepoint.com%2F%3Au%3A%2Fr%2Fpersonal%2Fs205726_dtu_dk%2FDocuments%2Fs1_A_2.zip%3Fcsf%3D1%26web%3D1%26e%3DcGsF7b&data=05%7C01%7Cjliang6%40tulane.edu%7Cf96fafa4ff7f40c5260f08da3783116b%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637883333930784282%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4JMs5c9y6H17ek%2FLS%2BYpBmOAJS5fYM9n5WVb4d8yaBQ%3D&reserved=0>
I gave access to you. Let me know if it works. Thank you in advance!

―

**Comment by evastone97** [comment]
you mean, the study or the link?

**Comment by jiadeL** [comment]
The link. I open it, but the websit say this:

Det virkede ikke
Vi beklager, men ***@***.*** kan ikke findes i adresselisten dtudk-my.sharepoint.com. Prøv igen senere, mens vi forsøger at løse problemet automatisk for dig.
________________________________
发件人: Eva ***@***.***>
发送时间: 2022年5月17日 5:43
收件人: sccn/eeglab ***@***.***>
抄送: Liang, Jiade ***@***.***>; Comment ***@***.***>
主题: Re: [sccn/eeglab] pop_loadstudy error() (Issue #476)


External Sender. Be aware of links, attachments and requests.

you mean, the study or the link?

**Comment by evastone97** [comment]
Yes, is because I gave access only to Prof. Delorme. Do you have the same error @jiadeL ?

**Comment by jiadeL** [comment]
Yes

________________________________
发件人: Eva ***@***.***>
发送时间: 2022年5月17日 5:46
收件人: sccn/eeglab ***@***.***>
抄送: Liang, Jiade ***@***.***>; Mention ***@***.***>
主题: Re: [sccn/eeglab] pop_loadstudy error() (Issue #476)


External Sender. Be aware of links, attachments and requests.

Yes, is because I gave access only to Prof. Delorme. Do you have the same error @jiadeL<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FjiadeL&data=05%7C01%7Cjliang6%40tulane.edu%7Cf2d14e867d0946558d1108da378599f3%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637883344197186271%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xzskfuNEum%2Fs%2B9ka1MChRY6pFuGjDZzuvGo5TmH0rbE%3D&reserved=0> ?

―

**Comment by evastone97** [comment]
..I hope there is a solution on that. I am trying now to create again my datasets and create a new study.  Hope it works for you too!

**Comment by evastone97** [comment]
@jiadeL  do you also have this error when trying to create a study? 

![image](https://user-images.githubusercontent.com/82998648/168758556-0120e20b-0a30-4c9e-8585-74fb45c49b5d.png)
 I realized that I don't get this error when I am uploading my datasets manually. (but this takes time..)

**Comment by evastone97** [comment]
OK I recreate again my datasets and I have added them manually and now the study is saved successfully. 
But when I tried to precompute channel measures I got this error:
![image](https://user-images.githubusercontent.com/82998648/168764091-ec216b7b-c13d-4957-b5dc-4dbff366fa0e.png)

I have added channel location to all the datasets at the same time so what might be wrong for that?

**Comment by jiadeL** [comment]
Sorry, I don't meet the same issue as you. But I meet an issue about the size of the data is too big. Do you know any way to deal with it?
________________________________
发件人: Eva ***@***.***>
发送时间: 2022年5月17日 15:51
收件人: sccn/eeglab ***@***.***>
抄送: Liang, Jiade ***@***.***>; Mention ***@***.***>
主题: Re: [sccn/eeglab] pop_loadstudy error() (Issue #476)


External Sender. Be aware of links, attachments and requests.

@jiadeL<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FjiadeL&data=05%7C01%7Cjliang6%40tulane.edu%7Cb1b514876ec5454203f108da37da122d%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637883707020911654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XMt1zKYiDxvoq3bm7gGwhbA83gc8yLeiXfFNZ82ftGo%3D&reserved=0> do you also have this error when trying to create a study?

[image]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F82998648%2F168758556-0120e20b-0a30-4c9e-8585-74fb45c49b5d.png&data=05%7C01%7Cjliang6%40tulane.edu%7Cb1b514876ec5454203f108da37da122d%7C9de9818325d94b139fc34de5489c1f3b%7C0%7C0%7C637883707020911654%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p7ebqbhqvbYVX0TX5whymZ3Q2pSdJBxLPfXyVf0L6HM%3D&reserved=0>
I realized that I don't get this error when I am uploading my datasets manually. (but this takes time..)

―

**Comment by arnodelorme** [comment]
First check which dataset is missing channel location by typing on the command line

ALLEEG.chanlocs

This will show you the channel location structure for all the datasets.
If you still have problem, upload the data to https://drive.google.com/drive/folders/1l-cg6EU0ajErW0TIb0JTeoScgJMT6TWC?usp=sharing
as the link you provide does not allow to download the data. 

I am closing the issue for now as the error is relatively obvious, but feel free to reopen.
Thank you
