### ISSUE TITLE
close error () Unrecognized EEG field name EEG

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#477]
Hello again,

I have created a new study and I tried to precompute component measures but I got this error.

![image](https://user-images.githubusercontent.com/82998648/168878153-7d5b3691-e321-44dc-a5d2-13389718a87b.png)

I cannot even find a function called close..
Do you know what might be the reason for that?

**Comment by arnodelorme** [comment]
Strange. Never seen that before. Can you upload your study at https://drive.google.com/drive/folders/1Ewm6HSsa-tlLM3v_3ck-sJezChM6ijvv?usp=sharing

**Comment by evastone97** [comment]
I have uploaded the study in the file. Let me know if you need anything else.

**Comment by arnodelorme** [comment]
Zip file is corrupted, unfortunately.

**Comment by evastone97** [comment]
I will try to create a smaller study and send a link again
________________________________

**Comment by arnodelorme** [comment]
I have fixed the issue in 17de44248 I think. Closing this for now, but it did not fix it, please let me know.

**Comment by arnodelorme** [comment]
And make sure to reopen the issue otherwise, I will not see it.
