### ISSUE TITLE
Low threshold in std_findsameica causes false values in STUDY.cluster

### ISSUE THREAD

**Issue by nastiaglushko** [eeglabdevelopers/eeglab#48]
### Description

Problem already reported before (https://sccn.ucsd.edu/bugzilla/show_bug.cgi?id=1464) still affects the STUDY structure. std_editset, std_checkset, and std_createcluster use std_findsameica(ALLEEG) with the default threshold, which creates NaNs in STUDY.setind and leads to false values in STUDY.cluster.sets and STUDY.cluster.comps. A clear warning message would be useful (for example: check if the ICs within subjects are consistent across conditions; if so, increase the default threshold in std_findsameica?).

<br>
### Steps to Reproduce

1. Create study using std_editset
2. std_checkset(STUDY, ALLEEG)
3. size(STUDY.setind)
</br>
<br>
### Expected behavior:
For 25 subjects and 2 conditions, size(STUDY.setind) should be:
2 25
STUDY.cluster.comps should have 1510 components.
</br>
<br>
### Actual behavior:
The size of STUDY.setind in my case is 2 29 when the threshold of std_findsameica is not adjusted inside std_checkset and std_editset. STUDY.cluster.comps has more than 1700 components.
</br>
<br>
### Versions

|   |   |
|----| ---- | 
| OS version     | [*Mojave (10.14.5)*] |
| Matlab version | [*2019a*] |
| EEGLAB version | [*eeglab14_1_0b* but I glanced over the 2019 version and the issue is likely to be still present there, too] |

**Comment by arnodelorme** [comment]
This refers to an old version of EEGLAB. In the new one, we have increased the threshold by a 10-fold factor to account for the present issue.

Arno
