### ISSUE TITLE
Error in function std_readfile() at line 130

### ISSUE THREAD

**Issue by jeenalrambhia** [eeglabdevelopers/eeglab#480]
I am trying to plot channel measures in a study initially it worked fine but now i am facing this error. please guide me how to solve this.

"unable to perform assignment because the size of the left side is 0-by-119 and the size of the right side is 249-by-119"

sorry it is line 130
![error](https://user-images.githubusercontent.com/41319321/169218860-8f9757c7-6f8d-4fd2-924b-8670e96d62f7.png)

**Comment by arnodelorme** [comment]
Are you using the latest version of EEGLAB. Would you mind to share your study (including the data files?)?

**Comment by jeenalrambhia** [comment]
Thanks for your reply. This worked for me yesterday. I am not sure why it
is showing an error today.
Study is to differentiate between the rest state and mathematical
calculation state the dataset is of physionet EEGMAT.
please find the link below for dataset.
https://physionet.org/content/eegmat/1.0.0/
I am using the files in EDF format.

also i am facing another error which is while building pre-cluster  which
says
"cannot process components from different ICA decomposition of the same
subject"
error occurred in function std_readdata() at line 183

I am new to this please guide me if i have done anything wrong.

Thanks
Jeenal

**Comment by mplaweck** [comment]
For testing purposes, have you tried to eliminate the group designation? I have seen a similar error with a dataset with two sessions per subject

**Comment by jeenalrambhia** [comment]
Thanks it works but still i get the other error "cannot process components from different ICA decomposition of the same
subject" while building pre cluster 
error occurred in function std_readdata() at line 183
can you tell where i am going wrong

**Comment by arnodelorme** [comment]
Can you recompute ICA at the study level and make sure the checkbox “merge data from different dataset for a given subject” or something similar is selected?

**Comment by jeenalrambhia** [comment]
If i create a study using only subjects and condition as mentioned in the tutorial it is giving me error which states
" pop_select error:undefined argument 'trials' "
(error occurred in function pop_select() at line 220)

**Comment by arnodelorme** [comment]
If you want us to look into the problem, please send me your entire study (all files). I know it might be large. You can put the data below. Thank you

https://drive.google.com/drive/folders/1arxIkdQbYGP-R3Q9XT_g0yi3q4FBwEM7?usp=sharing

**Comment by jeenalrambhia** [comment]
I have uploaded the files. Thank you very much.

**Comment by arnodelorme** [comment]
- I downloaded all the data. 
- Imported them all.
- Assigned names and condition to them since they did not have any
```
for iS = 1:length(ALLEEG), ALLEEG(iS).subject = ALLEEG(iS).filename(8:9); ALLEEG(iS).condition = ALLEEG(iS).filename(11); end
```
- lookup channels
- precompute spectrum (no interpolation)
- plotted spectrum

Work for me.

**Comment by arnodelorme** [comment]
![Screen Shot 2022-05-31 at 8 44 20 PM](https://user-images.githubusercontent.com/1872705/171323741-83986fa7-09b8-4445-a042-d3e87550b9a2.png)

**Comment by arnodelorme** [comment]
I am going to close this for now. Make sure you have the latest EEGLAB version from Github. If you find another problem with this data, or want me to try something else with the STUDY, please let me know.
