### ISSUE TITLE
EEGLAb error in function pop_loadset at line 139:

### ISSUE THREAD

**Issue by Dalezd** [eeglabdevelopers/eeglab#482]
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/105900006/169443774-f19185bd-7080-4ee8-b26f-8cfee6168a11.png">

The file can't be loaded. I'm so sorry I haven't found solution of this bug.
The chip of my laptop is M1.
<br>
#### Versions
|   |   |
|----| ---- | 
| OS version     | [*macOS Monterey 12.4*] |
| Matlab version | [*2021a*] |
| EEGLAB version | [*eeglab 2020.0*] |

**Comment by arnodelorme** [comment]
This is likely due to the special characters. Could you put it in a folder without special characters?

**Comment by Dalezd** [comment]
> This is likely due to the special characters. Could you put it in a folder without special characters?
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/105900006/169446251-97b2f656-3809-4a52-a36a-b6bbc2fced17.png">
I've tried before.But the problem still exists.

**Comment by mengtao150** [comment]
I have the same problem, when I load sub1_2 it shows error 139 as shown in how, when I load sub2_2 there is no such problem.
![QQ浏览器截图20240424171259](https://github.com/sccn/eeglab/assets/53102174/efcf6f70-fcf3-456e-ba80-dc2d92928477)

**Comment by mengtao150** [comment]
![image](https://github.com/sccn/eeglab/assets/53102174/0a1d755f-5133-4e72-86b7-f68ef9cd5d11)
