### ISSUE TITLE
asr_calibrate error at line 145

### ISSUE THREAD

**Issue by AegeanSea353** [eeglabdevelopers/eeglab#485]
Dear Arnaud, 

I just encountered an error when using asr and clean rawdata. The bug is as follows:

The yulewalk() function was not found and there is no pre-computed spectral filter for your sampling rate. If you would like to use the default spectral filter please try to resample to
(Error occurred in function asr_calibrate() at line 145)

![screenshot_20220524211559](https://user-images.githubusercontent.com/106162459/170044069-2758be4f-44c5-4cd2-827b-937d6a8ba282.jpg)

 Here are some steps before meeting this bug: 

1. I use eeglab to preprocess EEG data (collected by EGI, epochs about 10mins, 1000hz sampling rate) and the first step is basic FIR filter, set by the 0.1-30hz range and 50hz notch.
2. Then I try to use ASR and clean rawdata to remove artifacts in the data preliminary and found this problem.

Thanks!

| OS version | macOS High Sierra 10.13.3 |
| Matlab version | [R2018b] |
| EEGLAB version | [2020.0] |

**Comment by arnodelorme** [comment]
You need the MATLAB signal processing toolbox to use that function.
