### ISSUE TITLE
pop_fileio bug importing .fif eeg channel locations

### ISSUE THREAD

**Issue by enricovara** [eeglabdevelopers/eeglab#488]
### Description

loading eeg data as so:
`
EEG = pop_fileio(fullfile(inFolder,'s2_A__Ve2_0.fif'),'dataformat','auto');
`
results in a seemingly ok EEG struct that contains EEG.chanlocs with the complete list of channel names in the first column and 'eeg' for all channels in the second columns but [] in all other columns for all channels, instead of location values.

Opening the same file using mne python yields location data.

The s2_A__Ve2_0.fif file and expected location data .mat files are attached.

Thanks!

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Mac OS 11.6.2 (20G314)] |
| Matlab version | [R2019b] |
| EEGLAB version | [2022.0] |
| Fieldtrip-lite version | [v20220602] |
| Fileio version | [v20220602] |
| bva-io version | [v1.71] |

[s2_A__Ve2_0.fif.zip](https://github.com/sccn/eeglab/files/8833321/s2_A__Ve2_0.fif.zip)
[chanLocs-64.mat.zip](https://github.com/sccn/eeglab/files/8833328/chanLocs-64.mat.zip)
[original_chan_locs.zip](https://github.com/sccn/eeglab/files/8833335/original_chan_locs.zip)

**Comment by arnodelorme** [comment]
Yes, it is strange. I imported the FIF file and the channels had locations. However, the nose is pointed in the wrong direction. I set the option in the EEGLAB channel editor to point the nose to the +Y direction. Yet, some channels are clearly misplaced (FP2 for example).

**Comment by arnodelorme** [comment]
![Screen Shot 2022-06-20 at 11 27 05 PM](https://user-images.githubusercontent.com/1872705/174737565-51479c08-e5d8-4b14-9947-51ec0c2287e3.png)

**Comment by arnodelorme** [comment]
To do: import FIF file properly

**Comment by arnodelorme** [comment]
I have imported other FIF files containing EEG and the orientation was OK. I have added a warning message. a9d7c4335
