### ISSUE TITLE
std_precomp_error

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#490]
Hello

I have another small study with 18 subjects and 3 conditions and I tried to precompute component measures and I got this memory issue problem.

I am sharing the folder with the study: https://drive.google.com/drive/folders/1SdzzuZnfnrxiUHyUaRCrVsjSCrUikskH?usp=sharing

Can you please let me know if the problem is only in my pc or is something internal?

![image](https://user-images.githubusercontent.com/82998648/172155959-f1e20538-c6bb-40d8-982f-4a38fb1f1b9b.png)

and this is what I am getting in the command window:
![image](https://user-images.githubusercontent.com/82998648/172467050-c1632ad6-1f0e-4102-9e11-de207f785e48.png)

Kind Regards,
Evangelia

**Comment by arnodelorme** [comment]
You might want to disable parallel computation in the EEGLAB preference. Let me know

**Comment by evastone97** [comment]
Ι disable the option but I still have the same issue, slightly better becsause it stopped in another participant but still I dont have the complete time frequency analysis for all of them.  
This is the study link: https://drive.google.com/drive/folders/1sJRlWqtLbWEUEvuvr5i3CJ-Mn9anxLE5?usp=sharing
