### ISSUE TITLE
ERPImage Study Error - processerpim at line 474 - Reopening

### ISSUE THREAD

**Issue by mplaweck** [eeglabdevelopers/eeglab#491]
This is a reopening of a prior error with additional replication details...

Created a simple study from a complicated dataset for testing and development - 1 subject with 2 sessions
Precompute study parameters _(including removal of prelabeled artifactual components)_ without problem (ERP, Spectra, and ERPImage).
Plotting for ERP and Spectra works without Issue.
Attempting to plot ERPimage produces the error

EEGLAB error in function processerpim() at line 474
Output argument "outsort" (and maybe others) not assigned during call to "erpimage".

![bug](https://user-images.githubusercontent.com/94379267/172462418-f4a374fe-c63a-4e23-9dae-b099fe88e4c2.jpg)

I have loaded the 1 subject 2 session dataset at
https://drive.google.com/file/d/1RjXBw_GK2KRyEik8yBGpOIwB5zk2Tzc_/view?usp=sharing

To reproduce,
-Load study
-Precompute study parameters, but include the removal of prelabeled artifactual components
-Attempt to plot ERPimage

I am now running the developer Version 2022.1b, which solved a prior error with std_readfile with multi-session subjects

| OS version | Win 11|
| Matlab version | R2021a |
| EEGLAB version | 2022.1b|

**Comment by arnodelorme** [comment]
Thank you for your clear and detailed report. This was fixed in f12bf1889
