### ISSUE TITLE
pop_comperp doesnt give output - empty figure without warnings

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#492]
Hello,

I tried to compare two conditions from two different datasets by choosing the: Sum/Compare comp. ERPs  and I fill the following

![image](https://user-images.githubusercontent.com/82998648/172553475-480ea853-fda0-408b-945f-77969f06d53e.png)

But it gives me an empty figure, and this is what I have from the command window:
![image](https://user-images.githubusercontent.com/82998648/172553596-0e94b85b-bafa-4efd-8006-0055140a6eb4.png)

What do you think it might be a problem?

**Comment by arnodelorme** [comment]
Yes, empty figure is not good. This function was removed from the menu though and is not being used anymore. Use the STUDY ERP plotting instead.

**Comment by evastone97** [comment]
I find out why is because I didnt put anything in the component subset box (I should have put [] if I want all the components or channels) and then is fine.

**Comment by arnodelorme** [comment]
Good to hear.

**Comment by evastone97** [comment]
I have one theoritical question on the use of this function if you can answer me from here. I would like to find the electrodes with the maximum activity for the specific clusters. So I thought by using this function for the channels I can see where I see the higher amplitudes but my main question is how can I link the channels with the components in order to find the best ones?

**Comment by arnodelorme** [comment]
```
[~,ind] = max(abs(EEG.icawinv(:,10)));
```

will find the index of the channel with the max activity

**Comment by evastone97** [comment]
Thank you! yes its useful, but I have to have selected or laoded a specific dataset. If I want to find the max activity from a cluster in my study desing what can I do?

**Comment by arnodelorme** [comment]
You can do the same with the individual components of the clusters for each individual or taking the average cluster maps for all individuals.

**Comment by evastone97** [comment]
My question my sound a bit silly, I have found the electrode with the highest amplitude from eash subject (dataset) thtough the icainv as you send before. But how can I choose to compute the best electrode from the average cluster topomap?
Thank you in advance :)

**Comment by arnodelorme** [comment]
I think "electrode with the highest amplitude from eash subject" is good enough. The other requires scripting.

**Comment by evastone97** [comment]
Great!, thank you :)
