### ISSUE TITLE
bvaio pop_writebva error: Unrecognized field name "nbchan"

### ISSUE THREAD

**Issue by Valerie123hi** [eeglabdevelopers/eeglab#493]
Hello!

I have a problem with exporting EEG data from Eeglab to Brainvision Analyzer (via bvaio).

It works fine to load existing datasets (also the whole database).
However, I can only export one file at a time (manually by clicking on file - - > export - - > Write Brain Vis. exchange format file in Eeglab) 

I copied the history file of this operation and tried to apply it to all files:

   EEG.etc.eeglabvers = '2021.1'; % this tracks which version of EEGLAB is being used, you may ignore it
    EEG = eeg_checkset( EEG );
    EEG = eeg_checkset( EEG );
    EEG = eeg_checkset( EEG );
    EEG = eeg_checkset( EEG );
    EEG = eeg_checkset( EEG );
    EEG = eeg_checkset( EEG );
    EEG.etc.eeglabvers = '2022.0'; % this tracks which version of EEGLAB is being used, you may ignore it
    EEG = eeg_checkset( EEG );
    pop_writebva(EEG,'E:\folder\allfiles(datafile).name');

I always get this error:

Unrecognized field name "nbchan".

Error in pop_writebva (line 94)
for index = 1:EEG.nbchan

Line 94 looks like this (it's the 3rd line here) 

% write data
% ----------
for index = 1:EEG.nbchan
    fwrite(fid3, EEG.data(index,:), 'float' );
end;

What could be the problem, and how can I solve it other than having to export all 580 files separately?

Thank you!
Valerie

**Comment by arnodelorme** [comment]
Yes, you can only export one file at a time. I have added an error at https://github.com/arnodelorme/bva-io/commit/6a89aca54f0da2af3529fc1e8958a5091348f9fc
