### ISSUE TITLE
reorganizeddata() at line 328

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#495]
Hello, 

I have a study where I precomputed all the necessary components and then I did my clustering and I wanted to plot the ERPs on a cluster-based permutation test.

So I made this choice in EEGLAB STATS and then I press to plot the ERPs and I got this error:

![image](https://user-images.githubusercontent.com/82998648/173356478-3cc37520-e2de-43e8-81ef-c866c5c86500.png)

![image](https://user-images.githubusercontent.com/82998648/173356390-de5972a8-68aa-43b5-928f-53f7466d4fc4.png)

Do you know what might be the reason for that?

**Comment by arnodelorme** [comment]
Dear Eva,

I would need to get the data to try to reproduce the problem.

**Comment by evastone97** [comment]
Hello I finally found what the problem was, it was something wrong in my datasets that mess up the process I did it again from the beggining and it worked thank you !
