### ISSUE TITLE
No .fdt file created when filtering data, can't open filtered files

### ISSUE THREAD

**Issue by Sarah236** [eeglabdevelopers/eeglab#496]
Hi all, trying to filter eeg data following the guide screenshot below. 
``
<img width="753" alt="Screen Shot 2022-06-13 at 10 10 23" src="https://user-images.githubusercontent.com/107416764/173373644-c20dac0a-2f00-4a5f-8376-51c0ab77c096.png">
<img width="783" alt="Screen Shot 2022-06-13 at 10 10 31" src="https://user-images.githubusercontent.com/107416764/173373654-9182be79-7281-4751-8fc5-c2ec7a016596.png">

All seems fine during the filtering process, and when I am done the filtered file is shown in eeglab, and I can manually inspect the channels afterwards. However, when I close it and go to file->load existing dataset I see there is only a .set file in the folder, and when I try to open that I get the following error:

<img width="512" alt="Screen Shot 2022-06-10 at 2 00 39 PM" src="https://user-images.githubusercontent.com/107416764/173373751-f1602fbf-670d-4f16-a103-0b3131f7ba1f.png">

In the matlab code this is what I see:

pop_loadset(): loading file /Users/sarahgilmore/Desktop/UConn/Research/Internal Attention/Study 2/Study 2 Data/P05/EEG Files/Lecture 1/P05L1_datafilt.set ...
pop_loadset(): Incompatible with new format, trying old format and converting...

Anyone have any ideas what is going on there?

**Comment by arnodelorme** [comment]
Dear Sarah, would you mind sharing your data. If it is not too big, you can zip it and drag and drop here. If there is a "fdt" file associated with your "set" file make sure to include both.

**Comment by arnodelorme** [comment]
Hi Sarah, closing this report since you did not respond, but do not hesitate to reopen it if you have a dataset to share.
