### ISSUE TITLE
eeglab error in function prepare_headmodel() at line 74

### ISSUE THREAD

**Issue by mlrocca** [eeglabdevelopers/eeglab#497]
### Description
Hi, 

I am using in eeglab the function component dipole coarsefit

Even though I have fieldtrip-lite (v20220612) installed on eeglab version v2021.1 I have this error message:

eeglab error in function prepare_headmodel() at line 74

Undefined function ft_read_headmodel for input arguments of type char

If you think this is a bug, please submit a detailed description of how to reproduce the problem (and upload a small dataset) at https://github.com/sccn/eeglab/issues/

Could you help me to understand what is the problem?

**Comment by arnodelorme** [comment]
Did you install Fieldtrip manually? EEGLAB prefers Fieldtrip to be in the plugins folder. This way if it can add the necessary paths. Otherwise, you need to make sure that the Fieldtrip is in the path.
