### ISSUE TITLE
caxis error line 33

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#499]
Hello,

I have run time frequency analysis on my data and I try to run some statistics on them. I have an output  figure but I also have this errpr - I think is something going wrong with the plot for the pvalues.

![image](https://user-images.githubusercontent.com/82998648/173768622-e4817aaf-4ca6-49d4-aeab-6879133f0b72.png)

![image](https://user-images.githubusercontent.com/82998648/173768730-0d9fcae0-0059-485e-8b37-2d94ff13237b.png)

This is the link for my study:
https://drive.google.com/drive/folders/1_IUo8q8pO-3b3emnzSAlYJDVx0m1YP3z?usp=sharing

**Comment by arnodelorme** [comment]
This is now fixed in 86af1969f. Let me know.

**Comment by evastone97** [comment]
Perfect now it works!, but that means that there was no significant difference in this dataset? (as I saw from the description of your commit) Also how cluster based permutation test with p value 0.05 has no significance and the other tests (non parametric and/or parametric) they show significance?

**Comment by arnodelorme** [comment]
Sometimes, different methods for computing significance vary. It should be similar, though.
