### ISSUE TITLE
Bug when rereferencing to mathematically linked earlobes

### ISSUE THREAD

**Issue by nexxoc** [eeglabdevelopers/eeglab#50]
Hi,

I am recording an EEG with a fixed reference (Afz in my case). After importing the files and adding channel locations in eeglab, I then want to re-reference the EEG to "A1 A2" using the pop up windows (mathematically linked earlobes). This works fine, "A1 A2" appears under "Reference".

However, when doing this, A2 disappears from the data locations windows. Only A1 is still present (with "Channel in data array" unchecked). This leads to the problem that, if I want to re-reference again (e.g. to average), I can only select A1 in the "Add current reference channel back to dataset" and A2 completly disappears from my dataset.

I can manually add A2 in the "channel location" window, but this completly messes up my whole data structure.

Is this a bug or am I missing something?

Malte

**Comment by arnodelorme** [comment]
Dear nexxoc,

The proper way to do that is to calculate average reference first, the reference to the channel pair.

https://sccn.ucsd.edu/wiki/I.4:_Preprocessing_Tools#Re-reference_to_multiple_channels

Let me know if this helps,

Arno
