### ISSUE TITLE
Bug when precomputing channel measures of continuous data

### ISSUE THREAD

**Issue by MarceloFilipchuk** [eeglabdevelopers/eeglab#501]
### Description

[*Description of the bug or feature
Error when precomputing channel measures for 1 epoch 1 trial continous data for multiple subjects. The error message was: " pop_select error undefined argument 'trials' "

<br>
#### Steps to Reproduce
I got an error when precomputing channel measures of a 144 subjects with 1 trial 1 epoch of continous data per subject.

<br>
I solved it by correcting what I believe must have been a misstyping of the argument 'trial' in line 275 of "std_spec". I replaced 'trials' for 'trial' as apparently pop_select uses the argument 'trial' (without 's'). Here I attached said part:

TMP = pop_select(TMP, 'trials', [epochCount:(epochCount+EEG(iEEG).trials-1)]); 
changed for:
TMP = pop_select(TMP, 'trial', [epochCount:(epochCount+EEG(iEEG).trials-1)]); 

I don't know if this fix is correct, but at least allowed me to continue precomputing the channel measures.
<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     |Windows 10|
| Matlab version |R2020a|
| EEGLAB version |2022.0|

**Comment by arnodelorme** [comment]
Thank you. The issue has been solved in 2e2cf2701
