### ISSUE TITLE
EEGLAB error - moving components between clusters

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#504]
Hello, 

I have tried to move one component from a cluster and I got this error. I dont know why but before for another study it work perfectly, now no..
![image](https://user-images.githubusercontent.com/82998648/175348741-78278452-a5c0-4d4d-a8de-a4c7ee69fbb0.png)

**Comment by arnodelorme** [comment]
Hi Eva. Sorry I was on vacation. Would you mind sharing your study and also indicate to me which component I should try to move?

**Comment by evastone97** [comment]
Hi Prof. Delorme, thank you for asking, actually I re-do the custers again, I dont know why the GUI didnt let me to reassing the components. I can share the study though so you can see if there is something. For now I dont want any help with EEGLAB since my master project is coming to an end. I would like to thank you for your support and for answering questions in the formum. I got a lot of technical support just by asking and that help me answering most of questions related to my project. I will also mention you in my thesis for that :) Have a nice day!

**Comment by arnodelorme** [comment]
Thank you Eva. Yes, please share your study if you can.
