### ISSUE TITLE
Assign Bin Error [Invalid Identifier]

### ISSUE THREAD

**Issue by MrvKrt** [eeglabdevelopers/eeglab#507]
Hi, I have a problem with the stage of EEG Lab, Assign Bin. After creating event, I receive this error message below: 

fprintf error
`Invalid file identifier. Use fopen to generate a valid file identifier. (Error occured in function createeventlist() at line 239)`

**Comment by arnodelorme** [comment]
Would you mind providing more detail. Which dataset, which event? We need to be able to reproduce the problem. Thank you.

**Comment by MrvKrt** [comment]
I have a gtec hd5 file.  I follow the order analysing my data;
Import file, select data and apply channel locations. Apply ERP Lab, Filter for EEG data.
Channel Data (scrolls) cleaning part, after run ICA. Reject data using ICA, remove components.
Create Bin List. Assign Bins then I receive the error message. Here's my the error:

![image](https://user-images.githubusercontent.com/63539249/177057449-ce6c5922-1698-4e0a-b72d-74c9ac799c07.png)

**Comment by arnodelorme** [comment]
This is an ERPLAB problem apparently. I suggest copying and pasting your issue at https://github.com/lucklab/erplab/issues
