### ISSUE TITLE
Channel spectra and maps bao

### ISSUE THREAD

**Issue by self-me** [eeglabdevelopers/eeglab#51]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
![image](https://user-images.githubusercontent.com/50400322/64761894-bc5fec80-d56f-11e9-866e-5a7071b4a8d5.png)

| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |
![image](https://user-images.githubusercontent.com/50400322/64761909-c2ee6400-d56f-11e9-92a0-70311eef76de.png)
这一步出现以下错误
![image](https://user-images.githubusercontent.com/50400322/64761960-d4d00700-d56f-11e9-8669-95e344422b37.png)

**Comment by arnodelorme** [comment]
Would you mind to provide the dataset you are using as input?

**Comment by self-me** [comment]
Thank you. The trouble has been solved
