### ISSUE TITLE
pop-up during LIMO batch processing

### ISSUE THREAD

**Issue by CPernet** [eeglabdevelopers/eeglab#512]
The pop up says "Do you want to keep the unsuccessfully processed subjects"
Would be great if there is no pop up during batch processing
--> refers to wrongly assigned LIMO issue https://github.com/LIMO-EEG-Toolbox/limo_tools/issues/108

the code that generates the pop up is [here](https://github.com/sccn/eeglab/blob/develop/functions/studyfunc/std_limo.m#L640) in std_limo.m, not sure how to deal with this, as keeping tmp files is useful for debugging

**Comment by arnodelorme** [comment]
Closing this for now. But will reopen if I see it again. Would be great to have a script that generates the problem.
