### ISSUE TITLE
report which dataset are not correct in a study

### ISSUE THREAD

**Issue by CPernet** [eeglabdevelopers/eeglab#514]
when loading a study, the command window returns:
```
Rebuilding trial information structure for STUDY  
Warning: some datasets are continuous and trial information cannot be created  
```

it would be useful to users to know which one it is

**Comment by arnodelorme** [comment]
When you get this message, it is usually all of them.

Arno

**Comment by CPernet** [comment]
no it was just sub-18 from Wakeman and Henson (when cleaning too much, epoching doesn't work)

**Comment by arnodelorme** [comment]
This is because one dataset only has one epoch left.

[ALLEEG.trials ] 

Will tell you which one.

Arno
