### ISSUE TITLE
EEGLAB error in function pop_resample() at line 224

### ISSUE THREAD

**Issue by quitealot** [eeglabdevelopers/eeglab#515]
### EEGLAB error in function pop_resample() at line 224

Hello!
An issue about downsampling resting -state EEG data of 64 channels. The pre-data's sampling rate is 1024.5902 Hz. 

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*MATLAB R2019b*] |
| EEGLAB version | [*EEGLAB v2022.0*] |
![727ae980421f46e29bfe5f3dfdb75b7](https://user-images.githubusercontent.com/89231502/183362757-55deb268-c828-41cb-a383-bdeb67ebba45.jpg)

**Comment by arnodelorme** [comment]
Yes, there is a known problem with resampling data with a fractional sampling rate. I would change the sampling rate to 1024 first in the data editor (Edit > Dataset info menu item). Then you can resample.
