### ISSUE TITLE
ICLabels error eeg_rpsd() line 38

### ISSUE THREAD

**Issue by af9246** [eeglabdevelopers/eeglab#518]
### Description

When trying to run "tools --> classify components using ICLabel --> label components", after pop up menu and selecting default (or lite or beta), I get the following error message

![image](https://user-images.githubusercontent.com/111197310/184505952-3d20257f-370b-4273-9f00-60b947d12401.png)

<br>

**Comment by arnodelorme** [comment]
Apologies for the late reply. Would you mind sharing your dataset?

**Comment by arnodelorme** [comment]
Closing this for now, feel free to reopen.
