### ISSUE TITLE
Warning about adding 'resources' to path

### ISSUE THREAD

**Issue by VisLab** [eeglabdevelopers/eeglab#52]
### Description

I just started using Matlab 2019a.  I ran eeglab from the eeglab directory and got the following two warnings:
1)
`Warning: Adding folders named 'resources' to the path is not supported:
D:\Research\FluencyProject\eeglab14_1_2b\functions\resources 
> In path (line 109)
  In addpath (line 86)
  In eeglab>addpathifnotinlist (line 2059)
  In eeglab>myaddpath (line 2088)
  In eeglab (line 293) `

2)
`Warning: Adding folders named 'resources' to the path is not supported:
D:\Research\FluencyProject\eeglab14_1_2b\functions\resources 
> In path (line 109)
  In addpath (line 86)
  In eeglab>addpathifnotinlist (line 2059)
  In eeglab>myaddpath (line 2088)
  In eeglab (line 293)
  In eeglab (line 1090) 
`

<br>
#### Actual behavior:
Just a warning ---- this must be new to R2019a

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 7] |
| Matlab version | [R2019a] |
| EEGLAB version | [14_1_2b] |

**Comment by olafdimigen** [comment]
Getting the same warning using same MATLAB/EEGLAB version and Win 10

**Comment by arnodelorme** [comment]
We have renamed the "ressources" folder "supportfiles" for that reason in EEGLAB 2019.0 and 2019.1

**Comment by linaismail** [comment]
Hello I have the same issue while using EEGLAB 2019

**Comment by jcmota0** [comment]
Change the name of the "resources" folder to "supportfiles".
Go to the eeglab.m file, and change all the lines that have the "resources" folder name to "supportfile". 
Reload eeglab and you won't have the error.
