### ISSUE TITLE
Cannot perfomr datatype transformation after deleting channels

### ISSUE THREAD

**Issue by finch-f** [eeglabdevelopers/eeglab#526]
### Description

I want to compute CSD on EEG data which was obtained from Neuroscan 64 electrodes. As channels CB1 and CB2 have no location values, I delete the two channels and then click the Datatype transformation in ERPLAB. Sadly, an error occurred. It said EEGLAB error in function pop_chanedit() at line 745: Cannot open file
<br>

#### Steps to Reproduce

1. load EEG dataset
2. In the EEGLAB Edit menu, click 'select data', choose CB1 and CB2, then remove the two channels
3. In the ERPLAB menu, click 'Datatype transformation', choose ' CSD from EEG data set'

<br>
#### Expected behavior:
[*What you expected to happen*]
![ERPlab](https://user-images.githubusercontent.com/39895713/188492970-5fc46d83-7118-48cc-9014-5f85ad28036f.jpg)

<br>
#### Actual behavior:

[ICA_filt_event_1_11.zip](https://github.com/sccn/eeglab/files/9491385/ICA_filt_event_1_11.zip)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*win10*] |
| Matlab version | [*2019a*] |
| EEGLAB version | [*2020.1*] |

**Comment by arnodelorme** [comment]
You need to post your message on the ERPLAB issue. Thank you,
