### ISSUE TITLE
Install/update of SASICA fails

### ISSUE THREAD

**Issue by eioe** [eeglabdevelopers/eeglab#53]
### Description

Installing SASICA plugin via GUI fails with error 'Invalid zip file "...\tmp.zip". Error occured in function unzip() at line 84.'
Installing SASICA (1.3.4) manually (i.e., downloading & extracting into plugin folder) works. 
Installing other plugins via GUI also works.

<br>

#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 |
| Matlab version | 2017b |
| EEGLAB version | v2019.0 |

**Comment by arnodelorme** [comment]
@dungscout96 would you mind to investigate why this plugin fails to install.

**Comment by arnodelorme** [comment]
This has been fixed for EEGLAB 2019.1. It is unclear why the file was corrupted.
