### ISSUE TITLE
Plot Single Trial Figure not deleting after pop_subcomp() completion

### ISSUE THREAD

**Issue by KCull887** [eeglabdevelopers/eeglab#532]
### Description

'Plot single trials' figure not being deleted upon acceptance and completion for component removal during call to pop_subcomp()

<br>
#### Steps to Reproduce

1. Obtain .set file that has undergone ICA decomposition
2. Call pop_subcomp() providing data from step 1 as input with visualization turned on
3. Select 'Plot Single Trials' option
4. Select 'Accept' in main pop up

<br>
#### Expected behavior:

Expected plotted data figure to close

<br>
#### Actual behavior:

Single Trial data plotted figure remained after clicking 'Accept' and finishing component removal

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 19042.1889 |
| Matlab version | R2021b |
| EEGLAB version | Eeglab 2021.0|

**Comment by arnodelorme** [comment]
You the EEGPLOT figure when component are being removed. Good point. This is a feature more than a bug. The figure is non modal. But we will have a look.
