### ISSUE TITLE
Issue importing xdf from lab recorder to eeglab

### ISSUE THREAD

**Issue by Tbuck21** [eeglabdevelopers/eeglab#535]
### Description
xdf files imported to eeglab via xdf importer and mobilab extension both give errors regarding the 'channel names' parameter, mobilab fails to import the file, xdf importer imports the file and reads it as having 125 channels. We are using an 8 electrode headset.  

data found here
https://drive.google.com/drive/folders/1hJ21sbZxhnBwP9vRv99yI2UkUVN2dqfx?usp=sharing
<br>
#### Steps to Reproduce

1. Obtain .xdf file from labrecorder
2. use matlab/eeglab's mobilab/xdf importer to import data
3. view data scroll within 

<br>
#### Expected behavior:
Expected to obtain an output that displays 8 channels.  

<br>
#### Actual behavior:
obtained an output that displayed 125 channels

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 10] |
| Matlab version | [R2022a] |
| EEGLAB version | [v2022.1] |

**Comment by arnodelorme** [comment]
I have posted your problem on other forums. I think the issue is likely with the driver of your 8-channel device which writes corrupted data to the LSL stream.
