### ISSUE TITLE
eeglab-Cannot connect to the Internet to retrieve statistics for extensions 

### ISSUE THREAD

**Issue by naloui1** [eeglabdevelopers/eeglab#536]
Hello,
I am using eeglab for more than one year.
Today, I tried to use eeglab. But I encountered the following problems

Some menus items hidden. Use Preference menu to show them all.
eeglab: options file is C:\Users\NA263951\eeg_options.m
Retrieving plugin versions from server...
Retreiving download statistics...

**Cannot connect to the Internet to retrieve statistics for extensions
Index exceeds the number of array elements (0).
Error in plugin_getweb (line 65)
for iRow = 1:length(stats{1})
Error in eeglab (line 914)
        pluginTmp = plugin_getweb('', pluginlist, 'newlist');**

Can someone help please?
Thank you in advance

**Comment by arnodelorme** [comment]
This happens when the internet is on but the connection times out. This has been fixed in recent EEGLAB releases.
