### ISSUE TITLE
edit->channel locations: from .elp file

### ISSUE THREAD

**Issue by kwswan2** [eeglabdevelopers/eeglab#538]
### Description
When changing the channel locations in older versions of eeglab, the attached .elp file works fine for 128 channel biosemi data. however, the newest version of eeglab produces an error message ( see attached screenshots for gui 2022.1 vs 2021.1). attached is also the .elp file we are using (to enable upload, this file is here a .txt file, in reality, the file has the extension .elp) . Any suggestion would be appreciated.

[Importing channel locations in version eeglab2022.1 vs. version eeglab2021.1.pptx](https://github.com/sccn/eeglab/files/9725050/Importing.channel.locations.in.version.eeglab2022.1.vs.version.eeglab2021.1.pptx)
[coords3.txt](https://github.com/sccn/eeglab/files/9725063/coords3.txt)

**Comment by arnodelorme** [comment]
OK, I have fixed in the issue in e9fe2f6da
