### ISSUE TITLE
Unable to open .vhdr file obtained from brain vision recorder

### ISSUE THREAD

**Issue by narvaria333** [eeglabdevelopers/eeglab#539]
latest version of EEGLAB is not able to open .vhdr format file obtained from brain vision recorder. 

[ EEGLAB not showing option to open .vhdr files obtained from brain vision recorder
https://drive.google.com/file/d/1Fs73jBiouKnJrNqp5T7Gf19yqV8KGMl7/view?usp=sharing
https://drive.google.com/file/d/1Fs73jBiouKnJrNqp5T7Gf19yqV8KGMl7/view?usp=sharing]

<br>
#### Steps to Reproduce

1. click on "import data" in FILE section
2. Using  eeg function and plugin options open brain vis rec .vhdr and .ahdr files
3. it should open .vhdr file.

<br>
#### [ * It should open vhdr files normally*]

<br>
#### Actual behavior:
[*reporting error in pop load(bv) i.e. reading the file]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*ubuntu*] |
| Matlab version | [*R2022a*] |
| EEGLAB version | [*2022.1*] |

**Comment by arnodelorme** [comment]
Can you share a file?

**Comment by narvaria333** [comment]
I will ask my PhD guide first then send you a google link for that .
However, problem is not with the file but the update in my ubuntu desktop I
think, because I am able to open the same file in my personal computer with
window 10. However I tried to reinstall eeglab but its not working.

Regards,
Abhishek SIbngh Narvaria

**Comment by arnodelorme** [comment]
Yes, please share the file. Closing this report for now but feel free to reopen.
