### ISSUE TITLE
Crash when rotating channel location to +y direction after adding channel location file 

### ISSUE THREAD

**Issue by panjessi** [eeglabdevelopers/eeglab#543]
Matlab version: R2022b 
EEGLab version: eeglab2021.0

Matlab crashes when I used EEGlab to rotate channel location to +y direction after loading channel location . ced file

**Comment by arnodelorme** [comment]
Does MATLAB returns an error, or does it completely crash?

**Comment by panjessi** [comment]
It becomes “not responding” and the mouse is stuck in loading.

**Comment by arnodelorme** [comment]
I have seen that before. Do you have a newer M1 Mac? For me, I rebooted and the problem went away. You can also go in the OSx security and sometimes they block MATLAB GUI.

**Comment by arnodelorme** [comment]
Closing this for now
