### ISSUE TITLE
Error reported for ERSP plot in Study

### ISSUE THREAD

**Issue by Naba1210** [eeglabdevelopers/eeglab#545]
ERROR: Number of elements must not change EEGlab study

Dear EEGLAB,

I am writting here to report a bug related to the std_stdcond function (also in the GUI).

#### Steps to Reproduce
 
Load the [Objective1.study]
Study location: https://drive.google.com/drive/u/2/folders/0ALSJMw_UHlf9Uk9PVA
![1](https://user-images.githubusercontent.com/74348971/198218530-c6c24536-e3c0-4a9f-978c-10b0720847d3.jpg)

[First Step]
STUDY-->Run ICA-->Head Model and fitting-->Component Dipole autofit-->DIPFIT<15%

[Second Step]
STUDY --> Precompute channel measures -->
[Third Step]
STUDY -->Pre clustering
![3](https://user-images.githubusercontent.com/74348971/198218471-d9e06604-60db-4ce1-9024-b947ca966e45.jpg)

[Fourth Step]-->cluster complonents

[Fifth Step]--> Plot ERSP [ERROR]

Number of elements must not change. Use [] as one of the size inputs to automatically calculate the appropriate size for that dimension.

![4](https://user-images.githubusercontent.com/74348971/198219541-d5ed4469-d68e-4041-8e87-e669ed7c9ea3.jpg)

Hypotheses
I suspect that the data structure has similar events but there are some files which are showing uevents "[]"

The original files are all having same data structure, but turns out after precomputing this was the only difference i could find

<html>
<body>

OS version | Windows 11 22000.1098
-- | --
Matlab version | Matlab R2021b
EEGLAB version | EEGLAB v13.6.5b

</body>
</html>

**Comment by arnodelorme** [comment]
Apologies for the late reply. I was traveling. I have requested access to the data.

**Comment by arnodelorme** [comment]
The shared folder is empty so I cannot test. Closing this report for now.
