### ISSUE TITLE
EEGLAB on the linux command line goes into debug mode? 

### ISSUE THREAD

**Issue by ulloaa** [eeglabdevelopers/eeglab#550]
### Description

When we run eeglab commands as slurm jobs (HPC cluster) on the command line egglab goes into debug mode. For example:
<br>
#### 

*matlab -nodisplay -nodesktop -nojvm -nosplash -r 	"eeg = pop_loadbv('/my/eeg/data', 'test.vhdr')*

<br>
#### Expected behavior:
*Not to go into debug mode*

<br>
#### Actual behavior:
*Goes into debug mode*

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Linux Centos*] |
| Matlab version | [*2022a*] |
| EEGLAB version | [*2022.0*] |

**Comment by arnodelorme** [comment]
Apologies for the late reply. We run in slurm all the time without any issue. To run in debug mode, one must type "dbstop if error" but this is nowhere to be found in EEGLAB code.

I am at loss here, but please comment on the issue if you find the problem.
