### ISSUE TITLE
Facing 'Reference to non-existent field 'signalTypeIndicator'' problem in EEGLAB using Blinker

### ISSUE THREAD

**Issue by 19-17-18** [eeglabdevelopers/eeglab#551]
### Description
I am facing 'signalTypeIndicator'  for .cnt file after 'Run Blinker'
#### Versions

|   |   |
|----| ---- | 
| OS version     | [19044.2251] |
| Matlab version | [2017a] |
| EEGLAB version | [2022] |

**Comment by arnodelorme** [comment]
Closing this report. Does not seem to be related to EEGLAB.
