### ISSUE TITLE
EEGLAB preprocessing troubles

### ISSUE THREAD

**Issue by p3k88** [eeglabdevelopers/eeglab#552]
Good evening,
I am writing to kindly ask you for help with a problem I am experiencing in the EEG preprocessing phase. It is a recording of about 3 minutes, continuous, in resting state through a 128 channel system (ANT_waveguard). We believe that the problem is related to the configuration of the electrodes but we are not sure and we cannot solve it.

1-	We recorded a 3 min continuous sample of EEG (resting state) via 128-channel ANT Waveguard . The file is saved by default in a proprietary format (“.TRC”). However, it can be exported to .EDF
2-	The EDF file has these characteristics
 
![image](https://user-images.githubusercontent.com/118300414/201991617-42e355c3-dfbc-4f54-bbd1-b184a680a59e.png)

This is an extract of the track:
 
![image](https://user-images.githubusercontent.com/118300414/201991651-42691ec9-b598-4728-89ae-2b6943930ca4.png)

 
![image](https://user-images.githubusercontent.com/118300414/201991669-1d77a175-5c8a-41e9-806a-e4dcaef290cc.png)

3-	Subsequently we exclude from the analyzes the electrode 65 and 130 which are two “marker” and set the channel locations . We have made many attempts with different configurations:
a.	We tried "look up locs " as in the following image 
 
![image](https://user-images.githubusercontent.com/118300414/201991696-c67795dd-b8ee-44c5-963f-30c26896f342.png)
![image](https://user-images.githubusercontent.com/118300414/201991713-d09b9dd9-a6c5-48c5-84f6-d390cd989509.png)
![image](https://user-images.githubusercontent.com/118300414/201991725-ce179409-30a1-4b40-8f07-804cff15ace7.png)

 
b.	We also tried to import numerous files (.ced . spf .txt .mat ) with different possible configurations for ant-waveguard 128 channels headset. We checked that the order of the electrode labels was the same.
4-	After configuring the position of the electrodes this is channel spectra and maps (re- referencing has not yet been carried out )
 
![image](https://user-images.githubusercontent.com/118300414/201991785-68f62cd9-9122-4a5a-85ec-db69931fbe2c.png)

Then we proceed to referencing (average) and this is channel spectra and maps

 
![image](https://user-images.githubusercontent.com/118300414/201991800-da5e2564-1149-491f-b4a6-8cfda237e5d2.png)

5-	We proceed with the inspection of the track, low pass and high pass filter (2-30 Hz) and then ICA to identify the different components and this is what results:

 
![image](https://user-images.githubusercontent.com/118300414/201991828-ff67a827-c744-487e-a719-2e30ee393abb.png)

There are numerous "strange" components ( eg 7 8 9 11 12 14 etc ):
In detail, one of these (9):

 
![image](https://user-images.githubusercontent.com/118300414/201991865-51623a25-c0c0-463f-bd3d-77e2e2886bca.png)

Unfortunately this type of "artifact" is massively present, compromising all subsequent analysis (EEG Microstates). 
We tried different electrode configurations found online or adapted from other software, different filters, interpolated bad channels, changed the sample rate without success. 
We know that the quality of the track is not optimal (the recording is done in an environment with a lot of background noise) but we do not think that the problems can come from the quality of the track. We hypothesized that it has to do with the location of the electrodes.

We then wrote to the company that distributes the EEG machine  which only sent us a file with the coordinates of the electrodes. Unfortunately in the file there are labels different from those of the International 10–20 system (and there are also 256 electrodes instead of 128) so we cannot use it.

We can’t figure out the problem and a possible solution.

I also attach Gdrive links with data, channel locations etc 
https://drive.google.com/drive/folders/1hqSfyLy3VJwn3dsvnxVxl9cjLMLJr2DS?usp=share_link

I thank you immensely and in advance for any possible advice.
Thank you,

**Fede**

**Comment by arnodelorme** [comment]
This looks like an amplifier issue. We can see the bundle of electrodes affected.
I am closing this bug report, but you should talk to your manufacturer.
