### ISSUE TITLE
EEGLAB error in std_precompt() #477

### ISSUE THREAD

**Issue by Sanlucat** [eeglabdevelopers/eeglab#553]
### Description

Hello,
i was trying to STUDY with 8 datasets of continuous data from the same subject and 15 subjects. I got the error attached in the file. I tried the fixed version of the function std_precomp.m [https://github.com/sccn/eeglab/blob/develop/functions/studyfunc/std_precomp.m](url) but the error remained. 

<br>
#### Steps to Reproduce

1. File => Create study 
2. Simple ERP Study
3. I complete each condition by the file associated and then "ok" 
5. Error happened

<br>
#### Expected behavior:
I'm expected that function create a study.

<br>
#### Actual behavior:
No study is created and an error in the function at line (#477) happened. 

<br>
#### Versions
<img width="924" alt="Capture d’écran 2022-11-16 à 09 12 08" src="https://user-images.githubusercontent.com/118341839/202124426-516b26fd-bb1e-45d6-be26-7405044c4169.png">

|   |   |
|----| ---- | 
| OS version     | [*macOS Monterey*] |
| Matlab version | [*MATLAB R2022b*] | 
| EEGLAB version | [*EEGLAB v2022.1*] |

**Comment by Sanlucat** [comment]
> ### Description
> Hello, i was trying to STUDY with 8 datasets of continuous data from the same subject and 15 subjects. I got the error attached in the file. I tried the fixed version of the function std_precomp.m [https://github.com/sccn/eeglab/blob/develop/functions/studyfunc/std_precomp.m](url) but the error remained.
> 
> 
> #### Steps to Reproduce
> 1. File => Create study
> 2. Simple ERP Study
> 3. I complete each condition by the file associated and then "ok"
> 4. Error happened
> 
> 
> #### Expected behavior: I'm expected that function create a study. 
> #### Actual behavior: No study is created and an error in the function at line (#477) happened. 
> #### Versions
> <img alt="Capture d’écran 2022-11-16 à 09 12 08" width="924" src="https://user-images.githubusercontent.com/118341839/202124426-516b26fd-bb1e-45d6-be26-7405044c4169.png">
> 
> OS version	[_macOS Monterey_]
> Matlab version	[_MATLAB R2022b_]
> EEGLAB version	[_EEGLAB v2022.1_]

**Comment by arnodelorme** [comment]
Thank you. FIxed in 3391bab37
