### ISSUE TITLE
Error when removing channel using types

### ISSUE THREAD

**Issue by dungscout96** [eeglabdevelopers/eeglab#558]
### Description
When using pop_select with argument `rmchantype` it failed with error
```
Error using eeg_decodechan
Too many input arguments.

Error in pop_select (line 291)
        inds = eeg_decodechan(EEG, g.rmchantype, 'type', 'labels', true);
```

#### Steps to Reproduce

EEG = pop_loadset('.../eeglab/sample_data/eeglab_data.set');
rm_chan_types = {'AUDIO','MEG','EOG','ECG','EMG','EYEGAZE','GSR','HEOG','MISC','PPG','PUPIL','REF','RESP','SYSCLOCK','TEMP','TRIG','VEOG'};
EEGNew = pop_select(EEG, 'rmchantype', rm_chan_types);

#### Expected behavior:
EEGNew have all channels specified in `rm_chan_types` removed 

#### Actual behavior:
It crashed with the error mentioned above.

#### Versions

|   |   |
|----| ---- | 
| OS version     | macOS 12.0.1 |
| Matlab version | R2021a |
| EEGLAB version | develop as of commit [a3de748](https://github.com/sccn/eeglab/commit/a3de7483965a3eaaabd26d7e7840acf618e4d7c2) |

**Comment by arnodelorme** [comment]
Fixed in 8559c7bd9
Thanks for the clear example
