### ISSUE TITLE
EEGLAB error when adding new subjects to existing study

### ISSUE THREAD

**Issue by MJ202201** [eeglabdevelopers/eeglab#559]
### Description

When I try to use STYDY plot ERPs 

I got an error saying **_"eeglab error in the function getfilename() at line 504:
Array indices must be positive integers or logical values"_**

![eeglab error in the function getfilename() at line 504---STUDY plot erps](https://user-images.githubusercontent.com/107088712/204849721-82c072ef-b6ab-4138-a9ee-6f88dc69f768.png)

I have tried to debug it by myself but apparently, I cannot find the function named getfilename()... So now I do not know where to start. Can you help me to fix this problem?

The step I went through is

1. File > Load existing STUDY 
2. Edit > channel location
3. Study > precomputed data
4. Study > plot channel measures > plot erps

Thank you in advance
[eeglab error in the function getfilename() at line 504---STUDY plot erps.zip](https://github.com/sccn/eeglab/files/10117561/eeglab.error.in.the.function.getfilename.at.line.504---STUDY.plot.erps.zip)

**Comment by arnodelorme** [comment]
Apologies for the late response. WOuld you mind sharing your entire study?

**Comment by mdussaultgomez** [comment]
Hi, was there ever a solution to this issue? It's happening to me as well whenever I try add new subjects to an already created study.

**Comment by leima1** [comment]
I am also unable to add new subjects/runs to an existing study. 

After adding in a new dataset in pop_study() and clicking Ok EEGLAB returns error "Unrecognized function or variable 'realindex. ' In function std_editset() at line 292.

It appears that realindex is created at line 169, if STUDY does not have dataset info. However, if the study has dataset info, then std_editset crashes at line 292.  

Swapping 'realindex' with 'currentind,'  at line 292 seems to help, but I want to double-check if there are any consequences in doing that. @arnodelorme 

I am using eeglab v2023.0

Thanks!

**Comment by arnodelorme** [comment]
Good. There is no consequences in doing that. I have fixed the code.

**Comment by YANKI21** [comment]
Dear arnodelorme,

I am also taking the same error, line 504 getfilename. 

Could you please help?

**Comment by arnodelorme** [comment]
Would you mind trying with the latest EEGLAB version?

**Comment by arnodelorme** [comment]
OK, the cache has been cleared as well when adding a new dataset.
