### ISSUE TITLE
pop_biosig unsupported data format

### ISSUE THREAD

**Issue by DNCECHLim** [eeglabdevelopers/eeglab#563]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce
<img width="545" alt="스크린샷 2022-11-30 오후 2 02 19" src="https://user-images.githubusercontent.com/102575010/205199952-ad18c6d4-5454-44f3-864b-57786d8f8a51.png">

1. I use anticamp plus from brainproduct for EEG experiment. I pilot my experiment and get EEG, header and marker files. However, they are not opening in EEGLAB v2022.1. One weird thing is EEG file that i saved 4 years ago is opening in EEGLAB v2022.1. This EEG file is saved another version of anticamp. 
2. I asked to brainproduct technician and they could open my EEG file by using brainanalyzer, thus they concluded EEG file is not corrupted.
3. Is EEGLAB is not available EEG file for current device? or i set up path incorrectly? however another EEG file is still opening in my Mac. How can i solve this problem?

Additionaly, if i use File/io function, this message pops up.
<img width="645" alt="스크린샷 2022-12-02 오후 12 16 15" src="https://user-images.githubusercontent.com/102575010/205207129-ad7d0ddb-3241-4609-b052-91c0cd52814c.png">

Thank you!

<br>
#### Expected behavior:
[*EEG file is opened in EEGlab*]

<br>
#### Actual behavior:
[*EEG file can't be opened in EEGlab*]

I uploaded raw_data for EEG. 
[EEG_raw_data.zip](https://github.com/sccn/eeglab/files/10137635/EEG_raw_data.zip)
<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*MacOS Big Sur 11.5.2*] |
| Matlab version | [*R2021a*] |
| EEGLAB version | [*v2022.1*] |

**Comment by clementlee2000** [comment]
Which software did you use to record the data? If it's Brain Product's software (which could have been updated in the 4 years since you recorded the older dataset), it's entirely possible for their data format to have changed.

IIRC BrainProducts software allows for .xdf export (or has some LabStreamingLayer compatible recording app that will produce an .xdf). That would be a good way to get your data into EEGLAB.

**Comment by arnodelorme** [comment]
I have imported the 3 files using the BVA-IO plugin without problem. Use the BVA-io plugin.
