### ISSUE TITLE
Plugin menu not launching

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#565]
In the development version, the plugin menu is not launching. The issue is due to the changes in the commit: 

https://github.com/sccn/eeglab/commit/c52055a329d1334ef00cb05dd710e5e758df4afd

See comments in commit.
R

**Comment by arnodelorme** [comment]
Is it fixed with the last change. Thanks Ramon, really sorry about that.

**Comment by nucleuscub** [comment]
Super. Thanks, @arnodelorme . I forgot how much fun I had doing this ;) .  I'm happy to help somehow. 

R
