### ISSUE TITLE
Tools doesnot have an option of locate dipoles using DIPFIT even if DIPFIT installed 

### ISSUE THREAD

**Issue by jeenalrambhia** [eeglabdevelopers/eeglab#567]
hi 
My EEGLAB tools doesnot have an option for locate dipoles using DIPFIT. please let me know how do i resolve this. DIPFIT is already installed.
![image](https://user-images.githubusercontent.com/41319321/205873223-d54951e4-a942-4be0-9961-483316600075.png)

**Comment by arnodelorme** [comment]
Yes, it is the menu "Source localization using DIPFIT" in your screen capture. Best
