### ISSUE TITLE
Warning on importing GDF files

### ISSUE THREAD

**Issue by rakansha** [eeglabdevelopers/eeglab#57]
### Description
I have been getting warnings on importing gdf files. What does it mean? 

[https://ibb.co/bK9jL7j](url)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 10*] |
| Matlab version | [*R2018b*] |
| EEGLAB version | [*9.4.0.813654 *] |

**Comment by arnodelorme** [comment]
These are warning from the BIOSIG toolbox. In general nothing to worry about but you could contact the author for more information.

http://biosig.sourceforge.net/

Best wishes,

Arno
