### ISSUE TITLE
pop_rmdat error

### ISSUE THREAD

**Issue by ceren-arslan** [eeglabdevelopers/eeglab#573]
Dear EEGLAB,

I use v2022.0, and I have an error about the pop_rmdat function. When  I input 1 for inverselection in my script (e.g., EEG = pop_rmdat( EEG, {'boundary'},[-1 1], **1)** ), it changes the last input as 0, as it is the default. The code for the function differs between versions, and it seems to overwrite our input now. I am attaching an image of a comparison between different code versions. 

[https://drive.google.com/file/d/14cU9u6xZ2FXGa05Zqr7y9ObZB9iuyT55/view?usp=sharing](url)

|   |   |
|----| ---- | 
| Matlab version | [*MATLAB R2022.a*] |
| EEGLAB version | [*EEGLAB  @v2022.0*] |

**Comment by arnodelorme** [comment]
There was a bug in the function that has now been fixed in 710dd17a6
