### ISSUE TITLE
pop_editset error issue

### ISSUE THREAD

**Issue by Hyemin-Ha088** [eeglabdevelopers/eeglab#579]
### Description
![스크린샷_20230112_055903](https://user-images.githubusercontent.com/112856819/212236571-6d1bd142-1be7-4dde-abd5-fd36e880cbf7.png)

![스크린샷_20230113_011600](https://user-images.githubusercontent.com/112856819/212236341-376f8520-7e54-41d2-88b1-59004a4e346e.png)

I imported data like the 1st picture and have error 433 like 2nd picture.

<br>
#### Steps to Reproduce

1. [*First Step*] Convert csv file to txt file
2. [*Second Step*] Open the Import dataset info
3. [*and so on...*] Input txt file in Data file/array
4. Input Channal location file
5. Click 'OK'

<br>
#### Expected behavior:
I wanted txt file converted through csv file to be converted to set file

<br>
#### Actual behavior:
I had an error w/ the message “EEGLAB error in function pop_editset() at line 433:”

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Window 11] | 
| Matlab version | [R2022b] | 
| EEGLAB version | [v2022.1] |

**Comment by arnodelorme** [comment]
ASCII files must contain array of numbers. If they do not, the function will crash.
