### ISSUE TITLE
Wrong values plotted in EEGlab topoplot

### ISSUE THREAD

**Issue by git1t** [eeglabdevelopers/eeglab#581]
Hi, 

I'm trying to use the EEGlab topoplot function to plot t-value. More specifically, I want to see whether there are statistically significant t-values between two different groups at the different electrodes for three different conditions. 

For this, I use  topoplot(data2use,chanlocs,'electrodes', 'numbers','maplimits',clim,...
        'headrad', 'rim','intsquare','off','style','fill',...
        'emarker',{'.','k',20,1}  )
where data2use is a single vector containing the t-values to plot per electrode 1 to 128 and chanlocs contains my electrode coordinates. 
I then use a colormap with 4 color steps to show colors only when t-values > 1.99 or <-1.99.

I do not get an error message. However, when I inspect my plots and compare them with the t-values, I see that they are not correct. 
For instance, for condition "CSinFF", electrodes 93 and 127 are significant, but are shown in white in the plot, while e.g. the data2use values at position 115 and 122 are not significant, but are shown in blue in the plot as though passing the threshold. 

The data2use values are correct and the electrode numbers shown in the plot also are at the correct positions, so I don't understand why the plotting goes awry and if this is a bug or where the error lies... 
Would be very grateful for your help!!

Attached you will find my script and location files (which is originally .ced, but the file format is not supported for the upload here...), as well as the CSinFF example input file and plot mentioned above. 
Please let me know if you need any more details. 

Kind regards

[script.txt](https://github.com/sccn/eeglab/files/10474939/script.txt)

[location128channels.txt](https://github.com/sccn/eeglab/files/10472449/location128channels.txt)

[tvalue_CSinFF_typ-poor.csv](https://github.com/sccn/eeglab/files/10472454/tvalue_CSinFF_typ-poor.csv)
![Plot_oddSums_GA_tvalue_CSinFF_typ-poor](https://user-images.githubusercontent.com/52077669/213874386-12d0f7b3-e0fe-4ab8-9d52-fb0c4d0aacaf.jpg)

**Comment by arnodelorme** [comment]
I think the issue is with the reduced colormap. Your plot does look nice though. Unfortunately, we are too busy to help, but check with @amisepa , he might be able to fix that as a consultant.
