### ISSUE TITLE
EEGLAB error in function runica() at line 873

### ISSUE THREAD

**Issue by xiaoya675** [eeglabdevelopers/eeglab#586]
### D
<img width="415" alt="6f84ad8758273478e7ab3e189b91362" src="https://user-images.githubusercontent.com/125549698/219317613-8036d35e-d8e2-402f-971d-feeaabc43389.png">
escription

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment]
Would you mind sharing a dataset so we can test?

**Comment by arnodelorme** [comment]
Closing this but feel free to reopen.
