### ISSUE TITLE
EEGLAB error in function check_accept_value() at line 7

### ISSUE THREAD

**Issue by Praline-x** [eeglabdevelopers/eeglab#589]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Win10*] |
| Matlab version | [*2019*] |
| EEGLAB version | [*14.3*] |

**Comment by arnodelorme** [comment]
This is not an eeglab function
