### ISSUE TITLE
About using TAAHC or AAHC in EEGLAB with the MST1.0 toolbox.

### ISSUE THREAD

**Issue by Yifan-wang830** [eeglabdevelopers/eeglab#590]
Dear all,

I am writing this post to ask for your help in dealing with an error I am encountering while using the MST1.0 toolbox through TAAHC clustering in EEGLAB. Specifically, I am receiving an error message indicating that the corr function corresponding to the double type input parameter in the raahc script on line 159 is not defined. The error code reads: cc = abs(corr(Xshuff)); % polarity invariant.

I have been trying to resolve this issue for some time now, but to no avail. As such, I would greatly appreciate any insights or suggestions that you might have on how to address this problem. Have any of you encountered a similar issue before? If so, how did you go about resolving it? Any advice or guidance you could offer would be greatly appreciated.

Thank you in advance for your time and assistance. I look forward to hearing your thoughts and insights

|   |   |
|----| ---- | 
| OS version     | [*OS Monterey 12.1*] |
| Matlab version | [*2022b*] |
| EEGLAB version | [*2022.0*] |

**Comment by arnodelorme** [comment]
Dear Yifan, you should post your problem on this repository https://github.com/atpoulsen/Microstate-EEGlab-toolbox
