### ISSUE TITLE
Run field error at STUDY level

### ISSUE THREAD

**Issue by stellafychang** [eeglabdevelopers/eeglab#592]
### Description

There is a conflict when I formed a STUDY. The datasets have a 'run' field in EEG.event, and it creates a conflict at STUDY level.

<br>
#### Expected behavior:
The value in the run field in pop_study should be 1, because all datasets are the first run.
<br>
#### Actual behavior:
The value in the run field is 49 in the STUDY.
<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Ventura 13.2.1 |
| Matlab version | R2021b |
| EEGLAB version | 2022.1 |

![Screenshot 0005-02-27 at 17 11 43](https://user-images.githubusercontent.com/68676265/223298253-e3415f8d-ce75-40a0-abb2-d83062d0a0e7.png)

**Comment by arnodelorme** [comment]
Yes, there is not much to do. You need to rename the "run" field in all event structures.
By the way, I doubt there are 49 runs in your experiment. If you do not care about "run" in datasets or in the event structure, then you can ignore this message.
