### ISSUE TITLE
EEGLAB error in function pop_resample() at line 224

### ISSUE THREAD

**Issue by drowning-in-codes** [eeglabdevelopers/eeglab#594]
Hi man, I'm working with dataset https://physionet.org/content/eegmmidb/1.0.0/.  And I've seen Issue  #255 ,so I download the extension **import edf** to deal with annotation and event. But when I try to change the sampling rate, 
![image](https://user-images.githubusercontent.com/60743790/224999889-1fe0bbe8-e9e3-4ca7-a847-d32aa3a4d3b0.png)
this kind of error  occurs, and I want figure out why will this happen and how to deal with it.

**Steps to Reproduce**
1. use **import edf** extension to deal with dataset https://physionet.org/content/eegmmidb/1.0.0/.
2.import this dataset or `EEG = import_edf('F:\S001R07.edf', 0);
[ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 0,'gui','off'); ` and  Tools->change sampling rate.
 Thanks for your selfless help.

**Comment by arnodelorme** [comment]
import_edf is not an EEGLAB function. Use pop_biosig instead. Thank you.
