### ISSUE TITLE
dipfit 5.0

### ISSUE THREAD

**Issue by tiborauer** [eeglabdevelopers/eeglab#595]
### Description

The current version of the DIPFIT plugin (5.0) has empty subfolders (private and standard_\*).

<br>
#### Steps to Reproduce

1. Download https://sccn.ucsd.edu/eeglab/plugins/dipfit5.0.zip
2. Extract
3. Inspect subfolders

**Comment by arnodelorme** [comment]
I have released dipfit 5.1. Can you try again?

**Comment by tiborauer** [comment]
Thanks! The [plugin list](https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php) was not updated.

**Comment by arnodelorme** [comment]
You might need to refresh the page. It is showing 5.1 for me.

Arno

**Comment by tiborauer** [comment]
Yes. I know. I meant couple of hours ago.
