### ISSUE TITLE
newcrossf returns a wrong output in 'alltfX', 'alltfY'

### ISSUE THREAD

**Issue by itziknorman** [eeglabdevelopers/eeglab#597]
### Description
When newcrossf compares two conditions (input data is cell array {x1,x2}, {y1,y2}), and the argument 'type' is 'coher' (linear coherence), the variables that later become the output, i.e., Tfx1, Tfx2, Tfy1, Tfy2 - are being squared before the statistical test to speed up the computation:
Tfx1 = Tfx1.*conj(Tfx1); Tfx2 = Tfx2.*conj(Tfx2);
Tfy1 = Tfy1.*conj(Tfy1); Tfy2 = Tfy2.*conj(Tfy2); 

The problem is that they are also returned squared and then you cannot recover the original timefrequency decomposion (i.e. unsquared).

#### Steps to Reproduce

Run newcrossf with two conditions, and select linear coherence ('type','coher'), for example:

  % EEGLAB spectrogram parameters:
    params = struct;
    params.freqs = [3:30];
    params.timesout= 250;
    params.timesout = 175;
    params.cycles = [3 0.5];
    params.freqscale = 'linear';
    params.alpha = 0.01;
    params.naccu = 200;
    params.boottype = 'shuffle';
    params.baseboot = 0;
                   
% {x1, x2}: two 3D matrices with EEG data from channel A, one per each condition.
% {y1, y2}: two 3D matrices with EEG data from channel B, one per each condition.

 [CC,~,t_out,f_out,cohboot,~,allCoh,alltfX,alltfY] = newcrossf({x1,x2},{y1,y2},...
        EEG.pnts,[EEG.times(1) EEG.times(end)],EEG.srate,params.cycles,...
        'freqscale',params.freqscale,'plotphase','off','plotamp','off','timesout',params.timesout,...
        'freqs', params.freqs,'baseline',nan,'subitc','off','type','coher',... 
        'alpha',params.alpha,'naccu',params.naccu,'boottype',params.boottype,'baseboot', params.baseboot);

<br>
#### Expected behavior:
alltfX is supposed to contain the single trial spectral decomposition of x1 and x2;
and alltfY is supposed to contain the single trial spectral decomposition of y1 and y2

<br>
#### Actual behavior:
alltfX contains the **square** of the spectral decomposition of x1 and x2;
and alltfY contains the **square** of the spectral decomposition of y1 and y2

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | macOS Monterey 12.6.2 |
| Matlab version | 2021.1 |
| EEGLAB version | v2021.1 |

**Comment by arnodelorme** [comment]
I see what you mean. This has been fixed in 36d3982a6
