### ISSUE TITLE
Manage Extensions: Plugin Error

### ISSUE THREAD

**Issue by kvanbenthem** [eeglabdevelopers/eeglab#598]
### Error with Manage Extensions

[*I have a new error that occurs when I try to go to the Manage Extensions in the main EEGLAB GUI*]
![image](https://user-images.githubusercontent.com/129001069/227797250-e1776726-d4f3-4c3a-8a9b-04cf639be885.png)

<br>
#### Steps to Reproduce

1. [*Open EEGLAB*]
2. [*Go to File Tab*]
3. [*Click on Manage Extension*]

<br>
#### Expected behavior:
[*I should get a GUI to add or update the extensions and plugins*]

<br>
#### Actual behavior:
[*Unrecognized field name plugin  in function plugin_getweb() line 89  *]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 10*] |
| Matlab version | [* 2023a current version*] |
| EEGLAB version | [*v2023.0 current version*] |

**Comment by arnodelorme** [comment]
I would need more information. Can you show what the message is in the MATLAB window?

**Comment by kvanbenthem** [comment]
The error message is this: “Unrecognized field name “plugin” in function plugin_getweb() line 89 “

**Comment by kvanbenthem** [comment]
In the command window of Matlab the last line is this: "Retrieving download statistics..."

**Comment by arnodelorme** [comment]
I think it is because it fails to connect to the internet -- even though the internet is on. I have added an additional check in 0f2226c67
