### ISSUE TITLE
Unrecognized field name "cellArray"

### ISSUE THREAD

**Issue by shadow825** [eeglabdevelopers/eeglab#599]
EEGLAB error in function checkoldformat() at line 301:   Unrecognized field name "cellArray".
But I can't find the file "checkoldformat.m" in my compute

**Comment by arnodelorme** [comment]
This is a subfunction of pop_loadset. Can you share your dataset?

**Comment by shadow825** [comment]
My data file is in MAT format, and it doesn't seem to support uploading files in this format. But I found the checkoldformat function and seem to understand the cause of the problem. It should be a problem with my data. Thank you guy.
