### ISSUE TITLE
event types not appearing when plotting raw data

### ISSUE THREAD

**Issue by robpetrosino** [eeglabdevelopers/eeglab#600]
### Description

I have started collecting data for my EEG experiment using Cedrus Stim Trigger box wirelessly connected to the CGX 20-channel headset. I am presenting auditory stimuli through Presentation. The trigger markers seem to be correctly sent by the Stim Trigger to the acquisition software. 

The recording was saved as a Brain Vision Analyzer file (i.e., with the usual triplet of files -- .eeg, .vhdr, .vmrk). I used the usual plug-in by selecting it from the EEGlab GUI: File > Import data > Using EEGlab functions and plugins > From Brain Vis. Rec. .vhdr or .ahdr file. I have the bva-io plugin (v.1.71) installed on MATLAB 2023a. After importing the data in EEGlab, no event marker shows up when plotting – see screenshot below. 

![Screen Shot 2023-03-22 at 11 31 58 AM](https://user-images.githubusercontent.com/30778296/229063459-3e3e32c4-c65a-4250-af2c-279fea2dfc15.png)

Both both even types/codes and latencies seem to be there, as the following two commands correctly retrieves the list of each: 

```
my_events = {EEG.event.type}
my_latencies = [EEG.event.latency]
```

The dataset may be downloaded [here](https://drive.google.com/file/d/1eZNQdUh4-jFhQW8Hz22STqgSF6Q5Ec0W/view?usp=sharing).

#### Versions

|   |   |
|----| ---- | 
| OS version     | [macOS Monterey 12.6.2] |
| Matlab version | [2023a] |
| EEGLAB version | [2023.0] |

**Comment by arnodelorme** [comment]
This is because there are no events in that window. You need to scroll right or change the time scale.
