### ISSUE TITLE
EEG.chaninfo.removedchans field error?

### ISSUE THREAD

**Issue by stellafychang** [eeglabdevelopers/eeglab#601]
### Description

I have been using EEG.chaninfo.removedchans for monitoring the removed channels after ASR. After I updated MATLAB and EEGLAB version, I found that the structure of EEG.chaninfo.removedchan has become different. After ASR, I will interpolate the removed channels and I found that the removed channels were still interpolated correctly, so I'm not sure if the information of the removed channels has been stored in a different location now.  

<br>
#### Steps to Reproduce

1. *First Step*: run ASR and get some channels to be rejected
2. *Second Step*: check the content of EEG.chaninfo.removedchans
<br>
#### Expected behavior:
<br>
The removed channels information will be in EEG.chaninfo.removedchans.
<br>

![previous](https://user-images.githubusercontent.com/68676265/229267060-75bbbcad-b2d9-4a47-bcac-c02ef0d61ffd.png)

<br>
#### Actual behavior:
<br>
I was supposed to see 40 removed channels, but they cannot be found.
<br>

![afterUpdated](https://user-images.githubusercontent.com/68676265/229266841-9e2cab8f-896c-40f8-a2d5-0cc38d8389bb.png)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*R2023a*] |
| EEGLAB version | [*2023.0*] |

**Comment by arnodelorme** [comment]
Let me check. The information of the channels removed by ASR is also in EEG.etc.clean_channel_mask (or something similar)

**Comment by arnodelorme** [comment]
I have removed channels in 2 passes of clean_rawdata and both were saved appropriately (the second pass adding to the first pass). I think this bug refers to an older version of clean_rawdata. 

If you think there is still a problem with the latest version of clean_rawdata, let us know (and upload data so we can test). Thank you so much.

**Comment by stellafychang** [comment]
I was wondering how you tested. I pulled clean_rawdata from github and called it using three different ways in command line, but none of them save EEG.chaninfo.removedchans. There are the three ways that I called clean_rawdata:
```
EEG = clean_rawdata(EEG, 10, -1, 0.85, -1, 20, 0.25);
EEG = clean_artifacts(EEG, 'chancorr_crit', 0.85, 'line_crit','off', 'burst_crit', 20,'window_crit', 'off', 'window_crit_tolerances','off', 'highpass_band','off','flatline_crit', 10); 
EEG = pop_clean_rawdata(EEG, 'FlatlineCriterion',10,'ChannelCriterion',0.85, 'LineNoiseCriterion','off','Highpass', 'off','BurstCriterion',20,'WindowCriterion',0.25,'BurstRejection','off','Distance','Euclidian','WindowCriterionTolerances',[]);
```
However, if I called clean_rawdata using the **GUI**, the removed channels will be in EEG.chaninfo.removedchans. I wrote up a few lines which can save removed channel labels by taking in EEG.etc.clean_channel_mask, but it would be great if I could quickly check the removed channels in EEG.chaninfo.removedchans after clean_rawdata is called in a preprocess script.
