### ISSUE TITLE
Add Scatter plot functionality to electrode locations in topoplots

### ISSUE THREAD

**Issue by neuromechanist** [eeglabdevelopers/eeglab#603]
In several cases, there is a need to report channel quality metrics per electrode. This can be nicely visualized with [scatter plot functionality](https://www.mathworks.com/help/matlab/ref/scatter3.html), such as variable size and colors for the data points. However, the current implementation of the topo plots using plot3. Therefore, a new mode should be created for scatter plots while backward compatibility is ensured.

**Comment by arnodelorme** [comment]
Added comment to pull request.
