### ISSUE TITLE
EEGLAB error in function dipplot() at line 691

### ISSUE THREAD

**Issue by stellafychang** [eeglabdevelopers/eeglab#605]
### Description

I tried to plot the dipoles using GUI at STUDY level, but there was a pop-up window showed up: EEGLAB error in function dipplot() at line 691.

<br>
#### Steps to Reproduce

1. *First Step:* please load the STUDY from the Issue 516
2. *Second Step:* go to 'STUDY' -> 'Edit/plot components clusters'

<br>
#### Expected behavior: I could get the plot of dipoles with EEGLAB 2021.1

<br>

<img width="1134" alt="2021 1_allCls" src="https://user-images.githubusercontent.com/68676265/230272247-93742713-84ec-4869-a119-ff4bed8f0eb1.png">

<br>
#### Actual behavior: After switching to EEGLAB2023.0, I got this error.

<img width="1150" alt="2023 0_allCls" src="https://user-images.githubusercontent.com/68676265/230272577-e06e1ee1-b966-459b-9b25-78ecafb012de.png">

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | MacOS Ventura 13.2.1 |
| Matlab version | R2023a |
| EEGLAB version | 2023.0 |

**Comment by arnodelorme** [comment]
We have updated Dipfit. Can you update your version in the plugin manager and check that it works?

**Comment by stellafychang** [comment]
Yes. I updated Dipfit to 5.2 and it works now. Thank you.

**Comment by arnodelorme** [comment]
Wonderful. Thanks
