### ISSUE TITLE
eeg_isboundary() slows pop_resample()

### ISSUE THREAD

**Issue by ammsimmons** [eeglabdevelopers/eeglab#606]
### Description

When trying to resample/downsample continuous EEG data, the process is many orders of magnitude slower than in previous EEGLAB versions. I encountered this for my data, which has more events than usual, so this exceedingly slow resampling _could_ be due to my data but it is still a nontrivial wait time. 

Moreover, the resampling works orders of magnitude faster (as expected) when I simply comment out logic in eeg_isboundary() that considers if the event is a boundary event like so (lines 56-66):

'''

        %eeglab_options;
        if ischar(tmpevent(1).type)
            if strcmpi('boundary', tmpevent(1).type)
                logi = true;
            end
         %elseif option_boundary99
             %if tmpevent(1).type == -99
                 %logi = true;
             %end
        end

'''
As far as I can tell, the eeglab_options command populates the workspace with the ability to test option_boundary99, so maybe a quick fix is a lighter output from eeglab_options for option_boundary99, i.e. just a logical 1 or 0. 

(Side note: this issue could have been a side effect of a recent fix to allow compatibility with ERPLAB which uses -99 event as a boundary event.)

<br>
#### Steps to Reproduce

1*. Set pop_editoptions('option_boundary99', true);
2. Load continous EEG data
3. Resample to a lower sampling rate. 

* It is possible the issue occurs regardless if the option_boundary99 is set or not. 

<br>
#### Expected behavior:
Very fast resampling

<br>
#### Actual behavior:
Very slow resampling -- I tested to see if it is running and it indeed runs (so with debugger, I step in and out of loop, and the events are being processed). No error messages. However, it is orders of magnitude slower than expected! 

<br>
#### Versions
EEGLAB 2023.0

|   |   |
|----| ---- | 
| OS version     | [macOS Catalina|
| Matlab version | R2021b |
| EEGLAB version | 2023.0 |

**Comment by arnodelorme** [comment]
This commit should fix the speed issue. a8f739613 
Let us know. Closing this for now, but feel free to reopen the issue and thank you for reporting the problem.
