### ISSUE TITLE
Issue with channel lookup

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#609]
Load up this file

EEG = pop_biosig('/Users/arno/Downloads/ds003343/sub-13/ses-01/eeg/sub-13_ses-01_task-fps_run-01_eeg.bdf');

- And then try channel lookup from the GUI
- Then scroll to next channel and there is an error

**Comment by sdebener** [comment]
Hi Arno,
we have a very similar/related issue, pointing to line 1033 in pop_chanedit (see below). My students are frustrated, they cannot use eegh anymore to add channel locations with pop_chanedit ;-/. We use EEGLAB2023.0 in class....
Cheers,
Stefan

*******
IMPORTANT: After importing/modifying data channels, you must close
the channel editing window for the changes to take effect in EEGLAB.
TIP: Call this function directly from the prompt, ">> pop_chanedit([]);"
     to convert between channel location file formats
readlocs(): 'loc' format assumed from file extension
31 channel with the same label found and imported
Channel lookup: no location for Nz,LPA,RPABrace indexing is not supported for variables of this type.

Error in pop_chanedit (line 1033)
    userdata.commands = { userdata.commands{:} args{:} };
 
Error while evaluating UIControl Callback.

Brace indexing is not supported for variables of this type.

Error in pop_chanedit (line 1033)
    userdata.commands = { userdata.commands{:} args{:} };
 
Error while evaluating UIControl Callback.

**Comment by arnodelorme** [comment]
Thanks Stefan, I have implemented this fix 0ed822cf6 which works for me. Could you let me know if it works for you?

**Comment by arnodelorme** [comment]
Closing this for now, but please reopen if you encounter any problem.
