### ISSUE TITLE
Problem with plugin_getweb()

### ISSUE THREAD

**Issue by usman-afzali** [eeglabdevelopers/eeglab#611]
### Description

[*So, I am trying to open EEGLab on Matlab, both latest versions as of Apr 2023. It shows a problem with plugin that I don't know how to fix. Any help with this will be highly appreciated. I am attaching a screenshot for your reference.*]

<br>
#### Steps to Reproduce

1. [*Open Matlab*]
2. [*type eeglab in the commnand window*]
3. [*Go to EEGlab file menu and click manage EEGLab extensions*]

<br>
#### Expected behavior:
[*supposed to show a list of available extensions that can be installed.*]

<br>
#### Actual behavior:
[*Gives an error - plugin_getweb() at line 89:*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*MATLAB 2023a*] |
| EEGLAB version | [*v2023.0*] |

**Comment by arnodelorme** [comment]
There is no screen shot. Could you add the screen shot?

**Comment by juliannemcleod** [comment]
I am having the same problem. Here is a [screenshot:]

<img width="1125" alt="Screen Shot 2023-05-15 at 10 42 38 AM" src="https://github.com/sccn/eeglab/assets/133693699/4365e49e-e52f-4f21-ba9e-97f887437fc8">

OS version: macOS 12.2.1
Matlab version: 2022b
EEGLab 2version: 2022.1

**Comment by cmmrandau** [comment]
Same problem here on two separate computers running 2022.1. I remember having this error some year ago but it resolved itself. Currently downloading latest version (github clone).

**Comment by cmmrandau** [comment]
> Same problem here on two separate computers running 2022.1. I remember having this error some year ago but it resolved itself. Currently downloading latest version (github clone).

It works with the latest version from github. Strange that this error came out of nowhere. I suspect server issues since the newest version complains but still loads (and cloning was very slow at 80 KiB/s): 
```
Retrieving download statistics...
Issue with decoding plugin information, Octave 7.x required to decode JSON strings
Plugin list incomplete - maybe an issue with internet connection - aborting.
```

**Comment by arnodelorme** [comment]
There was a temproary issue with our database. It is fixed now. Can you check?

**Comment by usman-afzali** [comment]
Thank you so much. Sorry, I did not attach a screenshot, but the one attached by @juliannemcleod was similar to ours. It seems to be fine now.

**Comment by arnodelorme** [comment]
OK, thanks
