### ISSUE TITLE
Error with ICLabel

### ISSUE THREAD

**Issue by rohitgarud** [eeglabdevelopers/eeglab#612]
Hello,
I am new to EEGLab. I am getting the following error when I try to Label the ICA components using ICLabel.
```
Error using dagnn_bc.Conv
Error: File: Conv.m Line: 1 Column: 10
Class name and filename must match.

Error in dagnn_bc.DagNN.loadobj (line 26)
    block = constr() ;

Error in run_ICL (line 30)
    net = dagnn_bc.DagNN.loadobj(netStruct);

Error in iclabel (line 56)
labels = run_ICL(version, features{:});
```

I am using MATLAB 2020b and EEGLab version 2023, ICLabel version 1.4. I have tried installing older versions of ICLabel but same error is shown. Please help me solve this issue.

Thank you

**Comment by arnodelorme** [comment]
Which version of ICA label are you using? Can you check that the folder 

eeglab/plugins/ICLabel/matconvnet

is present and not empty

**Comment by rohitgarud** [comment]
Thank you @arnodelorme for your prompt response. 
I am using ICLabel version 1.4. I have installed it using the Extension manager from EEGLAB and checked that the folder is not empty.

**Comment by rohitgarud** [comment]
When I install EEGLAB with MATLAB runtime, it works. So I think the issue is with the MATLAB installation.

**Comment by arnodelorme** [comment]
Ah good to know.
