### ISSUE TITLE
Error when adding old ref. channel back to the data in v2023.0

### ISSUE THREAD

**Issue by QingkaiZhu** [eeglabdevelopers/eeglab#614]
### Description

I want to retain the old reference channel and then compute the average reference but got an error in the pop_reref window.
![image](https://user-images.githubusercontent.com/113549413/236073861-8fb28811-2dfb-4a40-b079-4a52efe26086.png)

This is a regression bug, it works in eeglab v2022.1 and failed in v2023.0

### Steps to Reproduce

Just follow the steps in the official tutorial with _eeglab_data.set_, you will get the error after clicking on the Retain old reference button(the button with 3 dots)
- https://eeglab.org/tutorials/05_Preprocess/rereferencing.html#retaining-the-reference-channel

#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*R2022b*] |
| EEGLAB version | [*v2023.0*] |

**Comment by arnodelorme** [comment]
Did you add the old reference to the list of channels as recommended in the tutorial?

**Comment by arnodelorme** [comment]
I tried the tutorial and it worked for me. I am closing this report, but feel free to reopen.

**Comment by carrie372** [comment]
@arnodelorme when I follow the tutorial I end up with two Cz channels. One for channel 24 and the new one appended in channel locations.
