### ISSUE TITLE
wrong variable name used in std_editset line 292, causing study to crash

### ISSUE THREAD

**Issue by sahin-ozsoy** [eeglabdevelopers/eeglab#617]
### Description

At line 292 of std_editset, the variable name is set to realindex instead of currentind

<br>
#### Steps to Reproduce

 create a study using two set files programmatically.

<br>
#### Expected behavior:
add the second set to the study file

<br>
#### Actual behavior:
undefined variable error in std_editset function

<br>
#### Versions
2023.0

|   |   |
|----| ---- | 
| OS version     | win
| Matlab version | 2022b
| EEGLAB version | 2023.0

**Comment by arnodelorme** [comment]
Good catch. Thanks.
