### ISSUE TITLE
clean_channels misses channels with large amplitude?

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#618]
Trying to create bad channels in a file for a tuto (by simply multiplying the signal by 3 for FC3 and by 15 for AF8), to show them in an illustration with vis_artifacts. To my surprise, clean_channels did not detect them despite huge difference in amplitude, and removes other channels that look good. There must be some rescaling in vis_artifacts because my bad channels are not visible in vis_artifacts. But they are still there. 

Channels that should be removed: FC3 and AF8
![image](https://github.com/sccn/eeglab/assets/58382227/24129a10-8b39-4b1f-b868-dfe07cc5efa1)

Channels removed instead by vis_artifacts: T7 PO7 O1 --> notice how the bad channels are rescaled and not visible here. 
![image](https://github.com/sccn/eeglab/assets/58382227/84f97062-37b0-4b0d-bcd1-b688af628728)

Plot after clean_rawdata shows that FC3 and AF8 are still in the data. 
![image](https://github.com/sccn/eeglab/assets/58382227/97c6f75b-e612-47ab-bde9-1d3a5c7a9fbf)

STEPS:

Load "sample_data2.2.set" from here: https://github.com/amisepa/BrainBeats/tree/main/sample_data

    oriEEG = EEG;
    pop_eegplot(EEG,1,1,1);   % here you can see FC3 and AF8 are clearly bad
    EEG = pop_clean_rawdata(EEG,'FlatlineCriterion',5,'ChannelCriterion',.85, ...
        'LineNoiseCriterion',5,'Highpass','off', 'BurstCriterion','off', ...
        'WindowCriterion','off','BurstRejection','off','Distance','off');    
    vis_artifacts(EEG,oriEEG);   % clean_channels removed 
    badChan = ~contains({oriEEG.chanlocs.labels}, {EEG.chanlocs.labels});
    fprintf(1, 'Bad channels were: ');
    fprintf(1, '%s ', oriEEG.chanlocs(badChan).labels )
    fprintf(1, '\n')
    pop_eegplot(EEG,1,1,1);

**Comment by arnodelorme** [comment]
This is because clean_rawdata uses the correlation between channels, and you did not destroy the correlation by multiplying them. So it is all good. Your artifacts are not physiologically plausible.

**Comment by amisepa** [comment]
Ok thanks! would it work if I reverse polarity? or do I need to shuffle data to create a fake bad channel?

**Comment by arnodelorme** [comment]
Reversing polarity will not work either. You can take the mirror time image.

EEG.data(1,:) = EEG.data(1:end:-1:1)

**Comment by amisepa** [comment]
Great thanks
