### ISSUE TITLE
clean_channels help is incorrect

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#619]
function [signal,removed_channels] = clean_channels(signal,corr_threshold,noise_threshold,window_len,max_broken_time,num_samples,subset_size)

% Signal = clean_channels(Signal,CorrelationThreshold,WindowLength,MaxBrokenTime,NumSamples,SubsetSize,UseGPU)

--> missing noise threshold and GPU should be subset_size in help

**Comment by arnodelorme** [comment]
I don’t get it.

**Comment by amisepa** [comment]
function: clean_channels(signal, corr_threshold, noise_threshold, window_len, max_broken_time, num_samples, subset_size)

help: clean_channels(Signal, CorrelationThreshold, WindowLength, MaxBrokenTime, NumSamples, SubsetSize, UseGPU)

3rd input of help should be noise_threshold and last should be subset size (not UseGPU)

**Comment by arnodelorme** [comment]
Thanks Done.
