### ISSUE TITLE
Problem of importing data

### ISSUE THREAD

**Issue by yeonamon** [eeglabdevelopers/eeglab#62]
### Description

There were some issues related to import data, so I deleted eeglab and reinstalled it twice.
For importing, I used this path 'file - import data - using the FILE-IO interface'.
Then the notice 'Fileio extension is not installed. Do you want to download it now?' comes up, and when I click 'Yes'... there is an error,

'EEGLAB error in function plugin_askinstall() at line 78:

Struct contents reference from a non-struct array object.'

as same as the image below.
![image](https://user-images.githubusercontent.com/57457649/68327854-6a01fe80-00ce-11ea-9c99-d656be1ab117.jpg)

How can I fix it? I also installed another version of MATLAB(2019), it doesn't work. 
<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [64-bit Operating System, x64-based processor] |
| Matlab version | [R2017a] |
| EEGLAB version | [2019, latest ver.] |

**Comment by arnodelorme** [comment]
Would you mind to try with EEGLAB 2019.1 instead of 2019.0?

**Comment by arnodelorme** [comment]
I have checked and could reproduce the problem in EEGLAB 2019.0 under Windows (Mac and Unix are fine). The issue has to do with checking URL certificates in newer versions of Matlab and cannot be easily fixed. EEGLAB 2019.1 uses a different method so it fixes the issue.
