### ISSUE TITLE
Dipfit does not update EEG.dipfit.chansel when batch processing?

### ISSUE THREAD

**Issue by elannon** [eeglabdevelopers/eeglab#620]
Hello, 

I am batch processing 2 data files and I get the following error "EEGLAB error in function dipfit_gridsearch() at line 63:  Index exceeds the number of array elements" when I reach the dipfit stage. Is this a know problem?

I looked at the code and from what I can tell "EEG.dipfit.chansel" retains the number of channels from the previous (maybe first) dataset that was processed (preprocessed?). Since I use cleanRawData to delete bad channels these don't match and I get an error. Do you think this might be the issue?

#### Steps to Reproduce
All steps are completed with GUI
1. Import .MFF files one at a time and save as .SET files
2. Select both files with dataset selection dropdown menu
3. All following steps are completed with 2 dataset select as batch process:

5. resample to 250z
6. re-reference to average
7. cleanRawData with default values and no reconstruction
8. re-reference to average with interpolate deleted channels selected
9. ICA (Infomax)
10. ICLabel
11. Dipfit - Head Model and settings with "'coord_transform',[0 -15 0 0.08 0 -1.571 10.2 9.3 10]"
12. Dipfit - Compute Dipole Autofit --- Here is where I get the error

Here is a link to the datafiles:
https://drive.google.com/drive/folders/16I-FL_aQoq9jiOht44ztYyFH-sRsu1wR?usp=share_link

| OS version     | Windows 10 enterprise; Version:22H2 |
| Matlab version | R2020b|
| EEGLAB version | "You are using the latest version of EEGLAB." |
"dipfit" v5.2 

Thanks for the help!

**Comment by arnodelorme** [comment]
Yes, this is quite possible. We have fixed this in f3c9d4b18
