### ISSUE TITLE
pop_chanedit doesn't allow `append`

### ISSUE THREAD

**Issue by mosh-shu** [eeglabdevelopers/eeglab#621]
Hi, 

I tried to manually `append` a channel using the `pop_chanedit` function, but it causes an unwanted bug.
Whenever I insert something like {num label theta radius X Y Z sph_theta sph_phi sph_radius } according to the comment on line 93, it returns an error at line 678. 
This occurs when I input `EEG.chanlocs` as the first argument of the function,  and I'm guessing that in this case, `allfields` at line 670 should be `fieldnames(chans(1))` instead of `fieldnames(chans)`, as `length(fieldnames(chans)` evaluated at line 678 returns the number of channels instead of the number of fields in each row of `chanlocs`.
I'm currently solving this issue by manually creating a struct to append a row to the `EEG.chanlocs` data structure.

I hope this helps.

**Comment by arnodelorme** [comment]
I have fixed the documentation and the code. ae28f76d2
