### ISSUE TITLE
Manage plugins

### ISSUE THREAD

**Issue by suaybarslan** [eeglabdevelopers/eeglab#622]
### Description

When I try to manage my plugins, it gives me an error: "error in function plugin_web() at line 89". I am curious to know as to whether this error is due to the service interruptions. 

<br>
#### Steps to Reproduce

1. Open EEGLAB
2. goto File/Manage plugins

<br>
#### Expected behavior:
Open the plugin window to dowload and setup. 

<br>
#### Actual behavior:
The error message. 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | windows10 |
| Matlab version | 2022 |
| EEGLAB version | 2022 |

**Comment by arnodelorme** [comment]
There was a temporary issue with our database. Could you try again?
