### ISSUE TITLE
urevent structure not created for .mff files

### ISSUE THREAD

**Issue by kathryn-sam** [eeglabdevelopers/eeglab#623]
### Description

Hi,
I have been facing a problem when importing .mff files. When I import a .mff file, the urevent structure is empty. This happens both with my own files, and with the testmff.mff file from the EEGLAB sample data. The EEG.event structure does not contain a urevent column either. 

![image](https://github.com/sccn/eeglab/assets/124139317/0726b192-1425-452c-a536-3d2cf7689802)

The urevent structure remains empty after pre-processing the data (e.g. epoching, rejecting trials) as well.

However, when I import other file types such as the Neuroscan CNT test data, or if I import data from a MATLAB array, the urevent structure is automatically populated with values after importing.

![image](https://github.com/sccn/eeglab/assets/124139317/7eed05f2-8161-43fa-a404-ec1c934558e7)

#### Steps to Reproduce

`EEG = pop_mffimport({'E:\\...\\CEE_FEC_207__mff EEGLAB.mff'},{'code'},0,0)`
or 
`EEG = pop_mffimport({'D:\\....\\eeglab\\eeglab_current\\eeglab2023.0\\sample_data\\test_data\\testmff.mff'},{'code'},0,0);`

#### Expected behavior:

Adds event data to the urevent structure and creates a urevent column in the EEG.event structure.

#### Actual behavior:

![image](https://github.com/sccn/eeglab/assets/124139317/2b830570-66e6-44a3-9a7d-9485da043116)
![image](https://github.com/sccn/eeglab/assets/124139317/4164109d-b04b-4978-bdd9-4bcef86db901)

#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 11] |
| Matlab version | [R2023a] |
| EEGLAB version | [2023.0] |
| MFFMatlabIO version | [4.1] |

**Comment by arnodelorme** [comment]
Good point. You can type

```
EEG = eeg_checkset(EEG, 'makeur');
```

for now to create the event structure. But we will fix the MFF plugin as well.

**Comment by kathryn-sam** [comment]
Thank you!
