### ISSUE TITLE
Error with the use of PREP pipeline 

### ISSUE THREAD

**Issue by kevinkhso** [eeglabdevelopers/eeglab#624]
### Description

<img width="628" alt="Screenshot 2023-05-20 at 2 40 45 PM" src="https://github.com/sccn/eeglab/assets/134122021/6d97a676-a46b-48b9-8678-8ab63590b855">

I am trying to run the PREP pipeline my data set. I have the Signal Processing Toolbox and the PREPpipline installed but there is an error returned as "Undefined function 'getFieldExists' for input arguments of type 'struct'." when I try to run with my dataset May I know how to solve the issue? 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*macOS Monterey Ver 12.3*] |
| Matlab version | [*R2023a*] |
| EEGLAB version | [*2023.0*] |

**Comment by ludgarri** [comment]
Just uninstall and then install again the plugin, I had the same issue and resolved it this way.
