### ISSUE TITLE
assert error - update

### ISSUE THREAD

**Issue by evastone97** [eeglabdevelopers/eeglab#626]
Hello I had this warning after i done ICA , I tried to label my components and I got this assert error message. What might have been wrong?

![Capture](https://github.com/sccn/eeglab/assets/82998648/38dd83e2-1b27-4277-ae98-01e75f2cfd22)

**Comment by arnodelorme** [comment]
Your ICA data has complex number. How did you compute ICA?

**Comment by evastone97** [comment]
Hello, 

I compute ICA with the runica algorithm and I did a dimensionality reduction of 30. I have a screenshot below:
![ica](https://github.com/sccn/eeglab/assets/82998648/4f7f092e-ccca-4dac-9a9d-ba4c58f9a26c)



Note: the data have been preprocessed (single files for each subject) with ica and then IC Label was used on them for artifact rejection.
Is the error created because of double ICA , or because the data before have been preproceeced with ica and ic label in single files? ( ica should be in the whole study probably from the beggining so also for artifact rejection and then I should continue from there?)

what I was trying to do afterwards is to create a study including all the single files of the subjects, implement dimensionallity reduction and then classify (but I am stack in IC label)

**Comment by arnodelorme** [comment]
Closing this issue for now, but let me know if the issue persist.
