### ISSUE TITLE
PACtools

### ISSUE THREAD

**Issue by koffiefernadljis** [eeglabdevelopers/eeglab#627]
I am trying to use PACtools but I keep getting this message 

ans =

    'std_pacprecom: Frequency values are not consistent with the computed ITC measure
     This may happen when the frequency resolution of the input vector is higher than the
     one already computed. Consider, Modifying your frequency input vector or recompute the ITC. Anyone know why this comes up? 
     '

**Comment by koffiefernadljis** [comment]
For study mode^^

**Comment by arnodelorme** [comment]
Closing this for now.
