### ISSUE TITLE
Channel location (chanlocs) coordinate unit

### ISSUE THREAD

**Issue by jackz314** [eeglabdevelopers/eeglab#630]
Inspired by BESA's [sfp documentation](http://wiki.besa.de/index.php?title=Working_With_Additional_Files#sfp_.28surface_point_coordinate.29_file) that states the channel coordinates can be in m, cm, or mm. MNE's [read_raw_eeglab](https://mne.tools/stable/generated/mne.io.read_raw_eeglab.html) also asks for a montage unit and defaults to mm. So I was wondering if there's a standard unit that the coordinates in `chanlocs` are saved in? Or is it arbitrary and only estimated when needed? If it's estimated, could someone point me to the code that does this? Thanks!

**Comment by arnodelorme** [comment]
Sorry for late answer. It is arbitrary although the unit can be defined in the EEG.chanlocs.unit field. I have looked at a couple of SFP file and the unit is not specified in the file.
