### ISSUE TITLE
ERROR IN USING CLEAN RAW DATA USING ASR IN TOOL EEGLAB

### ISSUE THREAD

**Issue by soniya-usgaonker** [eeglabdevelopers/eeglab#631]
Detecting flat line...
Scanning for bad channels...
Your dataset appears to lack correct channel locations; using a location-free channel cleaning method.
Finding a clean section of the data...
Determining time window rejection thresholds...done.
Keeping 93.1% (2579 seconds) of the data.
eeg_insertbound(): 120 boundary (break) events added.
Estimating calibration statistics; this may take a while...
Determining per-component thresholds...done.
Now cleaning data in 3076 blocks....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
eeg_insertbound(): 61 boundary (break) events added.
Now doing final post-cleanup of the output.
Determining time window rejection thresholds...done.
Keeping 99.2% (2695 seconds) of the data.
eeg_lat2point(): Points out of range detected. Points replaced with maximum value
eeg_insertbound(): 15 boundary (break) events added.
Warning: EEG.etc.clean_sample is present. It is overwritten.
Use vis_artifacts to compare the cleaned data to the original.
Warning: vis_artifacts failed. Skipping visualization. Could be because of duplicate channel
label. 
> In pop_clean_rawdata (line 219) 
Done.

SIR I WANT TO KNOW IF IT HAS CLEANED MY SUBJECT OR IT I SUNABLE TO CLEAN IT .I AM USING CLEANRAW DATA AND USING ASR FUNCTION IN EEGLAB

**Comment by arnodelorme** [comment]
Looks like the data was cleaned.
