### ISSUE TITLE
unrecognized function or variable "totalpnts"

### ISSUE THREAD

**Issue by greasycat** [eeglabdevelopers/eeglab#632]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

#### Steps to Reproduce

1. Download dataset from the official [tutorial](https://eeglab.org/tutorials/10_Group_analysis/multiple_subject_proccessing_overview.html#perform-batch-processing)
2. Load all 10 datasets
3. Filter
4. Run ICA

#### Expected behavior:

ICA properly performs.

#### Actual behavior:

unrecognized function or variable "totalpnts"
Shouldn't totalpnts be assigned before line 385?

https://github.com/sccn/eeglab/blob/1fb779eadc85b7b8d3546b44abcec862a055dbbc/functions/popfunc/pop_runica.m#LL385C8-L393C12

#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 |
| Matlab version | R2023a |
| EEGLAB version | 2023.0 |

**Comment by arnodelorme** [comment]
Good point. I have implemented this fix. 743c32bec
