### ISSUE TITLE
EEGLAB select data error 

### ISSUE THREAD

**Issue by rahmilee** [eeglabdevelopers/eeglab#634]
### Description

I am trying to select channels from the mat file, previously I didn't have this problem but I keep getting some errors. When go to the script to look at the error being produced there is no code at that line (line 134 of eeglab.m).

![Screen Shot 2023-06-15 at 4 05 44 PM](https://github.com/sccn/eeglab/assets/121198359/0e2729a1-2a4d-4a91-a555-22b2dbd7b675)

I am trying to extract epochs of every 10 seconds. 
When I have the parameters from 0 to 10 seconds (or any parameter) I get the error that the data is empty.

*I have tried by loading existing data and both loading raw data with the same outcome.
*The options also look different to than the options I see in other tutorials of how to utilize extract epoch.

![Screen Shot 2023-06-15 at 4 12 27 PM](https://github.com/sccn/eeglab/assets/121198359/af8685f0-721f-4245-ac69-a2bf7681b948)

Which then continues to ask to remove baseline but I cannot type in the parameters of the baseline I would like to remove.

![Screen Shot 2023-06-15 at 4 12 38 PM](https://github.com/sccn/eeglab/assets/121198359/7a6cb682-d790-4b5b-b5ef-5137b6d96505)

*The options also look different to than the options I see in other tutorials of how to utilize baseline removal.

Ultimately I want the data output for every ten seconds of the continuous recording for a set parameter that I would have in Hz or amp.

Is this something that I could get using EEGLAB?

Thank you very much!

 

<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Big Sur*] |
| Matlab version | [*R2020b*] |
| EEGLAB version | [*v2023.0*] |

**Comment by arnodelorme** [comment]
Would you mind sharing your data? We have modified this function recently, so there might be a problem with it.
