### ISSUE TITLE
Can't retain reference when re-referencing to average

### ISSUE THREAD

**Issue by A-J-Hanson** [eeglabdevelopers/eeglab#636]
The current EEGlab 2023 fails to find the reference channel information when re-referencing even when it has been entered through the channel locations interface.
From what I can tell...
The updated pop_reref.m appears to be looking for chaninfo.removedchans for the reference information. Which isn't created when appending the reference channel infomation.
When previously in EEGlab 2021.1, pop_reref looked for this information in chaninfo.nodatachans. which is created when appending with the reference channel info.

**Comment by arnodelorme** [comment]
Good observation. We will fix it.

**Comment by estebandleonc** [comment]
Hello, I am having the same problem with this new version 2023 of EEGLAB. Please @arnodelorme could you help us fixing this? Thank you

**Comment by arnodelorme** [comment]
This has been fixed in the current version. Thank you.
