### ISSUE TITLE
Problem in epoch EEG data

### ISSUE THREAD

**Issue by atiy90** [eeglabdevelopers/eeglab#637]
### Error when epochs extract EEG

Hello EEGLAB team,

I am currently facing an issue extracting epochs from my EEG data. The error message keeps popping up, as shown in the link below. I have also attached the dataset and the raw data.
https://drive.google.com/drive/folders/1D0Y3jHFCrn4bFqo1I1KyJHRtxequKGAv?usp=sharing

May I know how to solve this epoch problem? Can it be done with GUI only, without codes or scripts? I am not familiar with codes or scripts, so I hope you can help me with this. Thank you.
<br>
#### Steps to Reproduce

1. [add event, using text event attached]
2. [add channel location] I am using 14 channel
3. [filteration 0.5-40Hz]
4. [interpolate]
5. [ica]
6. [epoch]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Microsoft 10] |
| Matlab version | [2021] |
| EEGLAB version | [2023] |

**Comment by arnodelorme** [comment]
There is no event in the EDF file you shared (only event 4 at the beginning). This is why you cannot extract data epochs.
