### ISSUE TITLE
no matter what I use for catchstrs, I get pop_newset after populating com

### ISSUE THREAD

**Issue by dmedine** [eeglabdevelopers/eeglab#648]
### Description

I am developing a plugin for eeglab and I am having trouble with getting the history mechanism to work. No matter how I define my callbacks in the eeglabplugin_*.m file, I am faced with the `Dataset info -- pop_newset()` dialog.

Not sure if it is a bug or something I don't understand, but I am having trouble using the history machinery while developing a plugin. Specifically, no matter what flag I use in `catchstrs.*` when defining my callback in the gui setup code, my pop functions will always trigger a `Dataset info -- pop_newset` dialog. I made a dummy project demonstrating the behavior: https://github.com/dmedine/eeglab_dummy

<br>
#### Steps to Reproduce

1. clone repository into eeglab/plugins 
2. load eeglab
3. load the example dataset
4. choose `Tools->dummy->add_to_hist` and see a `Dataset info -- pop_newset` dialog

<br>
#### Expected behavior:

When the flag on `catchstrs` is `add_to_hist` (or anything else), I expect the com output by the function to be added to `LASTCOM` and not to be prompted to rename/save the dataset. This is what is indicated by the documentation: https://eeglab.org/tutorials/contribute/design_plugin.html#extensions-and-eeglab-history

<br>
#### Actual behavior:

The `com` string is added to the history, but the rename/save dataset dialog appears.

<br>
#### Versions

dev

|   |   |
|----| ---- | 
| OS version     | Windows 11 |
| Matlab version | 2021b |
| EEGLAB version | dev |

**Comment by arnodelorme** [comment]
I think what you want is the option "catchstrs.new_non_empty"

Let me know.
