### ISSUE TITLE
pop_limo or std_limo

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#650]
Full factorial option from the menu. "interaction model for categorical indep. var."
This option does not work with Henson Wakeman (9 betas + constant). First, the list of beta remains the same. Then, the LIMO.mat files of the subjects have LIMO.fullfactorial = 0

@CPernet do you have any idea why?

**Comment by CPernet** [comment]
because we prevent people to make interactions at the 1st level - and then they complain about 2nd level what to do
only advance users will know what to do -- via GUI only one column per condition, we discussed that long time ago

**Comment by arnodelorme** [comment]
OK, this option was removed from the menu.
