### ISSUE TITLE
error in function roi_plotcolordlobes() at line 699

### ISSUE THREAD

**Issue by fooms2512** [eeglabdevelopers/eeglab#651]
I've included the description of the steps, the error, and the files to check this error.
https://www.dropbox.com/sh/i6qxowo1xfxuvwt/AACNVRXZ6GChSyb26TSVCCTua?dl=0

| OS version     | Windows11 |
| Matlab version | R2020a |
| EEGLAB version | Dev |

**Comment by arnodelorme** [comment]
Your MATLAB version is too old. You need 2020b not 2020a. @nguyen-td, maybe we could use a different function.
