### ISSUE TITLE
Help epoching

### ISSUE THREAD

**Issue by kr1st1na7** [eeglabdevelopers/eeglab#652]
How can I epoch with start and end set by two event marker instead of a time surrounding one marker?

**Comment by arnodelorme** [comment]
In EEGLAB you cannot extract epochs of different length. You can extract data segments if you write a script.

**Comment by kr1st1na7** [comment]
Hi,
Could you clarify what you mean by extracting data segments if I write a
script? Are there any steps available?

**Comment by arnodelorme** [comment]
It all depends on what you want to do. You should send a message to the eeglablist

**Comment by carrie372** [comment]
I used custom scripts to do variable epoching from -200-ms from start of trial to time of response. However, the eeglab interface is not registering this information (epochs not updating when running "eeglab redraw"), trials are not recognized, and plotting functions no longer work. My coding is correct in terms of pulling events, calculating the epoch duration, etc.

Any ideas on how to fix this? Attached are outputs of EEG.event and EEG.epochs after running the attached code.

![Screen Shot 2024-01-18 at 11 19 45 AM](https://github.com/sccn/eeglab/assets/157049734/58b15ec0-e08e-4274-babd-dddbf4817ac8)
![Screen Shot 2024-01-18 at 11 21 01 AM](https://github.com/sccn/eeglab/assets/157049734/9418f369-9c98-4535-91eb-8eb67509bc46)
![Screen Shot 2024-01-18 at 11 22 53 AM](https://github.com/sccn/eeglab/assets/157049734/7d8774bb-b908-4f20-adab-73e1e1ed46fa)
