### ISSUE TITLE
inspect/label component by map

### ISSUE THREAD

**Issue by taliehmir** [eeglabdevelopers/eeglab#653]
### Description

[i used to work with the option 'inspect/label component by map' and click on each component to see the component with plot, suddenly that doesn't work appropriately any more i get always error and ERP plot is empty.]

https://drive.google.com/drive/folders/1XpjN8M3AFlglnv7qgCXH6EmbTFJxVtWH?usp=sharing

#### Steps to Reproduce

1. [eeglab]
2. [file> load existing dataset]
3. [inspect/label component by map> IC1]

<br>
#### Expected behavior:
[component with 3 plots]

<br>
#### Actual behavior:
[shows only two plots, ERP plot is empty]

<br>
#### Versions

| OS version | macBook Air |
| Matlab version | R2023a |
| EEGLAB version | 2023.0 |

**Comment by arnodelorme** [comment]
It works for me with your dataset. Can you try with the EEGLAB version on Github? 
![Screen Shot 2023-07-13 at 6 26 04 AM](https://github.com/sccn/eeglab/assets/1872705/8fbf5317-b713-42c0-bdc4-ad532869210c)

**Comment by taliehmir** [comment]
I have already tried with the EEGLAB version on Github, but it didn't work
again!

Am Do., 13. Juli 2023 um 18:27 Uhr schrieb Arnaud Delorme <
***@***.***>:
