### ISSUE TITLE
Std_makedesign > > > uniquelegacy error line 64

### ISSUE THREAD

**Issue by empetrucci** [eeglabdevelopers/eeglab#655]
### Description

Cannot make new study designs by GUI or commandline. Error ultimately thrown in uniquelegacy line 64 as it expects input to be a double, but it is actually a struct, and it cannot convert the struct to a double. When using the GUI it does say "this is not a bug," yet when I step through the code it seems like the input (a) "should be" a struct as it is derived from STUDY.datasetinfo fields.

[Google Drive Folder](https://drive.google.com/drive/folders/1dcV4257B-wo6A1jt-IJ5Uy1kjLBjGnLt?usp=sharing)

<br>
#### Steps to Reproduce

1. Add the script and the study variable into your workspace
2. Run create_studydesign.m

<br>
#### Expected behavior:
New study design is created

<br>
#### Actual behavior:
Error using double
Conversion to double from struct is not possible.

Error in uniquelegacy (line 64)
                a = double(a);

Error in unique (line 159)
        [varargout{1:nlhs}] = uniquelegacy(varargin{1},logical(flaginds(1:3)));

Error in unique_bc (line 47)
    [C,IA,IB] = unique(A,varargin{:},'legacy');

Error in std_getindvar (line 100)
            tmpvals = unique_bc([ allSetinfoVals{:} ] );

Error in std_makedesign (line 202)
[indvars, indvarvals, ~, paired] = std_getindvar(STUDY);

Error in create_studydesign (line 7)
[STUDY] = std_makedesign(STUDY, ALLEEG, 2, 'name', 'Rest NTGBO', 'variable1', 'condition', 'values1', {'notask', 'think', 'gratitude', 'breath', 'open'}, 'variable2', 'group', 'values2', {'expert', 'novice'});
 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Edition: Windows 10 Enterprise; Version: 22H2; OS build: 19045.3086|
| Matlab version | R2022b |
| EEGLAB version | 2022.1 Need to update; I'll try that soon|

**Comment by arnodelorme** [comment]
```
ALLEEG = STUDY.datasetinfo;
```

This code above creates the problem. Create a STUDY the standard way.
