### ISSUE TITLE
"mexsload not found in path" Issue

### ISSUE THREAD

**Issue by alparslanonder** [eeglabdevelopers/eeglab#657]
Hi, While I was trying to import my edf file (EDF-C) I faced with this problem. I removed then loaded the latest version of Biosig, try lots of things but I keep having this problem, how can I solve it?

Thanks a lot.

![image](https://github.com/sccn/eeglab/assets/64606536/20165447-64e4-4f16-832b-1542224d33e0)

**Comment by arnodelorme** [comment]
Do you have windows. If this is the case, then mexSLOAD should be installed. If you do not have windows then it is more complex. https://sourceforge.net/p/biosig/wiki/FAQ/

**Comment by arnodelorme** [comment]
Closing this for now. I updated the help message.

**Comment by lopezchau** [comment]
> Do you have windows. If this is the case, then mexSLOAD should be installed. If you do not have windows then it is more complex. https://sourceforge.net/p/biosig/wiki/FAQ/

Dear Arno, I have a MacOS system and followed the steps but I was not able to open an EDF file with mexSLOAD.  It is of my interest because events are not loaded with the default settings.

**Comment by arnodelorme** [comment]
You do not need mexsload to load EDF events. You can use other options when calling the biosig function. For example, try importing with annotation off.

```
EEG = pop_biosig('file.edf', 'importannot', 'off');
[ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG);
eeglab redraw
```

**Comment by lopezchau** [comment]
> You do not need mexsload to load EDF events. You can use other options when calling the biosig function. For example, try importing with annotation off.
> 
> ```
> EEG = pop_biosig('file.edf', 'importannot', 'off');
> [ALLEEG EEG CURRENTSET] = eeg_store(ALLEEG, EEG);
> eeglab redraw
> ```

Thank you so much for your answer!  Still no luck while importing events after I uncheck the annotations option.  After I imported the file with no events I use the "Import event info" from the menu, but more than 300k of events are imported after a long time.

When I try other import plugins like **import_edf** the events are imported normally but I get an error that says there is another edfread function and I need to remove it from the path.

Sorry if the question is too basic, but these are my first steps with EEGLab.

<img width="708" alt="Captura de pantalla 2024-05-04 a la(s) 3 32 36 p  m" src="https://github.com/sccn/eeglab/assets/143896040/a194f69d-c1f2-4bd6-94e1-5b9332b3ffed">

**Comment by arnodelorme** [comment]
Can you share your EDF file?

**Comment by lopezchau** [comment]
> Can you share your EDF file?

Absolutely Arno. It would be such an honor.  I am new to EEGLab and having support from you is unbelievable.

Thank you so much.  Greetings from Peru.

PS: Just to let you know that data have being acquired from a Neuron Spectrum 64. It is a russian made amplifier. We are planning to do some research with it and a same brand TMS device (TMS-EEG).

https://neurosoft.com/en/catalog/eeg/neuron-spectrum-64#overview

EDF File:
https://drive.google.com/file/d/1--m7MZvoHEpzg_sh_gTh_adeqhgh22Ou/view?usp=sharing

**Comment by Lucreziadimarino** [comment]
@lopezchau Ciao! Ho lo stesso identico problema... hai risolto?

**Comment by alparslanonder** [comment]
As I experienced, the exact problem was in the Headers of the .edf files, with a pipeline I solved the issue about the headers and I did not have the same issue again.

**Comment by Lucreziadimarino** [comment]
@lopezchau  come hai fatto a risolvere? perchè io non riesco in alcun modo a visualizzare gli eventi nonostante io abbia la certezza che ci siano. Sono una studentessa che sta eseguendo un progetto sperimentale per la tesi e non sono riuscita ancora a risolvere

**Comment by arnodelorme** [comment]
I apologize for the late reponse. This file does not contain any event. Closing the issue for now.

https://drive.google.com/file/d/1--m7MZvoHEpzg_sh_gTh_adeqhgh22Ou/view?usp=sharing
