### ISSUE TITLE
questdlg2 horizontal geometry

### ISSUE THREAD

**Issue by CPernet** [eeglabdevelopers/eeglab#658]
### Description

When using basic input as for the matlab function, the GUI is too small horizontally

example: questdlg2('Type of merging','Options','Evaluate single conditions','Pool Conditions','Evaluate single conditions');

| OS version     | [windows] |
| Matlab version | [2022] |
| EEGLAB version | [dev] |

**Comment by arnodelorme** [comment]
OK, I will look at that.

**Comment by arnodelorme** [comment]
OK done. 430643c32

![Screen Shot 2023-07-18 at 7 10 48 PM](https://github.com/sccn/eeglab/assets/1872705/bb5e130c-7c18-4ffc-8cd6-abe32cb0faf2)
