### ISSUE TITLE
Java exception on MFF

### ISSUE THREAD

**Issue by vmathew7** [eeglabdevelopers/eeglab#660]
Hi
I am a Ph.D. scholar working on face processing studies. We use EGI 65 electrode system in our lab. While trying to analyse data using EEGLAB we used the latest version of MFFimport4.1. 
When I am using MFFMatlabIO to import files I am getting the following Java exception error, which I have attached as an image.
This is only happening to few files. 
Please help about how to import the file for doing analysis.

Sincerely
Thanking you in advance

![Screenshot 2023-07-24 120702](https://github.com/sccn/eeglab/assets/61224829/5e2ffa17-7862-4516-a2f5-faf80454976f)

**Comment by arnodelorme** [comment]
This is due to the Java library cannot handle. If the file (usually XML file) is modified then it can be imported. Can you share a data file?

**Comment by vmathew7** [comment]
Thank you for the response. I am sharing the link for accessing the file in your Email, hope that's fine. https://drive.google.com/drive/folders/1FVYPbmbK1slWDj_biN3w4MwPlYTK5GOZ?usp=drive_link

**Comment by arnodelorme** [comment]
Yes, thanks

**Comment by vmathew7** [comment]
Hi, hope the file was accessible. I just wanted to follow up on this issue. Is there something I can refer to identify the issues and make changes to import the files?

Thanking you in advance

**Comment by vmathew7** [comment]
Hi, I wanted to follow up on this issue. Really looking forward to a response. 

Thanking you in advance.

**Comment by arnodelorme** [comment]
I have had a look. The issue is associated with some number format error in info1.xml. When I remove the calibration information (below is how the file looks like after modification), then I can import it.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<dataInfo xmlns="http://www.egi.com/info_n_mff" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <generalInformation>
        <fileDataType>
            <EEG>
                <EEGFile />
                <sensorLayoutName>HydroCel GSN 64 1.0</sensorLayoutName>
                <montageName>HydroCel GSN 64 1.0</montageName>
            </EEG>
        </fileDataType>
    </generalInformation>
    <hardwareFilterAdjusted shiftMicroseconds="66000">true</hardwareFilterAdjusted>
</dataInfo>
```

See attached screen capture. The calibration information is not critical, but data will not be scaled according to calibration values. 

![Screen Shot 2023-08-08 at 10 23 07 AM](https://github.com/sccn/eeglab/assets/1872705/3fabade9-3702-436d-a0da-2f947ab0e9a9)

**Comment by arnodelorme** [comment]
Note to self: removing the channels n="" solves the issue. A fix would be to edit the file and remove such channels.

**Comment by vmathew7** [comment]
Thank you so much, I have made the changes by deleting n="" channels in the info1.xml file and it's importing. Thank you again for your time.

**Comment by arnodelorme** [comment]
Fixed.
