### ISSUE TITLE
Error when loading existing dataset

### ISSUE THREAD

**Issue by wycalan** [eeglabdevelopers/eeglab#662]
### Description
You can access the mentioned datasets by downloading them from this link: https://cloud.zjnu.edu.cn/share/e67dedf539903582b13aba03e0?lang=en

When attempting to use the "load existing dataset" function in MATLAB 2021a on macOS to load the file named "sub01_0_raw.set," EEGLAB encounters an error stating "cannot read file sub01_0_raw.set. This is not a bug (Error occurred in function pop_loadset() at line 152)." However, no issues arise when loading the same dataset using MATLAB 2021a on a Windows 10 system. Furthermore, there are no issues when loading the "sub01_2_clean.set" file on MATLAB 2021a on macOS. 
Additionally, it is worth noting that the "sub01_0_raw.set" dataset can be successfully loaded using MATLAB 2016b on the same macOS.

|   |   |
|----| ---- | 
| OS version     | [*macOS Catalina, on macbook pro 2019 intel chip*] |
| Matlab version | [*2021a*] |
| EEGLAB version | [*2023.0*] |

**Comment by arnodelorme** [comment]
It was saved using MATLAB 5.0, which is 25 years old, and probably no longer supported by the Mathworks. I think this is why it cannot be imported. I tried reading the file in 2023a and it failed. I tried in 2014a and it worked. I would just import it and resave it in EEGLAB 2016 and you will be good to go.
