### ISSUE TITLE
Parallel toolbox

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#663]
When changing the preferences in the menu, you still need to start parpool manually for eeg_eval

**Comment by CPernet** [comment]
I try to deal with that in https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/limo_check_ppool.m -- you'll prob find a better way but night help as starting point

**Comment by arnodelorme** [comment]
Thanks!

**Comment by arnodelorme** [comment]
Should be fixed now.
