### ISSUE TITLE
Restricting trial length

### ISSUE THREAD

**Issue by droe11** [eeglabdevelopers/eeglab#670]
Restricting length of trial and channel EEG data to the participant with the lowest so that the size of the EEG.data structure is the same for each participant. 

Hi everyone, I am relatively new to EEGLAB and have what may be quite a simple issue. 

I have EEG data from multiple participants (37), I am trying to use a plugin classifier designed for MATLAB on the data. However, to use this plugin, the size of the EEG.data structure needs to be the same. Unfortunately, due to pre-processing/cleaning of the EEG data, the EEG.data structure has different channel and trial lengths for each participant. 

I have tried going about resolving this but I have no experience with EEGLAB. Although what I try appears to work on the face of it - meaning when I save the data the plugin works, I can then no longer load the saved data into EEGLAB suggesting to me that it is corrupted somehow. 

The following is how I have been trying to edit the data structure. 

minSamples = min(size(EEG.data,2));
numTrials = 148;

eegDataRestricted = zeros(size(EEG.data, 1), minSamples, numTrials);

for trial = 1:numTrials
    if size(EEG.data, 2) > minSamples
        eegDataRestricted(:,:,trial) = EEG.data(:, 1:minSamples, trial);
    else
        eegDataRestricted(:,:,trial) = EEG.data(:,:,trial);
    end
end
disp(['Original size: ', num2str(size(EEG.data))]);
disp(['Restricted size: ', num2str(size(eegDataRestricted))]);

EEG.data = eegDataRestricted;

channels_To_Keep = 1:67;

eegDataRestricted = EEG.data(channels_To_Keep, :, :);

% Display the sizes before and after restriction
disp(['Original size: ', num2str(size(EEG.data))]);
disp(['Restricted size: ', num2str(size(eegDataRestricted))]);

EEG.data = eegDataRestricted;
EEG.trials = 148;
EEG.epoch (149:153) = [];

saveDirectory = 'C:\Users\PCP22DR\Documents\MATLAB\EEG and mvpa stuff\MVPA\Dans\Condition_a\';
filename = '1.set';
pop_saveset(EEG, [saveDirectory, filename]);

I am using MATLAB version R2022a and EEGLAB version v2023.0

Any help would be greatly appreciated. 

Thank you, 
Dominic

**Comment by arnodelorme** [comment]
Dear Dominic,

Aussming you have multiple dataset loaded in memory, use something like

```
maxlen = min([ALLEEG.pnts])
for iEEG = 1:length(ALLEEG)
     ALLEEG(iEEG).data = ALLEEG(iEEG).data(:, 1:maxlen);
end
```
