### ISSUE TITLE
Error using fprintf Invalid file identifier. Use fopen to generate valid file identifiers

### ISSUE THREAD

**Issue by miuwu** [eeglabdevelopers/eeglab#671]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
When I just want to EEPLAB→Eventlist→Create EEG EVENTLIST, it always reports errors: Error using fprintf Invalid file identifier. Use fopen to generate valid file identifiers
<br>
#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]
![image](https://github.com/sccn/eeglab/assets/51154675/02fa3a1a-7faa-4997-9e0e-956cb6f50016)

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*2022a*] |
| EEGLAB version | [*2023*] |

**Comment by arnodelorme** [comment]
This is an ERPLAB problem. Apologies for the late answer. Please refer to https://github.com/ucdavis/erplab
