### ISSUE TITLE
Clustering plot error with EEGLAB 2023.0 version

### ISSUE THREAD

**Issue by deepagupta** [eeglabdevelopers/eeglab#672]
### Description

Clustering plotting bug as described below with screenshots attached

<br>
#### Steps to Reproduce

1. Load your datasets
2. Create STUDY with all the loaded datasets (selected r.v. <15% and removed external cortical dipoles)
3. Performed clustering (Study -> PCA clustering(original) ->'Build preclustering array' (dipoles weightage 1) followed by the 'cluster components' (outliers checked with std. dev. 3 and k=27) step. 
4. Plot/edit - > plot dipoles option gives error as can be seen in the attached screenshot

<br>
#### Expected behavior:
dipole plots (attached by using EEGLAB 2022.0 on the same windows machine and MATLAB 2022a works fine as shown in the screenshot below)

![20230831kmeansSHOTS](https://github.com/sccn/eeglab/assets/718251/d20876f2-3459-4f2c-8725-07b26b82201b)

<br>
#### Actual behavior:
error message with incomplete plot as can be seen below (attached by using EEGLAB 2023.0 with same matlab and windows version)

![clustering_bug2](https://github.com/sccn/eeglab/assets/718251/21bb3907-dea2-434f-aa31-e9468cbe8f36)
![clustering_bug](https://github.com/sccn/eeglab/assets/718251/3376acaf-5dfd-4ff5-a683-9858d62f759a)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows] |
| Matlab version | [2022a] |
| EEGLAB version | [2023.0] |

**Comment by arnodelorme** [comment]
Can you type

which dipplot

Are you using dipfit 5.3?

**Comment by deepagupta** [comment]
Thank you Arnaud. That helped, however, with ERPimage, I still get the following error message. Please advise:

![ERPimage_error](https://github.com/sccn/eeglab/assets/718251/d200d498-a361-4a65-bc8b-655245dfe4bf)


On investigating, I am seeing that the array at that line#243 is empty. I checked, all my plugins are now up to date but I am still getting the above error message on visualization. If possible, may I request some hints on how to proceed better please? Thank you in advance

MATLAB: 2022a
EEGLAB: v2023.0

**Comment by deepagupta** [comment]
Thank you.
