### ISSUE TITLE
Component cluster plotting not updating after adding/removing components 

### ISSUE THREAD

**Issue by clayishmarmot19** [eeglabdevelopers/eeglab#673]
Description
ERSP plots will not update following the addition or removal of components.

![github2](https://github.com/sccn/eeglab/assets/143841486/ab64bef2-e58c-4744-8dd4-325e49843be5)
Cluster with one component from each group

![github3](https://github.com/sccn/eeglab/assets/143841486/409f116a-4415-4249-9b54-bfed812eeaf5)
Cluster with 3 components from each group. Plotting the same as if it still had one component from each group. 

#### Steps to Reproduce

1. Create study with datasets (excluding s21)
2. Compute component measures (power spectrum, ersp, scalp map) and add 'baseline', [-6500 -5500] in Time/freq parameters
3. Build clustering array using scalp maps and dipole location
4. Cluster components
5. Create new cluster and add 1 component
6. Plot ERSP
7. Add another component 
8. Plot ERSP
9. ERSP plots should look different 

#### Actual behavior: Both ERSP and Spectra plotting functions do not update the plots following cluster edits. This occurs in all clusters. 

| OS version     | Windows 10 Enterprise v21H2 |
| Matlab version | 2023a |
| EEGLAB version | 2023.0 |

**Comment by arnodelorme** [comment]
Good point. It is a cache issue. Addition or removal of components should clear the cache. Fixed in f407502d7
