### ISSUE TITLE
EEG-Beats

### ISSUE THREAD

**Issue by mpilgrm** [eeglabdevelopers/eeglab#675]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
![EEGissue](https://github.com/sccn/eeglab/assets/144920524/cded1a8c-4dcb-40e7-b255-182ce77b44f3)
<br>
#### Steps to Reproduce

1.  Have EEG-Beats1.1.2 installed
2. Select plugin and select channel. 
3 run it
4. [*and so on...*]

<br>
#### Expected behavior: produce graphs and clean data to just get heart rate data
[*What you expected to happen*]

<br>
#### Actual behavior: EEGLAB line 23 error
[*What actually happened*]

<br>
#### Versions
![EEGissue](https://github.com/sccn/eeglab/assets/144920524/cded1a8c-4dcb-40e7-b255-182ce77b44f3)

|   |   |
|----| ---- | 
| OS version     | [*fill in*] | Windows 10
| Matlab version | [*fill in*] |2023a 
| EEGLAB version | [*fill in*] | V2023.1

**Comment by arnodelorme** [comment]
@VisLab would you mind to transfer this issue to the EEG-beats plugin repo?
