### ISSUE TITLE
eeg_getdatact not trying to find FDT file

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#676]
EEG = pop_loadset('/expanse/projects/nemar/openneuro/ds004022/sub-01/eeg/sub-01_task-motorimagery_run-2_eeg.set')

crashes but FDT file is present

**Comment by arnodelorme** [comment]
Fixed

**Comment by LegacySue** [comment]
hello, could you share me how to fix it? thx!!

**Comment by arnodelorme** [comment]
It is fixed in EEGLAB, you just need to download the latest version.

**Comment by LegacySue** [comment]
fixed, thank you very much
