### ISSUE TITLE
Importing .eeg file

### ISSUE THREAD

**Issue by sodeleoz** [eeglabdevelopers/eeglab#678]
Hello,
I'm new to using this and I've been trying to import .eeg files to preprocess however once the I try to leave the spaces for the subsets blank, I receive this error.
![image](https://github.com/sccn/eeglab/assets/125423621/d0ef6a18-dc5b-4dba-8694-6ae28ff869a6)
When I do fill out the blanks, I receive this error.
![image](https://github.com/sccn/eeglab/assets/125423621/09da5b13-23e4-4a94-9924-ae945fc51cc1)
How may I fix this? 
And is there another option to be able to import all of the .eeg files at the same time? Creating a study only allows .set.

Here is the dataset I am using:
https://drive.google.com/drive/folders/1M9wNaskVQqI3ZGQVdgvA3YHZp72MQOsy?usp=sharing

Thank you.

**Comment by AminAlam** [comment]
I think your datasets have a problem, as the problem is not because of EEGLAB. The error is coming from neuroscanio1.7 plugin and the reason for this errors is that your .eeg datasets don't have any channels (chan= fread(fid, 1, 'ushort') is an empty list)

**Comment by arnodelorme** [comment]
Agreed, you should use the BVA-IO plugin. These are brain vision exchange files.
