### ISSUE TITLE
ROIconnect: pipeline_connectivity

### ISSUE THREAD

**Issue by deepagupta** [eeglabdevelopers/eeglab#679]
### Description

While running ```pipeline_connectivity.m``` in the ```test_pipes``` folder of ROIconnect plugin, I get the below error message that the struct has duplicate fields during the brainmovie3d_causal function call (pipeline connectivity>pop_roi_connectplot>roi_plotbrainmovie line#136 that calls brainmovie3d_causal) as described below: 

Bug description: please see 'Actual Behavior' below

Suggestion:
I changed line#136 in roi_plotbrainmovie.m 

```

 brainmovie3d_causal( ersp, ersp, array, array, 1, 1, [1:length(ersp)], ...
     'coordinates', pos, ...
     'latency', 1, ...
     'coordformat', 'mni', ...
     'dipplotopt', {'meshdata' template_models(2).hdmfile ,'meshedgecolor',[0.3 0.3 0.3] 'meshoptions' {'facealpha',0,'edgealpha',1}}, ...
     'modulateEdgeSize', 'on', ...
     'nodeSizeLimits', [0.05 0.10], ...
     'nodeColorDataRange', [0.5 1], ...
     'edgeSizeLimits', [0.05 0.25], ...
     'edgeColorDataRange', [g.threshold 1], ...
     'caption', false, ...
     g.brainmovieopt{:});
 %    'nodeSizeDataRange', [-100 100], ...
 delete(findobj(gcf, 'tag', 'img'))
 set(findobj(gcf, 'tag', 'mesh'), 'visible', 'on')
```

to the following to avoid that error:

```

brainmovie3d_causal( ersp, ersp, array, array, 1, 1, [1:length(ersp)], ...
    'coordinates', pos, ...
    'latency', 1, ...
    'coordformat', 'mni', ...
    'dipplotopt', {'meshdata' template_models(2).hdmfile ,'meshedgecolor',[0.3 0.3 0.3] 'meshoptions' {'facealpha',0,'edgealpha',1}}, ...
    'modulateEdgeSize', 'on', ...
    'edgeSizeLimits', [0.05 0.25], ...
    'edgeColorDataRange', [g.threshold 1], ...
    'caption', false, ...
    g.brainmovieopt{:});
%    'nodeSizeDataRange', [-100 100], ...
delete(findobj(gcf, 'tag', 'img'))
set(findobj(gcf, 'tag', 'mesh'), 'visible', 'on')
```

<br>
#### Steps to Reproduce

1. Download ROIconnect
2. Run: test_pipes/pipeline_connectivity.m [source: https://github.com/sccn/roiconnect/blob/master/test_pipes/pipeline_connectivity.m]

<br>
#### Expected behavior:

![ROIpipeline_connectivity_output_screenshot 2023-09-26 123504](https://github.com/sccn/eeglab/assets/718251/545baadb-4463-481c-a3d7-8a32d7b7696f)

<br>
#### Actual behavior:

```
Error using struct
Duplicate field name "nodeColorDataRange"

Error in brainmovie3d_causal (line 245)
    g=struct(varargin{:});

Error in roi_plotbrainmovie (line 120)
brainmovie3d_causal( ersp, ersp, array, array, 1, 1, [1:length(ersp)], ...

Error in pop_roi_connectplot (line 506)
            roi_plotbrainmovie(matrix, 'cortex', EEG.roi.cortex, 'atlas', EEG.roi.atlas, g.plot3dparams{:});

Error in pipeline_connectivity (line 52)
pop_roi_connectplot(EEG, 'measure', 'MIM', 'plot3d', 'on',  'plotcortex', 'off', 'plot3dparams', {'threshold', 0.29, 'brainmovieopt' {'nodeColorDataRange', [], 'nodeSizeLimits', [0 0.2]}});
```

#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 10 Education*] |
| Matlab version | [*2022a or/and 2023a*] |
| EEGLAB version | [*2023.0*] |

**Comment by arnodelorme** [comment]
Thank you for your report. The issue is likely because you are not using the right brainmovie_causal function. You might be using the one from SIFT. Remove SIFT then install the Brainmovie plugin. Feel free to reopen the issue if it does not fix the problem.
CC @nguyen-td
