### ISSUE TITLE
What are the output arrays (diffmap, sourcepot, and datapot) from the dipfit method in eeglab providing?

### ISSUE THREAD

**Issue by ssakthivel18** [eeglabdevelopers/eeglab#684]
I am confused why the diffmap, sourcepot, and datapot arrays only have 1 column. Shouldn't these values change over time? How is it only providing 1 value per electrode? How do I find the activation values at each dipole from this output from the dipfit method?

**Comment by arnodelorme** [comment]
It is only one value because these depict ICA components (which are static) not time courses.

https://eeglab.org/tutorials/09_source/DIPFIT.html
