### ISSUE TITLE
Inquiry on how to group electrodes into lobe

### ISSUE THREAD

**Issue by atiy90** [eeglabdevelopers/eeglab#685]
Hello there,

I am trying to do spectral density analysis for EEG data using EEGLAB. I want to group several electrodes based on different lobes. For example, F3, F4, and Fz channels into one frontal lobe and channel T4, T3 into the temporal lobe. I have no experience in coding or scripting, so any help using the EEGLAB GUI is highly appreciated. Thank you.

**Comment by arnodelorme** [comment]
Yes, you can group electrodes when plotting results at the group analysis level. 

https://eeglab.org/tutorials/10_Group_analysis/study_data_visualization_tools.html
