### ISSUE TITLE
Matlab becomes unresponsive when closing figures

### ISSUE THREAD

**Issue by Fitosm** [eeglabdevelopers/eeglab#686]
### Description

When I use the red close button on the top left of figures in EEGlab, Matlab becomes unresponsive and requires a force quit.  Figures can be successfully closed from the top menu of the window or from the Matlab command window.

<br>
#### Steps to Reproduce

1. [Open a figure]
2. [Click the red close icon in the upper left of the figure window]

<br>
#### Expected behavior:
the figure will close

<br>
#### Actual behavior:
Matlab freezes/becomes infinitely unresponsive (Matlab actually crashed until I updated to the newest version of eeglab.m)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Mac 14.0] |
| Matlab version | [R2023b update 1] |
| EEGLAB version | [2023.1 with updated eeglab.m for my matlab version] |

**Comment by arnodelorme** [comment]
This is MATLAB issue probably linked to Mac os 14. Closing for now.
