### ISSUE TITLE
Interpolating erros

### ISSUE THREAD

**Issue by EstebanSarrias** [eeglabdevelopers/eeglab#689]
### I am trying to interpolate removed data.

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
#### Steps to Reproduce

1. EEG = pop_tesa_removedata( EEG, [-2,15], [], {'TMS'});% 0 value, needs interpolation
2. tesa_plot(EEG, 'xlim', [-800,500], 'ylim', [-40,40], 'elec', 'O2', 'CI', 'on');
3. EEG = pop_tesa_interpdata( EEG, 'cubic', [5,5] );

#### Expected behavior:
What I expected to happen is that eeg removed data can be interpolated around TMS pulses

<br>
#### Actual behavior:
Index in position 2 is invalid. Array indices must be positive integers or logical values.

Error in tesa_interpdata (line 232)
                X = x(:,TP1:TP2);

Error in pop_tesa_interpdata (line 97)
EEG = tesa_interpdata( EEG, interpolation, interpWin );
 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 11] |
| Matlab version | [R2022b] |
| EEGLAB version | [v2023.1] |

**Comment by arnodelorme** [comment]
Would you mind posting the problem on https://github.com/nigelrogasch/TESA 
This is a plugin function not an EEGLAB core function.
