### ISSUE TITLE
EEGLAB error in function pop_writeeeg()

### ISSUE THREAD

**Issue by ghost** [eeglabdevelopers/eeglab#69]
Hi all,

I got this error when I tried to export my data in .edf . I tried to install the neuroscanio plugin, it didn't work.

<br>

1. Open an EEG (epoched)
2. File->export->data to EDF/etc
3. This dataset contains epochs. Do you want to export the concatenated data epochs? YES (If NO, it doesn't do anything)

<br>

It give me the error:
EEGLAB error in function pop_writeeeg()

<br>
#### Actual behavior:
[*What actually happened*]

<br>

|   |   |
|----| ---- | 
| OS version     | windows 10|
| Matlab version | [R2018b] |
| EEGLAB version |v2019.0 |

**Comment by ghost** [comment]
update: I tried with a file that was already concatenated. It's the same.

**Comment by jmkendallbar** [comment]
Hello, I am also having this problem. I am using the latest version of EEGLAB (v2019.0), with Matlab version 2017a, and Windows 10. 

I was trying to export the following dataset (attached as a .zip) as an .edf. My dataset has 7 channels of electrophysiological data which has already been processed using the "runica" function. However, this error occurs even when I try to export the original, unprocessed data.
[EEGLAB Dataset.zip](https://github.com/sccn/eeglab/files/3866338/EEGLAB.Dataset.zip)

My friend was able to export as an .edf by using a previous version (14.1.2). 

Thank you for any help you can provide!

**Comment by jmkendallbar** [comment]
Here is the error message.
![image](https://user-images.githubusercontent.com/57967704/69191957-72980300-0ad8-11ea-9369-3e6a3b6d625f.png)

**Comment by arnodelorme** [comment]
Downloading the latest version 2019.1 fixes the problem. See also this message

https://sccn.ucsd.edu/pipermail/eeglablist/2019/014463.html

https://sccn.ucsd.edu/pipermail/eeglablist/2019/015007.html
