### ISSUE TITLE
welch() at line 87: Incorrect use of zeros ; The value of Size must be an integer

### ISSUE THREAD

**Issue by a1phaeeg** [eeglabdevelopers/eeglab#690]
### Description
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.]
When I just want to plot→channel spectra and maps，it always reports errors: EEGLAB error in function welch() at line 87:
Incorrect use of zeros
The value of Size must be an integer

The file has been uploaded to Google drive, as shown below
https://drive.google.com/drive/folders/1QnhZySVRuG6oAD3vzw3zyvZ8VMQP5kbI?usp=sharing

The EEG data *.set was converted from *.edf files.

![image](https://github.com/sccn/eeglab/assets/140239750/bf4ad6fc-e3d6-4564-83b1-dfea662f8903)

Please help me solve this issue.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*2020a*]  |
| EEGLAB version | [*2022.1*] |

**Comment by AminAlam** [comment]
Hi,

I used the most recent dev version of EEGLAB with you datasets and it's working fine. Try upgrading to the most recent EEGLAB

**Comment by a1phaeeg** [comment]
> Hi,
> 
> I used the most recent dev version of EEGLAB with you datasets and it's working fine. Try upgrading to the most recent EEGLAB

I'll try it, thank you!

**Comment by arnodelorme** [comment]
Might be a problem with the fact the statistics toolbox is absent. I was able to load the file 1.set and plot the spectrum.

![Screen Shot 2023-10-23 at 6 36 38 PM](https://github.com/sccn/eeglab/assets/1872705/b2341185-1452-4e31-ade3-962913af8477)

**Comment by a1phaeeg** [comment]
The most recent dev version of EEGLAB  is working fine, thank you very much!
