### ISSUE TITLE
I have an issue wheI have the same problem，matlab2019b eeglab2023.1

### ISSUE THREAD

**Issue by blink12138** [eeglabdevelopers/eeglab#691]
I have an issue when opening the manage extension from the EEGLAB (v2019.0) dropdown menu (File > Manage EEGLAB extensions) and it's throwing an error:

![image](https://github.com/sccn/eeglab/assets/128175003/24372405-62d6-4eb5-a897-c1fad8266430)

I've tried updating java, disabling the firewall and I have active internet connection yet the error still shows.

I need to download the LSL plugin.

_Originally posted by @arayes2000 in https://github.com/sccn/eeglab/issues/20#issuecomment-1594428833_

**Comment by arnodelorme** [comment]
You can download plugins manually from this page

https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php

**Comment by blink12138** [comment]
<img width="544" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/462153c5-41bb-4c04-8e5d-74fcb2dce3cd">
<img width="576" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/b4c5caaa-cd40-455d-9c7e-28e37d34f0a0">
I have tried adding it manually, but there seems to be a problem with the expansion of eeglab and it cannot be installed

I have tried:

1. Replace matlab2020b with matlab2019b

2. Change the version of eeglab from January 2019 to January 2023

3. Replaced Java version 1.8.202 to the latest Java11

4. Closed the firewall, used administrator running and compatibility mode

None of the above is useful

Is it related to updating the Windows 11 system or the files on the C drive

**Comment by blink12138** [comment]
<img width="495" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/3e5e7b8d-8279-4a87-8873-087810a63d79">
<img width="529" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/7a3c2bad-f3ad-40f2-a4fe-7022909f5466">
<img width="512" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/f7d9e586-0cbf-4936-b978-9197bb5133ef">

**Comment by blink12138** [comment]
<img width="542" alt="image" src="https://github.com/sccn/eeglab/assets/130914571/b2e9026b-796b-4877-8e69-ec78b3d5e0aa">
I have tried adding it manually, but there seems to be an issue with the expansion of eeglab and it does not display

**Comment by blink12138** [comment]
Thank you very much for your reply and help. Thank you very much for any inconvenience caused


> 您可以从此页面手动下载插件
> 
> https://sccn.ucsd.edu/eeglab/plugin_uploader/plugin_list_all.php

Thank you very much for your reply and help. Thank you very much for any inconvenience caused

**Comment by arnodelorme** [comment]
Yes, it is usually a firewall issue.

**Comment by blink12138** [comment]
> 是的，这通常是防火墙问题。

But I completely closed my firewall and it was useless，Is there any other possible reason

**Comment by blink12138** [comment]
![image](https://github.com/sccn/eeglab/assets/130914571/e0bbdb23-3978-489c-9fb4-34b51169d50b)
<img width="481" alt="d7f53368c5921905fe92250e160e936" src="https://github.com/sccn/eeglab/assets/130914571/ca7dc9df-79c7-4f6a-b2e4-23dabd237f3f">

I have found a solution, which is to establish a network proxy and unify the network proxy address of MATLAB with the proxy address of the computer

My computer system: windows11

MATLAB: matlab2020b

Eeglab: eeglab2023-1
