### ISSUE TITLE
execution of script pop_loadbv as a function is not supported MAC IOS

### ISSUE THREAD

**Issue by betulyilmaz34** [eeglabdevelopers/eeglab#694]
### I am trying to load  a vhdr.file using EEGLAB.2021 with Mac. Such error attached keeps popping up. I also tried EEGLAB.2023 but still does not work. I do not how to fix it, İ'd really appreciate your help.

(<img width="527" alt="Screen Shot 2023-10-26 at 12 48 10" src="https://github.com/sccn/eeglab/assets/149065781/5c2e58b2-3b47-4661-ac03-ca95ce675ab4">)))

<br>
#### Steps to Reproduce

1. File-> import data
2. Using EEGLAB functions and plugins -> from brain vision recorder vhdr or hdr
3. error (seen in the screenshot)

<br>
#### Expected behavior:
[import data and open the file in eeglab]

<br>
#### Actual behavior:
[*execution of script pop_loadbv as a function is not supported*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*12.2.1*] |
| Matlab version | [*R2023b*] |
| EEGLAB version | [*v2021.1*] |

**Comment by AminAlam** [comment]
Hi, can you please share the data file? This way we can better check the source of error

**Comment by betulyilmaz34** [comment]
Sure, I’ve attached a file I am trying to analyze, which is a vhdr file.
Thank you,
Betül 

￼

**Comment by arnodelorme** [comment]
This error arises because of the script named pop_loadbv which is located in the folder /Users/betul and which shadows the real function in the BVA-io plugin.
