### ISSUE TITLE
Incorrect std baseline in newtimefbaseln?

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#697]
Looks like there may be an error during baseline removal (for ERP or ERSP), when calling _newtimefbaseln_ in newtimef.

Line 142:  
`allMstd{ind}  = meanBaseln;`
should be: 
`allMstd{ind}  = meanStd;`

See
![image](https://github.com/sccn/eeglab/assets/58382227/7d6e5de8-0ab9-4473-9e10-df28cdf3a43d)

**Comment by arnodelorme** [comment]
Good catch. Fixed.
