### ISSUE TITLE
error in zapline function 

### ISSUE THREAD

**Issue by yoojchoo** [eeglabdevelopers/eeglab#698]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]
Hi, 
I'm trying to use zapline plugin to remove linenoise in my dataset with a default one line for running it:  EEG = clean_data_with_zapline_plus_eeglab_wrapper(EEG,struct('noisefreqs','line')) % specifying the config is optional

<br>
#### Steps to Reproduce

1. I typed 
**EEG = clean_data_with_zapline_plus_eeglab_wrapper(EEG,struct('noisefreqs','line')) % specifying the config is optional,** 
following the line (this is what GUI produced as well). 
3. Then I got an error in the command window. 

<br>
#### Expected behavior:
I was expecting that zapline function would work properly. 

<br>
#### Actual behavior:
This is the error message I got from this: 

Undefined function 'bandpass' for input
arguments of type 'single'.
Error in clean_data_with_zapline_plus
(line 356)
        data_narrowfilt =
        bandpass(data,[noisefreq-detectionWinsize/2
        noisefreq+detectionWinsize/2],srate);
        Error in
        clean_data_with_zapline_plus_eeglab_wrapper
        (line 25)
    [EEG.data, EEG.etc.zapline.config,
    EEG.etc.zapline.analyticsResults,
    plothandles] =
    clean_data_with_zapline_plus(EEG.data,
    EEG.srate, zaplineConfig); 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Linux*] |
| Matlab version | [*R2017a*] |
| EEGLAB version | [*v2021.0*] |

**Comment by arnodelorme** [comment]
I have moved this bug to the zapline plus plugin https://github.com/MariusKlug/zapline-plus/issues/23
