### ISSUE TITLE
pop_newtimef colorbar scale error

### ISSUE THREAD

**Issue by kunnnnnnnn** [eeglabdevelopers/eeglab#700]
### Description
[B1EEG.zip](https://github.com/sccn/eeglab/files/13238616/B1EEG.zip)

pop_newtimef function produce a figure with wrong colorbar, as in the figure, the value is over 9, while the colorbar only scale to 5 at maximal.
![1698926902167](https://github.com/sccn/eeglab/assets/49976531/af738cbb-9d10-4d7a-9a14-d66f5c14c622)

<br>
#### Steps to Reproduce

data: in attach files

code:
B1out = pop_newtimef(B1EEG,1,8,[-760  5900],[2  0.8],'freqs',[2,31],'plotitc','off','plottype','image','ntimesout', 561,'title',channel,'winsize',500);

<br>
#### Expected behavior:

colorbar scale to more than 9

<br>
#### Actual behavior:

colorbar only scale to 5

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [windows 10] |
| Matlab version | [2023b] |
| EEGLAB version | [v2023.1] |

**Comment by arnodelorme** [comment]
This is because the color is saturated. The value is 9 and the colorbar is in between -5 and 5. To convince yourself, click on the image, then on the command line, type

```
clim([-9 9])
```

And the plot should change. Closing for now.
