### ISSUE TITLE
调用“readbvcon"时，未对输出参数“CONF”(可能还包括其他参数)赋值。

### ISSUE THREAD

**Issue by zxsjcf** [eeglabdevelopers/eeglab#702]
<img width="604" alt="b573deb719c15e9d797e0253c11e411" src="https://github.com/sccn/eeglab/assets/151358030/c02ef5ae-6ed4-4773-be76-391bed589c03">
<img width="509" alt="5c048916c5feee84a9f491d6a103358" src="https://github.com/sccn/eeglab/assets/151358030/b6458b5e-53f9-41fd-b3d5-52ef73f9d7fa">
<img width="540" alt="3234b4ceb5baff0ae928c0fb6da59d8" src="https://github.com/sccn/eeglab/assets/151358030/a2b2e746-74ef-4927-a22d-ac93057d0a64">
<img width="652" alt="3f4f6bb40d6089f5838d3bb6b2308b1" src="https://github.com/sccn/eeglab/assets/151358030/01a44445-07ba-46c0-bcea-10d643f29425">
I am a novice, and eeglab encountered a problem when importing vhdr files. The conf function is using the latest version of eeglab. How can I solve this problem

**Comment by Allexxann** [comment]
Looks like a junk file from MacOSX. If so, it cannot be opened, as it is not a real datafile.

**Comment by arnodelorme** [comment]
Correct. This is not a valid .vhdr file. There should also be a .vmrk and .eeg/.dat file. Closing this for now.
