### ISSUE TITLE
Interpolating using 'spacetime' method

### ISSUE THREAD

**Issue by droe11** [eeglabdevelopers/eeglab#704]
Hi EEGLAB community, 

I am trying to interpolate EEG data back so that I can perform multivariate machine learning algorithm on the channel data. 

I have been able to successfully use the EEGOUT = eeg_interp function with the 'spherical' method.

However, whenever I try it using the 'spacetime' method I get this error: 

Unrecognized function or variable 'griddata3'.

Error in eeg_interp (line 243)
        badchansdata = griddata3(ygood, xgood, zgood, tmpdata,...

I am unsure of what this means and how to correct it. 

For the function I am currently using these specifications:  EEGOUT = eeg_interp (EEG, chans, method, t_range;

The chans = 128 electrode file that I have loaded in, the method = either 'spherical' or 'spacetime' and the t_range = [EEG.xmin EEG.xmax]. 

I would appreciate any help on this issue. 

MATLAB 2022a
EEGLAB V2023.0

Thank you, 
Dominic

**Comment by arnodelorme** [comment]
Apologies for the late response. You might be the first one to use that option in a long time (griddata3 was discontinued in 2009). I have fixed the issue in b31d183c7
This option is very very slow.
