### ISSUE TITLE
EEGLAB error in function plugin_menu()

### ISSUE THREAD

**Issue by DanielaRazo** [eeglabdevelopers/eeglab#706]
### Description

[*Description of the bug or feature
Attach a link to Dropbox or Google Drive with screenshots and your data if possible.*]

<br>
![Error](https://github.com/sccn/eeglab/assets/152453495/5e55422f-c758-4bdc-88a3-669e78d73dfe)

#### Steps to Reproduce

1. [*First Step*]
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
Unrecognized field name "downloads"

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by AminAlam** [comment]
Are you trying to install a new plugin? Please indicate the version of EEGLABas well.

**Comment by DanielaRazo** [comment]
> Are you trying to install a new plugin? Please indicate the version of EEGLABas well.


Yes, EEGLAB loads normally but when I want to install a new plugin that appears. I have the latest version, 2023.1

**Comment by AminAlam** [comment]
I've tried this and it works with Matlab 2023b and EEGLAB 2023. Based on how the plugin struct is made [here](url), this error shouldn't be raised. Can you please mention the exacts steps which result in this error?

**Comment by arnodelorme** [comment]
I am closing this for now. Let us know if the error can be reproduced and how.
