### ISSUE TITLE
can not save a simple study

### ISSUE THREAD

**Issue by user00066** [eeglabdevelopers/eeglab#708]
<br>
#### Expected behavior:
[*What you expected to happen*]
After I finished a simple study, I cannot save it. I am sure that I didnot use specail symbols, including spaces, etc. And the codes seem right (show below)
![图片5](https://github.com/sccn/eeglab/assets/153261666/129b9425-9d69-4647-8b95-e608d4e9c496)

<br>
#### Actual behavior:
[*What actually happened*]
Reading subjects' data or looking up measure values in EEGLAB cache.
Plotting data using axis size [0.039,0.06]
Plotting all channel...
Press OK to close plotting interface and save the STUDY
If you press CANCEL, the whole STUDY will be lost.
Done.

|   |   |
|----| ---- | 
| OS version     | [*Windows 10*] |
| Matlab version | [*2023*] |
| EEGLAB version | [*v9.10*] |

**Comment by arnodelorme** [comment]
This is usually due to MATLAB permission problems. MATLAB may not be authorized to write into that folder even if you are as a user. Try saving another file with MATLAB in that folder. Closing for now, but feel free to reopen.

**Comment by user00066** [comment]
您好，来信已收到，我会尽快给您回复，谢谢，辛苦啦                                                        ——聂帅
