### ISSUE TITLE
Suggestions for EEGLAB from ERP visualization study

### ISSUE THREAD

**Issue by vladdez** [eeglabdevelopers/eeglab#712]
Dear developers, 
In early 2023, we conducted a user experience study on ERP visualization tools. The main focus was on understanding how practitioners use ERP visualizations, but we also collected tool-specific feedback. 
For each plot type in our study, we asked users to provide challenges and potential improvements for the toolbox they last used. The raw responses for your toolbox and general feedback for ERP visualization are attached in the following CSV files.
We further provide user preferences, and some discussion and recommendations on ERP plotting in our preprint [1], which might be of interest as well. We are very open to comments and critiques, please use any of the following contacts to reach out. 
Note that in some cases the first column includes other tool names too, because people had the same issue with multiple tools.
[vladimir.mikheev@vis.uni-stuttgart.de](mailto:vladimir.mikheev@vis.uni-stuttgart.de)
[benedikt.ehinger@vis.uni-stuttgart.de](mailto:Benedikt.Ehinger@vis.uni-stuttgart.de)
[1] doi: https://doi.org/10.1101/2023.12.20.572507
[eeglab.csv](https://github.com/sccn/eeglab/files/13752055/eeglab.csv)
[general_feedback.csv](https://github.com/sccn/eeglab/files/13752056/general_feedback.csv)

**Comment by arnodelorme** [comment]
Thank you Vladimir @vladdez and apologies for the late reply (I have seen this before though ;-). It will take time to process all of that data.

- Use intuitive names for functions.

We try

- Make scientific color maps the default option.

Yes, we plan to replace HSV with TURBO. This is the plan for EEGLAB 2024.1 

- Make upward polarity notation the default option.

Default in EEGLAB

- Encourage users to give labels to topoplots which indicate whether a single time-point or an average of time-ranges is used (e.g. using the range bracket notation).

Topoplot labels are usually set by default in EEGLAB to indicate these options.

- Make error bars and error ribbons easy to use and nudge users to always include them.

I do not think this is relevant for EEGLAB.

- Use plotting backends that allow for flexible customization by the users.

Yes, EEGLAB options have many many options (especially from the command line)

- Ensure the plots can be made reproducible, especially if the users can edit them via a GUI.

Yes, EEGLAB writes its own history making plot easily reproducible.
