### ISSUE TITLE
ICLabel ERROR

### ISSUE THREAD

**Issue by Qianxi0313** [eeglabdevelopers/eeglab#716]
### Description

Hi, everyone. I am getting the following error when using ICLabel. 
<img width="299" alt="截屏2024-01-15 21 13 42" src="https://github.com/sccn/eeglab/assets/138086835/93b56833-81f0-43eb-8961-d75dba5b8cfc">

ERROR：
<img width="827" alt="截屏2024-01-15 21 15 35" src="https://github.com/sccn/eeglab/assets/138086835/9249baa8-c258-4ee6-8c8a-62d587748d90">

I tried it on two computers. Mac used the Matlab 2021 with 2023EEGLAB, and Windows used the Matlab 2023 equipped with 2023 EEGLAB. They all encountered the same problem.

Anyone has ideas of how to fix it? Thanks a lot.

**Comment by arnodelorme** [comment]
Yes, you need the signal processing toolbox, unfortunately. The simplest option is to purchase it from Mathworks or to use the compiled version of EEGLAB where it is not needed.
