### ISSUE TITLE
Problem with ICA MARA in Automagic toolbox 

### ISSUE THREAD

**Issue by cg091** [eeglabdevelopers/eeglab#717]
Hello all,

We are pre-processing some EEG data and we encountered a problem doing ICA MARA in the Automagic toolbox.  We are using the cap AntNeuro NA-261. The problem arises when the software uploads the cap's channel file in the '.xyz' format. Automagic fails to recognize the channel file, even when the file is extracted directly from the other software Brainstorm. The error message is depicted in the attached figure. 
[https://drive.google.com/file/d/1LLs_r24j1zI-n_axIArAxwKTNvnmcOB0/view?usp=drive_link](url)

We are reaching out to seek assistance in finding a potential solution. The software functions well with different caps, and we have not yet identified how to resolve the current issue.

**Comment by arnodelorme** [comment]
I do not have a solution to propose. You might want to convert the channel coordinate to a format that MARA can process.
