### ISSUE TITLE
Variable epoching with custom code

### ISSUE THREAD

**Issue by carrie372** [eeglabdevelopers/eeglab#718]
I used custom scripts to do variable epoching from -200-ms from start of trial to time of response. However, the eeglab interface is not registering this information (epochs not updating when running "eeglab redraw"), trials are not recognized, and plotting functions no longer work. My coding is correct in terms of pulling events, calculating the epoch duration, etc.

Any ideas on how to fix this? Attached are outputs of EEG.event and EEG.epochs after running the attached code.

![Screen Shot 2024-01-18 at 11 19 45 AM](https://github.com/sccn/eeglab/assets/157049734/58b15ec0-e08e-4274-babd-dddbf4817ac8)
![Screen Shot 2024-01-18 at 11 21 01 AM](https://github.com/sccn/eeglab/assets/157049734/9418f369-9c98-4535-91eb-8eb67509bc46)
![Screen Shot 2024-01-18 at 11 22 53 AM](https://github.com/sccn/eeglab/assets/157049734/7d8774bb-b908-4f20-adab-73e1e1ed46fa)

_Originally posted by @carrie372 in https://github.com/sccn/eeglab/issues/652#issuecomment-1898919477_

**Comment by arnodelorme** [comment]
EEGLAB cannot create epochs of different lengths (although you can create discontinuities to do that artificially). To create variable of different length, you might want to try Fieldtrip.
