### ISSUE TITLE
help me reduce the numbers of channels edf

### ISSUE THREAD

**Issue by amcornea** [eeglabdevelopers/eeglab#719]
### Description
I am new to eeglab and I can not reduce the number of channels - this would my my first problem
I need to remove the artefact the interfere with the eeg signal.

<img width="1008" alt="Screenshot 2024-01-19 at 21 39 38" src="https://github.com/sccn/eeglab/assets/52606587/b5717620-6327-4507-9cac-fe5c00e0f544">

**Comment by amcornea** [comment]
please help me with this.
thank you

**Comment by arnodelorme** [comment]
To reduce the number of visible channels, you can use the EEGPLOT menu "Settings > Number of channels to display." I hope this helps.
