### ISSUE TITLE
Downloading EEG Lab Compiled to a Mac running Sonoma 14.2.1

### ISSUE THREAD

**Issue by SNAPLAB12** [eeglabdevelopers/eeglab#721]
### Description
I am not able to download the EEG Lab compiled software because my mac says it is not able to determine if it contains malware. I have tried several times and keep getting the same message. Is there a way around this?

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Sonoma 14.2.1 |
| Matlab version | n/a |
| EEGLAB version | current EEG lab compiled version |

**Comment by arnodelorme** [comment]
Yes, this is annoying. There is downloading and executing. This is the direct link https://sccn.ucsd.edu/eeglab/currentversion/eeglab_compiled_macos.zip I tried downloading it on my MAC and it was ok.

**Comment by SNAPLAB12** [comment]
Good morning,

Thank you for the link. I tried it with the same result. Please find a screen shot of what happened attached.

I am not sure if there is something I need to change in settings. This has never happened to me before. I tried downloading with Brave, as well as Google Chrome to see if there would be a difference, but unfortunately to the same result both times.

Thanks!


________________________________

**Comment by arnodelorme** [comment]
There is no real way around that except to disable some security on your MAC.
