### ISSUE TITLE
ICLabel error on Linux (default option)

### ISSUE THREAD

**Issue by tadeshi88** [eeglabdevelopers/eeglab#722]
ICLabel is not working on Linux with the default option, resulting in the below error.
 
![image](https://github.com/sccn/eeglab/assets/157595919/d49a0729-74ff-4474-9177-03196ad30dc3)

The ICversions Lite/Beta functions seamlessly. All ICversions worked on two Windows machines I tested with identical Matlab/EEGLab versions. Thus, likely a Linux-specific issue.

The issue is within the following Matlab function:
 Matlab2023b/toolbox/signal/signal/+signal/+internal/+resample/uniformResample.m
An associated workspace has been saved to aid in debugging. The code execution is interrupted just before the line causing the crash.

[workspace.zip](https://github.com/sccn/eeglab/files/14037475/workspace.zip)

Versions

![image](https://github.com/sccn/eeglab/assets/157595919/72cee196-bccd-4601-bba8-34dcce855f48)
EEGLAB v 2023.1

**Comment by arnodelorme** [comment]
We primarily use Linux (although not Ubuntu - CentOS) and have no problem with ICLabel. Can you share your dataset with ICA weights prior to running ICLabel?

**Comment by tadeshi88** [comment]
Thanks for your response.

I've encountered the reported issue while working with the BrainBeats tutorial, using a sample dataset from their repository https://github.com/amisepa/BrainBeats/tree/v1.4/sample_data

To replicate the error, I loaded the specified file and performed ICA decomposition using:

EEG = pop_loadset; 
and
EEG = pop_runica(EEG, 'icatype', 'picard', 'maxiter', 500);
 
Without any additional processing, the data results in a substantial number of components. However, this is not the cause of problem, as the same process works on another system or on my Ubuntu with a different IC version.

The dataset after importing and ICA decomposition, but before running ICLabel, is under the following Google Drive link:
[Dataset Link](https://drive.google.com/drive/folders/1vSuVx7X9FJ44_m6R0wBzsDGdRpBFIPkX?usp=drive_link)

As a temporary workaround, I have adjusted the default ICLabel option to "beta," which allows both ICLabel and BrainBeats to function correctly.

**Comment by arnodelorme** [comment]
@amisepa can you pitch in? Does this dataset has EEG?

**Comment by amisepa** [comment]
We have already exchanged a few emails about this strange issue and I thought it might be a Linux issue since it works with on Windows and Mac. If this is the sample dataset from BrainBeats, it contains  64 EEG channels, 1 ECG channel and 1 PPG channel. BrainBeats automatically deals with the heart ones. Did you remove them here?

**Comment by amisepa** [comment]
I loaded the file, there are only the 65 EEG channels, as expected. However, the ICA weights are not there, suggesting you did not run ICA (or at least you did not save the file after running it):
![image](https://github.com/sccn/eeglab/assets/58382227/b69c5647-aeab-4091-b153-605b74fbd0cc)

**Comment by amisepa** [comment]
I ran ICA and ICLabel worked fine. Not sure what the issue could be.

**Comment by arnodelorme** [comment]
Strange. Let’s close the issue and reopen it if we get more insight as to what the problem might be.

**Comment by arnodelorme** [comment]
Strange. Let’s close the issue and reopen it if we get more insight as to what the problem might be.

**Comment by tadeshi88** [comment]
Thank you for your help. I've recently transferred the work to another machine, where it works. Our Linux server hosts a variety of plugins, some of which may be outdated. I suspect this might be the root of the issue. I will investigate and keep you informed once I've successfully identified the problem.
