### ISSUE TITLE
Bug ERSP without baseline correction

### ISSUE THREAD

**Issue by meyiduleme** [eeglabdevelopers/eeglab#723]
### Description

[*I am using the GUI popchanplot() to plot ERSP measures. I have a study with 13 conditions and 50 participants. Data has been properly precomputed. I have the last version of EEGLAB (and try to fix the bug dowloading the eeglab-develop from github). When I plot ERSP , I get the following Warning:"Warning: std_readdata ignored at least one parameters: "subbaseline"" Then I have several plots displayed, without baseline correction. How can I obtain the ERSP plots with baseline correction? writing code or using the GUI*]

<br>
#### Steps to Reproduce

1. [*Open eeglab*]
2. [*Load Existing study*]
3. [*Precompute channels measure (default parameters)*]
4. [*Plot channel measures*]
5. [*All subjects, plot ERSP for one electrode,"Plot channels individually", default parameters*]

<br>
#### Expected behavior:
[*ERSP plotted with baseline correction*]

<br>
#### Actual behavior:
[*ERSP without baseline correction. "Warning: std_readdata ignored at least one parameters: "subbaseline""*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*2023b*] |
| EEGLAB version | [*2023.1*] |

**Comment by arnodelorme** [comment]
To perform baseline corrections in a study, you need to change the plotting options. STUDY = pop_erspparams(STUDY) or use the graphic user interface.
