### ISSUE TITLE
pop_comments overwrites EEG variable

### ISSUE THREAD

**Issue by grivlis** [eeglabdevelopers/eeglab#724]
### Description

pop_comments overwrites the EEG variable with the comments even choosing 'Cancel'

<br>
#### Steps to Reproduce

1. Start eeglab
2. File->Load existing dataset
3. choose eeglab_data.set from the sample_data subdir and click open
4. Edit->About this dataset
5. click 'Cancel'
6. notice that the EEG variable in the workspace has now changed; it contains the comments

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment]
Thank you. This has been fixed in 88010d0a2
