### ISSUE TITLE
pop_importepoch error

### ISSUE THREAD

**Issue by carrie372** [eeglabdevelopers/eeglab#725]
### Description

Trying to import epoch info following the instructions [linked](https://eeglab.org/tutorials/04_Import/Importing_Event_Epoch_Info.html#importing-epoch-info-matlab-array-or-text-file-into-eeglab) from EEGLAB tutorial. I get the error "There must be as many field names as there are columns in the file/array, This is not a bug (Error occurred in function pop_importepoch() at line 252)"

<br>
#### Steps to Reproduce

1. [load data set]
2. [import epoch]
3. [enter information as instructed]

sample data file for epoch to import
![datasetsample](https://github.com/sccn/eeglab/assets/157049734/07c074e5-c9cc-4f93-9408-27a7b11ebc31)

pop_importepoch window and what I input into the GUI
![pop_importepoch](https://github.com/sccn/eeglab/assets/157049734/809a8a3c-52a0-4562-9ab8-60620ab3ec52)

<br>
#### Expected behavior:
[epochs to be imported]

<br>
#### Actual behavior:
[error message described above]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [MacOS 10.15.7 and Windows 11 22621.3007] |
| Matlab version | [2023a and 2023b] |
| EEGLAB version | [2023.1] |

**Comment by arnodelorme** [comment]
If you get an error that the number of trials do not match the number of trials in the EEG dataset, you might want to look at your dataset (how many epochs in this dataset) and the file you are trying to import (how many rows). I have checked that the tutorial data can be imported. I am closing this for now but feel free to reopen.

**Comment by carrie372** [comment]
I have checked this and they are the same amount.

**Comment by arnodelorme** [comment]
There should be one more row in the text file (because of the header). Is that the case?

**Comment by carrie372** [comment]
yes
