### ISSUE TITLE
@arnodelorme when I follow the tutorial I end up with two Cz channels. One for channel 24 and the new one appended in channel locations.

### ISSUE THREAD

**Issue by carrie372** [eeglabdevelopers/eeglab#727]
@arnodelorme when I follow the tutorial I end up with two Cz channels. One for channel 24 and the new one appended in channel locations.

_Originally posted by @carrie372 in https://github.com/sccn/eeglab/issues/614#issuecomment-1932692502_

**Comment by LukeCepza** [comment]
I think it is because Cz is an offline reference on your EEG system. Online references doesn't show up in eeg records because reference is already applied. Offline you would have to reference first to Cz, then Cz would dissapear from channel list. Afterwards (i guess) you would add again Cz and re-reference to scalp average. Please also share more details on your issue :)

**Comment by carrie372** [comment]
"Offline you would have to reference first to Cz, then Cz would dissapear from channel list. Afterwards (i guess) you would add again Cz and re-reference to scalp average." What are the steps for this in EEGLAB? 

"Please also share more details on your issue" Can you please specify the details you would like? Below is a screenshot of vhdr file with Cz listed as reference. 
<img width="833" alt="Screenshot 2024-02-08 131711" src="https://github.com/sccn/eeglab/assets/157049734/f0a933c8-1cf7-4cb4-b210-0c75e28f3e66">

**Comment by LukeCepza** [comment]
In the GUI you would do something like this

Specify reference Cz:
![image](https://github.com/sccn/eeglab/assets/29745762/f770d790-dccb-490a-a357-37cfd0113236)

Compute scalp average reference and recover Cz reference.
![image](https://github.com/sccn/eeglab/assets/29745762/40afc037-914b-4ce1-86bc-0396c2f86ee8)

However, I'm pretty sure it is equivalent as just doing scalp average reference. I think it would be better just to reference to Cz first, and then scalp average without trying to recover Cz as this helps to increase SNR.

Hope this helps :)

**Comment by carrie372** [comment]
Thank you!!!

**Comment by arnodelorme** [comment]
Thank you Luke for assisting Carrie.
