### ISSUE TITLE
ICA components removal

### ISSUE THREAD

**Issue by Angqi-Li** [eeglabdevelopers/eeglab#729]
### Description
I don't know why everytime I do remove the components from the data and to remove the components already flagged and click on 'yes'. It will stuck most of the time, I need to force quit matlab everytime. Please help! thanks in advance.

<br>
#### Steps to Reproduce

1. Do ICA decomposion and inspect the components
2. And reject the one as marked
3. Remove the components from the data 

<br>
#### Expected behavior:
will show up 'Comfirmation' window to plot single trials and comfirm the removal

<br>
#### Actual behavior:
 when remove from data window shows up, click 'yes'. Most of the time it will stuck. I need to force quit matlab to stop it.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | *macos sonoma 13.5* |
| Matlab version | *matlabR2023b* |
| EEGLAB version | *eeglab2023.1*|

**Comment by arnodelorme** [comment]
Yes, this is not the expected behavior. However, without being able to reproduce the problem, there is little we can do.
