### ISSUE TITLE
std_readfile error when making ersp plots

### ISSUE THREAD

**Issue by markpayumo** [eeglabdevelopers/eeglab#737]
### Description

Hi, I’m trying to plot and extract ersp data from precomputed measures in STUDY design with the following code: `[STUDY, erspdata, ersptimes, erspfreqs] = std_erspplot(STUDY,ALLEEG, 'channels’,{‘E1’,’E2’,…});`

However, I get the following error:

```
Reading all ERSP data:..
Error using std_readfile
Cannot use file to lookup channel names, the file needs to be recomputed

Error in std_readersp (line 289)
                                 erspbase{c, g}                             = std_readfile( setinfo(setinds{c,g}(:)), 'measure', 'erspbase', opts{:});

Error in std_erspplot (line 230)
    [STUDY allersp alltimes allfreqs tmp events unitPower] = std_readersp(STUDY, ALLEEG, 'channels', opt.channels, 'infotype', opt.datatype, 'subject', opt.subject, ...
```

I found this [thread](https://sccn.ucsd.edu/pipermail/eeglablist/2015/009488.html) about a similar error and made sure the all the channel names are consistent across subjects, but I’m still getting this error.

<br>
#### Steps to Reproduce

1. Load STUDY design
2. From GUI, Study > Precompute channel measures > check ERSP > input parameters: `'cycles', [13 30], 'nfreqs', 100, 'freqs', [13 30],'freqscale', 'linear','ntimesout', 250, 'baseline', [1000 2000]`
3. Extract ersp data with following code:` [STUDY, erspdata, ersptimes, erspfreqs] = std_erspplot(STUDY,ALLEEG, 'channels’,{‘E1’,’E2’,…});`

<br>
#### Expected behavior:
Produce ERSP plots and extract erspdata

<br>
#### Actual behavior:
Get std_readfile error

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Sonoma 14.2.1 |
| Matlab version | MATLAB R2023a |
| EEGLAB version | v14.1.2* |

*separate issue but I use an old version because more recent versions (EEGlab2023) has given me weird-looking ersp plots similar to [this](https://github.com/sccn/eeglab/issues/389 )

**Comment by arnodelorme** [comment]
The error indicates to recompute the file. Can you try that?

**Comment by markpayumo** [comment]
Thanks Arnaud- this worked! I noticed that some of the participants did not have a design .datersp file even though they were present in the STUDY and EEG structure. They must have been missed somehow in the initial precomputation, so I just recomputed those specific files and the erspdata could be read
