### ISSUE TITLE
Importing .EEG

### ISSUE THREAD

**Issue by Faqani1993** [eeglabdevelopers/eeglab#738]
### Description

I wanted to import my egg file from **Neuroscan .EEG file** plugin, but I received the error. 

EEG lab error  in function loadeeg() at line 253.
Unrecognised function or variable 'chann_names'.

<img width="491" alt="Screenshot 2024-02-28 at 10 32 28 pm" src="https://github.com/sccn/eeglab/assets/83502082/bf540e3a-5f1c-40d6-a256-a370224a70b4">

| OS version     | [MacBook Pro 2023 version 13.5 |
| Matlab version | [R2023b] |
| EEGLAB version | [v2023.1] |

**Comment by arnodelorme** [comment]
Are you sure it is a Neuroscan file? Can you share the file?

**Comment by Faqani1993** [comment]
> Are you sure it is a Neuroscan file? Can you share the file?

My data is in EEG format. 

https://1drv.ms/u/s!AmRplatHNX8NaycgjGdjBKpDcLg?e=a1nftH

Thank you.

**Comment by Faqani1993** [comment]
> Are you sure it is a Neuroscan file? Can you share the file?

I recorded the EEG signals with an MITSAR amplifier and WINEEG software.

**Comment by arnodelorme** [comment]
Yes, this is not neuroscan. You need to export to EDF from WINEEG (reload the .eeg file in WINEEG and export it as EDF). Best

**Comment by Faqani1993** [comment]
Thank you so much.
