### ISSUE TITLE
problem in MicrostatesLab

### ISSUE THREAD

**Issue by SilviaC12345** [eeglabdevelopers/eeglab#744]
Help me, 
When I study microstates with MicrostateLab, in EEGlab.

I have some problems including this one.  which occurs when I study the "plot temporal dynamic", of microstates.
![image](https://github.com/sccn/eeglab/assets/163135222/847dcab4-2ebd-4d5c-b6c5-584316247168)
![image](https://github.com/sccn/eeglab/assets/163135222/24a58be9-d1bf-414f-af01-ccdc1a9d5efb)

Can you help me understand how this is solved?

Furthermore, I don't know how I can segment a 3 minute resting dataset with eeglab, for the study of microstates. I should cut it into smaller sets. Can you help me with this too?
Greetings

<br>
#### Expected behavior:
[*What you expected to happen*]

<br>
#### Actual behavior:
[*What actually happened*]

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*fill in*] |
| Matlab version | [*fill in*] |
| EEGLAB version | [*fill in*] |

**Comment by arnodelorme** [comment]
This is an EEGLAB plugin and so the issue has to do with the plugin itself. I suggest you contact the plugin authors.
