### ISSUE TITLE
`in set file` should be movd to EEG.datfile

### ISSUE THREAD

**Issue by neuromechanist** [eeglabdevelopers/eeglab#746]
Concerning an issue with loading EEGLAB SET files in MNE-Python, when `EEG.data` does not point to the FDT file, I think the problem seems to root from the following lines:

https://github.com/sccn/eeglab/blob/f3570debd4a50f85f135fd27c50ca0e062fb60d1/functions/popfunc/pop_loadset.m#L146
https://github.com/sccn/eeglab/blob/f3570debd4a50f85f135fd27c50ca0e062fb60d1/functions/popfunc/pop_loadset.m#L152

Line 144 overwrites `EEG.data` if `EEG.data` is not **numeric**. But if EEG.data is not numeric, why should it be replaced with the `in set file` flag? And more importantly, where is the data?

Line 152 also poses a similar question. If `EEG.datfile` does not exist or is empty, `EEG.data` is overwritten with the `in set file` flag.

In both cases, it seems that the `EEG.datfile` should have been overwritten with the flag, not the `EEG.data`.

Overall, since this is only under `info` reading mode, which is not the default mode, and since there is another check for this flag a few lines down, leaving it as is should not cause much problem. The problem will be if the user loads the data in the `info` mode and saves the file right away (likely directly using Matlab, very unlikely).

**Comment by arnodelorme** [comment]
This is for a load mode 'info' where the data stays on disk. I have looked at the lines but they seem OK. 

There was a bug I fixed 6 months ago about ‘in set file’ and FDT file. I believe EEGLAB reads these files OK although they probably should be exported again for other software.

Closing this for now, but feel free to reopen.

I have also created an issue about ds003645

https://github.com/sccn/NEMAR-pipeline/issues/70
