### ISSUE TITLE
FIF file orientation

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#747]
The exported file

https://nemar.org/dataexplorer/detail?dataset_id=ds003645

This is the original data

https://openneuro.org/datasets/ds000117/versions/1.0.5

**Comment by arnodelorme** [comment]
I have checked and it is correct. The script should be run again maybe to generate ds003645

**Comment by dungscout96** [comment]
So my understanding is that I should run the export script again without any modifications?
