### ISSUE TITLE
I can not locate the channels

### ISSUE THREAD

**Issue by andreaeugeniolosi** [eeglabdevelopers/eeglab#748]
### Description

Simply after I import the data and try to locate the channels the error I attached to this report pops up.

#### Steps to Reproduce

1. File/Import data
2. Edit/ Channel locations

![thumbnail_image](https://github.com/sccn/eeglab/assets/59801491/34f196eb-eb99-41a7-b0af-9e8935eb10ba)

#### Versions

| Windows version     | 11 |
| Matlab version | R2023b|
| EEGLAB version | latest |

**Comment by arnodelorme** [comment]
This is likely because you clone this repository without submodules.
