### ISSUE TITLE
warning "at least two versions of EEGLAB in your path"

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#752]
I get this warning even though there is only one eeglab is installed and added to the path. 

![Screenshot 2024-03-25 125908](https://github.com/sccn/eeglab/assets/58382227/ce3e0a53-5d66-4cb5-92d3-f2bb32e193e0)

**Comment by arnodelorme** [comment]
Can you pull the changes and let me know if there is still an issue?

**Comment by amisepa** [comment]
still there

**Comment by arnodelorme** [comment]
Try again now (there was a connectivity issue).

If it still does not work, after making sure, you are not in the EEGLAB path
Can you try

tmp = fileparts(which(‘eeglab’));
rmpath(tmp)
which(‘eeglab’)

The second one should be empty

**Comment by amisepa** [comment]
that last pull worked ;)

**Comment by arnodelorme** [comment]
OK super.

**Comment by amisepa** [comment]
Thanks!

**Comment by arnodelorme** [comment]
No thanks to you for reporting it 😁
