### ISSUE TITLE
pop_saveset asks for string, only accepts char arrays

### ISSUE THREAD

**Issue by Luke-Acuff** [eeglabdevelopers/eeglab#756]
### Description

The pop_saveset function returns an error "error: argument 'filename' must be a string" despite the argument being a string. Looking into the source code, the 'finputcheck' EEGLAB function checks if the input is a string at line 213 by assessing tmpval with 'ischar; which checks for char arrays, not strings. If a char array is desired, the case and error message should return and ask for a char array, not a string. If a string truly is desired, 'isstring' should be used in place of 'ischar'.

<br>
#### Steps to Reproduce

1. Load eeglab
2. Load EEG data as EEG
3. Run the following line of code
4. pop_saveset(EEG, 'filename', "test");

<br>
#### Expected behavior:
For pop_saveset to save EEG when the 'filename' argument is a string.

<br>
#### Actual behavior:
pop_saveset throws "error: argument 'filename' must be a string" 

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 10 Enterprise|
| Matlab version |2023b|
| EEGLAB version |2024a|

**Comment by arnodelorme** [comment]
This is because "test" is different from 'test' 
This has been fixed in c9050116f
Thank you for reporting the problem
