### ISSUE TITLE
Bug report: std_erspplot function when drawing 2 by 2 conditions using channel data

### ISSUE THREAD

**Issue by sato16** [eeglabdevelopers/eeglab#758]
Dear EEGLAB manager,
Thank you for developing and maintaining a great toolbox. I may be wrong but I found a bug in  std_erspplot function so I would like to share the information.  

### Issue
When I try to plot ersp topomap in channel data at 2 by 2 conditions, the plot of statistical results seems incorrect. In addition, this bug may relate to https://sccn.ucsd.edu/pipermail/eeglablist/2022/016748.html

### Reproducing bug
I reproduced the bug by using 5-subject experiment tutorial data, so I attached mlx file.
[plot_ERSPtest_2by2.mlx.zip](https://github.com/sccn/eeglab/files/14981071/plot_ERSPtest_2by2.mlx.zip)

### Cause of the bug
The solution seems to pass stat.effect as argument. In particular,  [*line 391 in std_erspplot.m*]  should be changed as below
- before:
 ```
std_chantopo(allersp, 'groupstats', pgroup, 'condstats', pcond, 'interstats', pinter, 'caxis', opt.caxis, ...
 'chanlocs', locs, 'threshold', alpha, 'titles', alltitles);
```
- after:
```
 std_chantopo(allersp, 'groupstats', pgroup, 'condstats', pcond, 'interstats', pinter, 'caxis', opt.caxis, ...
'chanlocs', locs, 'threshold', alpha, 'titles', alltitles, 'effect', stats.effect);
```

### Versions
|   |   |
|----| ---- | 
| OS version     | [*mac Monterey version 12.6*] |
| Matlab version | [*matlab 2023b*] |
| EEGLAB version | [*EEGLAB 2024.0*] |

I hope this will be useful to you.
Best regards,
 Fumiaki Sato

**Comment by arnodelorme** [comment]
Good catch. Thank you for reporting the issue. This has been corrected in 98ad62028
