### ISSUE TITLE
Error loading channel locations from Brainstorm .mat file 

### ISSUE THREAD

**Issue by mahmad27** [eeglabdevelopers/eeglab#761]
### Description

I'm trying to import the channel locations from a '.mat' Brainstorm file within EEGLAB for a single participant. When using the readlocs() function, I get an error. I'm using the Leipzig Study for Mind-Body-Emotion Interactions (LEMON) data for participant 'sub-010291' and the EEG data can be accessed from [here](https://ftp.gwdg.de/pub/misc/MPI-Leipzig_Mind-Brain-Body-LEMON/EEG_MPILMBB_LEMON/EEG_Raw_BIDS_ID/sub-010291/RSEEG/) as a BrainVision file and the channel locations can be accessed from [here](https://ftp.gwdg.de/pub/misc/MPI-Leipzig_Mind-Brain-Body-LEMON/EEG_MPILMBB_LEMON/EEG_Localizer_BIDS_ID/sub-010291/).

#### Steps to Reproduce

1. Load BrainVision EEG files for sub-010291 (from LEMON dataset)
2. Load channel locations from Brainstorm file (sub-010291.mat)

#### Expected behavior:
Channel locations loaded successfully

#### Actual behavior:
EEGLAB error in function readlocs at line 423:
Unrecognized function or variable 'elocBrainstrom'.

#### Versions

|   |   |
|----| ---- | 
| OS version     | macOS Sonoma 14.3 |
| Matlab version | R2023b |
| EEGLAB version | 2024.0* |

**Comment by arnodelorme** [comment]
There was a minor glitch with the readlocs function to read this kind of file. Now fixed in 7fad5e6b8

```
readlocs('sub-010291.mat')
readlocs(): 'mat' format assumed from file extension

ans = 

  1×63 struct array with fields:

    labels
    X
    Y
    Z
    type
    sph_theta
    sph_phi
    sph_radius
    theta
    radius
    sph_theta_besa
    sph_phi_besa
```
