### ISSUE TITLE
Help for source localization

### ISSUE THREAD

**Issue by Clem-Bt** [eeglabdevelopers/eeglab#763]
Hi, 

I want to use source localization in eeglab to analyse my data from 256 channels.
I'm trying to use DIPFIT as follows:

1. Tools > Source localization using DIPFIT > Distributed Source component modeling

The aim is to compare brain activity between two groupes during a motor imagery task.
However, I always have this error: 

EEGLAB error un function double_dpss() at line 362:

Undefined function 'dpss' for input arguments of type 'double'

Can someone help me please?

Thanks a lot!

| Matlab version | [R2024a] |
| EEGLAB version | [v2024.0] |

**Comment by arnodelorme** [comment]
This is because you do not have the signal processing toolbox. It is required for this application. I have updated the function to provide a better error message.
