### ISSUE TITLE
error in ICA

### ISSUE THREAD

**Issue by Tlynnnn** [eeglabdevelopers/eeglab#769]
### Description
EEGLAB error in function runica() at line 841:错误使用runicaUSER ABORT
How can I deal with the problem?
![屏幕截图 2024-04-30 144156](https://github.com/sccn/eeglab/assets/130028155/ed55b680-f272-4ecd-a126-91a1412c68bb)

**Comment by arnodelorme** [comment]
This is likely because you pressed the button to interrupt ICA. Simply do not press the button and let ICA finish would be my advice.
