### ISSUE TITLE
clean_artifacts distance error

### ISSUE THREAD

**Issue by karhei** [eeglabdevelopers/eeglab#77]
### Description
EEGLAB2019:
using clean_artifacts with ASR / BurstCriterion will lead to an error in line 230 of clean_artifacts.m: 
    if ~strcmpi(distance, 'euclidian')    
which loads Matlab's distance function.

| Matlab version | [2016a] |
| EEGLAB version | [2019_1] |

**Comment by umarshahdin** [comment]
i'm also facing the same issue could you please tell me how to solve this issue

**Comment by arnodelorme** [comment]
I have issue a new version 2.1. Let me know if it works for you (you can access it through the plugin manager - if it does not, please submit a new issue directly to the clean_rawdata repository https://github.com/sccn/clean_rawdata/issues).

**Comment by umarshahdin** [comment]
Hi @arnodelorme,
It’s working properly now.

I want you to make a video session on ASR which is not available on your youtube channel. Could you please do this?
It’s a kind request.

Thank you
Umar.

**Comment by arnodelorme** [comment]
Yes, I will try to do that before the end of the year.
