### ISSUE TITLE
Study: Clearing

### ISSUE THREAD

**Issue by nicalbee** [eeglabdevelopers/eeglab#770]
### Description

After importing a BIDS dataset as a STUDY, when cases are cleared from the STUDY, they remain in STUDY.design.cases.value (possibly other variables). This means that an error comes up at line 248 of std_readdata further down the pipeline as the subjectList (created on line 154 of std_readdata) doesn't have a matching file (248: fileName = getfilename({STUDY.datasetinfo(datInds).filepath}, STUDY.datasetinfo(datInds(1)).subject, { STUDY.datasetinfo(datInds).session }, fileExt, length(uniqueSessions) == 1);)

<br>
#### Steps to Reproduce

1. Import BIDS STUDY folder (may occur for other Study setups - I haven't tested)
2. In the EEGLAB GUI: select 'Study' > 'Edit study info'
3. Use the 'Clear' button to remove a file or two and click 'Ok'
4. Examine the 'STUDY.design.cases.value' variable in the MATLAB command window. The cleared subject numbers remain present for me.

<br>
#### Expected behavior:
I would expect that using the 'Clear' button would remove files/participants from the Study data set at all levels.

<br>
#### Actual behavior:
Despite the row being cleared in the 'Study' > 'Edit study info' GUI, some elements of the file remain and can cause issues at later stages. For example, when plotting:

![20240507 EEGLAB std_readdata at line 248](https://github.com/sccn/eeglab/assets/8664310/256207e2-6bde-4d1d-b22d-caa90db854be)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Microsoft Windows 10 Enterprise - 10.0.19045 Build 19045|
| Matlab version | '9.13.0.2080170 (R2022b) Update 1' |
| EEGLAB version | v2024.0 |

**Comment by arnodelorme** [comment]
Thank you for reporting the problem. This has been corrected in 87f3cffd9
