### ISSUE TITLE
vis_artifacts gen_colormap error (new error)

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#773]
![image](https://github.com/sccn/eeglab/assets/58382227/eb8fcd66-fe88-4e4a-a4e2-13d060dea86e)

**Comment by arnodelorme** [comment]
Can you provide a dataset and a way to reproduce  the problem?

**Comment by amisepa** [comment]
I'm not getting it anymore...

Meanwhile, you can update the colormap in vis_artifacts with the new one :)
![image](https://github.com/sccn/eeglab/assets/58382227/d2d59f9a-a198-436f-acf3-10f0c5743971)

**Comment by arnodelorme** [comment]
These are for events. It does not matter that much.

**Comment by arnodelorme** [comment]
Closing for now. Let me know if you can reproduce the problem.
