### ISSUE TITLE
Issue when reading channel locations from Brainstorm file with empty SCS field

### ISSUE THREAD

**Issue by nguyen-td** [eeglabdevelopers/eeglab#774]
### Description

Similar to #761 but the current version throws the error `Index exceeds the number of array elements. Index must not exceed 0.` when the `elocIn.SCS` field is empty. I am trying to convert [this](https://github.com/brainstorm-tools/brainstorm3/blob/master/defaults/eeg/ICBM152/channel_BrainProducts_ActiCap_97.mat) Brainstorm chanlocs file  into EEGLAB's chanlocs format.

Extending
https://github.com/sccn/eeglab/blob/02a306cce16716ed5db85f260271c9dde7d85893/functions/sigprocfunc/readlocs.m#L426
by `if isfield(elocIn.SCS, chans{iChan}) && ~isempty(elocIn.SCS.(chans{iChan}))` will fix it. 

#### Steps to Reproduce

1. Download the Brainstorm chanlocs [here](https://github.com/brainstorm-tools/brainstorm3/blob/master/defaults/eeg/ICBM152/channel_BrainProducts_ActiCap_97.mat)
2. Run `readlocs('channel_BrainProducts_ActiCap_97.mat');`

#### Versions

|   |   |
|----| ---- | 
| OS version     | macOS Sonoma 14.3 |
| Matlab version | R2024a |
| EEGLAB version | dev |

**Comment by arnodelorme** [comment]
Thanks. This has been fixed in https://github.com/sccn/eeglab/commit/cf60b0a28aac120e45844b84437a6d203d046a67
