### ISSUE TITLE
wrong ICA label after using pop_iclabel

### ISSUE THREAD

**Issue by thchabin** [eeglabdevelopers/eeglab#777]
Hi, 

I recently experienced wrong ICA labelling after applying decomposition with runica and using then the pop_iclabel function. The decomposition seems right based on topographies and signals but it does not give the right labels.

I did not change any parameters but after moving to Windows 11 and having reinstalled eeglab it was not working well anymore.

I run this ICA on a biosemi 64 channel dataset (average ref and filtered), I checked the channel loc file which is right. Here is an example of what I get for basic vertical and horizontal eye artifacts : 

![Capture d'écran 2024-06-07 103539](https://github.com/sccn/eeglab/assets/172021165/1205db58-f5e6-4a4a-ad62-e1c07c9eba1c)
![Capture d'écran 2024-06-07 103648](https://github.com/sccn/eeglab/assets/172021165/0c62ce68-80d3-4a25-be55-b1da76b795a4)

If you have any idea of what happens, thanks for your help. 

Thibault.

**Comment by arnodelorme** [comment]
This was fixed in ICLabel 1.6. Can you update the plugin from the command line?

**Comment by thchabin** [comment]
Indeed I missed the update, the issue is fixed, thanks.
