### ISSUE TITLE
ICLabel picks up right ear sources as an eye components in eeglab2024.0

### ISSUE THREAD

**Issue by MakotoMiyakoshi** [eeglabdevelopers/eeglab#778]
See the comparison between 2022.1 (left) and 2024.0 (right.

![icLabel](https://github.com/sccn/eeglab/assets/46033589/15abd287-671f-40bb-a41f-b2588e85b092)

**Comment by KlausGramannTUB** [comment]
we observed the exact same thing and resolved the issue after reinstalling ICLabel. Let me know whether this also works for you.

**Comment by arnodelorme** [comment]
This was fixed in the newer version of ICLabel. Can you update ICLabel?

Arno

**Comment by MakotoMiyakoshi** [comment]
Arno, when I downloaded the latest version of EEGLAB, this broken ICLabel
came with it.

Makoto

**Comment by arnodelorme** [comment]
Yes, I know, but then you have a red message to update ICLabel when you start EEGLAB.

Arno

**Comment by MakotoMiyakoshi** [comment]
I disagree with your solution, but understand that the error has been
already taken care of.
I would agree with you if the red message would show "DANGER! YOU PUBLISH
THE ICLABEL RESULTS AND YOU WILL REGRET IT FOREVER" in 40 point font size.
It's because users can't know the severity of the problem the update took
care of.

Makoto

**Comment by arnodelorme** [comment]
Yes, I could overwrite it in EEGLAB 2024.0 but then some versions of EEGLAB 2024.0 would be different from others. I plan to release 2024.1 early July and then we can have a warning message in red.

Arno
