### ISSUE TITLE
Data tip error for std_itcplot.m and std_erspplot.m

### ISSUE THREAD

**Issue by sarahakhras** [eeglabdevelopers/eeglab#783]
When calling  std_itcplot.m and std_erspplot.m with plot on, I noticed the Y-axis data tip isn't accurate. Attached is an example. 
![Screenshot 2024-07-08 152236](https://github.com/sccn/eeglab/assets/37897259/c5ea6efb-5023-4495-8d51-2bdb556c2f9b)

I was trying to double-check if ITC and ERSP data extracted using std_itcplot and std_erspplot map correctly onto the plots, but the Y axis threw the results off. 

Any advice on this would be helpful! 

#### Versions
| Matlab version | [R2022a] |
| EEGLAB version | [v2024.0] |

**Comment by arnodelorme** [comment]
Yes, the data tips is linear. Best is to use a visual estimate or compute your ERSP with linear spaced frequencies.
