### ISSUE TITLE
install biosig plugin 

### ISSUE THREAD

**Issue by amisepa** [eeglabdevelopers/eeglab#785]
Just did a pull and tried to load a bdf file. When prompted to install biosig by eeglab (because it wasn't installed), I clicked Yes, and got this error.

![image](https://github.com/sccn/eeglab/assets/58382227/b59a0ed5-5a10-468d-96b6-0e26eaa9de6b)

**Comment by amisepa** [comment]
and this:
![image](https://github.com/sccn/eeglab/assets/58382227/1e2d3782-e26c-4100-b09b-2fb5fe1a0128)

**Comment by arnodelorme** [comment]
Which version of EEGLAB are you using? The development version?

**Comment by amisepa** [comment]
Yes, develop

**Comment by amisepa** [comment]
I also get this warning when I launch eeglab, even though I just did a pull on develop. Normal?

![image](https://github.com/sccn/eeglab/assets/58382227/61515c18-d993-4320-b2c3-1fdf83056fe1)

**Comment by arnodelorme** [comment]
I just removed biosig, restarted EEGLAB, then try to open a BDF, installed BIOSIG, and imported the BDF. 

Yes, warning message is OK. I am releasing version 2024.1 but it is not registered yet.

**Comment by arnodelorme** [comment]
Can you try again
- Do a pull
- Quit MATLAB
- Remove BIOSIG folder
- Start MATLAB
- Import BDF

**Comment by amisepa** [comment]
same error. I even reinstalled eeglab because I had some changes I couldn't discard.

**Comment by amisepa** [comment]
in case it's helpful, I was able to install bdf_import plugin, so the error is specific to biosig

**Comment by arnodelorme** [comment]
We would need to get on a quick call to look into that. Are you available now?

**Comment by amisepa** [comment]
solved
