### ISSUE TITLE
ICLabel bugs at EEGLAB2024.0

### ISSUE THREAD

**Issue by guangouyang** [eeglabdevelopers/eeglab#788]
### Description

Hi, I am a fan of ICLabel and I really appreciate the team's contribution.

Recently, I found that the ICLabel at EEGLAB2024.0 seems to have a bug. The ocular artifacts are mislabeled as brain signals. It appears to be a technical glitch, not from methodological parts. Hope it can fixed. I am returning to older versions (before 2023) and everything just works fine.

<br>
#### Steps to Reproduce

1. Load any EEG data, properly bandpass filter it (e.g., 1-40Hz), run ICA and ICLabel
2. Check the results and you will see clearly ocular artifacts were all labeled as other types (e.g., brain). This is not happening in 2023 version or earlier.

|   |   |
|----| ---- | 
| OS version     | na|
| Matlab version | R2024a |
| EEGLAB version | 2024.0|

**Comment by arnodelorme** [comment]
This was fixed in ICLabel 1.6. You should get a message to update the plugin when you start EEGLAB. Let us know.
