### ISSUE TITLE
Error in function tftopo() at line 324

### ISSUE THREAD

**Issue by zaeemhadi** [eeglabdevelopers/eeglab#795]
### Description

<br>
#### Steps to Reproduce

1. Inside the study --> plot channel measures, when clicking Plot ERSPs,
2. an error message pops up saying
"Undefined function 'turbo' for input arguments of type 'double'.

This is not a bug (Error occurred in function tftopo() at line 324."

<br>
#### Expected behavior:
ERSP plot should appear, which was functional in eeglab 2024.0

<br>
#### Actual behavior:
An error message pops up and an empty MATLAB figure panel without the plot.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     |Windows 10|
| Matlab version | 2019b |
| EEGLAB version | 2024.1 |

**Comment by arnodelorme** [comment]
This is because you are using MATLAB earlier than 2020. Can you edit the icadef.m function and change the default colormap to "jet" line 70.
