### ISSUE TITLE
eeg_regepoch ignores the recurrence argument if only given a recurrence argument

### ISSUE THREAD

**Issue by Luke-Acuff** [eeglabdevelopers/eeglab#798]
### Description

The eeg_regepoch function ignores the recurrence argument if only given an EEG argument and a recurrence argument key value pair. This is likely due to line 111 "if nargin < 3" failing to assign the input g.recurrence value to g.limits, even though only 3 arguments (EEG, recurrence key, recurrence value) argument should be valid. Changing to "if nargin <= 3" resolves this issue.

<br>
#### Steps to Reproduce

1. Load EEG data in eeglab
2. Run eeg_regepoch with only a recurrence argument, i.e. EEG = eeg_regepoch(EEG, 'recurrence', 2)

<br>
#### Expected behavior:
Data should be epoched into 2 second increments.

<br>
#### Actual behavior:
Observe that data is epoched into 1 second increments.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | Windows 11 Enterprise |
| Matlab version | 2024a |
| EEGLAB version | 2024.1 |

**Comment by arnodelorme** [comment]
Thank you. This was fixed in f04f6a4a2
