### ISSUE TITLE
Event codes error when imported as ASCII. 

### ISSUE THREAD

**Issue by rabhattaraiL** [eeglabdevelopers/eeglab#8]
My EEG experiment is to show a visual stimulus to the subject. The subject do not need to give any response. They just need to look at the visual stimulus.
Stimulus:
A 'red' object displayed in random position on screen for time = 1, 2, 3, 5, 6, 8, 9, 11, 13, 14, 16, 17, 18 and 20 seconds -> Standard.
A 'Blue' object displayed in random position on screen for time = 4, 7, 10, 12, 15 and 19 -> Rare
The object changes to blue 6 times in the 20 seconds experiment.
Event codes: I have created one separate file for the events. I have attached it below (March13_Trial4_eventocdes.txt'). It contains 'Type' 'Latency' and 'Duration'.
After applying 'Create EEG Eventlist', I get this output of EVENTLIST attached as (March14_Trial1_elist.txt), which is very confusing because all the ecode value is -88 making me unable to create bin descriptor for further process. Where did I go wrong ? 

[March14_Trial1_elist.txt](https://github.com/sccn/eeglab/files/2964489/March14_Trial1_elist.txt)
[March13_Trial4_eventcodes.txt](https://github.com/sccn/eeglab/files/2964491/March13_Trial4_eventcodes.txt)

**Comment by arnodelorme** [comment]
Did you import the file using menu item "File > Import events > From Matlab and ASCII" array. I have imported your file March13_Trial4_eventcodes.txt without any problem.
