### ISSUE TITLE
"Update Marks" Button not displayed when using pop_eegplot( EEG, 1, 1, 0); command

### ISSUE THREAD

**Issue by RomainGrandchamp** [eeglabdevelopers/eeglab#801]
### Description
"Update Marks" Button is not displayed when using pop_eegplot( EEG, 1, 1, 0); command

<br>
#### Steps to Reproduce

1. Start eeglab
2. Load existing dataset
3. Type pop_eegplot( EEG, 1, 1, 0); in command line

<br>
#### Expected behavior:
eegplot window should open with an "Update Marks" button in lower right corner allowing to update the continuous signal segments, or epochs, marked for rejection. 

<br>
#### Actual behavior:
eegplot window opens but there is no "Update Marks" button in lower right corner. Marked sections cannot be updated in the dataset

![eeglab](https://github.com/user-attachments/assets/db20e328-979d-47b6-8cb9-1a3b69b721fa)

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [*Windows 11*] |
| Matlab version | [*R2020b*] |
| EEGLAB version | [*v2023.1*] |

**Comment by arnodelorme** [comment]
This is because it is only for data epochs. I have updated the documentation.
