### ISSUE TITLE
dimension bug in newtimeftrialbaseln?

### ISSUE THREAD

**Issue by marcobuiatti** [eeglabdevelopers/eeglab#805]
### Description
When using newtimeftrialbaseln with option 'trialbase','full'

line 99:
"    else                           tmpbase = 1:size(P,2); % full baseline "
but second dimension of P is frequency, not time, as indicated in the function's help (lines 8-10):
% Inputs:
%   tf       - [3-D or 4-D array] single-trial spectral estimates
%           [freqs x times x trials] or [channels x freqs x times x trials)

and confirmed by line 103 where mean over time is computed:
            mbase = mean(P(:,:,tmpbase,:),3);

Therefore I think that line 99 should be replaced by:
"    else                           tmpbase = 1:size(P,3); % full baseline "

Please correct me if I misunderstood.

Best,

Marco

#### Versions

|   |   |
|----| ---- | 
| OS version     | [Windows 11 PRO] |
| Matlab version | [R2024a] |
| EEGLAB version | [v2024.2] |

**Comment by arnodelorme** [comment]
There are cases where the baseline is in the 2nd dimension like at line 110 
```
mbase = mean(P(:,tmpbase,:),2);
```
I believe that this line 
```
1:size(P,2);
```
is fine. However, if you find an example where this is not the case, by all means, reopen the bug.
