### ISSUE TITLE
Problem with Matlab/Python Fooof compatibility

### ISSUE THREAD

**Issue by tatkamen** [eeglabdevelopers/eeglab#809]
I have installed Python,  Fooof,  and Matlab wrapper for Fooof in EEGLAB, following  the instructions  here https://github.com/bfbarry/EEGLAB-specparam. 
I can see the Fooof menu from the EEGLAB GUI using  Tools > FOOOF > Fit power spectra. However, when we click ”ok” to run the power spectra, we get  one of two errors:
Error 1: EEGLAB error in function fooof() at line 0: Python commands require a supported version of CPython.
Error 2: EEGLAB error in function fooof() at line 43: Unable to resolve the bane ‘py.numpy.array’.
I am using Matlab 2023a on Mac intel64. I have tried Python versions 3.8.19, 9.9 and 9.10.14.  All combinations get one of the above errors. 
I have tried running Python within Anaconda or separately.  I have tried installing Fooof within Anaconda and directly in the Python's folder. All combinations get one of the above errors. 
Any help with the above issues would be greatly appreciated.

**Comment by arnodelorme** [comment]
Yes, I have tried that as well. This function does not seem stable. We have a new FOOOF option when computing spectrum in studies.
