### ISSUE TITLE
EEGLAB error in function pop_select_comps_AD() at line 168.The error message is that he number of input parameters was insufficien。

### ISSUE THREAD

**Issue by 346836814** [eeglabdevelopers/eeglab#811]
my version of eeglab is 13.6.5b and adjust is 1.1.1. When I ran the ADJUST plugin, I encountered an error. How can I resolve this issue?
the figure shows the error.
When I ran the ADJUST plugin, it displayed an error: 'EEGLAB error in function pop_select_comps_AD() at line 168.' The error message is that he number of input parameters was insufficien。
![image](https://github.com/user-attachments/assets/97558a19-73ad-4bb4-8066-dd493a19d37d)

there is a config figure.
 
![image](https://github.com/user-attachments/assets/7b0fbbe3-8df7-4474-9502-2c719333ed78)

firstly，i clicked the "ok" button.
![image](https://github.com/user-attachments/assets/247847b2-e65c-42e1-a50d-212b457b319e)
then,the error was coming;
![image](https://github.com/user-attachments/assets/9d05e221-8ee1-437f-b3f0-09deaf9b329c)

**Comment by 346836814** [comment]
I obtained the report.txt file, but after comparing its results with those from the IClable plugin, I believe the results after running ADJUST are problematic.

**Comment by arnodelorme** [comment]
Yes, these are two different plugins. I have not used ADJUST so I do not know how to answer. Perhaps you should contact ADJUST authors or try a more recent version of EEGLAB.

**Comment by 346836814** [comment]
Ok，I understand it.Thank you.
