### ISSUE TITLE
The requested array exceeds the maximum possible variable size

### ISSUE THREAD

**Issue by PhD-GOAT** [eeglabdevelopers/eeglab#814]
### Description

Memory error while importing EEG file?

<br>
#### Steps to Reproduce

1. impot data from Neuroscan .EEG file
2. [*Second Step*]
3. [*and so on...*]

<br>
#### Expected behavior:
Expect .EEG files to be imported.

<br>
#### Actual behavior:
![image](https://github.com/user-attachments/assets/45aa399d-1a4e-4de3-a03c-e955d66ccc69)

An error occurred while using: zeros
The requested array exceeds the maximum possible variable size.

<br>
#### Versions

|   |   |
|----| ---- | 
| OS version     | [window 11] |
| Matlab version | [R2024b] |
| EEGLAB version | [v2024.2] |

**Comment by arnodelorme** [comment]
Are you sure it is a neuroscan file? Different manufacturers use the .eeg extension.

**Comment by PhD-GOAT** [comment]
> Are you sure it is a neuroscan file? Different manufacturers use the .eeg extension.

Thank you for telling me what I missed. It is a 128-channel ActiveTwo EEG system (BioSemi), and it is an .EEG file. I installed bdfimport and tried to import it, but a format error appears.

**Comment by arnodelorme** [comment]
You might want to rename your file to BDF. ActiveTwo biosemi files are BDF files. Closing for now, but feel free to reopen.
