### ISSUE TITLE
I CAN'T EXTRACT EVENTS FROM MY .EDF FILE

### ISSUE THREAD

**Issue by Lucreziadimarino** [eeglabdevelopers/eeglab#820]
Hi, i'm a biomedical engineering student, i have to use eeglab for my thesis. I have .edf files for some subjects. For each file there is an event that underlines the end of closed eyes session and the beginning of the open eyes session. I have imported my .edf files through biosig toolboox, but i can't see the event. I have also tried to use plugin import_edf but my files are too long and i can't use it. How can i solve my problem??

![Immagine 2024-10-27 131348](https://github.com/user-attachments/assets/823a6702-06c9-4b88-9cc4-b1df3c2a8e8b)
This is the result during my attempts

**Comment by arnodelorme** [comment]
Can you share your EDF file?
