### ISSUE TITLE
Trace colors in pop_subcomp()

### ISSUE THREAD

**Issue by arnodelorme** [eeglabdevelopers/eeglab#83]
This is just a very small issue... but I've been noticing for a while that when removing components from the GUI, the figure that's generated when you choose "Plot ERPs" shows the original ERPs in red and the component-removed ERPs in blue, whereas the figure for "Plot single trials" shows the original data in blue and the component-removed in red. Is there any reason these can't be the same? (Like I said, this is not really a problem, just a very small thing; I've just noticed it a lot.)

Best,
Steve Politzer-Ahles

**Comment by nucleuscub** [comment]
Dear Steve,
When you use "plot ERPs", what is plotted is, (1) Trial ERPs with all components (blue), and (2) Trial ERPs without the components removed (2) (original message: 'Trial ERPs (blue) with and (red) without these components')).  This is consistent with the black ->original, red-> component-removed data in eegplot.
I hope I'm not missing anything here.
 Best,
R
We are closing this bug
