### ISSUE TITLE
RELAX-Jr error in EEGLab

### ISSUE THREAD

**Issue by duszewypuscil** [eeglabdevelopers/eeglab#830]
Hi

I'm trying to preprocess some EEG .BDF data with RELAX-JR pipeline. However, after I try to do so with singular .set file, I got an error:

EEGLAB error in function RELAXJr_Wrapper() at line 749:

Unrecognized function of variable 'RELAX_issues_to_check'.

I have all prerequisite toolboxes installed (as far as I know) and it all should be working. Changing HEOG channels or leaving them as they are by default does change nothing. 
Please advice :)

(also my first time asking for help on github, if I did something incorrect - please don't yell, just advice :)

|   |   |
|----| ---- | 
| OS version     | Sonoma 14.6.1 |
| Matlab version | R2023a (9.14.0.2206163) |
| EEGLAB version | v2024.2 |

**Comment by arnodelorme** [comment]
RELAX is an EEGLAB plugin. Would you mind to contact the authors directly?

**Comment by duszewypuscil** [comment]
Sure, thank you
