### ISSUE TITLE
Bug 1188 - (pop_studydesign) pop_studydesign vulnerability in 'combine conditions' 

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#89]
https://sccn.ucsd.edu/bugzilla/show_bug.cgi?id=1188
### Bug 1188 in BUGZILLA

**[reply] [−]DescriptionAgatha Lenartowicz 2011-12-16 09:37:22 PST**
Hi guys. There is a vulnerability in one of the pop/std_studydesign scripts that I haven't been able to nail to a specific location. It occurs when a design is created with combined condition. For instance, I have combined ages 7:1:14 into four groups (7/8, 9/10, 11/12 & 13/14). I've observed two funny behaviors:  1. When I select a subset to view just 2 groups (e.g., 7/8, 9/10), this works ok, but then when I return to the design GUI the other two group (e.g., 11/12, 13/14) are missing. Gone from history.  2. When I select conditions that were not in the original design (e.g., just 7, 8, 9 etc) and save, this does not produce an error. But when I return to the design view my combined conditions are completely missing from view.  So in general, there is something wrong with the "combine conditions" bits of the code b/c as soon as a small change is made within the design (e.g., for purposes of viewing a subset or by error) - things go wrong. I can't give you a study to view (my study is too huge) but I have a backup study if you want to view this behavior on my machine.  Cheers Agatha

**[reply] [−]Comment 1Agatha Lenartowicz 2011-12-16 10:05:21 PST**
An additional comment is that the "combine conditions" option needs to allow for a renaming of the new condition. Combining the condition names (current default) produces problems b/c when the name gets too long things start going wrong (both in file saving during precomputing and in viewing the results). Agatha 

**[reply] [−]Comment 2Arnaud Delorme 2012-01-02 21:08:48 PST**
Hi Agatha,  let me try to investigate this on your machine when we find a chance. Renaming of condition would be great. I will think about it.  I think the error is due to the fact that the independent variables you are working on are numerical (same problem in std_getindvar), a feature I only added recently.  Thanks,  Arno

**[reply] [−]Comment 3Arnaud Delorme 2012-01-14 12:19:15 PST**
Hi Agatha,  yes, this is a strange behavior. The reason is that combined conditions are not saved unless you use them in a design. If they are not used, then they disappear when you exit the GUI.  Did you experience something different from that? Thanks,  Arno 

**[reply] [−]Comment 4Agatha Lenartowicz 2012-01-15 14:09:59 PST**
That sounds like it would account for what I observed. If it's harmless then I suspect it won't be a problem but I can't recall if it corrupted the design structure or not. Agatha 

**[reply] [−]Comment 5Arnaud Delorme 2012-02-09 16:43:17 PST**
testing the wiki.  Arno

**Comment by arnodelorme** [comment]
This bug does not require further analysis. Given we do not have the original study we cannot test further.
