### ISSUE TITLE
Error in event codes as a function of cnt file length

### ISSUE THREAD

**Issue by edauer1** [eeglabdevelopers/eeglab#9]
The event time is incorrect when importing large (> 1 Gig )( file storage type 3) in Neuroscan CNT files. In these files, events are stored as sample number and the offset for the header and channel description should not be removed. The subtraction creates an offset ( 22 milliseconds in our case with 66 channels) of event times and will be more or less depending on the number of channels on the cap. The timing is correct when the file size is below 1 gig. A fix is proposed as a pull request.

**Comment by arnodelorme** [comment]
I have moved the code to the neuroscanio repository and acknowledged your contribution.
