### ISSUE TITLE
Bug 1122 - Inappropriate rank-recovering in second and later ICA 

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#90]
### Bug report 1122 in BUGZILLA

**Makoto 2011-08-19 17:05:52 PDT**
There was a question post to EEGLAB mailing list related to this issue. I investigated it and found that even after discarding several ICs, the next ICA allows a full-rank decomposition. This was replicated with ver 10.1.1.0b (the reported user used it), and also with 10.2.3.4b.

Makoto

**Comment by arnodelorme** [comment]
@mmiyakoshi@ucsd.edu I could not reproduce the problem. I loaded the tutorial dataset, removed 3 components and recalculated the rank and it was reduced by 3. Now I agree that this is a persistent problem with the Matlab rank function. There is not much we can do though (except as in runica have our own rank function and compare with Matlab results).
