### ISSUE TITLE
Matlab pca built-in function overshadowed by AAR plug-in 

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#96]
### Bug report 1970 in BUGZILLA

**[reply] [−]DescriptionRamon Martinez-Cancino 2017-01-12 17:49:29 PST**
The pca.m function from the plugin AAR overshadows the MATLAB built-in function.

**[reply] [−]Comment 1Ramon Martinez-Cancino 2017-07-28 09:36:43 PDT**
Dear German,   It seems that the pca.m function on the plugin AAR is overshadowing the built-in function in MATLAB. This is causing problems since the arguments of both functions are differents.  Can you please handle this on the plugin?  Thanks in advance,  Ramon

**Comment by arnodelorme** [comment]
Transfered to the AAR plugin and added a note to the plugin manager https://github.com/germangh/eeglab_plugin_aar/issues/1
