### ISSUE TITLE
Complex values passed to std_plottf

### ISSUE THREAD

**Issue by nucleuscub** [eeglabdevelopers/eeglab#97]
### Description
in line 736 of pop_precomp.m we are passing to std_pottf  the variable tmpX (time-freq data) with complex numbers. I'm not sure std_plottf can handle this, since it is throwing an error while trying to set the plot caxis because of the complex values. Should this be instead {abs(tmpX)*10*log10}? . 

#### Steps to Reproduce

1. *Load a study*
2. *Launch pop_precomp from GUI or command line*
3. *Check ERSP and press the Test button*

A figure will pop up, but later there is a warning informing of an error, leading to line 503 of tftopo.m The issue is originated due to the complex numbers in g.limits. 

#### Versions

|   |   |
|----| ---- | 
| OS version     | [*10.14.3*] |
| Matlab version | [*R2018b*] |
| EEGLAB version | [*Develop version as in Dec 5, 2019*] |

**Comment by arnodelorme** [comment]
Fixed in aaea8d7c6
